""" słownik skrótów literatury """

literatura = {
    "AACapCrac.":"Acta actorum capituli Cracoviensis w Archiwum Kapitulnym w Krakowie",
    "ABMK":"Archiwa, Biblioteki i Muzea Kościelne",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z Archiwum tzw. Bernardyńskiego we Lwowie, t. I-XIX, wyd. O. Pietruski, X. Liske, A. Pro­chaska, Lwów 1868-1906",
    "AJG":"Archiwum Klasztoru Paulinów na Jasnej Górze",
    "AJZR":"Archiv jugo-zapadnoj Rossii izdavajemyj Kommissiju dla razbora drevnich aktov , cz. 1, Kiev 1858",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności w Krakowie",
    "AKM":"Archiwum Kurii Metropolitalnej w Krakowie",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności w Krakowie",
    "Aktaunii":"Akta unii Polski zLitwą 1385-1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "APGd.":"Archiwum Państwowe w Gdańsku",
    "APK t .":"Archiwum Państwowe w Krakowie",
    "ArchSang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. II, V, Lwów 1888, 1897",
    "BCzart.":"Biblioteka Książąt Czartoryskich w Krakowie",
    "BCzart.Katalog":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, cz. 1; Dokumenty’ z lat 1148-1506, Kraków 1975",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BobrzSmol.":"M. Bobrzyński, S. Smolka, Jan Długosz . jego życie i stanowisko w piśmiennictwie, Kraków 1893",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1916",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "BukSprzedaż":"W. Bukowski, Sprzedaż i dziedziczenie urzędu w Polsce późnośredniowiecznej. Casus burgrabstwa krakowskiego, w: Teki Krakowskie, V. 1997, s. 29-37",
    "CB":"Castrensia Biecensia w APKr.",
    "CC":"Castrensia Cracoviensia w APKr",
    "CCR":"Castrensia Cracoviensia. Relationes w APKr.",
    "CDWiel.":"Codex diplomatics Vielicensis, Lwów 1872",
    "CL":"Castrensia Lublinensia w Archiwum Państwowym w Lublinie",
    "Codex Vitoldi":"Codex epistolaris Vitoldi, magni ducis Lithuaniae 1376-1430. wyd. A. Prochaska, Kraków 1882",
    "ConsCrac.":"Consularia Cracoviensia w APKr.",
    "Crac.art.Supl.":"Teksty źródłowe do dziejów kultury' i sztuki z archiwaliów kurialnych i kapitulnych w Krakowie 1433-1440, wybrał i oprać. B. Przyby­szewski, Wrocław 1988",
    "DLb.":"(Jana Długosza) Liber beneficiorum dioecesis Cracoviensis. t. I-III. wyd. A. Przezdziecki, Opera omnia VII-IX, Kraków 1863-1864",
    "DłAnn.":"Joannis Dlugossii Annales seu cronicae incliti Regni Poloniae, lib. I i n.. Varsaviae 1964 n.",
    "Długosz":"Joannis Długosz Senioris canonici Cracoviensis opera omnia, t. I-XIV, Cracoviae 1863 n.",
    "Dogiel IV":"Codex diplomatics Regni Poloniae et Magni Ducatus Lithuaniae. ed. M. Dogiel. t. IV, Vilnae 1764",
    "DokPaul.":"Zbiórdokumentów zakonu 00. Paulinów w Polsce, z. 1 (1382-1464), wyd. J. Fijałek. Kraków 1938",
    "DokPaul. 2":"Zbiór dokumentów zakonu 00. Paulinów vr Polsce , z. 2 (1464-1537), oprać. J. Zbudniewek, w przygotowaniu",
    "DokWęg. I-II":"Dokumenty polskie z archiwów dawnego Królestwa Węgier. 1 .1 (do 1450 r.), wyd. S. A. Sroka. Kraków 1998; t. II w druku",
    "DSZK":"Dokumenty sądu ziemskiego krakowskiego 1302-1453, wyd. Z. Perzanowski, Wrocław 1971",
    "DwGen.":"W. Dworzaczek, Genealogia, Warszawa 1959, tablice",
    "Engel":"P. Engd, Magyarorszag vilagi archontológidja 1301-1457 , t. I-II. Budapest 1996",
    "Epist.":"Codex epistolaris saeculi decimi quiunti, t. I-III. Kraków 1876-1894",
    "FastnachtKatOssol.":"Catalogus diplomatum Bibliothecae Ossoliniani Supplementum, oprać. A. Fastnacht, Wrocław 1951",
    "GItin.":"A. Gąsiorowski. Itinerarium króla Władysława Jagiełły 1386-1434. Warszawa 1972",
    "GItinKW":"A. Gąsiorowski, Itinerarium króla Kazimierza Wielkiego. Materiały 1333-1370 , Roczniki Historyczne, 64, 1998",
    "GórOdr.":"K. Górski, Ród Odrowążów u- wiekach średnich , Rocznik Polskiego Towarzystwa Heraldycznego, 8, Kraków 1928",
    "GórSMalb.":"K. Górski, Starostowie malborscy w latach 1457-1510. Pierwsze półwiecze polskiego Malborka, Toruń 1960",
    "GStar.":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej , Warszawa 1981",
    "ISB":"Inowrocławski słownik biograficzny , t. 2, Inowrocław' 1994 ",
    "IvBart.":"B. Ivanyi, Bartfa Szabad kiralyi varos leveltara 1319-1526 , I. Kótet 1319-1501, Budapest 1910",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej S. Wacława , t. I-II, wyd. F. Piekosiński. Kraków 1874",
    "KDM":"Kodeks dyplomatyczny Małopolski, t. I-IV. w yd. F. Piekosiński. Kraków 1876-1905; t. V -Materiały w Pracowni Słow nika Historyczno-Geograficznego Małopolski w Średniowieczu IH PAN w Krakowie",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, t. I-XI, Poznań 1877-1999",
    "Kętrzyński I":"W. Kętrzyński, Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich, 1.1, Lwów 1881",
    "Kieszkowski I-II":"J. Kieszkowski. Kanclerz Krzysztof Szydłowiecki. Z dziejów kultury' i sztuki zygmuntowskich czasów, t. I-II, Poznań 1912",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa, wyd. F. Piekosiński. 1.1, Kraków 1879",
    "KMog.":"Diplomata monasterii Clarae Tumbae prope Cracoviam, wyd. E. Janota, Kraków 1865",
    "Knigi":"Knigi pol'skoj koronnoj metriki XVstoletija, Matricularum Regni Poloniae codices saeculo XV conscripti, 1.1. Księga nr 10 z lat 1447-1454. wyd. A. Mysłowski, W. Graniczny, Warszawa 1914",
    "KPol.":"Kodeks dyplomatyczny Polski, t. I-III, Warszawa 1847-1858",
    "KSN":"Najstarsza księga sądu najwyższego prawa niemieckiego na zamku krakowskim, wyd. A. Kłodziński, w: AKPr. X. Kraków' 1936",
    "KTyn.":"Codex diplomatics monasterii Tynecensis, cz. I, wyd. W. Kętrzyński. S. Smolka. Lwów 1875",
    "KUJ":"Codex diplomatics universitatis studii generalis Cracoviensis, t. I-IV, wyd. Ż. Pauli, Kraków 1870-1900",
    "Kurtyka, Elita":"Elita małopolska XIII i XIV w. -przerwa czy kontynuacja (na przykładzie Toporów: potomstwo Żegoty wojewody i kasztelana krakowskie­ go), w: Genealogia-Polska elita polityczna w wiekach średnich na tle porównawczym, Toruń 1993, s. 35-60",
    "Kurtyka, Kariera":"J. Kurtyka, Kariera wojewody krakowskiego Andrzeja z Tęczyna na tle rywalizacji stronnictw za panowania Kazimierza Wielkiego. w: Cracovia-Polonia ^Europa, Kraków 1995. s. 255-291",
    "Kurtyka, Krąg":"J. Kurtyka, Krąg rodowy i rodzinny Jana Pakosławica ze Stróżysk i Rzeszowa (ze studiów nad rodem Półkoziców w XIII i XIV wieku), Przemyskie Zapiski Historyczne, 6-7, 1989/1990 [druk 1991]",
    "Kurtyka, Problem":"J. Kurtyka, Problem identyczności urzędów ziemskich krakowskich i nadwornych w wiekach XIV-XVI, w: Urzędy dworu monarszego dawnej Rzeczypospolitej i państw ościennych, red. A. Gąsiorowski, R. Skow­ron, Kraków 1996",
    "Kurtyka, Tęczyńscy":"J. Kurtyka, Tęczyńscy. Studium z dziejów polskiej elity możnowładczej w średniowieczu, Kraków 1997",
    "Kurtyka, Topory":"J. Kurtyka, Topory, Starekonie i Okszy ce. W sprawie związków międzyrodowych w XIII iXIV w., Kw.Hist. 2, 1992, s. 17-37",
    "Kutrzeba, Akta sejmikowe I":"Akta sejmikowe województwa krakowskiego, 1.1, wyd. S. Kutrzeba, Kraków 1932",
    "KutrzSądSand.":"S. Kutrzeba, Sądy ziemskie i grodzkie w wiekach średnich. II. Województwo sandomierskie, RAU hf, seria 2, t. XV, Kraków 1901",
    "Kw.Hist.":"Kwartalnik Historyczny",
    "Leśniak":"F. Leśniak, Wielkorządcy krakowscy XVI-XVIII w., Kraków 1996",
    "Mazur":"Z. Mazur, Studia nad kancelarią księcia Leszka Czarnego, Wrocław 1975",
    "MK":"Metryka koronna w AGAD",
    "MPH":"Monumenta Poloniae historica, t. II-VI, Lwów-Kraków 1872-1893",
    "MPHs.n.":"Monumenta Poloniae historica. Series nova , t. I-X, Kraków 1951 -Warszawa 1978",
    "MrozNagr.":"P. M. Mrozowski, Polskie nagrobki goty ckie, Warszawa 1994",
    "MRPS":"Matricularum Regni Poloniae summaria, t. I-IV, wyd. T. Wierzbowski, Warszawa 1905-1912",
    "Niesiecki":"K. Niesiecki, Herbarz polski, t. I-X, wyd. J. N. Bobrowicz, Lipsk 1839-1846",
    "OfCrac.":"Acta officialatus Cracoviensis w AKM",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVI w., Warszawa 1962",
    "PANKr.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Paprocki":"B. Paprocki, Herby ry cerstwa polskiego, Kraków 1858",
    "PerzDok.":"Z. Perzanowski, Dokument i kancelaria sądu ziemskiego krakowskie go do połowy XV w., Kraków 1968",
    "Prawa, przywileje":"Prawa, przywileje i statuta miasta Krakowa (1507-1795), wyd. F. Piekosiński- S. Krzyżanowski, t. 1-2, Kraków 1885-1909",
    "Prochaska":"Materiały archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 roku, wyd. A. Prochaska, Lwów 1890",
    "Przybyszewski III, V":"Wypisy źródłowe do dziejów Wawelu z archiwaliów kapitulnych i kurialnych krakowskich 1440-1500 (Źródła do dziejów Wawe­lu, t. III), wybrał i oprać. B. Przybyszewski, Kraków 1960; toż, 1516-1525, (Źródła do dziejów Wawelu, t. V), Kraków 1970",
    "PSB":"Polski słownik biograficzny, t. I-XXXVIII, Kraków 1935-1998",
    "RachJag.":"Rachunki dworu króla Władysława Jagiełły i królowej Jadwigi z l. 1388-1420 , wyd. F. Piekosiriski, Kraków 1896",
    "RachKrak.":"Najstarsze księgi i rachunki miasta Krakowa , wyd. F. Piekosiński i J. Szujski, Kraków 1878",
    "RachKról.":"Rachunki królewskie z lat 1471-1472 i 1476-1478, oprać. S. Gawęda, Z. Perzanowski, A. Strzelecka. Wrocław 1960",
    "RachLw.":"Księga przychodów i rozchodów miasta Lwowa , t. 1-2 (1404-14, 1414-26), wyd. A. Czołowski, Pomniki dziejowe Lwowa II-III, Lwów 1896-1905",
    "Rybus":"H. Rybus, Królewicz kardynał Fryderyk Jagiellończyk jako biskup krakowski i arcybiskup gnieźnieński , Warszawa 1935",
    "Ryklnv.":"Inventarium omnium et singulorum privilegiorum ...in Archivo Regni in Arce Cracoviensi .... wyd. E. Rykaczewski, Lutetiae Parisiorum 1862",
    "ScabCrac.":"Scabinalia Cracoviensia w APKr.",
    "Seruga":"J. Seruga, Dokumenty pergaminowe w zbiorach biblioteczno-archiwalnych hr. Tarnowskich w Suchej, Kraków 1936",
    "SHGKr.":"Słownik historyczno-geograficzjiy województwa krakowskiego w średniowieczu, cz. I-III, Wrocław 1980-Kraków 1997",
    "SHGP":"Słownik historyczno-geograficzny województwa poznańskiego w średniowieczu , cz. I-III, Wrocław 1982-Poznań 1997",
    "SHGSan.":"Słownik historyczno-geograficzny ziemi sanockiej w średniowieczu, cz. 1-2, oprać. A. Fastnacht, Brzozów 1991-1998",
    "Sikora, Dybacze":"F. Sikora, Dybacze-Czuryłowie herbu Radwan w XV-XVI w., w: Patientia et tempus. Księga jubileuszowa dedykowana dr. Marianowi Korneckiemu, Kraków 1999",
    "Sikora, Początki":"F. Sikora, Początki starostwa nowomiejskiego korczyńskiego, w: Społeczeństwo Polski średniowiecznej, t. 6, Warszawa 1994",
    "Sikora, Starostwo":"F. S ikora, Starostwo krakowskie pod rządami Jana z Tarnowa w latach 1406-1409, w: Homines et societas. Czasy Piastów i Jagiellonów, Poznań 1997",
    "Sikora, Ze studiów":"F. Sikora, Ze studiów nad dokumentami i kancelarią Leszka Czarnego , Studia Historyczne, 21, 1978",
    "Sochacka, Jan z Czyżowa":"A. Sochacka, Jan z Czyżowa namiestnik Władysława Warneńczyka. Kariera rodziny Półkozów w średniowieczu, Lublin 1993",
    "SPPP":"„Starodawne prawa polskiego pomniki”, t. II: Wypisy z ksiąg dawnych sądowych ziemskich i grodzkich ziemi krakowskiej, wyd. A. Z. Helcel. Kra­ków 1870; t. VII/2: Inscriptiones clenodiales ex libris iudicialibuspalatinatus Cracoviensis, wyd. B. Ulanowski, Kraków 1885; t. VIII: Antiquissimi libri iudiciales terre Cracoviensis , wyd. B. Ulanowski, Kraków 1884-1886",
    "SprWęg.":"Sprawozdanie z poszukiwań na Węgrzech dokonanych z ramienia Akademii Umiejętności, Kraków 1919",
    "SUB":"Schlesisches Urkundenbuch. Bd. 4: 1267-1281, bearb. von W. Irgang. Kóln-Wien 1988",
    "Szybkowski":"S. Szybkowski, Krzyżacki szpieg, lubelski mieszczanin i sandomierski chorąży. Kilka uwag w sprawie badań prozopograficznych personelu kancelarii Wielkiego Księcia Witolda , w: Krzyżowcy, kronikarze, dyplomaci. Gdańsk-Koszalin 1997",
    "TB":"Terrestria Biecensia w APKr.",
    "TC":"Terrestria Cracoviensia w APKr.",
    "TCzch.":"Terrestria Czchoviensia w APKr.",
    "Teut.":"Teutonicalia. Księgi sądu wyższego prawa magdeburskiego na zamku krakowskim w APKr. (Obecna nazwa zespołu SWPM = Sądy Wyższe Prawa Miejskiego)",
    "TęgRec.":"J. Tęgowski, rec. z U IV/1. w: Prz. Hist.. 82. 1991, z. 3-4, s. 526-527",
    "TNar.":"Teki Naruszewicza w BCzart. w Krakowie",
    "TL":"Terrestria Lublinensia w AP w Lublinie",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy",
    "VL":"Volumina legum , t. I-III, Petersburg 1859",
    "VMPL":"Vetera monumenta Poloniae et Lithuaniae, 1.1. Rzym 1860",
    "WierzbFragm.":"Dwa fragment}' ksiąg kancelatyjnych królewskich z 1-szej połowy XV w. wyd. T. Wierzbowski, Warszawa 1907",
    "WronRaw. I-II":"J. Wroniszewski. RódRawiczów. (I:) Warszowice i Grotowice. Toruń 1992; (II:) Współrodowcy Warszowiców i Grotowiców, Toruń 1994",
    "Zap. Hist.":"Zapiski Historyczne",
    "Zbiory Popielów":"Zbiory Popielów w AGAD",
    "ZDKK":"Zbiór dokumentów katedry i diecezji krakowskiej, cz. I-II. wyd. S. Kuraś, Lublin 1965-1973",
    "ZDM":"Zbiór dokumentów małopolskich, cz. I-VIII. wyd. I. Sułkowska-Kurasiowa, S. Kuraś, Wrocław 3962-1975",
    "Zeissberg":"H. Zeissberg, Kleinere Geschichtsequellen Polens im Mittelalter, w: Archiv fur ósterreichische Geschichte. 55, 1877",
    "Żychl.":"T. Żychliński, Złota księga szlacht}' polskiej, t. I-XXXI, Poznań 1879-1908"
}