""" słownik skrótów literatury """

literatura = {
    "ABWil.":"Archiwum Benedyktynek Wileńskich w Opactwie Benedyktynek w Żarnowcu",
    "AD":"Aвтогрфы (коллекция) П. П. Дубровского (F. 971) w RNB w Sankt Petersburgu",
    "ADS":"Archiwum domu Sapiehów wydane staraniem rodziny, t. I: Listy z lat 1575–1606, oprac. A. Prochaska, Lwów 1892",
    "Aftanazy I":"R. Aftanazy, Dzieje rezydencji na dawnych kresach Rzeczypospolitej, t. I, Wrocław 1986",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "Akta Unji":"Akta Unji Polski z Litwą 1385–1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "Akta zjazdów":"Akta zjazdów stanów Wielkiego Księstwa Litewskiego, t. I: Okresy bezkrólewi (1572–1576, 1586–1587, 1632, 1648, 1696–1697, 1706–1709, 1733–1735, 1763–1764), oprac. H. Lulewicz, Warszawa 2006",
    "Akty JZR":"Акты, относящiеся къ исторiи Южной и Западной Россiи, собранные и изданные Архeографическою комиссиею, t. I–XV, Санкт- Петербург 1863–1892 ",
    "Aleksandro Jogailaičio dvaro sąskaitū knygos (1494–1504)":"Lietuvos didžiojo kunigaikščio Aleksandro Jogailaičio dvaro sąskaitū knygos (1494–1504), parenge D. Antanavičius ir R. Petrauskas, Vilnius 2007",
    "ALRG":"Aкты Литовско-русскаго государства изданные М. Довнар Запольским, t. I, Москва 1900",
    "AMCh":"Archiwum Młynowskie Chodkiewiczów w ANKr., Oddział na Wawelu",
    "ANKr.":"Archiwum Narodowe w Krakowie",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APR":"Archiwum Potockich z Radzynia w AGAD",
    "AR":"Archiwum Warszawskie Radziwiłłów w AGAD",
    "Archiw JZR":"Архив Юго-Западной России, издаваемый временною комиссиею для разбора древних актов высочайше учрежденною при Киевском военном, Подольском и Волынском генерал-губернаторе, cz. 1–8, Киев 1859–1914",
    "ASang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. I–VII, wyd. B. Gorczak, Lwów 1887",
    "ASD":"Aрхеографичecкiй сборнiкъ документовъ относящихся къ исторіи Сeверозападной Руси, t. I–XIV, Вильна 1867–1904",
    "Augustyniak":"U. Augustyniak, Testamenty ewangelików reformowanych w Wielkim Księstwi Litewskim w XVI–XVIII wieku, wyd. II popr. i rozsz., Warszawa 2014",
    "AWAK":"Акты, издаваемые Виленскою археографическою комиссiею, t. I–XXXIX, Вильна 1865–1915",
    "AZR":"Акты относящиеся къ истории Западной России, собранные и изданные Архeографическою комиссиею, t. I–V, C.-Петербург 1848– 1863",
    "BA":"Беларускі архіў, t. II, Менск 1928",
    "Barącz":"S. Barącz, Rys dziejów zakonu kaznodziejskiego w Polsce, t. II, Lwów 1861",
    "Biełarussia w epochu ﬁ eodalizma":"Белорусся в эпоху феодализма. Сборник документов и матерялов в трех томах, t. I–III, Минск 1959–1961",
    "BN":"Biblioteka Narodowa w Warszawie",
    "BNANB":"Центральная научная библиотека им. Якуба Коласа НАН Беларуси, Минск",
    "Bon.":"A. Boniecki, Herbarz polski, t. I–XVI, Warszawa 1899–1913",
    "BonPoczet":"A. Boniecki, Poczet rodów w Wielkim Księstwie Litewskim w XV i XVI wieku, Warszawa 1887 (dodane do tytułu słowo Spis oznacza „Spis dygnitarzy i urzędników duchownych i świeckich” - umieszczony na końcu książki)",
    "BonU.":"A. Boniecki, Herbarz polski. Uzupełnienia i sprostowania do Części I, Warszawa 1901",
    "Borkowska":"Dekret w niebieskim ferowany parlamencie. Wybór testamentów z XVII–XVIII wieku, oprac. M. Borkowska OSB, Kraków 1984",
    "BOZ":"Biblioteka Ordynacji Zamojskiej w Bibliotece Narodowej",
    "BPW":"Biblioteka Publiczna m.st. Warszawy",
    "Bułhakowie":"W. Bułhak, Bułhakowie. Zarys historii rodu, Warszawa 1994",
    "BUW":"Biblioteka Uniwersytecka w Warszawie",
    "CCR":"Castrensia Cracoviensia Relationes w ANKr.",
    "CDIAUK":"Центральний державний історичний архів України, Київ",
    "Chmiel":"A. Chmiel, Zbiór dokumentów znajdujących się w Bibliotece hr. Przezdzieckich w Warszawie, Kraków 1890",
    "Chrapowicki":"J.A. Chrapowicki, Diariusz, cz. I, oprac. T. Wasilewski, Warszawa 1978, cz. II, oprac. A. Rachuba i T. Wasilewski, Warszawa 1988",
    "Ciechanowicz":"J. Ciechanowicz, Rody rycerskie Wielkiego Księstwa Litewskiego, t. I–V, Rzeszów 2001",
    "Codello":"A. Codello, Konfederacja wojskowa na Litwie w l. 1659–1663, „Studia i Materiały do Historii Wojskowości”, t. VI, 1960, cz. 1",
    "Codex ep. Vitoldi":"Codex epistolaris Vitoldi magni ducis Lithuaniae 1376-1430, oprac. A. Prochaska, Cracoviae 1882",
    "Codex ep. XV":"Codex epistolaris saeculi decimi quinti, t. I, oprac. A, Sokołowski, J. Szujski, Kraków 1876, t. II–III, oprac. A. Lewicki, Kraków 1891–1894",
    "Czarniauski IV":"Ф.В. Чарняўскі, Ураднікі Менскага ваяводства XVI-XVIII стст. Біяграфічны даведнік, выпуск IV, Miнск 2015",
    "Czart.":"Biblioteka Książąt Czartoryskich w Krakowie",
    "DanSkarb.":"Skarbiec diplomatów papiezkich, cesarskich, krolewskich; uchwał narodowych, postanowień różnych władz i urzędów posługujących do krytycznego wyjaśnienia dziejów Litwy, Rusi Litewskiéj i ościennych im krajów, zebrał I. Daniłowicz, t. I–II, Wilno 1860–1862",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae, t. I–V, wyd. M. Dogiel, Wilno 1758–1764",
    "Dokumenty pokoju mełneńskiego":"Dokumenty strony polsko-litewskiej pokoju mełneńskiego z 1422 roku, wyd. P. Nowak i P. Pokora, Poznań 2004",
    "Dounar":"А. Доўнар, Пацвярджальны прывілей Полацку 1633 г., „Commentarii Polocenses Historici”, t. I, 2006, s. 43–49",
    "Dworzaczek":"W. Dworzaczek, Genealogia. Tablice, Warszawa 1959",
    "Dzieje Ciechanowieckich":"Dzieje rodziny Ciechanowieckich herbu Dąbrowa (XIV–XXI wiek), red. A. Rachuba, Warszawa 2013",
    "EJ":"Encyklopedia wiedzy o jezuitach na ziemiach Polski i Litwy 1564–1995, oprac. L. Grzebień i in., Kraków 1996",
    "Elekt.":"J. Dunin-Borkowski, M. Dunin-Wąsowicz, Elektorowie królów Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, Lwów 1910; O. Pietruski, Elektorów poczet, którzy niegdyś głosowali na elektorów Jana Kazimierza roku 1648, Jana III roku 1674, Augusta II roku 1697 i Stanisława Augusta roku 1764, Lwów 1845",
    "Estr.":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografi a polska, stulecie XV–XVIII, t. I–XXXIX, Kraków 1870–1952",
    "Faszczów":"Archiwum Faszczów w AGAD",
    "FHPL":"Fontes Historiae Parlamentorum Lituanicorum, t. I: Lietuvos Didžiosios Kunigaikštystis seimelių instrukcijos 1788–1790, parengė R. Jurgaitis, A. Stankevič, A. Verbickienė, Vilnius 2015",
    "FRC":"Zbiory Fundacji Rodziny Ciechanowieckich, Zamek Królewski w Warszawie",
    "Gałubowicz, Miscellanea":"В.У. Галубовіч, Miscellanea Historica Polocensia. Даследаванні па гісторыі Полаччыны XII–XVII стст., Гродна 2014",
    "Gałubowicz, Połackaja szlachta":"В.У. Галубовіч, Полацкая шляхта і дынастыя Вазаў, Мінск 2016",
    "GazWarsz.":"„Gazeta Warszawska”",
    "GazWil.":"„Gazety Wileńskie”",
    "GBS":"Гербоўнік беларускай шляхты, t. I–IV, Мінск 2002–2016",
    "GNO":"„Gazeta Narodowa y Obca”",
    "Gordziejew":"J. Gordziejew, Komisje Porządkowe Cywilno-Wojskowe w Wielkim Księstwie Litewskim w okresie Sejmu Czteroletniego (1789–1792), Kraków 2010",
    "GP":"„Gazety Polskie”",
    "Haratym":"A. Haratym, Paweł Tetera hetman na Prawobrzeżu (po 1620-1671), w: Hetmani zaporoscy w służbie króla i Rzeczypospolitej, red. P. Kroll, M. Nagielski, M. Wagner, Zabrze 2010",
    "Hedemann, Dzisna":"O. Hedemann, Dzisna i Druja magdeburskie miasta, Wilno 1934",
    "HHuSA Wien":"Haus-, Hof- und Staatsarchiv w Wiedniu",
    "IJM":"Историко-юридическiе матерiалы, извлеченные изъ актовыхъ книг губернiи Витебской и Могилевской, издание A.M. Созонова, Н. Мещер- скаго, М. Веровкина, Д.И. Довгялло, t. I–XXXII, Витебск 1871–1906",
    "IRIRAN":"Архив Санкт-Петербургского института истории РАН, Русская секцыя архива",
    "Iwański":"N.M. Iwański, Proportio aeternae veritatis […], Cracoviae 1737",
    "Jag.":"Biblioteka Jagiellońska w Krakowie",
    "Jaszczołt":"T. Jaszczołt, Ród Niemiry z Wsielubia - Niemirowiczowie i Szczytowie herbu Jastrzębiec do połowy XVI wieku, w: Unia w Horodle na tle stosunków polsko-litewskich. Od Krewa do Zaręczenia wzajemnego Obojga Narodów, red. S. Górzyński, Warszawa 2015",
    "Jewłaszewski":"„Гістарычныя запіскі” Ф. Еўлашоўскага, уклаў У. М. Свяжынскі, Мінск 1990",
    "JfG":"„Jahrbuch für Genealogie, Heraldik und Sphragistik”, Jb. 1893-1914, Mitau 1894-1930",
    "Jurkevičius":"A. Jurkevičius, The nomination procedure of the oﬃ cials of the city of Polotsk in 1498–1563, „Zapiski Historyczne”, t. LXXXII, 2017, z. 4, s. 625–647",
    "Kal. Grodz.":"Kalendarz Grodzieński",
    "Kal. Polit.":"Kalendarz (Kalendarzyk) Polityczny (na poszczególne lata)",
    "Kal. Polit. KP i WXL":"Kalendarz Polityczny Królestwa Polskiego i Wielkiego Xięstwa Litewskiego",
    "Kal. Poł. Soc. Jesu":"Kalendarz Połocki Societatis Jesu",
    "Kal. Wil.":"Kalendarz Wileński",
    "Kamer.":"Archiwum Kameralne w AGAD",
    "Kaniewska":"Listy króla Zygmunta Augusta do Radziwiłłów, oprac. I. Kaniewska, Kraków 1999",
    "KDKDW":"Kodeks dyplomatyczny katedry i diecezji wileńskiej, t. I: 1387–1507, wyd. J. Fijałek, W. Semkowicz, Kraków 1938–1948",
    "Kelma":"E. Kelma, Ród Sakowiczów i jego majętności w XV i pierwszej połowie XVI w., „Lituano-Slavica Posnaniensia”, R. III, 1989, s. 155–177",
    "KL":"„Kuryer Litewski”",
    "KMMP 1727":"Кніга магістрата места Полацка 1727 года, падр. А.М. Латушкін, М.Д. Макараў, Вільня-Беласток 2012",
    "KojałComp.":"W. Wijuk Kojałowicz, Herbarz rycerstwa W.X.Litewskiego tak zwany Compendium, wyd. F. Piekosiński, Kraków 1897",
    "Kol. Warsz.":"Kolęda Warszawska (na kolejne lata)",
    "Konarski, Szlachta":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Konarski, Platerowie":"S. Konarski, Platerowie, „Materiały do Biografii, Genealogii i Heraldyki Polskiej”, t. IV, 1967",
    "Korczak, Monarcha i poddani":"L. Korczak, Monarcha i poddani. System władzy w Wielkim Księstwie Litewskim w okresie wczesnojagiellońskim, Kraków 2008",
    "Korczak, Rada":"L. Korczak, Litewska rada wielkoksiążęca w XV wieku, Kraków 1998",
    "Kościałkowski":"S. Kościałkowski, Antoni Tyzenhauz podskarbi nadworny litewski, t. I–II, Londyn 1970–1971",
    "Kotłubaj":"E. Kotłubaj, Życie Janusza Radziwiłła, wojewody wileńskiego, hetmana wielkiego W.X.L., Wilno–Witebsk 1859",
    "Kórnik":"Biblioteka PAN w Kórniku",
    "KP":"„Kuryer Polski”",
    "Krasnołuckij":"А. Краснолуцкий, Злая судьба рода Голынских?, С.-Петербург 2009",
    "Kriegseisen":"W. Kriegseisen, Ewangelicy polscy i litewscy w epoce saskiej (1696–1763). Sytuacja prawna, organizacja i stosunki międzywyznaniowe, Warszawa 1996",
    "Kronika halicko-wołyńska":"Kronika halicko-wołyńska (Kronika Romanowiczów), Pomniki Dziejowe Polski, Seria II: Tom XVI, wyd. D. Dąbrowski i A. Jusupović, Kraków–Warszawa 2017",
    "LECUrkund.":"Liv-, Est- und Curlandisches Urkundenbuch nebst Regesten, Hrsg. v. F.G. v. Bunge, H. Hildebrand, P. Schwartz, L. Arbusow, Abteilung 1 Bd. 10–12, Riga–Moskau 1896–1910, Abteilung 2 Bd. 1–3, Reval–Riga–Moskau 1900–1914",
    "Lietuvos inventoriai XVII a.":"Lietuvos inventoriai XVII a. Dokumentų rinkinys, sud. K. Jablonskis, M. Jučas, Vilnius 1962",
    "Lisiejczykau":"Д. Лiсейчыкаў, Святар в беларускам соцыуме. Прасапаграфiя унiяцкага духавенства 1596–1839 гг., Мiнск 2015",
    "Ljubawskij, Obłastnoje dielenije":"М. Любавский, Областное деление и местное управление Литовско-русского государства ко времени издания перваго Литовскаго Статута, Москва 1893",
    "LM 1":"Lietuvos Metrika. Knyga nr 1 (1380–1584), par. A. Baliulis, R. Firkovičius, Vilnius 1998",
    "LM 3":"Lietuvos Metrika. Knyga nr 3 (1440–1498), par. L. Anužytė, A. Baliulis, Vilnius 1998",
    "LM 5":"Lietuvos Metrika. Knyga nr 5 (1427–1506), par. A. Baliulis, A. Dubonis, D. Antanavičius, Vilnius 2012",
    "LM 6":"Lietuvos Metrika. Knyga nr 6 (1494–1506), par. A. Baliulis, Vilnius 2007",
    "LM 8":"Lietuvos Metrika. Knyga nr 8 (1499–1514), par. A. Baliulis, R. Firkovičius, D. Antanavičius, Vilnius 1995",
    "LM 9":"Lietuvos Metrika. Knyga nr 9 (1511–1518), par. K. Pietkiewicz, Vilnius 2003",
    "LM 10":"Lietuvos Metrika. Knyga nr 10 (1440–1523), par. E. Banionis, A. Baliulis, Vilnius 1997",
    "LM 11":"Lietuvos Metrika. Knyga nr 11 (1518–1523), par. A. Dubonis, Vilnius 1997",
    "LM 12":"Lietuvos Metrika. Knyga nr 12 (1540–1543), par. I. Valikonytė, N. Šlimienė, S. Viskantaitė-Saviščevienė, L. Steponavičenė, Vilnius 2007",
    "LM 14":"Lietuvos Metrika. Knyga nr 14 (1524–1529), par. L. Karalius, D. Antanavičius, Vilnius 2008",
    "LM 17":"Lietuvos Metrika. Knyga nr 17 (1530–1536), par. L. Karalius, D. Antanavičius, Vilnius 2015",
    "LM 20":"Lietuvos Metrika. Knyga nr 20 (1536–1539), par. R. Ragauskienė, D. Antanavičius, Vilnius 2009",
    "LM 25":"Lietuvos Metrika. Knyga nr 25 (1387–1546), par. D. Antanavičius, A. Baliulis, Vilnius 1998",
    "LM 228/9":"Судебная книга витебского воеводы, господарского маршалка, волковыского и оболецкого державцы М.В. Клочко (1533-1540), ред. А.Л. Хорошкевич, Г.Я. Голенченко, Москва 2008",
    "LM 249/35":"Lietuvos Metrika (1554–1568), par. S. Viskantaitė-Saviščevienė, I. Valikonytė, Vilnius 2018",
    "LMAB":"Lietuvos mokslų akademijos Vrublevskių biblioteka w Wilnie",
    "LNBW":"Lietuvos nacionalinė Martyno Mažvydo biblioteka w Wilnie",
    "Lulewicz":"H. Lulewicz, Sejmiki litewskie przed sejmem 1572 roku. Projekt obsady funkcji poselskich, w: Litwa w epoce Wazów, red. W. Kriegseisen, A. Rachuba, Warszawa 2006",
    "LVIA":"Lietuvos valstybės istorijos archyvas w Wilnie",
    "LVTS":"Lietuvos vyriausiojo tribunolo sprendimai 1583–1655, par. V. Raudeliūnas ir A. Baliulis, Vilnius 1988",
    "LVVA":"Latvijas Valsts vēstures arhīvs w Rydze",
    "LwNNB":"Львівська національна наукова бібліотека України імені В. Стефаника",
    "Łappo":"И.И. Лаппо, Великое княжество Литовское за время от заключения Люблинской унии до смерти Стефана (1569–1586). Опытъ изследованія политическаго и общественнаго строя, t. I, С. Петербургъ 1901",
    "Ławno":"Acta Stanów Wielkiego Xięstwa Litewskiego na pospolite ruszenie vigore laudum Wileńskiego 14 Augusti 1698 postanowionego między Ławnem a Puzewiczami - 1698 21 Decembris, Wilno 1699",
    "Łop.":"Biblioteka Publiczna im. Łopacińskich w Lublinie. Dział Rękopisów",
    "Łopaciński":"E. Łopaciński, Akcesy do konfederacji warszawskiej rządu i obywateli Wielkiego Księstwa Litewskiego, odb. „Ateneum Wileńskie”, XI, 1936",
    "Łoza, Kawalerowie":"S. Łoza, Kawalerowie Orderu Świętego Stanisława 1765–1813, Warszawa 1925",
    "Łoza, Order":"S. Łoza, Order Orła Białego, Warszawa 1939",
    "MA":"Менскія акты, Вып. 1 (XV–XVIII ст.), cклад. З. Даўгяла, Мінск 1930",
    "Maciejewska":"W. Maciejewska, Dzieje ziemi Połockiej w czasach Witołda (1385–1430), Wilno 1933",
    "Macuk, Buyniccy":"А. Мацук, Род Буйнiцкiх в Палацкам ваяводстве ў панаванне Аўгуста III, w: Беларускае Падзвiнне i вопыт, методiка i вынiкi палевых i мiждысцыплiнарных даследыванняў (до 20-годдзя археалагiчных i этнаграфiчных экспедiцый ПДУ), 17–18 красавiка 2014, Частка 2, pед. Д. Дук, Ч. Лобач i С. Швыкоўскiй, Наваполацк 2014, s. 107–116",
    "Macuk, Buynicki":"А. Мацук, Ян Буйнiцкi лiдaр шляхты Полацкага ваяводства ў панаванне Аўгуста III, w: Szlachta i ziemiaństwo na pograniczach kulturowych dawnej Rzeczypospolitej od XVI do początku XX wieku, red. D. Michaluk, K. Mikulski, Warszawa 2016, s. 85–96",
    "Macuk, Hrebniccy":"А. Мацук, Род Грабнiцкiх у грамадска-палiтiчнай жыттi Палацкага ваяводства ў панаванне Аўгуста III, w: Беларусь праз прызму рэгіянальнай гісторыі. Шумілінскі край: зб. навук. арт., рэд. В.М. Ляўко, Мінск 2018, s. 215–237",
    "Macuk, Połock":"А. Мацук, Полацкае ваяводства ў XVIII ст. Ваявода, шляхецкая эліта, соймікі, Мінск 2014",
    "Macuk, Sapieha":"А. Мацук, Жыццё і дзейнасць Аляксандра Міхала Сапегі да заняцця ўрада полацкага ваяводы, w: Полацкія чытанні - 2017: зб. матэрыялаў навукова-практычнай канферэнцыі (г. Полацк, 2 верасня 2017 года), Мінск 2017, s. 118–130",
    "Makarau 2008":"М. Макараў, Ад пасада да магдэбургіі. Прававое становішча насельніцтва местаў Беларускага Падзвіння ў XIV - першай палове XVII ст., Мінск 2008 ",
    "Makarau 2014":"М. Макараў, Месцкія ўлады Полацка (1580–1772 гг.): арганізацыя, персанальны склад, Смаленск 2014",
    "Malinowskij, Sbornik":"Сборник материалов, относящихся к истории панов-рады Великого княжества Литовского, издал J. Малиновскiй, Томскъ 1901",
    "Manifest 1733":"Sit Nomen Domini Benedictum. Actum in Curia Regia Varsaviensi sub tempus moderni Interregni Feria secunda in crastino Festi Omnium Sanctorum; Anno Domini Millesimo, Septingentesimo, Trigesimo tertio. Manifest […], [Warszawa 1733]",
    "Metryka Obolecka":"Wypisy z ksiąg metrykalnych paraﬁ i Obolce i notaty pamiętnikarskie Jana Antoniego Weyssenhoﬀ a (kserokopia w posiadaniu Tomasza Jaszczołta)",
    "MGChSz":"З. Яцкевiч, Малы гербоўнiк Халапенiцкай шляхты, Мiнск 1999",
    "Michalon Litwin":"Михалон Литвин, О нравах Татар, Литовцев и Москвитян, ред. А.Л. Хорошкевич, Москва 1994",
    "Mienicki, Rejestr":"R. Mienicki, Rejestr popisowy województwa połockiego z dn. 30.XI.1765 r., „Ateneum Wileńskie” R. XI, Wilno 1936, s. 303–342",
    "Mienicki, Trzy dokumenty":"Trzy dokumenty z wieku XV dotyczące ziemi połockiej, podał R. Mienicki, „Ateneum Wileńskie”, R. VII, 1930, s. 893–903",
    "Mies.":"Месяцеслов с росписью чиновных особ в Государстве на лето от Рождества Христова ... (od r. 1805: Месяцеслов с росписью чиновных особ или Общий штат Российской Империи на лето от Рождества Христова...) ...",
    "Mietryka WKL 28":"Метрыка Вялікага Княства Літоўскага. Kніга 28 (1522–1552), падр. В. Мянжынскі, Менск 2000",
    "Mietryka WKL 44":"Метрыка Вялікага Княства Літоўскага. Kніга 44 (1559–1566), падр. А.І. Груша, Мінск 2001",
    "Mietryka WKL 70":"Метрыка Вялікага Княства Літоўскага. Kніга 70 (1582–1585), падр. А.А. Мяцельскі, Мінск 2008",
    "MK":"Metryka Koronna w AGAD w Warszawie",
    "ML":"Metryka Litewska w RGADA (F. 389) w Moskwie",
    "MLKS":"Metryka Litewska. Księga Sigillat 1709–1719, oprac. A. Rachuba, Warszawa 1987",
    "MLKW 131":"Metryka Litewska. Księga Wpisów nr 131, oprac. A. Rachuba, Warszawa 2001",
    "MNKr.":"Muzeum Narodowe w Krakowie",
    "Naruszewicz, Diariusz":"A.S. Naruszewicz, Dyjaryjusz podróży Jego Królewskiej Mości na Sejm Grodzieński, wyd. M. Bober-Jankowska, Warszawa 2008",
    "Naruszewicz, Żywot":"Żywot J.K. Chodkiewicza wojewody wileńskiego, hetmana wielkiego W. Ks. Lit. przez Adama Naruszewicza, t. I–II, wyd. K.J. Turowskiego, Kraków 1858",
    "NBB":"Нацыянальнaя библиотека Беларусі",
    "NGABGr.":"Нацыянальны гістарычны архіў Беларусі w Grodnie",
    "NGABM":"Нацыянальны гістарычны архіў Беларусі w Mińsku",
    "Nies.":"K. Niesiecki, Herbarz polski, t. I–X, wyd. J.N. Bobrowicz, Lipsk 1839–1846",
    "Ochmański":"J. Ochmański, Historia Litwy, Wrocław–Warszawa 1982",
    "Olkieniki":"Postanowienie Generalne Stanów WXLit. - na Zjeździe Walnym woiewództw y powiatów, pospolitym ruszeniem pod Olkienikami uchwalone, RP 1700, Wilno 1700 ",
    "pisanije ROVPB":"Описанiе рукописнаго отделения Виленской публичной бивлiотеки, t. I–V, Вильна 1893–1906",
    "Osiński":"A. Osiński, Żywoty biskupów wileńskich, t. 1, Warszawa 1856",
    "Oss.":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "Ossoliński":"J.M. Ossoliński, Wiadomości historyczno-krytyczne do dziejów literatury polskiey, o pisarzach polskich, także postronnych…, t. II, Kraków 1819",
    "Ostrowskich":"Archiwum Ostrowskich z Ujazdu w AGAD",
    "Pamjatniki dipł. snoszenij":"Памятники дипломатических сношений древней России с державами иностранными, t. I, S.-Петербург 1851",
    "PANKr.":"Biblioteka Naukowa PAU i PAN w Krakowie",
    "Pasiecznik":"J. Pasiecznik OFM, Kościół i klasztor Franciszkanów w Zakliczynie nad Dunajcem, Kraków 1992",
    "Petrauskas":"R. Petrauskas, Lietuvos diduomenė XIV a. pabaigoje - XV a.",
    "Sudėtis":"struktūra valdžia, Vilnius 2003",
    "Pierapis wojska 1528":"Перапіс войска Вялікага княства Літоўскага 1528 года, падр. А.І. Груша, М.Ф. Спірыдонаў, М.А. Вайтовіч, Мінск 2003",
    "Pietkiewicz":"K. Pietkiewicz, Wielkie Księstwo Litewskie pod rządami Aleksandra Jagiellończyka. Studia nad dziejami państwa i społeczeństwa na przełomie XV i XVI wieku, Oświęcim 2014 (wyd. II poprawione)",
    "Piłsud.":"Archiwum Giniatowiczów Piłsudskich w AGAD",
    "Poczet szlachty":"Poczet szlachty galicyjskiej i bukowińskiej, Lwów 1857",
    "Poczobut":"J.W. Poczobut Odlanicki, Pamiętnik (1640–1684), oprac. A. Rachuba, Warszawa 1987",
    "Podymne min.":"Падымные рэестры Менскага ваяводства. Менскi павет 1775. Rejestry podymnego województwa mińskiego. Powiat miński 1775, укл. Д. Дрозд, Мiнск 2014",
    "Podymne nowogr.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo nowogródzkie 1690 r., red. A. Rachuba, oprac. H. Lulewicz, A. Rachuba, Warszawa 2002",
    "Połock 2012":"Древнейшие города Беларуси: Полоцк (praca zbiorowa), ред. А.А. Коваленя, О.Н. Левко и другие, Минск 2012",
    "Połockije gram., I–VI":"Полоцкие грамоты XIII - начала XVI вв., t. I–VI, сост. А.Л. Хорошкевич, Москва 1978–1982",
    "Połockije gram. 2015, I-II":"Полоцкие грамоты XIII - начала XVI вв., t. I–II, подг. А.Л. Хорошкевич, С.В. Полехов, В.А. Воронин, А.И. Груша, А.А. Жлутко, Е.Р. Сквайрс, А.Г. Тюльпин, Москва 2015",
    "Prinke, Sikorski":"R.T. Prinke, A. Sikorski, Królewska krew. Polscy potomkowie Piastów i innych dynastii panujących, Poznań 1997",
    "Prozorów":"Archiwum Prozorów i Jelskich w AGAD",
    "Przezdz.":"Archiwum Przezdzieckich w AGAD",
    "PSB":"Polski słownik biograficzny, Kraków 1935,",
    "PSRL":"Полное cобрание русских летописей, t. 32: Хроники: Литовская и Жмойтская, и Быховца, Москва 1975; t. 35: Летописи белорусско-ли- товские, Москва 1980",
    "Ptaszycki, Sprostowania":"S. Ptaszycki, Dzieje rodów litewskich jako materyjał do archeologii historycznej, Warszawa 1888 (odbitka z „Ateneum”, t. III, 1888, z. 3)",
    "Ptaszycki, Z dziejów":"S. Ptaszycki, Z dziejów starego rodu, „Charitas” - księga zbiorowa, Petersburg 1894",
    "Racz.":"Miejska Biblioteka Publiczna im. E. Raczyńskiego w Poznaniu",
    "Radaman":"A. Радаман, Арганізацыя і склад полацкага земскага суда ў другой палове XVI - першай треці XVII ст., „Герольд Litherland”, 18, 2011, s. 21–36",
    "RadzMem.":"A.S. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I–IV, wyd. A. Przyboś, R. Żelewski, Wrocław 1968–1974",
    "Rejestr przysięgowy":"Rejestr przysięgowy szlachty Wielkiego Księstwa Litewskiego 1655 r., edit. E.E. Lykova, M. Kulecki, w: Monumenta historica resgestas Europae Orientalis illustrantia, Fontes XV–XVII saec., t. IV, red. H. Grala, Moscoviae–Varsoviae 1999",
    "Rewizija 1552":"Рэвізія Полацкага ваяводства 1552 года, уклаў В. Варонін, Менск 2011.",
    "RGADA":"Российский государственный архив древних актов w Moskwie",
    "RGBM":"Российская государственная библиотека w Moskwie",
    "RGIA":"Российский государственный исторический архив w Sankt Petersburgu",
    "RGV":"А. Радаман, В. Галубовіч, Д. Вілімас, Земскіе ўраднікі Полацкага ваяводства (другая палова XVI - першая палова XVII стст., „Com- mentarii Polocenses Historici”, t. I, 2006, s. 73–80",
    "RIB":"Русская Историческая Библиотека, t. XX (Литовская метрика, часть 2, т. 1: Книги судных дел, С.-Петербург 1903); t. XXVII (Литов- ская метрика, часть 1, т. 1: Книги записей, С.-Петербург 1910); t. XXXIII (Литовская метрика, часть 3, т. 1: Книги публичных дел: Переписи войска литовского, изд. С. Пташицкиий, Петроград 1915)",
    "R(W)M":"Metryka Ruska (Wołyńska). Regesty dokumentów kancelarii koronnej dla ziem ukraińskich (województw wołyńskiego, bracławskiego, kijowskiego i czernihowskiego) 1569–1673, Kijów 2002",
    "RNBSPet.":"Российская национальная библиотека w Sankt Petersburgu",
    "Roskie, r.-m.":"AGAD, Archiwum Roskie, Akta rodzinno-majątkowe",
    "Rowell":"S.C. Rowell, The Role of Charitable Activity in the Formation of Vilnius Society in the 14 th to Mid–16 th Centuries, „Lithuanian Historical Studies”, XVII, 2012",
    "„Rubon”":"„Rubon. Pismo zbiorowe poświęcone pożytecznej rozrywce”, t. VIII, wyd. K. Bujnicki, Wilno 1847",
    "Rus.-Liw. Akty":"Russisch-Livländische Urkunden [tytuł ros.: Руско-ливонские акты], von K.E. Napiersky, Sankt Peterburg 1868",
    "Rybczonak, Swiażynski":"С. Рыбчонак, У. Свяжынскi, Радавод Корсаков гербу Корсак, „Спадчына”, 2, 2000, s. 200–216",
    "Rzońca":"J. Rzońca, Sejmy z lat 1597 i 1598, cz. I: Bezowocny sejm z 1597 roku, Warszawa–Wrocław 1989",
    "S...cki":"S...cki, Dostojnicy litewscy. Rozbiór krytyczny i uzupełnienia dzieła J. Wolﬀ a, Senatorowie, „Ateneum”, t. I, 1886",
    "Sang.":"Archiwum Sanguszków w ANKr., Oddział na Wawelu",
    "Sapiehowie":"Sapiehowie. Materjały historyczno-genealogiczne i majątkowe, t. I–III, Petersburg 1890–1894",
    "Sawicki":"M. Sawicki, Stronnictwo dworskie w Wielkim Księstwie Litewskim w latach 1648–1655, Opole 2010",
    "Sbornik dok. Siew.-Zap. kraja":"Сборник документов, касающихся адми- нистративного устройства Северо-Западного края при императрице Екатерине II (1792–1796), Вильна 1903",
    "Selart":"A. Сэларт, Полацкі князь Канстанцін і гісторыя Інфлянтаў у трэцяй чвэрці XIII ст. (tytuł oryginału: Der Fürst Konstantin von Polazk und die Geschichte Livlands im dritten Viertel des XIII Jh.), „Беларускі Гістарычны Агляд”, t. XI, Менск 2004, s. 3–25",
    "Semkowicz":"W. Semkowicz, O litewskich rodach bojarskich zbratanych ze szlachtą polską w Horodle roku 1413, „Lituano-Slavica Posnaniensia”, R. III, 1989, s. 7–139",
    "SGKP":"Słownik geografi czny Królestwa Polskiego i innych krajów słowiańskich, t. I–XV, Warszawa 1880–1900",
    "Sig.":"Sigillata (Księgi Sigillat) Metryki Koronnej w AGAD",
    "Sliesoriūnas":"G. Sliesoriūnas, Sejmiki nowogródzkie w okresie bezkrólewia 1696/1697 r. a nadanie językowi polskiemu statusu urzędowego w  Wielkim Księstwie Litewskim, w: Między Zachodem a Wschodem. Studia z dziejów Rzeczypospolitej w epoce nowożytnej, red. J. Staszewski, K. Mikulski, J. Dumanowski, Toruń 2002",
    "Sobieski":"Jakuba Sobieskiego, Pamiętnik wojny chocimskiej, xiąg troje, tłumaczenie i oprac. W. Syrokomla, Petersburg 1854",
    "Sozański":"A. Sozański, Imienne spisy osób duchownych, świeckich i wojskowych, które w pierwszych ośmiu latach panowania króla Stanisława Poniatowskiego od 1764–1772 r. w rządzie lub przy administracyi Rzeczypospolitej udział brały […], cz. I: Tablice i rejestr, Kraków 1866",
    "SRP":"Scriptores Rerum Polonicarum, t. V (Archiwum Komisyi Historycznej, t. II): Rewizya województwa połockiego z roku 1552, wyd. J. Szujski, Kraków 1880, s. 173–255",
    "Stryjkowski":"M. Stryjkowski, Kronika Polska, Litewska, Żmódzka i wszystkiej Rusi, t. I–II, Warszawa 1846",
    "Sucha":"Zbiór Branickich z Suchej w AGAD Suﬀ ragia 1733 - Suﬀ ragia Woiewodztw y Ziem Koronnych y W. X. Litewskiego Zgodnie na Nayiaśnieyszego Stanisława Pierwszego, Obranego Króla Polskiego Wielkiego Xiążęcia Litewskiego, Ruskiego, Pruskiego, Mazowieckiego, Zmudzkiego, Kijowskiego, Wołyńskiego, Podolskiego, Smoleńskiego, Infl antskiego y Czerniechowskiego. Dane między Warszawą a Wolą Dnia Dwudziestego Piątego Sierpnia [s] Roku Pańskiego Tysiącznego Siedmsetnego Trzydziestego Trzeciego [Warszawa 1733] (egz. m.in. APP 71, s. 189–325 [181–317])",
    "Suplement Generalney Konfederacyi":"Konfederacya generalna nierozdzielnie całey prowincyey W. X. Litew. z woyskiem, zgodnie od Woiewodztw, ziem, y powiatów uczyniona w Wilnie Anno D. 1716. mies: Marca dnia 23, Wilno [1716]",
    "Tabl. Korsaków":"Tablica genealogiczna rodu Korsaków w posiadaniu Michała Bartłomieja Korsaka",
    "Tęgowski":"J. Tęgowski, Pierwsze pokolenia Giedyminowiczów, Poznań-Wrocław 1999",
    "TML":"Transkrypcje Metryki Lit. w AGAD Warszawa",
    "Trybunał I":"Deputaci Trybunału Głównego Wielkiego Księstwa Litewskiego 1582–1696. Spis, red. A. Rachuba, oprac. H. Lulewicz, A. Rachuba, Warszawa 2007",
    "Trybunał II":"Deputaci Trybunału Głównego Wielkiego Księstwa Litewskiego 1697–1794. Spis, red. A. Rachuba, oprac. A. Rachuba, P.P. Romaniuk przy współpracy A. Macuka i J. Aniszczenki, Warszawa 2004",
    "Tworek":"S. Tworek, Materiały do dziejów kalwinizmu w Wielkim Księstwie Litewskim w XVII wieku, „Odrodzenie i Reformacja w Polsce”, t. XIV, 1969",
    "Tyszkiewicz":"E. T[yszkiewicz], O klasztorach zgromadzeń istniejących obecnie w Dyecezyi Wileńskiej, „Teka Wileńska”, 1858, nr 4",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII–XVIII wieku. Spisy, red. A. Gąsiorowski, t. I n., Wrocław–Kórnik 1985 n.",
    "Umaniec":"Ф.М. Уманец, Русско-литовская партия в Польше 1574–1576 гг., w: „Журналъ Министерства народного просвещения”, cz. 182 (XII 1875)",
    "Uruski":"S. Uruski, A.A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I–XV, Uzupełnienia t. I–VI, Warszawa 1904–1938",
    "UWKL":"Urzędnicy Wielkiego Księstwa Litewskiego. Spisy",
    "VC":"Volumina Constitutionum, t. 3, cz. 2, przygotowali S. Grodziski, M. Kwiecień, A. Karabowicz, przedmowa W. Uruszczak, Warszawa 2013",
    "Vilimas":"D. Vilimas, Lietuvos Didžiosios Kunigaikštystės žemės teismo sistemos formavimasis (1564–1588), Vilnius 2006",
    "Vitsko":"D. Vitsko, Stanowisko Wiśniowieckich wobec sporów o sejm konny w 1698 roku, w: Kultura parlamentarna epoki staropolskiej, red. A. Stroynowski, Warszawa 2013",
    "VL":"Volumina legum, t. I–X, Petersburg 1859, Kraków 1889, Poznań 1952",
    "VUB":"Vilniaus universiteto bibliotekos rankraščių skyrius ",
    "Waronin, Drysa":"В. Варонін, Дрыса у XVI ст., „Commentarii Polocenses Historici”, t. I, 2006, s. 20–31",
    "Waronin, Kroniczka":"В. Варонін, Wielkiego Księstwa Litewskiego Kroniczka krotko pisana, „Беларускі Гістарычны Агляд”, t. XI, Менск 2004, s. 40–54",
    "Waronin, Palityczny ład":"В. Варонін, Палітычны лад Полацкага ваяводства ў першай палове XVI ст., „Беларускі Гістарычны Агляд (Belorusian Historical Review)”, t. V/1, Менск 1998, s. 27–66",
    "Waronin, Wajna 1512–1522":"В.А. Варонін, Падзеі вайны 1512–1522 гадоў у Беларускім Падзвінні, w: Studia historica Europae Orientalis, выпуск VI, Мінск 2013, s. 192–218",
    "Wolański":"A. Wolański, Wojna polsko-rosyjska 1792 r., Warszawa 1996",
    "Wolﬀ":"J. Wolﬀ , Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386–1795, Kraków 1885 (egzemplarz z BN z własnoręcznymi popraw- kami i uzupełnieniami autora) ",
    "Wolﬀ Kn.":"J. Wolﬀ , Kniaziowie litewsko-ruscy od końca czternastego wieku, Warszawa 1895",
    "Zabiełłów":"Archiwum Zabiełłów w AGAD",
    "Zaliwaka":"А. Залiвака, Фасцыкул III–V, Мiнск 2013–2015",
    "Zb. Czoł.":"Zbiór Czołowskiego w AGAD",
    "Zb. Rus.":"Zbiór Rusieckich w ANKr.",
    "Zbiór aktów":"Zbiór aktów do historyi ustroju sądów prawa polskiego i kancelarii sądowych województwa krakowskiego z wieku XVI–XVIII, wyd. S. Kutrzeba, Archiwum Komisji Prawniczej, t. VIII cz. 2, Kraków 1909",
    "ZKW":"Zamek Królewski w Warszawie",
    "ZMRP":"Zbiór materiałów różnej proweniencji w AGAD",
    "ZZG":"Zbiór Zygmunta Glogera w ANKr., Oddział na Wawelu",
    "Żukowicz, Uprawlenije i sud":"П.Н. Жукович, Управление и суд в Западной России в царствование Екатерины II, „Журналъ Министерства народного просвещения”, Март-май, июль, 1914",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. I n., Poznań 1879 n.",
    "III Statut Lit.":"Статут Вялікага Княства Літоўскага 1588, Мінск 2010"
}