""" słownik skrótów literatury """

literatura = {
    "AAGn.":"Archiwum Archidiecezjalne w Gnieźnie",
    "AAP":"Archiwum Archidiecezjalne w Poznaniu",
    "ABMK":"„Archiwa, Biblioteki i Muzea Kościelne”",
    "ACap.":"Acta capitulorum nec non iudiciorum ecclesiasticorum selecta, wyd. B. Ulanowski, T. I-III, Kraków 1894-1908 ",
    "ADPł.":"Archiwum Diecezjalne w Płocku",
    "ADWł.":"Archiwum Diecezjalne we Włocławku",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, T. II n., wyd. O. Pietruski, X. Liske, Lwów 1870-1891",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKP":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "Akta unii":"Akta unii Polski z Litwą 1386-1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "Ämterbuch":"Das grosse Ämterbuch des Deutschen Ordens, wyd. W. Ziesemer, Danzig 1921",
    "Ann. Byszev.":"Annalium coenobii Byszeviensis seu Coronoviensis tomus I ab anno 1200 ad annum 1400, Biblioteka Raczyńskich w Poznaniu, rkp. 134",
    "APBydg.":"Archiwum Państwowe w Bydgoszczy",
    "APGd.":"Archiwum Państwowe w Gdańsku",
    "APP":"Archiwum Państwowe w Poznaniu",
    "APTor.":"Archiwum Państwowe w Toruniu",
    "ASPK":"Akta stanów Prus Królewskich, T. I, wyd. K. Górski, M. Biskup, Toruń 1955 ",
    "ASTPr.":"Acten der Ständetage Preussens unter der Herrschaft des Deutschen Ordens, wyd. M. Toeppen, T. I, Leipzig 1874",
    "BCzart.":"Biblioteka XX. Czartoryskich w Krakowie",
    "BielKancWŁ":"M. Bielińska, Kancelaria Władysława Łokietka w latach 1296-1299, SŹ 6, 1961",
    "BienDobrzWyw":"J. Bieniak, Dobrzyński wywód szlachectwa z 1378 roku, w: Heraldyka i okolice, Warszawa 2002",
    "BienDoliw":"J. Bieniak, Doliwowie w XIII wieku, w: Cracovia - Polonia - Europa, Kraków 1995",
    "BienElitaD":"J. Bieniak, Elita ziemi dobrzyńskiej w późnym średniowieczu i jej majątki, w: Stolica i region. Włocławek i jego dzieje na tle przemian Kujaw i ziemi dobrzyńskiej, Włocławek 1995",
    "BienElitaK":"J. Bieniak, Elita kujawska w średniowieczu, w: Człowiek w społeczeństwie średniowiecznym, Warszawa 1997",
    "BienKoścW":"J. Bieniak, Kościelna Wieś i jej dziedzice w średniowieczu, w: Kościelna Wieś na Kujawach. Studium osadnicze, Łódź 1994",
    "BienKsztZD":"J. Bieniak, Kształtowanie się terytorium ziemi dobrzyńskiej w Średniowieczu, ZH 51, 1986, z. 3",
    "BienList":"J. Bieniak, List kanclerza kujawskiego do rady Starego Miasta Torunia ze stycznia 1331 roku, ZK-D 1, 1978",
    "BienOdzysk":"J. Bieniak, Odzyskanie zachodnich Kujaw przez Kazimierza Wielkiego w 1337 r., ZH 39, 1974",
    "BienPowst":"J. Bieniak, Powstanie miasta samorządowego - najstarsze lokacje miejskie, w: Włocławek. Dzieje miasta, T. I, Włocławek 1999",
    "BienPPatr":"J. Bieniak, Prawa patronackie szlachty kujawskiej w kościołach parafialnych w świetle źródeł, w: Religijność na Kujawach i ziemi dobrzyńskiej w czasach staropolskich, Włocławek 2003",
    "BienPrzyn":"J. Bieniak, Przynależność administracyjno-polityczna kasztelanii nadgoplańskich w latach 1267-1327, Zeszyty Naukowe UMK w Toruniu, Historia 2, 1966",
    "BienRadziki":"J. Bieniak, Radziki (Radzikowo) i ich dziedzice w średniowieczu, w: Zamek w Radzikach Dużych na ziemi dobrzyńskiej, Rypin 2009",
    "BienRecPrChełm":"J. Bieniak, Recepcja prawa chełmińskiego na Kujawach i ziemi dobrzyńskiej w średniowieczu, Studia Culmensia Historico-Juridica, T. 1, Toruń 1990",
    "BienRŁab":"J. Bieniak, Ród Łabędziów, w: Genealogia. Studia nad wspólnotami krewniaczymi i terytorialnymi w Polsce średniowiecznej na tle porównawczym, Toruń 1987",
    "BienRyp":"J. Bieniak, Od wójtów Rypina do rodu szlacheckiego (Starorypińscy w XIV i XV stuleciu), w: Rypin. Szkice z dziejów miasta, Rypin  1994",
    "BienSadł":"J. Bieniak, Sadłowo i jego dziedzice w średniowieczu, w: Zamek w Sadłowie na ziemi dobrzyńskiej, Rypin 2004",
    "BienSpołK":"J. Bieniak, Społeczeństwo Kujaw w średniowieczu, w: Dwie części Kujaw. Związki i podziały w dziejach regionu, Włocławek-Inowrocław 2001",
    "BienŚrPRody":"J. Bieniak, Średniowieczne polskie rody rycerskie. Stan badań, problemy sporne, możliwości i trudności badawcze, w: Genealogia. Stan i perspektywy badań nad społeczeństwem Polski średniowiecznej na tle porównawczym, Toruń 2003",
    "BienWlkp":"J. Bieniak, Wielkopolska, Kujawy, ziemie łęczycka i sieradzka wobec problemu zjednoczenia państwowego w latach 1300-1306, Toruń 1969",
    "BienWładza":"J. Bieniak, Władza a społeczeństwo w świetle źródeł. Cztery epizody funkcjonowania sądu staropolskiego na Kujawach, w: Genealogia. Władza i społeczeństwo w Polsce średniowiecznej, Toruń 1999",
    "BienZapomn":"J. Bieniak, Zapomniana generacja Kościeleckich, w: Drogą historii. Studia ofiarowane profesorowi Józefowi Szymańskiemu..., Lublin 2001",
    "BienŻerk":"J. Bieniak, Krąg rodzinny Jadwigi z Żerkowa, w: Homines et societas. Czasy Piastów i Jagiellonów, Poznań 1997",
    "Biliński":"A. Biliński, Szlachta ziemi dobrzyńskiej za ostatnich Jagiellonów, Warszawa 1932",
    "BiskupZj":"M. Biskup, Zjednoczenie Pomorza Wschodniego z Polską w połowie XV wieku, Warszawa 1959",
    "BJag.":"Biblioteka Jagiellońska w Krakowie",
    "BobrG":"Księgi grodzkie bobrownickie w AGAD",
    "BobrZ":"Księgi ziemskie bobrownickie (oblaty) w AGAD",
    "Bon.":"A. Boniecki, Herbarz polski, T. I-XVI, Warszawa 1899-1913",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "BrzezZ":"Księgi ziemskie brzezińskie w AGAD",
    "BrzG":"Księgi grodzkie brzeskie w AGAD",
    "BrzZ":"Księgi ziemskie brzeskie w AGAD",
    "BullPol":"Bullarium Poloniae, wyd. S. Kuraś, I. Sułkowska-Kuraś [i in.], T. I n., Romae–Lublini 1982 n.",
    "CDPr.":"Codex diplomaticus Prussicus, wyd. J. Voigt, T. IV, Königsberg 1857",
    "ChronPol":"Chronologia polska, red. B. Włodarski, Warszawa 1957",
    "CodVit":"Codex epistolaris Vitoldi magni ducis Lithuaniae 1376-1430, wyd. A. Prochaska, Kraków 1882",
    "CVAT":"AGAD, Księgi ziemskie brzeskie, kopie: Copiae variorum actorum terrestrium 1399-1590",
    "CzwojRog":"B. Czwojdrak, Rogowscy herbu Działosza podskarbiowie królewscy. Studium z dziejów możnowładztwa w drugiej połowie XIV i w XV wieku, Katowice 2002",
    "DłAnn":"Ioannis Dlugossii Annales seu cronicae incliti Regni Poloniae, lib. IX, X/XI, XI, XII, Warszawa 1978-2003",
    "DocBidg":"Documenta Ecclesias [sic!] Civitatis Bidgostiensis (Bromberg) concernentia, Berlin 1918",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae, wyd. M. Dogiel, T. IV, Wilno 1764",
    "DokKujDobrz":"Dokumenty do dziejów Kujaw i ziemi dobrzyńskiej XIV-XIX w., wyd. Z. Guldon, R. Kabaciński, M. Kallas, J. Wojciak, Warszawa 1974",
    "DokMełn":"Dokumenty strony polsko-litewskiej pokoju mełneńskiego z 1422 roku, wyd. P. Nowak, P. Pokora, Poznań 2004",
    "Dwa fragmenty":"Dwa fragmenty ksiąg kancelaryjnych królewskich z 1-ej połowy XV wieku, wyd. T. Wierzbowski, Warszawa 1907",
    "Epist.":"Codex epistolaris saeculi decimi quinti, T. I-III, wyd. A. Sokołowski, J. Szujski, A. Lewicki, Kraków 1891–1894",
    "GąsForm":"A. Gąsiorowski, Formularz dokumentów traktatów polsko-krzyżackich z XIV-XV w., Archeion 66, 1978",
    "GąsItinWJ":"A. Gąsiorowski, Itinerarium króla Władysława Jagiełły 1386-1434, Warszawa 1972",
    "GąsKan":"A. Gąsiorowski, Kanonicy włocławscy w najstarszej metryce kapitulnej (1435-1500), w: Duchowieństwo kapitulne w Polsce średniowiecznej i wczesnonowożytnej. Studia nad pochodzeniem i funkcjonowaniem elity kościelnej, Toruń 2000",
    "GąsStar":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej, Warszawa 1981",
    "GnieznoG":"Księgi grodzkie gnieźnieńskie w APP",
    "GnieznoZ":"Księgi ziemskie gnieźnieńskie w APP",
    "GStAPK":"Geheimes Staatsarchiv Preussischer Kulturbesitz, Berlin-Dahlem",
    "GuldonLok":"Z. Guldon, Lokacje miast kujawskich i dobrzyńskich w XII–XVI w., ZK 2, 1968",
    "GuldPowPodz":"Z. Guldon, J. Powierski, Podziały administracyjne Kujaw i ziemi dobrzyńskiej w XII–XIV wieku, Warszawa 1974",
    "IMT":"Iura Masoviae terrestria, T. I-III, wyd. J. Sawicki, Warszawa 1972-1974",
    "InscrClen":"Inscriptiones clenodiales ex libris iudicialibus palatinatus Cracouiensis, wyd. B. Ulanowski, SPPP VII/3, Kraków 1885",
    "IP":"Ius Polonicum codicibus veteribus, manuscriptis et editionibus quibusque collatis, wyd. J. V. Bandtkie, Warszawa 1831",
    "ISB":"Inowrocławski słownik biograficzny, T. 2-4, Inowrocław 1994-2000",
    "JóźwRozDok":"J. Jóźwiak, W. Rozynkowski, Dokument układu w sprawie przynależności dziesięcin ze wsi Markowo na Kujawach z 16 marca 1383 roku, ZK 16, 2003, s. 185-191",
    "KaliszG":"Księgi grodzkie kaliskie w APP",
    "KaliszZ":"Księgi ziemskie kaliskie w APP",
    "KarczRKotw":"J. Karczewska, Ród Kotwiców na Kujawach w średniowieczu, Genealogia 14, 2002",
    "KarczRPom":"J. Karczewska, Ród Pomianów na Kujawach w średniowieczu, Poznań 2003",
    "KarczUrz":"J. Karczewska, Urzędnicy książąt kujawskich: Leszka, Przemysła i Kazimierza Ziemomysłowiców, cz. 1-2, ZK 12-13, 1997-1998",
    "KarczWłasn":"J. Karczewska, Własność szlachecka na pograniczu wielkopolsko-kujawskim w pierwszej połowie XV wieku, Kraków 2010",
    "KarDok":"D. Karczewski, Kujawskie dokumenty księcia słupskiego Kazimierza IV (Kaźka) z lat 1371-1376, cz. 1-2, ZH 67, 2002, z. 1-2",
    "KarLokRadz":"D. Karczewski, Lokacja Radziejowa na tle urbanizacji średniowiecznych Kujaw, w: Radziejów poprzez stulecia. Materiały sesji naukowej „Radziejów poprzez stulecia. W 750-lecie nadania praw miejskich dla Radziejowa” zorganizowanej 11 maja 2002 r. w Radziejowie, pod red. D. Karczewskiego, Włocławek 2002",
    "KatTor I":"Katalog dokumentów i listów krzyżackich oraz dotyczących wojny trzynastoletniej z Archiwum Państwowego w Toruniu, T. 2, opr. A. Radzimiński, J. Tandecki, Warszawa 1998 ",
    "KatTor II":"Katalog dokumentów i listów królewskich z Archiwum Państwowego w Toruniu, opr. A. Radzimiński, J. Tandecki, Warszawa 1999",
    "KcyniaG":"Księgi grodzkie kcyńskie w APP",
    "KcyniaZ":"Księgi ziemskie kcyńskie w APP",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej Ś. Wacława, T. I-II, wyd. F. Piekosiński, Kraków 1874-1883",
    "KDKM":"Kodeks dyplomatyczny księstwa mazowieckiego, wyd. J. T. Lubomirski, Warszawa 1863",
    "KDLit":"Codex diplomaticus Lithuaniae, wyd. E. Raczyński, Wrocław 1845",
    "KDM":"Kodeks dyplomatyczny Małopolski, T. I-IV, wyd. F. Piekosiński, Kraków 1876-1905",
    "KDMK":"Kodeks dyplomatyczny miasta Krakowa, wyd. F. Piekosiński, cz. I, Kraków 1879",
    "KDNiewodn":"Katalog dokumentów pergaminowych ze zbiorów Tomasza Niewodniczańskiego w Bitburgu, opr. J. Tomaszewicz, M. Zdanek, pod red. W. Bukowskiego, Kraków 2004",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, wyd. A. Gąsiorowski, T. Jasiński, T. Jurek, H. Kowalewicz, F. Piekosiński, I. Skierska, R. Walczak, [I. Zakrzewski], T. I-XI, Poznań 1877-1999",
    "KH":"„Kwartalnik Historyczny”",
    "KMaz":"Zbiór ogólny przywilejów i spominków mazowieckich, T. I, wyd. J. K. Kochanowski, Warszawa 1919",
    "KMog":"Zbiór dyplomów klasztoru mogilskiego, wyd. E. Janota, Kraków 1867",
    "Knigi":"Knigi polskoj koronnoj mietriki XV stoletija. Matricularum Regni Poloniae codices, wyd. A. Mysłowski, W. Graniczny, Warszawa 1914",
    "KoninG":"Księgi grodzkie konińskie w APP",
    "KoninZ":"Księgi ziemskie konińskie w APP",
    "KościanZ":"Księgi ziemskie kościańskie w APP",
    "KowG":"Księgi grodzkie kowalskie w AGAD",
    "KowZ":"Księgi ziemskie kowalskie w AGAD",
    "KPol.":"Codex diplomaticus Poloniae, T. I-IV, wyd. N. Bobowski, A. Muczkowski, L. Rzyszczewski, Warszawa 1847-1887",
    "KsTheud":"Księga Theudenkusa, wyd. L. Koczy, Toruń 1937",
    "KsŻołdu":"Księga żołdu Związku Pruskiego z okresu wojny trzynastoletniej 1454-1466, wyd. A. Czacharowski, Toruń 1969",
    "KZPoz":"Księga ziemska poznańska 1400-1407, wyd. K. Kaczmarczyk, K. Rzyski, Poznań 1960",
    "Lasocki":"Z. Lasocki, Dostojnicy i urzędnicy ziemi dobrzyńskiej w XIV i XV wieku, „Miesięcznik Heraldyczny” 13, 1934",
    "LCSCiołek":"Liber cancellariae Stanislai Ciołek, wyd. J. Caro, T. I-II, Wien 1871-1874",
    "Leksz.":"Die ältesten grosspolnischen Grodbücher, wyd. J. Lekszycki, T. I-II, Leipzig 1887-1889",
    "LelewelPocz":"J. Lelewel, Początkowe prawodawstwo polskie cywilne i kryminalne do czasów jagiellońskich, Warszawa 1828",
    "Lites":"Lites ac res gestae inter Polonos Ordinemque Cruciferorum: Lites1: wyd. A. T. Działyński, Poznań 1855-1856; Lites2: Editio altera, [wyd. I. Zakrzewski], T. I-II, Poznań 1890-1892; Lites3: wyd. H. Chłopocka, T. I, Wrocław 1970",
    "LScabVCT":"Liber scabinorum Veteris Civitatis Thorunensis 1363-1428, wyd. K. Kaczmarczyk, Toruń 1936",
    "Ludwig":"M. Ludwig, Besteuerung und Verpfändung königlicher Städte im spätmittelalterlichen Polen, Berlin 1984",
    "ŁęczG":"Księgi grodzkie łęczyckie w AGAD",
    "ŁęczZ":"Księgi ziemskie łęczyckie w AGAD",
    "MaleczKilka":"K. Maleczyński, Kilka nieznanych dokumentów z XIII w. przeważnie z archiwów poznańskich, KH 40, 1926",
    "MaleczKilkanaście":"K. Maleczyński, Kilkanaście dokumentów Władysława Łokietka z lat 1295-1329, SŹ 6, 1961",
    "MarzecUrz":"A. Marzec, Urzędnicy małopolscy w otoczeniu Władysława Łokietka i Kazimierza Wielkiego 1305-1370, Kraków 2006",
    "MitkKanc":"J. Mitkowski, Kancelaria Kazimierza Konradowica księcia kujawsko-łęczyckiego 1233-1267, Wrocław 1968",
    "MK":"Księgi wpisów Metryki Koronnej w AGAD ",
    "MM":"Metryka Księstwa Mazowieckiego z XV-XVI wieku, T. II, wyd. A. Włodarski, Warszawa 1930",
    "MosbWiad":"Wiadomości do dziejów polskich z Archiwum Prowincji Szląskiej, zebrał A. Mosbach, Wrocław 1860",
    "MożRŚw":"B. Możejko, Ród Świnków na pograniczu polsko-krzyżackim w średniowieczu, Gdańsk 1998",
    "MPH":"Monumenta Poloniae historica i MPH seria nowa (sn.) ",
    "MPV":"Monumenta Poloniae Vaticana",
    "MRPS":"Matricularum Regni Poloniae summaria, T. I-IV, wyd. T. Wierzbowski, Warszawa 1905-1917",
    "NakłoG":"Księgi grodzkie nakielskie w APP",
    "Neitmann":"K. Neitmann, Die Pfandverträge des Deutschen Ordens in Preussen, „Zeitschrift für Ostforschung“ 41, 1992, z. 1: dodatki.",
    "NiwDWąch":"M. Niwiński, Dokumenty Łokietka dla dóbr łęczyckich opactwa wąchockiego, KH 46, 1932",
    "NKDM":"Nowy kodeks dyplomatyczny Mazowsza, cz. II-III, wyd. I. Sułkowska-Kuraś i S. Kuraś, Warszawa 1989-2000",
    "NowakWłasn":"T. Nowak, Własność ziemska w ziemi łęczyckiej w czasach Władysława Jagiełły, Łódź 2002",
    "NowSzpetal":"J. Nowacki, Opactwo św. Gotarda w Szpetalu pod Włocławkiem zakonu cysterskiego, Gniezno 1934",
    "OrłZ":"Księgi ziemskie orłowskie w AGAD",
    "OżógInt":"K. Ożóg, Intelektualiści w służbie Królestwa Polskiego w latach 1306-1382, Kraków 1995",
    "PacGost":"K. Pacuski, Możnowładztwo i rycerstwo ziemi gostynińskiej w XIV i XV wieku, Warszawa 2009",
    "PakBrześć":"J. Pakulski, Brześć za rządów wójta Tylo (1306-1320) i jego lokalizacja, ZK-D 15, 2001",
    "PakPrzyw":"J. Pakulski, Przywilej księcia łęczyckiego, kujawskiego i dobrzyńskiego Kazimierza dla Piotrka Świętosławica z 10 marca 1252 roku, w: Scriptura custos memoriae, Poznań 2001",
    "PakRGodz":"J. Pakulski, Ród Godziębów w średniowiecznej Polsce, Toruń 2005",
    "PakWałd":"J. Pakulski, Wałdowscy i ich fundacja dla augustianów (w Górce?), w: Personae, colligationes, facta, Toruń 1991",
    "PawSejm":"A. Pawiński, Sejmiki ziemskie. Początek ich i rozwój aż do ustalenia się udziału posłów ziemskich w ustawodawstwo sejmu walnego 1374-1505, Warszawa 1895",
    "Pelech":"Der verlorene Ordensfoliant 5 (früher Hohmeister-Registrant II) des Hist. Staatsarchiv Königsberg mit Regesten (nach Rudolf Philippi und Erich Joachim), [opr. M. Pelech], Beiträge zur Geschichte des Deutschen Ordens, T. I, wyd. U. Arnold, Marburg 1986",
    "PiasOpis":"J. Piasecki, Opisanie klasztorów i kościołów księży franciszkanów prowincji polskiej, „Pamiętnik Religijno-Moralny” 5, 1843",
    "PiekWyb":"F. Piekosiński, Wybór zapisek sądowych grodzkich i ziemskich wielkopolskich z XV wieku, T. I, z. I, w tegoż, Studia, rozprawy i materiały..., T. VI, z. I, Kraków 1902",
    "PłBisk":"Księgi biskupie płockie w ADPł.",
    "PomUB":"Pommerellisches Urkundenbuch, wyd. M. Perlbach, Danzig 1882",
    "Pot. 304":"AGAD, Archiwum Publiczne Potockich, rkp. 304",
    "PoznańG":"Księgi grodzkie poznańskie w APP",
    "PoznańZ":"Księgi ziemskie poznańskie w APP",
    "ProkopArcyb":"K. R. Prokop, Arcybiskupi gnieźnieńscy w tysiącleciu, Kraków 2000",
    "PrUB":"Preussisches Urkundenbuch, T. I n., Königsberg 1882 n.",
    "PrzedG":"Księgi grodzkie przedeckie w AGAD",
    "PrzedZ":"Księgi ziemskie przedeckie w AGAD (Księga ziemska przedecka nr 1, z lat 1408-1414, w: Rossijskij Gosudarstwiennyj Archiw Driewnich Aktow, Moskwa, fond nr 356, opis 1, nr 57 - mikrofilm w posiadaniu dr hab. Joanny Karczewskiej i dr hab. Dariusza Karczewskiego użyczony prof. Januszowi Bieniakowi)",
    "PrzywSolca":"Przywilej lokacyjny miasta Solca Kujawskiego z 1325 r., opr. D. Karczewski, Solec Kujawski 2001",
    "PSB":"Polski słownik biograficzny, T. I n., Kraków 1935 n.",
    "PyzdryZ":"Księgi ziemskie pyzdrskie w APP",
    "RachJag":"Rachunki dworu króla Władysława Jagiełły i królowej Jadwigi z lat 1388 do 1420, wyd. F. Piekosiński, Kraków 1896",
    "RadzimElem":"A. Radzimiński, O elementach chronologicznych w dokumentach Ziemomysła księcia kujawskiego, Acta Universitatis Nicolai Copernici, Historia 26, 1992",
    "RadzimPrKPł":"A. Radzimiński, Prałaci i kanonicy kapituły katedralnej płockiej w XIV i I poł. XV w. Studium prozopograficzne, T. I-II, Toruń 1991-1993",
    "RadzZ":"Księgi ziemskie radziejowskie w AGAD",
    "RegTeut":"Regesta historico-diplomatica Ordinis Sanctae Mariae Theutonicorum, wyd. E. Joachim, W. Hubatsch, T. I-II, Göttingen 1948–1973",
    "RoczHist":"„Roczniki Historyczne”",
    "RTH":"„Rocznik (Polskiego) Towarzystwa Heraldycznego”",
    "SBPN":"Słownik biograficzny Pomorza Nadwiślańskiego",
    "SemkWyw":"Wywody szlachectwa w Polsce XIV-XVII w., wyd. W. Semkowicz, RTH 3, 1911-1912",
    "SHG":"Słownik historyczno-geograficzny ziem polskich w średniowieczu: Kr. - województwo krakowskie, Pł. - płockie, Pozn. - poznańskie",
    "SieradzanŚwiad":"W. Sieradzan, Świadomość historyczna świadków w procesach polsko-krzyżackich w XIV i XV wieku, Toruń 1993",
    "SierG":"Księgi grodzkie sieradzkie w AGAD",
    "SierZ":"Księgi ziemskie sieradzkie w AGA",
    "SławKretk":"T. Sławiński, Kretkowscy i ich dzieje od połowy XIV wieku, Warszawa 2011",
    "SperkaOtocz":"J. Sperka, Otoczenie Władysława Opolczyka w latach 1370-1401. Studium o elicie władzy w relacjach z monarchą, Katowice 2006",
    "SperkaSzafr":"J. Sperka, Szafrańcowie herbu Stary Koń. Z dziejów kariery i awansu w późnośredniowiecznej Polsce, Katowice 2001",
    "SperkaWojny":"J. Sperka, Wojny Władysława Jagiełły z księciem opolskim Władysławem (1391-1396), Cieszyn 2003",
    "SPPP":"Starodawne prawa polskiego pomniki",
    "SPŚ":"Społeczeństwo Polski średniowiecznej",
    "SrokaPolacy":"S. A. Sroka, Polacy na Węgrzech za panowania Zygmunta Luksemburskiego 1387-1437, Kraków 2001",
    "SRPr":"Scriptores rerum Prussicarum",
    "SuprOtocz":"A. Supruniuk, Otoczenie księcia mazowieckiego Siemowita IV (1374-1426). Studium o elicie politycznej Mazowsza na przełomie XIV i XV wieku, Warszawa 1998",
    "SzachKanc":"S. M. Szacherska, Kancelaria Siemowita księcia dobrzyńskiego, SŹ 11, 1966",
    "SzachOpSzp":"S. M. Szacherska, Opactwo cysterskie w Szpetalu a misja pruska, Warszawa 1960",
    "SzachZDz":"S. M. Szacherska, Z dziejów kancelarii książąt kujawskich w XIII wieku. Dwa nieznane dokumenty szpetalskie, SŹ 5, 1960",
    "SzadZ.":"Księgi ziemskie szadkowskie w AGAD",
    "SzwedaOrg":"A. Szweda, Organizacja i technika dyplomacji polskiej w stosunkach z zakonem krzyżackim w latach 1386-1454, Toruń 2009",
    "SzwedaRGrzym":"A. Szweda, Ród Grzymałów w Wielkopolsce, Toruń 2001",
    "SzybkBrudz":"S. Szybkowski, Brudzewscy herbu Pomian na Kujawach i w Wielkopolsce. Uwagi o majątkach, starostwach i genealogii, RoczHist 79, 2013",
    "SzybkDok1426":"S. Szybkowski, Dokument sądu ziemskiego inowrocławskiego z 11 V 1426. Pochodzenie sędziego ziemskiego inowrocławskiego Jana Rosiejowskiego z Dąbrówki, w: Mazowsze, Pomorze, Prusy, Gdańsk 2000",
    "SzybkDok1500":"S. Szybkowski, Dokument sądu ziemskiego dobrzyńskiego z 21 I 1500 r., w: Odkrywcy, princepsi, rozbójnicy, Malbork 2007",
    "SzybkKarJana":"S. Szybkowski, Kariera Jana Mikołajewica i Jana Janowica Kościeleckich. Starostwa bydgoskie, świeckie i dobrzyńskie w końcu XV w., w: Kopijnicy, szyprowie, tenutariusze, Gdańskie studia z dziejów średniowiecza nr 8, Gdańsk 2002",
    "SzybkKarMik":"S. Szybkowski, Kariera urzędnicza Mikołaja Kościeleckiego ze Skępego. Problemy chronologiczne i interpretacyjne, w: Drogą historii. Studia ofiarowane profesorowi Józefowi Szymańskiemu..., Lublin 2001",
    "SzybkKrzyż":"S. Szybkowski, Krzyżacy i ich dobrzyńscy poplecznicy w latach 1405-1413. Z badań nad polsko-pruskimi związkami transgranicznymi na początku XV wieku, „Komunikaty Mazursko-Warmińskie” 2010, nr 3",
    "SzybkKSU":"S. Szybkowski, Kujawska szlachta urzędnicza w późnym średniowieczu (1370-1501), Gdańsk 2006",
    "SzybkPięćDok":"S. Szybkowski, Pięć dokumentów sądu ziemskiego dobrzyńskiego z XIV i XV w., w: Biskupi, lennicy, żeglarze, Gdańsk 2003, s. 393-412 ",
    "SzybkPot":"S. Szybkowski, O potomstwie kasztelana dobrzyńskiego Andrzeja z Woli i Radzików, w: Odkrywcy, princepsi, rozbójnicy, Malbork 2007",
    "SzybkRCielep":"S. Szybkowski, Ród Cielepałów, Gdańsk 1999",
    "SzybkRos":"S. Szybkowski, Pochodzenie i krąg rodzinny sędziego ziemskiego inowrocławskiego Jana Rosiejowskiego z Dąbrówki, w: SzybkStGen",
    "SzybkStGen":"S. Szybkowski, Studia z genealogii i prozopografii polskiej szlachty późnośredniowiecznej, Gdańsk 2003",
    "SzybkStIn":"S. Szybkowski, Starostwo i starostowie inowrocławscy w latach 1364-1501. Zarys problematyki, ZK 20, 2007",
    "SzybkŚwiadk":"S. Szybkowski, Świadkowie przywileju wielkiego mistrza Ulryka von Jungingen z 28 X 1409 roku. Z badań nad prokrzyżacką orientacją wśród szlachty dobrzyńskiej w okresie wojny 1409-1411, ZH 75, 2010, z. 2",
    "SzybkUBydg":"S. Szybkowski., Ziemscy urzędnicy bydgoscy za Andegawenów i pierwszych Jagiellonów (1370-1492). Ustalenie chronologii, ZK 14, 2000/2001",
    "SzymczSzl":"A. Szymczakowa, Szlachta sieradzka w XV wieku. Magnifici et generosi, Łódź 1998",
    "SzymOtocz":"M. Szymecka, Otoczenie księcia słupsko-dobrzyńskiego Kaźka, w: Szlachta, starostowie, zaciężni, Gdańsk 1998",
    "SŹ":"„Studia Źródłoznawcze”",
    "ŚliwKształt":"B. Śliwiński, Kształtowanie się własności rycerskiej w północnej części ziemi dobrzyńskiej w XIII i XIV wieku, ZH 50, 1985, z. 4",
    "ŚliwPogr":"B. Śliwiński, Pogranicze kujawsko-pomorskie w XII–XIII wieku, Warszawa 1989",
    "ŚliwRycKuj":"B. Śliwiński, Rycerstwo kujawskie a biskupstwo włocławskie w XIII wieku. Kontakty majątkowe, ZH 49, 1984, z. 4",
    "ŚZHŁ":"Średniowieczne zapiski heraldyczne łęczyckie, wyd. T. Piotrowski, Z. Wdowiszewski, „Miesięcznik Heraldyczny” 14, 1935",
    "TNarusz.":"Teki Naruszewicza w BCzart. w Krakowie",
    "TPaw.":"Teki A. Pawińskiego, T. I-VII, Warszawa 1897-1905",
    "Tresslerbuch":"Das Marienburger Tresslerbuch der Jahre 1399-1409, wyd. E. Joachim, Königsberg 1896",
    "U ":"Urzędnicy dawnej Rzeczypospolitej XII–XVIII wieku. Spisy, red. A. Gąsiorowski, t. ",
    "UdBCulm":"Urkundenbuch des Bisthums Culm, T. I, wyd. C. P. Woelky, Danzig 1887",
    "VL":"Volumina legum, T. I, Petersburg 1859 ",
    "Weise":"Die Staatsverträge des Deutschen Orden in Preussen im 15. Jahrhundert, wyd. E. Weise, T. 1-3, Königsberg [1939] - Marburg 1966",
    "WenzelStibor":"G. Wenzel, Stibor vajda. Életrajzi tanulmány, Budapest 1874",
    "WłBisk":"Księgi biskupie włocławskie w ADWł.",
    "WłKons":"Akta konsystorza włocławskiego w ADWł.",
    "WronRRaw":"J. Wroniszewski, Ród Rawiczów, (I) Warszowice i Grotowice, Toruń 1992; (II) Współrodowcy Warszowiców i Grotowiców, Toruń 1994",
    "ZbiórPaul":"Zbiór dokumentów zakonu OO. Paulinów w Polsce, z. 1, wyd. J. Fijałek, Kraków 1938",
    "ZDM":"Zbiór dokumentów małopolskich, cz. I-VIII, wyd. S. Kuraś, I. Sułkowska-Kuraś, Wrocław 1962-1975",
    "ZdW":"Zasłużeni dla Włocławka, Włocławek 1991",
    "ZH":"„Zapiski Historyczne”",
    "Zielińscy":"G. i J. Zielińscy, Wiadomość historyczna o rodzie Świnków oraz rodowód pochodzącej od nich rodziny Zielińskich herbu Świnka, Toruń 1880-1881",
    "ZK":"„Ziemia Kujawska”",
    "ZK-D":"„Zapiski Kujawsko-Dobrzyńskie”, Seria A",
    "ZyglDział":"Z. Zyglewski, Mikołaj Działyński jako wojewoda kujawski w latach 1484-1491, ZK 13, 1998",
    "ZyglUrzB":"Z. Zyglewski, Późnośredniowieczne urzędy i urzędnicy w powiecie bydgoskim. Urzędnicy ziemscy - starostowie - burgrabiowie, Prace Komisji Historii Bydgoskiego Towarzystwa Naukowego 16, 1998"
}
