""" słownik skrótów literatury """

literatura = {
    "ABern. Kr.":"Archiwum Bernardynów w Krakowie",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziernskie z czasów Rzeczypospolitej Polskiej z archiwum tzw. bemardyńskiego we Lwowie, t. I-XXV, Lwów 1868-1935",
    "AJZ":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, wyd. W. Sobieski, J. Siemieński, K. Lepszy, t. I - IV, Warszawa-Kraków 1904-1948",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "APKr.":"Archiwum Państwowe w Krakowie",
    "APL":"Archiwum Państwowe w Lublinie",
    "Arch. Leszcz.":"Archiwum Leszczyńskich w APL",
    "Arch. Podh.":"Archiwum Podhoreckie w APKr.",
    "Arch. Radz.":"Archiwum Radziwiłłów w AGAD",
    "Arch. Rul.":"Archiwum Rulikowskich w APL",
    "Arch. Zam.":"Archiwum Zamoyskich w AGAD",
    "AS":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, wyd. Z. L. Radzimiński, P. Skobielski, B, Gorczak, t. I, Il, V, Lwów 1887-1897",
    "ASejmKr":"Akta sejmikowe województwa krakowskiego, t. III-V, wyd. A. Przyboś, Kraków 1959—1984",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "AT":"Acta Tomiciana, t. I-XVII, wyd. T. Działyński i in., Poznań 1852 n.",
    "AWAK":"Akta izdawajemyje Vilenskoju Archeograficzeskoju Kommissieju, t. XIX, Wilno 1892",
    "BANLw.":"Biblioteka Akademii Nauk we Lwowie",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwum Czartoryskich",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BKórn.":"Biblioteka Kórnicka Polskiej Akademii Nauk w Kórniku",
    "Błeszczyński":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII wieku, w: $, K. Kossakowski, Monografie historyczno-genealogiczne, t. III, Warszawa 1872",
    "BŁop.":"Wojewódzka Biblioteka Publiczna im. H. Łopacińskiego w Lublinie",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899—1913",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BOZ":"Biblioteka Ordynacji Zamoyskich w BN",
    "BULw.":"Biblioteka Uniwersytecka we Lwowie",
    "CBel.":"Castrensia Belsensia w CPAHL",
    "CBusc.":"Castrensia Buscensia w CPAHL",
    "CC":"Castrensia Cracoviensia w APKT.",
    "CCHhD":"Castrensia Chelmensia Decreta w APL",
    "CChl":"Castrensia Chelmensia Inscriptiones w APL",
    "CCHR":"Castrensia Chelmensia Relationes w APL",
    "CCPlen.":"Castrensia Cracoviensia Plenipotentiac w APKr.",
    "CCR":"Castrensia Cracoviensia Relationes w APKr.",
    "CCrasnR":"Castrensia Crasnostaviensta Relationes w APL",
    "CGrabD":"Castrensia Graboviecensia Decreta w APL",
    "CGrabl":"Castrensia Graboviecensia Inscripttones w APL",
    "CGrabR":"Castrensia Graboviecensia Relationes w APL.",
    "Chłapowski":"K. Chłapowski, Starostowie w Małopolsce 1565—1668, w: Społeczeństwo staropolskie, t. IV, Warszawa 1986",
    "CHorD":"Castrensia Horodlensia Decreta w APL",
    "CHorR":"Castrensia Horodlensia Relationes w APL",
    "CIP":"Corpus iuns Połonici, wyd. O. Balzer, t. III, Kraków 1906",
    "CLD":"Castrensia Lublinensia Decreta w APL",
    "CLI":"Castrensia Lublinensia Inscriptiones w APL",
    "CLPlen.":"Castrensia Lublinensia Plenipotentiae w APL",
    "CLR":"Castrensia Lublinensia Relationes w APL",
    "CLucl":"Castrensia Lucoviensia Inscriptiones w AGAD",
    "Cod. ep.":"Codex epistolaris saeculi decimi quinti, wyd. A. Sokołowski, J. Szujski, A. Lewicki, t. I-II, Kraków 1876-1894",
    "CPAHL":"Centralne Państwowe Archiwum Historyczne we Lwowie",
    "CSierl":"Castrensia Siradiensia Inscriptiones w AGAD",
    "Czołowski":"Zbiór A. Czołowskiego w AGAD",
    "DąbKB":"P. Dąbkowski, Kancelarie i księgi sądowe bełskie za czasów polskich, Przegląd Prawa i Administracji, nr 43, 1918",
    "DąbKBusk.":"P. Dąbkowski, Z przeszłości ksiąg grodzkich i ziernskich buskich, Kwartalnik Historyczny, 29, 1915",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae..., wyd. M. Dogiel, t. I-V, Wilno 1758-1764",
    "DokPaul.":"Zbiór dokumentów zakonu OO. Paulinów w Polsce 1328-1464, opr. J. Fijałek, Kraków 1938",
    "Dwa pamiętniki":"Dwa pamiętniki z XVII wieku Jana Cedrowskiego i Jana Floriana Drobysza Tuszyńskiego, wyd. A. Przyboś, Wrocław 1954",
    "DworzGen.":"W. Dworzaczek, Gerteałogia, Warszawa 1959",
    "DworzTarn. II":"W, Dworzaczek, Hetman Jan Tarnowski, Warszawa 1985",
    "Ehrlich":"L. Ehrlich, Starostwa w Halickiem w stosunku do starostwa lwowskiego w wiekach średnich 1390—1501, Studia nad Historią Prawa Polskiego, t. VI, z. 1, Lwów 1914",
    "IMT":"Iura Masoviae terrestria, t. I, wyd. J. Sawicki, Warszawa 1972",
    "Inv.":"Znventarium omnium et singulorum privilegiorum... in Archivo Regni... continentur, wyd, E. Rykaczewski, Paryż 1862",
    "Kalendarz":"Kalendarz polityczny dla Królestwa Polskiego i Wielkiego Księstwa Litewskiego na Rok Pański 1793..., Warszawa 1792",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD",
    "Kaniewska":"I. Kaniewska, Matopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa 1974",
    "KatCzart.":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, cz. 1 (1148—1506), opr. W. Szelińska, J. Tomaszewicz, Kraków 1975; cz. II (1506-1828), opr. J. Tomaszewicz, Kraków 1991",
    "KatPergSang,":"Katalog pergarminów znajdujących się w Archiwum XX. Sanguszków w Sławucie, opr. B. Gorczak, Sławuta 1912",
    "KDM":"Kodeks dypłomatyczny Małopolski, wyd. F. Piekosiński, t. TV, Kraków 1905; t. V - materiały w Pracowni Słownika Historyczno-Geograficznego Instytutu Historii PAN w Krakowie",
    "KDP":"Kodeks dyplomatyczny Polski, wyd. L. Rzyszczewski i in., t. I-IV, Kraków 1847-1887",
    "Kętrzyński":"Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich, wyd. W. Kętrzyński, t. I-III, Lwów 1880—1898",
    "KgŁęczO":"Księgi grodzkie łęczyckie, oblaty w AGAD",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "KmGrab.":"Księgi miasta Grabowca w APL",
    "Kod. dypl. tyn.":"Kodeks dyplomatyczny kłasztoni tvnieckiego, cz. I, wyd. W. Kętrzyński, S$, Smolka, Lwów 1875",
    "Kozicki":"Wypisy ks, Z. Kozickiego z ksiąg grodzkich i ziemskich chełmskich i krasnostawskich w PANKTr. rps 8821-8824 (cyt. zeszyty wg numeracji)",
    "KpB":"Księgi podkomorskie bełskie w CPAHL",
    "KpCh":"Księgi podkomorskie chełmskie w APL",
    "Laudą":"Odpisy laudów bełskich z lat 1572—1667 w BULw. (rps 2402. III)",
    "LRus. 1661":"Lustracja województwa ruskiego 1661-1665, cz. 1II, wyd. E. i K. Arłamowscy, W. Kaput, Wrocław 1976",
    "Łosiana":"Zbiór Łosiów w APL",
    "Łoziński":"W, Łoziński, Prawem i ewent, t. 1-11, Kraków 1957",
    "MalUGZL":"K. Maleczyński, Urzędnicy grodzcy i ziemscy Iwowscy w latach 1352-1763, Lwów 1938",
    "MAML":"Materiaty archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 r., wyd. A. Prochaska, Lwów 1890",
    "MH":"Miesięcznik Heraldyczny",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka tzw. Litewska w AGAD",
    "MPH":"Monumenta Poloniae Historica",
    "MRPS":"Matricułarum Regni Poloniae summaria, cz. I - V, wyd. T. Wierzbowski i in., Warszawa 1905-1961",
    "Nies.":"K. Niesiecki, Herbarz polski, t. I-X, wyd. J. N. Bobrowicz, Lipsk 1839-1846",
    "Orzelski":"Sventoslai Orzelski Interregni Poloniae libros 1572—1576, wyd. E. Kuntze, Kraków 1917",
    "Pałucki":"W, Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVT wieku, Warszawa 1962",
    "Pamiętniki o Koniecpolskich":"Pamiętniki o Koniecpolskich. Przyczynek do dziejów polskich XVII wieku, wyd. S. Przyłęcki, Lwów 1842",
    "PANKT.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, Kraków 1858",
    "Pawiński":"A. Pawiński, Sejmiki ziernskie 1374-1505, Warszawa 1895",
    "Poczet":"Elektorów poczet, wyd. O. Pietruski, Lwów 1845",
    "Przywileje":"Przywileje królewskiego miasta stołecznego Starej Warszawy 1376-1772, wyd. T. Wierzbowski, Warszawa 1913",
    "PSB":"Polski słownik biograficzny, t. I-XXXTV, Kraków 1935 n.",
    "Radziwiłł":"A. S. Radziwiłł, Memoriale rerum gestanim in Polonia, t. 1— V, wyd. A. Przyboś, R. Żelewski, Wrocław 1968-1975",
    "RTAW":"Regestra thelonei aquatici Władistaviensis saeculi XVI, wyd. S$. Kutrzeba, F. Duda, Kraków 1915",
    "RTH":"Rocznik Towarzystwa Heraldycznego we Lwowie",
    "Rusieccy":"Zbiór Rusieckich w APKr.",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego. Diariusz i relacje z lat 1691-1696, wyd. J. Woliński, Wrocław 1058",
    "Seruga":"J. Seruga, Dokumtenty pergaminowe w zbiorach biblioteczno-muzealnych hr. Tarnowskich w Suchej, Kraków 1936",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "Smoniewski":"Materiały Smoniewskiego w PANKTr.",
    "Sochaniewicz":"K. Sochaniewicz, A. Wolff, Urzędnicy województwa bełskiego do połowy XVI w., MH, 10, 1931",
    "Sozański":"A. Sozański, Imienne spisy osób duchownych, świeckich i wojskowych, które w pierwszych ośmiu latach panowania króla Stanistawa Poniatowskiego od 1764-1772 r. w rządzie lub przy administracji Rzeczypospolitej udział brały, Kraków 1866",
    "SPPP":"Starodawne prawa polskiego pomniki, t. VI, wyd. M. Bobrzyński, Kraków 1881",
    "ŚRP":"Scriptores rerum Polonicarum, t. VIII, Kraków 1885",
    "Stankowa":"M. Stankowa, Z dziejów powiatu grabowieckiego, Biuletyn Towarzystwa Regionalnego Hrubieszowskiego, 8, 1970, z. 1",
    "StankowaKs.":"M. Stankowa, Księga sądu ziemskiego hrubieszowskiego z lat 1429-1468, Archeion, 44, 1966",
    "Sucheni_Grabowska":"A. Sucheni-Grabowska, Afonarchia dwu ostatnich Jagiellonów a ruch egzekucyjny, t. I, Wrocław 1974",
    "TBel.":"Terrestria Belsensia w CPAHL",
    "TC":"Terrestria Cracoviensia w APKr.",
    "TCHhD":"Terrestria Chelmensia Decreta w APL",
    "TChl":"Terrestria Chelmensia Inscriptiones w APL",
    "TCN":"Terrestria Cracoviensia Nova w APKr.",
    "TCrasnD":"Terrestria Crasnostaviensia Decreta w APL",
    "TCrasnl":"Terrestria Crasnostaviensia Inscriptiones w APL",
    "TCrasnR":"Terrestria Crasnostaviensia Relationes w APŁ",
    "TCrl":"Terrestria Cracoviensia Inscriptiones w APKr.",
    "TGrab.":"Terrestria Graboviecensia w APL",
    "TKL":"Księgi Trybunału Koronnego Lubelskiego w APL",
    "TL":"Terrestria Lublinensia w APL",
    "TLI":"Terrestria Lublinensia Inscripliones w APL",
    "TP":"Teki Pawińskiego w PANK.",
    "TParcz.":"Terrestria Parczoviensia w APL",
    "TŚch.":"Teki Schneidra w APKr.",
    "TUI":"Terrestria Urzędoviensia Inscriptiones w APL",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII - XVIII wieku. Spisy, t. ln.",
    "Uchansciana":"Uchansciana czyli zbiór dokumentów wyjaśniających życie i działalność Jakuba Uchańskiego, t. V, wyd. T. Wierzbowski, Warszawa 1895",
    "Uruski":"S. Uruski, Rodzina, t. I-XV, Warszawa 1904-1931",
    "VL":"Volumina legum t. I-X, wyd. J. Ohryzko, Z.. Kaczmarczyk, Petersburg 1859 - Poznań 1952",
    "Wielądko":"W. W. Wielądko, Heraldyka, czyli opisanie herbów w jakim który jest ksztatcie..., t. I-V, Warszawa 1792-1798",
    "Wolff":"A. Wolff, Studia nad urzędnikami mazowieckimi 1370—1526, Wrocław 1962",
    "Zamoyskiego notaty":"Jana Zamoyskiego notaty heraldyczno-sfragistyczne, w: Studia, rozprawy i materiały z dziedziny historii polskiej i prawa polskiego, wyd. F. Piekosiński, t. VII, Kraków 1907",
    "Zbiór Pinoccich":"Zbiór Pinoccich w APKr.",
    "ZDKM":"Zbiór dypiomów klasztoru mogilskiego, w: Monografia opactwa Cystersów we wsi Mogile, Kraków 1867",
    "ZDM":"Zbiór dokumentów małopolskich, t. IZVII, wyd. $. Kuraś, I. Sułkowska-Kuraś, Wrocław 1962—1976",
    "Zielińska":"T. Zielińska, Magnateria polska epoki saskiej, Wrocław 1977",
    "Źródłopisma":"Źrzódłopisma do dziejów Korony Polskiej i W. X. Litewskiego, cz. 2-3, wyd. A. T. Działyński, Poznań 1856-1861",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. 1-XXX, Poznań 1879—1908"
}