""" słownik skrótów literatury """

literatura = {
    "ABCz":"Archiwum Braci Czeskich w Archiwum Państwowym w Poznaniu",
    "Acta Hist.":"I. Polkowski, Sprawy wojenne króla Stefana Batorego, t. XI, Kraków 1887",
    "Acta Stanów":"Acta Stanów Wielkiego Xięstwa Litewskiego na pospolite ruszenie vigore laudum Wileńskiego 14 Augusti 1698 postanowionego między Ław- nem a Puzewiczamiu... A. D. 1698, dnia 21 Decembris, Wilno 1699",
    "Acta Tom.":"Acta Tomiciana, t. I n., Poznań 1852 n.",
    "ADL":"Archiwum Druckich Lubeckich w Bibliotece Czartoryskich",
    "ADRadz.":"Archiwum domu Radziwiłłów, Scriptores rerum Polonicarum, L. VIII, Kraków 1885",
    "ADSap.":"Archiwum Donu Sapiehów, oprac. A. Prochaska, t. I, Lwów 1892",
    "ADWłoc.":"Archiwum Diecezjalne we Włocławku",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego Bernardyńskiego we Lwowie, t. I n., Lwów 1868 n.",
    "AKP":"Archiwum Krzeszowickie Potockich w Archiwum Państwowym w Krakowie",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, wyd. $. Kutrzeba i W. Semko- wicz, Kraków 1932",
    "Akty JZR":"Akty olnosjaśćijesja k istorii Jużnoj i Zapadnoj Rossii, t. I n., $. Peterburg 1863 n.",
    "Akty LM":"Akty Litovskoj Metriki sobrannyje F. l. Leontovićem, t. 1-Il, Warsza- wa 1896-1897",
    "Akty LRG":"Akty Litovsko-russkogo gosudarstva izd. M. Dovnar Zapolskim, t. I, Moskva 1900",
    "Akty ZR":"Akty otnosjaścćijesja k istorii Zapadnoj Rossii, t. l n., S$. Peterburg 1846 n.",
    "AMCh":"Archiwum Młynowskie Chodkiewiczów w Archiwum Państwowym w Krakowie, Oddział na Wawelu",
    "Antonović, Hramoty":"Gramoty velikich kniaziej litovskich s 1390 po 1569 god, sobr. V. Antonović, K. Kozłovskij, Kiev 1868",
    "APJ":"Archiwum Potockich z Jabłonny w AGAD",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APR":"Archiwum Potockich z Radzynia w AGAD",
    "AR":"Archiwum Radziwiłłów w AGAD",
    "Archiv JZR":"Archiv Jugozapadnoj Rossii izdavaemyj Vremennoju Kommisieju dlja rozbora drevnich aktov, cz. 1 n., t. I n., Kiev 1860",
    "ArchSang.":"Archiwum Sanguszków w Archiwum Państwowym w Krakowie, Oddział na Wawelu",
    "ASang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. I n., Lwów 1887 n.",
    "ASD":"Archeograficeskij Sbornik Dokumentov, t. I n., Vilna 1867 n.",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "ASZ":"Archiwum Spraw Zagranicznych Francuskie do dziejów Jana III, wyd. K. Waliszewski, t. I-III, Kraków 1879-1884 (Acta Historica res gestas Poloniae illustrantia, vol. III, V, VII)",
    "AVAK":"Akty izdavaemye Vilenskoju Kommissieju dlja razbora drevnich aktov, t In., Vilna 1865 n.",
    "AZ":"Archiwum Zamoyskich w AGAD",
    "BA":"Belaruski archiu, t. I-III, Mensk 1927-1931",
    "Baliński, Historia":"M. Baliński, Historia miasta Wilna, t. I-II, Wilno 1836",
    "Bardach, Z praktyki":"J. Bardach, Z praktyki kancelarii litewskiej za Zygmunta I Starego, w: Prace z dziejów Polski feudalnej, Warszawa 1960",
    "Berśadskij":"$. A. Berśadskij, Russko-jevrejskij archiv. Dokumenty i materiały dla istorii jeyrejev Rossii, t. I-III, $. Peterburg 1882-1903",
    "Bielski, Dalszy ciąg kroniki":"J. Bielski, Dalszy ciąg kroniki polskiej zawierającej dzieje od 1587 do 1598, wyd. F. M. Sobieszczański, Warszawa 1851",
    "BN":"Biblioteka Narodowa w Warszawie",
    "BOK":"Biblioteka Ordynacji Krasińskich (wg F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji hr. Krasińskich, Warszawa 1915)",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XV, Warszawa 1899-1912",
    "BonPocz.":"A. Boniecki, Poczet rodów w Wielkim Księstwie Litewskim w XV i XVI wieku, Warszawa 1887",
    "BOZ":"Biblioteka Ordynacji Zamojskiej w Bibliotece Narodowej",
    "BSS":"Biblioteka im. Sałtykova-ŚCedrina w Petersburgu",
    "BUANIw.":"Biblioteka Ukraińskiej Akademii Nauk we Lwowie",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego",
    "CDIA Kijów":"Centralnij dierżavnij istorićnij archiv w Kijowie",
    "CDLit.":"Codex diplomaticus Lithuaniae, ed. E. Raczyński, Wrocław 1845 ",
    "Chmiel, Rachunki dworu":"A. Chmiel, Rachunki dworu królewskiego 1544-1567, Kraków 1911",
    "Chmiel, Zbiór dok.":"A. Chmiel, Zbiór dokumentów znajdujących się w Bibliotece hr. Przezdzieckich w Warszawie, Kraków 1890",
    "Chrapowicki":"J. A. Chrapowicki, Diariusz. Część pierwsza: lata 1656-1664, oprac. T. Wasilewski, Warszawa 1978; Część druga: lata 1665-1669, oprac. A. Rachuba i T. Wasilewski, Warszawa 1988",
    "Chronika Bychovca":"Chronika Bychovca, wyd. N. N. Ułaśćik, Moskva 1966",
    "Codex ep. XV":"Codex epistolaris saeculi decimi quinti, t. I-III, Kraków 1876-1894",
    "Codex ep. Vitoldi":"Codex epistolaris Vitoldi magni ducis Lithuaniae 1376-1430, zebrał A. Prochaska, Cracoviae 1882",
    "Codex Mednicensis":"Codex Mednicensis seu Samogitiae dioecesis, Col. P. Jatulis, t. I-II, Roma 1984-1988",
    "Constitucie 1550-1581":"Constitucie, Statuta y Przywileie na walnych Seymiech Koronnych od Roku Pańskiego 1550 az do Roku 1581 uchwalone, Kraków 1581",
    "Czart.":"Biblioteka Czartoryskich w Krakowie",
    "Daneykowicz, Swada":"J. Daneykowicz Ostrowski, $wada polska y łacińska..., Lublin 1745",
    "DanLatop.":"Latopisiec Litwy i kronika ruska z rękopisu stawiańskiego przepisane, wyd. 1. Daniłowicz, Wilno 1827",
    "DanSkarb.":"Skarbiec diplomatów papieskich, cesarskich, królewskich, ..., zebrał I. Daniłowicz, t. I-II, Wilno 1860-62",
    "Diarjusz WRW":"Diarjusz Walnej Rady Warszawsiej z roku 1710, wyd. R. Mienicki, Wilno 1928",
    "Długosz, Dzieje":"J. Długosz, Dziejów polskich ksiąg dwanaście, t. IV-V, Kraków 1869-1870",
    "Dnevnik Ljubl. sejma":"Dnevnik Ljublinskago sejma 1569 goda sojedinenija Velikago Kniażestva Litovskago s Korolestvom Polskim, S. Peterburg 1869",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae..., t. I-V, wyd. M. Dogiel, Wilno 1758 n.",
    "Dok. pap.":"Dokumenty papierowe",
    "Dok. perg.":"Dokumenty pergaminowe",
    "Dokumenty Min. Justicii":"Dokumenty Moskovskogo Archiva Ministerstva JuSticii, t. I, Moskva 1897",
    "Dubiński, Zbiór praw":"P. Dubiński, Zbiór praw i przywilejów miastu stołecznemu Wilnowi nadanych, Wilno 1788",
    "Dubr.":"Avtografy Dubrovskogo",
    "Dybaś, W sprawie":"B. Dybaś, W sprawie traktatu puzewickiego z 1698 roku i jego następstw, „Zapiski Historyczne”, t. 53, 1988, z. 3-4",
    "F":"Fond, Fondas",
    "Fijałek, Uchrześcijanienie Litwy":"J. Fijałek, Uchrześcijanienie Litwy przez Polskę i zachowanie w niej języka ludu, Kraków 1914",
    "FCzoł.":"Fond Czołowskiego",
    "Folwarski":"H. Folwarski, Erazm Ciotek, biskup i dyplomata, Warszawa 1935",
    "FOss.":"Fond Ossolińskich",
    "FSap.":"Fond Sapiehów",
    "Faszczów":"Archiwum Faszczów w AGAD",
    "Genealogia imienia naszego":"Genealogia imienia naszego..., „Przegląd Poznański”, 1860, t. 30, s. 210-228",
    "Giltebrandt":"P. A. Giltebrandt, Rukopisnoje otdelenije Vilenskoj publićnoj biblioteki, Vilna 1871",
    "Halecki":"O. Halecki, Ostatnie lata SŚwidrygiełły i sprawa wołyńska za Kazimierza Jagiellończyka, Kraków 1915",
    "Heidenstein, Dzieje":"R. Heidenstein, Dzieje Polski od śmierci Zygmunta Augusta do roku 1594, t. I-II, Petersburg 1857",
    "Heidenstein, Pamiętniki":"R. Heidenstein, Pamiętniki wojny moskiewskiej w 6 księgach, Lwów 1894",
    "HRM":"Historica Russiae Monumenta, izd. A. $. Turgeniev, t. I-III, S. Peterburg 1841-1848",
    "Icones":"Icones Familiae Ducalis Radivilianae..., Nesviesii 1758",
    "IJM":"Istoriko-juridiceskije materialy izvlećonnyje iz aktovych knig gubernij Vitebskoj i Mogilevskoj, wyd. A. Sazonov, t. I-XXXII, Vitebsk 1871-1906",
    "Inw. Sang.":"Inwentarz Archiwum Romana Sanguszki w Sławucie, dokumenty, w Archiwum Państwowym w Krakowie, Oddział na Wawelu",
    "Jag.":"Biblioteka Jagiellońska w Krakowie",
    "Jakubczak, Jerzy Stumiłło":"S. Jakubczak, Jerzy Strumiłło - przywódca konfederacji lwowskiej 1464 roku, w: Społeczeństwo Polski średniowiecznej, t. V, Warszawa 1992",
    "Jankowski":"Cz. Jankowski, Powiat oszmiański. Materiały do dziejów ziemi i ludzi, t. I-IV, Petersburg 1896-1900",
    "Jasas":"R. Jasas, Pergameniu katalogas, Vilnius 1980",
    "Jasnowski":"J. Jasnowski, Mikołaj Czarny Radziwiłł (1515-1565), Warszawa 1939",
    "Jerlicz":"J. Jerlicz, Latopisiec albo kroniczka, wyd. K. W. Wójcicki, t. I-II, Warszawa 1853",
    "Jewłaszewski":"T. Jewłaszewski, Pamiętnik, Warszawa 1860",
    "Kal. Grodz.":"Kalendarz Grodzieński (za rok)",
    "Kal. Polit.":"Kalendarz Polityczny (za rok)",
    "Kal. Polit. KP":"Kalendarz Polityczny Królestwa Polskiego i Wielkiego Xięstwa Litewskiego (za rok) ",
    "Kal. Wil.":"Kalendarz Wileński (za rok)",
    "Kamer.":"Archiwum Kameralne w AGAD",
    "Kamieński":"A. Kamieński, Kariera rodu Siemaszków w XV - XVII wieku, „Lituano-Slavica Posnaniensia”, t. III, 1989",
    "Kapica Milewski, Herbarz":"I. Kapica Milewski, Herbarz, Kraków 1870",
    "Karczewski, Replika":"J. Karczewski, Replika ze strony jeneralnego prokuratora massy funduszów i interessów... Stefanii Radziwiłłówny, Wilno 1824",
    "Katalog Czart.":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, oprac. W. Szelińska, J. Tomaszewicz, cz. I, Kraków 1975",
    "KDKW":"Kodeks dyplomatyczny katedry i diecezji wileńskiej, wyd. J. Fijałek, W. Semkowicz, t. I, Kraków 1932-1948",
    "Kniga posolskaja":"Kniga posolskaja Metriki Velikogo kniażestva Litovskogo, soderzaśćaja v sebe dipłomaticeskije snośenija Litvy v gosudarstvovanije korolja Sigismunda-Avgusta (s 1545 po 1572 god), izd. I. N. Daniłović, M. A. Obolenskij, Moskva 1843",
    "Kodeks dypl. Litwy":"Kodeks dyplomatyczny Litwy, wyd. E. Raczyński, Vratislaviae 1845",
    "Kognowicki":"K. Kognowicki, Z życia Sapiehów y listy od monarchów, książąt y różnych panujących do tychże pisane, t. I-III, Wilno 1790-92",
    "KojałComp.":"W. Wijuk Kojałowicz, Herbarz rycerstwa W. X. Litewskiego tak zwany Compendium ..., wyd. F. Piekosiński, Kraków 1897",
    "KojałNom.":"W. Wijuk Kojałowicz, Nomenclator familiarum et stematum magni ducatus Lituaniae..., wyd. F. Piekosiński, Kraków 1905",
    "Kolęda Kr.":"Kolęda Krakowska (za rok)",
    "Kolęda Warsz.":"Kolęda Warszawska (za rok)",
    "Konarski":"S$. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Konarski, Platerowie":"S$. Konarski, Platerowie, w: Materiały do biografii, genealogii i heraldyki polskiej, t. [V, Buenos Aires - Paryż 1967",
    "KosmanWit.":"M. Kosman, Kancelaria wielkiego księcia Witolda, „Studia Źródłoznawcze”, t. XIV, 1969",
    "Kossakowski":"S$. K. Kossakowski, Monografie historyczno-genealogiczne niektórych rodzin polskich, t. I-III, Warszawa 1859-1872",
    "Kórnik":"Biblioteka PAN w Kórniku",
    "Kraszewski, Wilno":"J. I. Kraszewski, Wilno od początków jego do roku 1750, t. I-II, Wilno 1840",
    "KS":"Metryka Litewska. Księga Sigillat 1709—1719, oprac. A. Rachuba, Warszawa 1987",
    "Kurczewski, BW":"J. Kurczewski, Biskupstwo wileńskie, Wilno 1912",
    "Kurczewski, Kościół":"J. Kurczewski, Kościół zamkowy czyli katedra wileńska..., t. I-III, Wilno 1908",
    "Kwiatkowski, Urzędnicy":"S$. Kwiatkowski, Urzędnicy kancelaryjni koronni i dworscy Władysława III Warneńczyka (1434-1444), w: Rozprawy i sprawozdania Akademii Umiejętności, t. XVII, Kraków 1884",
    "Lewicki, Powstanie Świdrygiełły":"A. Lewicki, Powstanie Świdrygiełły, w: Rozprawy (i Sprawozdania) Wydziału Historyczno-Filozoficznego Polskiej Akademii Umiejętności, t. XXIX, Kraków 1892",
    "Lietuvos inventoriai":"Lietuvos inventoriai XVII a., wyd. K. Jablonskis, M. Jućas, Vilnius 1962",
    "LMAB":"Lietuvos Mokslu Akademijos Centrine biblioteka",
    "LNB":"Lietuvos Nacionaline Martyno Mażvydo biblioteka w Wilnie",
    "Lubavskij, Sejm":"M. Lubavskij, Litovsko-russkij sejm, Moskva 1900",
    "LVIA":"Lietuvos valstybinis istorijos archyvas",
    "Łappo":"I. I. Łappo, Velikoje kniazestvo Litovskoje za vremija ot zaklucenija Ljublinskoj unii do smerti Stefana Batorija, t. I, S$. Peterburg 1901; t. II: Velikoje kniażestvo Litovskoje vo vtoroj połovinie XVI stoletja. Litovsko-russkij povet i jego sejmik, Jurjev 1911",
    "Łop.":"Biblioteka Publiczna im. Łopacińskich w Lublinie",
    "Malinovskij, Rada VKL":"J. Malinovskij, Rada Velikago Kniażestva Litovskago v syjazi s bojarskoj dumoj drevniej Rossii, Ć. Il, vyp. 2, Tomsk 1912",
    "Malinovskij, Sbornik":"J. Malinovskij, Sbornik materialoy otnosjaśćichsja k istorii panov-rady Velikago Kniażestva Litovskago, t. I-II, Tomsk 1901-1912",
    "Matuszewicz":"M. Matuszewicz, Diariusz życia mego, t. I-II, oprac. B. Królikowski, Warszawa 1986",
    "Medeksza":"S. F. Medeksza, Księga pamiętnicza wydarzeń zaszłych na Litwie 1654-1668, wyd. W. Seredyński, Kraków 1875",
    "Mienicki, Stanisław Dowojno":"R. Mienicki, Stanistaw Dowojno, wojewoda połocki, „Ateneum Wileńskie”, t. IX, 1937",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka Litewska (w Ruskom Gosudarstvennom archive drevnich aktov w Moskwie, Fond 389)",
    "MNKTr.":"Zbiory Muzeum Narodowego w Krakowie, Oddział Biblioteki Czartoryskich",
    "Mon. Pol. Vat.":"Monumenta Poloniae Vaticana, t. IV, Kraków 1931",
    "Mon. Reform.":"Monumenta Reformationis Polonicae et Lithuanicae, seria 1/1, IV/1, 2, Wilno 1911-1915",
    "NAB Mińsk":"Nacjanal nyj archiu Belarusi w Mińsku",
    "Nab.":"Nabytki Oddziału III w AGAD",
    "Narbutt, Dzieje":"T. Narbutt, Dzieje narodu Litewskiego, t. VII, Wilno 1840",
    "Naruszewicz, Historia":"A. Naruszewicz, Historya Jana Karola Chodkiewicza, t. I-II, Lipsk 1837",
    "Niemcewicz, Zbiór pamiętników":"Zbiór pamiętników o dawnej Polsce, t. 1, Puławy 1830",
    "Nies.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-X, Lipsk 1839-1846",
    "Olkieniki":"Postanowienie generalne Stanów WXLit.... na Zjeździe Walnym... pod Olkienikami uchwalone, RP 1700, Wilno 1700",
    "Opis dokumentov VCA":"Opis dokumentovy Vilenskago centralnago archiva drevnich aktovych knig, vyp. I-X, Vilna 1901-1913",
    "Opisanije kievosofijskogo sobora":"Opisanije kievosofijskogo sobora, Kiev 1825",
    "Opisanije ROVPB":"Opisanije rukopisnogo otdieljenija vilenskoj publićnoj bibliotieki, t. I-V, Vilna 1893-1906",
    "Osiński":"A. Osiński, Żywoty biskupów wileńskich, t. I, Warszawa 1856",
    "Oss.":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "Pacowie":"J. Wolff, Pacowie. Materyjały historyczno-genealogiczne, Petersburg 1885",
    "Pamjatniki dipł. snośenij":"Pamjatniki dipłomaticeskich snośenij Moskovskogo Gosudarstva s Polsko-Litovskim, t. I-V, S. Peterburg 1882, Moskva 1913, w: Sbornik Imperatorskogo Russkogo Istorićeskago Obśćestva, t. 35, 59, 71, 137, 142",
    "Pamjatniki Vrem. Kom.":"Pamjatniki izdannye vremiennoju Kommissjeju dlja razbora drevnich aktov [...], Kiev 1845",
    "PANKT.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Papće, Aleksander Jagiellończyk":"F. Papće, Aleksander Jagiellończyk, Kraków 1949",
    "Paprocki, Herby":"B. Paprocki, Herby rycerstwa polskiego, Kraków 1848",
    "Pietkiewicz":"K. Pietkiewicz, Kiezgajłowie i ich latyfundium do połowy XVI wieku, Poznań 1982",
    "Piłsud.":"Archiwum Piłsudskich w AGAD",
    "Plateris":"A. Plateris, Teisiniai Livonijos ir Kurso santykiai su Lietuva (XVI-XVIII amziais), Kaunas 1938",
    "Platerów":"Archiwum Platerów z Antuzowa w AGAD",
    "Poczobut":"J. W. Poczobut Odlanicki, Pamiętnik (1640-1684), oprac. A. Rachuba, Warszawa 1987",
    "Poniat.":"Archiwum Rodzinne Poniatowskich w AGAD",
    "PSB":"Polski słownik biograficzny, t. I n., Kraków 1935 n.",
    "PSRL":"Połnoje sobranije russkich ljetopisiej, t. XXXII, Moskva 1975, t. XXXV, Moskva 1980",
    "Połockije gram.":"Połockije gramoty XIII - naćała XVI vv., sost. A. L. Chorośkiević, t. I-IV, Moskva 1977-1982",
    "Przezdziecki, Jagiellonki polskie":"A. Przezdziecki, Jagiellonki polskie XVI wieku, t. I-V, Kraków 1868-1878",
    "Ptaszycki":"S. Ptaszycki, Dzieje rodów litewskich jako materyjał do archeologii historycznej, „Ateneum”, t. III, 1888, z. 3",
    "Ptaśickij, Kniazja Puzyny":"S$. Ptaśickij, Kniazja Puzyny. lstoriko-geneałogićeskije materiały, S. Peterburg 1899",
    "Przyałgowski":"W. Przyałgowski, Żywoty biskupów wileńskich, t. I-III, Petersburg 1860",
    "RachK":"AGAD, ASK I, Rachunki Królewskie",
    "Rachuba, Polityka":"A. Rachuba, Polityka nominacyjna Stanisława Leszczyńskiego na Litwie w latach 1705-1709, „Przegląd Historyczny”, t. 83, 1992, z. 4, s. 617-632",
    "Rachuba, Sprawa obsady":"A. Rachuba, Sprawa obsady urzędów litewskich po Sapiehach w początkach XVIII wieku, w: Między wielką polityką a szlacheckim partykularzem. Studia z dziejów nowożytnej Polski i Europy ku czci Profesora Jacka Staszewskiego, Toruń 1993",
    "Rach. król.":"Rachunki królewskie z lat 1471-1472 i 1476-1478, oprac. S. Gawęda, Z. Perzanowski, A. Strzelecka, Wrocław-Kraków 1960",
    "Rachunki dworu Jagiełły":"Rachunki dworu króla Władysława Jagiełły i królowej Jadwigi z lat 1388 do 1420, wyd. F. Piekosiński, Kraków 1896",
    "Racz.":"Miejska Biblioteka Publiczna im. Edwarda Raczyńskiego w Poznaniu",
    "Radzimiński":"Z. Luba Radzimiński, Słowo o Namiestnikach rusko-litewskich i Marszatkach Wołyńskiej Ziemi, „Przegląd Polski”, R. 20, 1885, kwartał 1",
    "Radzimiński, Sprawa":"Z. Luba Radzimiński, Sprawa odrębnego pochodzenia Chodkiewiczów litewskich i białoruskich, „Rocznik Polskiego Towarzystwa Heraldycznego we Lwowie”, t. VIII, 1928",
    "RadzMem.":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I-IV, Wrocław 1968-1974",
    "RadzPamiętniki":"Pamiętniki Albrechta Stanisława Radziwiłła, wyd. E. Raczyński, t. 1-2, Poznań 1839",
    "Radziwiłł, Zebranie dni":"K. S. Radziwiłł, Zebranie dni z kalendarzów, AGAD, AR dz. VI, nr II-79",
    "Raganu teismai":"Raganu teismai Lietuvoje, par. K. Jablonskis, R. Jasas, Vilnius 1987",
    "Rejestry":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo wileńskie 1690 r., oprac. A. Rachuba, Warszawa 1989",
    "Revizja puść":"Revizja puść i perechodov zverinych [...] sostavlenaja... Hryhorjem Bohdanovićom Vołovićom v 1559 godu, Vilna 1867",
    "RIB":"Russkaja Istoriceskaja Biblioteka, t. XX, Petersburg 1903; t. XXXIII, Petrograd 1915",
    "Rimśa, Venclovas Agripa":"E. Rimśa, Venclovas Agripa ir jo gimine, „Lietuvis TSR Mosklu Akademijos Darbai”, 1 (94), 1986",
    "Roś, koresp.":"Archiwum Roskie w AGAD, korespondencja",
    "Roś, król.":"Archiwum Roskie w AGAD, królewszczyzny",
    "Roś, m-p":"Archiwum Roskie w AGAD, akta majątkowo-prawne",
    "S...Cki":"S...cki, Dostojnicy litewscy. Rozbiór krytyczny i uzupełnienie dzieła J. Woljfa „Senatorowie ”, „Ateneum”, t I, 1886",
    "SA":"Senieji aktai",
    "Sapiehowie":"[B. Gorczak], Sapiehowie. Materjaty historyczno-genealogiczne i majątkowe, t. I-III, Petersburg 1891",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego. Diariusz i relacje z lat 1691-1696, oprac. J. Woliński, Wrocław 1958",
    "Semk.":"W. Semkowicz, O litewskich rodach bojarskich zbratanych ze szlachtą polską w Horodle roku 1413, „Lituano-Slavica Posnaniensia”, t. III, 1989",
    "Sig.":"Księgi Sigillat Metryki Koronnej",
    "Sobranije gramot i aktov":"Sobranije drevnich gramot i aktov gorodov Minskoj gubernii, Minsk 1848",
    "Starowolski":"S. Starowolski, Monumenia Sarmatarum, Cracoviae 1655",
    "Stawski, Monumenta":"A. Stawski, Monumenta albo zebranie starożytnych ozdób... w dawnym obrazie kodeńskim, t. I-II, Sandomierz 1723",
    "Stryjkowski":"M. Stryjkowski, Kronika polska, litewska, zmodzka i wszystkiej Rusi, t II, Warszawa 1846",
    "Sucha":"Zbiór Branickich z Suchej w AGAD",
    "Sułkowska, Polska kancelaria":"I. Sułkowska-Kurasiowa, Polska kancelaria królewska w latach 1447-1506, Wrocław 1967",
    "Szostkiewicz":"Z. Szostkiewicz, Katalog biskupów obrządku łacińskiego przedrozbiorowej Polski, w: Sacrum Poloniae Millenium, t. I, Rzym 1954",
    "TML":"Metryka Litewska - transkrypcje w AGAD",
    "TO":"Teki Oniasza w Archiwum Państwowym w Poznaniu",
    "Tomaszewicz, Katalog":"J. Tomaszewicz, Katalog dokumentów pergaminowych Muzeum Narodowego w Krakowie, Kraków 1992",
    "Tomkowicz, Materiały":"S. Tomkowicz, Materyały do historii stosunków kulturalnych w XVI w. na dworze królewskim polskim, Kraków 1915",
    "TPaw.":"Teki Adolfa Pawińskiego, t. I-II, Warszawa 1897",
    "TPod.":"Teka Gabryela Junoszy Podoskiego arcybiskupa gnieźnieńskiego, wyd. K. Jarochowski, t. I-V, Poznań 1854",
    "TProch.":"Teki Prochaski",
    "TSang.":"Teki Sanguszków w Archiwum Państwowym w Krakowie, Oddział na Wawelu",
    "Tyszkiewicz, Groby":"E. Tyszkiewicz, Groby rodziny Tyszkiewiczów, Warszawa 1873",
    "Tyszkiewicz, Rachunki":"Rachunki podskarbstwa litewskiego 1648-1652, wydane ze współczesnego rękopisu, wyd. E. Tyszkiewicz, Wilno 1855",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, t. I n., Wrocław-Kórnik 1985 n.",
    "Umn":"Listy z czasów Jana III i Augusta II, wyd. G. B. Unn i W. Skrzydylka, Kraków 1870",
    "Vitoldiana":"Vitoldiana. Codex privilegiorum Vitoldi magni ducis Lithuaniae 1386-1430, wyd. J. Ochmański, Warszawa 1986",
    "VL":"Volumina legum, t. I-VII, Petersburg 1859 n.",
    "Vostokov, Opisanije":"Opisanije russkich i słovenskich rukopisjej Rumiancevskago muzeuma, sost. A. Vostokov, S$. Peterburg 1842",
    "VUB":"Vilniaus universiteto moksline biblioteka s",
    "Wisner, Wojsko":"H. Wisner, Wojsko litewskie I połowy XVII wieku, cz. III, „Studia i Materiały do Historii Wojskowości”, t. XXI, 1978",
    "Wolff":"J. Wolff, Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885; skrótem Wolff, Uzup. określamy egzemplarz tejże pracy w BN z odręcznymi uzupełnieniami Wolffa",
    "WolffKn.":"J. Wolff, Kniaziowie litewsko-ruscy od końca czternastego wieku, Warszawa 1895",
    "Wyczański, Między kulturą":"A. Wyczański, Między kulturą a polityką. Sekretarze królewscy Zygmunta Starego (1506-1548), Warszawa 1990",
    "Zabiełłów":"Archiwum Zabiełłów w AGAD",
    "Załuski":"A. Ch. Załuski, Epistolarum historico-familiarum..., t. I-III, Brunsbergae-Vratislaviae 1709-1711",
    "Zawisza":"K. Zawisza, Pamiętniki... wojewody mińskiego, wyd. J. Bartoszewicz, Warszawa 1862",
    "Zb. AB":"Zbiór Anny Branickiej w AGAD",
    "Zb.Bran.":"Zbiór Adama i Beaty Branickich w AGAD",
    "Zb.MN":"Zbiór z Muzeum Narodowego w AGAD",
    "Zbiór dawnych dypl.":"Zbiór dawnych dyplomatów i aktów miast: Wilna, Kowna, Trok, prawosławnych monasterów, cerkwi i w różnych sprawach, cz. I-II, Wilno 1843",
    "Zbiór Rus.":"Zbiór Rusieckich w Archiwum Państwowym w Krakowie",
    "ŹD":"Źródła Dziejowe, t. IX-X, Warszawa 1878-1881",
    "Zychliński":"T. Zychliński, Złota księga szlachty polskiej, t. 1 n., Poznań 1879 n."
}