""" słownik skrótów literatury """

literatura = {
    "ACap.":"Acta capitulorum nec non iudiciorum ecclesiasticorum selecta, t. I-III, Kraków 1894-1918",
    "ADL":"Archiwum Diecezjalne w Lublinie",
    "ADzT":"Archiwum Dzikowskie Tarnowskich w APKr. ",
    "AEp.":"Acta episcopalia w AKM",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tzw. bernardyńskiego we Lwowie, t. I-XIX, Lwów 1868-1906 ",
    "AKH":"“Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności”",
    "AKM":"Archiwum Kurii Metropolitalnej w Krakowie",
    "AKPr.":"“Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności”",
    "Akta Aleksandra":"Akta Aleksandra, Kraków 1927",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, Kraków 1932 ",
    "AmL":"Akta miasta Lublina w APL",
    "AOf.":"Acta officialia w AKM ",
    "AOfL":"Acta officialia w ADL",
    "APKr.":"Archiwum Państwowe w Krakowie ",
    "APL":"Archiwum Państwowe w Lublinie ",
    "APPń":"Archiwum Państwowe w Poznaniu ",
    "APWr.":"Archiwum Państwowe we Wrocławiu",
    "ArchSang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. II, V, Lwów 1888, 1897",
    "BalzerSkarb.":"O. Balzer, Skarbiec i Archiwum Koronne w dobie przedjagiellońskiej, Lwów 1917",
    "BCzart.":"Muzeum Narodowe w Krakowie -Biblioteka Czartoryskich ",
    "BienWlkp.":"J. Bieniak, Wielkopolska, Kujawy, ziemie łęczycka i sieradzka wobec problemu zjednoczenia państwowego w latach 1300-1306, Toruń 1969",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BoguckiKom.":"A. Bogucki, Komornik i podkomorzy w Polsce piastowskiej, [w:] Społeczeństwo Polski średniowiecznej, t. III, Warszawa 1985; s. 75-133",
    "BoguckiStud.":"A. Bogucki, Ze studiów nad polskimi urzędnikami nadwornymi w XIII wieku, “Czasopismo Prawno-Historyczne” 29, 1977, z. 2, s. 117-142",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XIV, Warszawa 1899-1913 ",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "CB":"Castrensia Biecensia w APKr. ",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CLI":"Castrensia Lublinensia Inscriptionum w APL ",
    "Codex Vitoldi":"Codex epistolaris Vitoldi, magni ducis Lithuaniae 1376-1430, Kraków 1882",
    "Długosz":"Joannis Dlugosz Senioris canonici Cracoviensis opera omnia, t. I-XIV, Cracoviae 1863 n.",
    "DłAnn.":"Joannis Dlugossii Annales seu cronicae incliti Regni Poloniae, lib. I i n., Varsaviae 1964 i n.",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae..., t. I i n., Wilno 1758 i n.",
    "DokPaul.":"Zbiór dokumentów oo. paulinów w Polsce (1328-1464), Kraków 1938",
    "DSZK":"Dokumenty sądu ziemskiego krakowskiego 1302-1453, Wrocław 1971",
    "DwGen.":"W. Dworzaczek, Genealogia, Warszawa 1959, tablice ",
    "DwTarn. I-II":"W. Dworzaczek, [I:] Leliwici Tarnowscy, Warszawa 1971; [II:] Hetman Jan Tarnowski, Warszawa 1985",
    "Dypl.":"Dyplomatyka wieków średnich, opr. M. Bielińska, A. Gąsiorowski, K. Maleczyński, Warszawa 1971",
    "Epist.":"Codex epistolaris saeculi decimi quinti, t. I-III, Kraków 1876- 1894",
    "FriedbŁab.":"M. Friedberg, Ród Łabędziów w wiekach średnich, odbitka z “Rocznika Polskiego Towarzystwa Heraldycznego” 7, Kraków 1925",
    "GackiŁys.":"J. Gacki, Benedyktyński klasztor Świętego Krzyża na Łysej Górze, Warszawa 1873",
    "GackiSiec.":"J. Gacki, Benedyktyński klasztor w Sieciechowie według pism i podań miejscowych, Radom 1872",
    "GItin.":"A. Gąsiorowski, Itinerarium króla Wladyslawa Jagiełły 1386-1434, Warszawa 1972",
    "GórOdr.":"K. Górski, Ród Odrowążów w wiekach średnich, odbitka z “Rocznika Polskiego Towarzystwa Heraldycznego” 8, Kraków 1928 ",
    "GórSMalb.":"K. Górski, Starostowie malborscy w Iatach 1457-1510, Toruń 1960",
    "GrodBusk":"R. Grodecki, Dzieje klasztoru premonstrateńskiego w Busku w wiekach średnich, Kraków 1913",
    "Grzegorz":"M. Grzegorz, Analiza dyplomatyczno-sfragistyczna dokumentów traktatu toruńskiego I466 r., Toruń 1970",
    "GStar.":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej, Warszawa 1981",
    "Halecki":"O. Halecki, Powołanie księcia Władysława Opolskiego na tron krakowski w r. 1273, Kw. Hist. 27, 1913, s. 214-315",
    "HruszMat.":"Materialy do istoriji suspilno politycznych i ekonomicznych widnosyn Zachidnoi Ukrainy, wyd. M. Hruszcwśkyj, Lwów 1905",
    "Inv.":"Inventarium omnium et singulorum privilegiorum ... in Archivo Regni ... continentur, Lutetiae Parisiorum 1862",
    "Iura Mas.":"Iura Masoviae terrestria, t. I-III, Warszawa 1972-1974 ",
    "IvBárt.":"B. Iványi, Bártfa szabad királyi város levéltára 1319-1526, I. Kötet 1319-I501, Budapest 1910",
    "KaczmMon.":"Z. Kaczmarczyk, Monarchia Kazimierza Wielkiego, t. I-II, Poznań 1939-1946",
    "KDKK":"Kodeks dyplomalyczny katedry krakowskiej Ś. Wacława, t. I-II, Kraków 1874",
    "KDM":"Kodeks dyplomatyczny Malopolski, t. I-IV, Kraków 1876-1905; t. V -Materiały w Pracowni Słownika Historyczno-Geograficznego Ziem Polskich w Średniowieczu IH PAN w Krakowie",
    "KDS":"Kodeks dyplomatyczny Śląska, t. I-III, Wrocław 1951 (1956)-1964",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, t. I-VII, Poznań 1877-1985",
    "KętrzElem.":"S. Kętrzyński, O elementach chronologicznych dokumentów Kazimierza Wielkiego, RAUhf 56, 1913 i odbitka Kraków 1913 ",
    "KętrzStud.":"W. Kętrzyński, Studia nad dokumentami XII wieku, RAUhf 26, 1891 i odbitka Kraków 1891",
    "Kierst":"W. Kierst, Wielkorządy krakowskie w XIV-XV st., Prz. Hist. 10, 1910, z. 1-3",
    "Kieszkowski":"J. Kieszkowski, Kanclerz Krzysztof Szydłowiecki, t. I-III, Poznań 1912",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa, t. I, Kraków 1879 ",
    "Klimecka":"G. Klimecka, Ród potomków Sieciecha w wiekach XII i XIII, “Studia Źródłoznawcze” 28, 1983, s. 51-68",
    "KMaz.":"Zbiór ogólny przywilejów i spominków mazowieckich, Warszawa 1919",
    "KMog.":"Diplomata monasterii Clarae Tumbae prope Cracoviam, Kraków 1865",
    "Knigi":"Knigi polskoj koronnoj mietriki XV stoletija, Matricularum Regni Poloniae codices saeculo XV conscripti, t. I, Warszawa 1914 ",
    "KopJędrz.":"Kopiarz jędrzejowski, Biblioteka UAM w Poznaniu, nr akc. 1609 (przed 1926 w posiadaniu W. Smoleńskiego)",
    "KPol.":"Kodeks dyplomatyczny Polski, t. I-III, Warszawa 1847-1858 ",
    "KrzyżDypl.":"S. Krzyżanowski, Dyplomy i kancelaria Przemysława IL Studium z dyplomatyki polskiej XIII wieku, “Pamiętnik Akademii Umiejętności”, Wydziały Filologiczny i Historyczno-Filozoficzny, t. 8, Kraków 1890 i odbitka",
    "KrzyżPSzczyrz.":"S. Krzyżanowski, Przywileje szczyrzyckie, Kw. Hist. 18, 1904, s. 193-209",
    "KTyn.":"Codex diplomaticus monasterii Tynecensis, cz. I, Lwów 1875 ",
    "KUJ":"Codex diplomaticus universitatis studii generalis Cracoviensis, t. I n., Kraków 1870 n.",
    "KuraśLub.":"Slownik historyczno-geograficzny województwa lubelskiego w średniowieczu, opr. S. Kuraś, [w:] Dzieje Lubelszczyzny, t. III, Warszawa 1983",
    "KutrzSądSand.":"S. Kutrzeba, Sqdy ziemskie i grodzkie w wiekach średnich, cz. II: Województwo sandomierskie, RAUhf 42, 1902, s. 75-236 ",
    "KutrzStar.":"S. Kutrzeba, Starostowie, ich początki i rozwój do końca XIV wieku, RAUhf 45, 1903, s. 231-348",
    "KW":"Księgi sądu kasztelana i wojewody lubelskiego w Wąwolnicy w APL",
    "Kw. Hist.":"“Kwartalnik Historyczny”",
    "Lites":"Lites ac res gestae inter Polonos Ordinemque Cruciferorum, t. I-II, Poznań 1890-1892",
    "LKP":"Lubelska księga podkomorska XV wieku, Lublin 1935",
    "Łop.":"Wojewódzka i Miejska Biblioteka Publiczna im. H. Łopacińskiego w Lublinie",
    "MaleczZarys":"K. Maleczyński, Zarys dyplomatyki polskiej wieków średnich, cz. I, Wrocław 1951",
    "MałStud.":"A. Małecki, Studia heraldyczne, t. I-11, Lwów 1890",
    "Mazur":"Z. Mazur, Studia nad kancelarią księcia Leszka Czarnego, Wrocław 1975",
    "MBiecza":"Materialy do historii miasta Biecza 1361-1632, Kraków 1914",
    "MitkPocz.":"J. Mitkowski, Początki klasztoru cystersów w Sulejowie, Poznań 1949",
    "MK":"Metryka Koronna w AGAD",
    "ModzOrg.":"K. Modzelewski, Organizacja gospodarcza państwa piastowskiego, X-XIII wiek, Wrocław 1975",
    "Mosbach":"A. Mosbach, Wiadomości do dziejów polskich z Archiwum Prowincyi Szląskiej, Wrocław 1860",
    "Mos.-Śliw.":"K. Mosingiewicz, B. Śliwiński, Rycerstwo polskie z końca XII w. w falsyfikacie Kazimierza Sprawiedliwego, Kw. Hist. 88, I981, s. 713-722",
    "MPH":"Monumenta Poloniae historica, t. II-VI, Lwów-Kraków 1872- 1893; nowa seria (s.n.) t. I-X",
    "MPV":"Monumenta Poloniae Vaticana, t. I-III, Kraków 1912-1914 ",
    "MRPS":"Matricularum Regni Poloniae summaria, t. I-V, Warszawa 1905-1961",
    "Niesiecki":"K. Niesiecki, Herbarz polski, t. I-X, Lipsk 1839-1846 ",
    "NiwińskiWąch.":"M. Niwiński, Opactwo cystersów w Wąchocku, RAUhf 68, 1930 i odbitka Kraków 1930",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVI wieku, Warszawa 1962",
    "PANKr.":"Biblioteka Polskiej Akademii Nauk w Krakowie ",
    "PapéeNajst.":"F. Papée, Najstarszy dokument polski, RAUhf 23; 1888 ",
    "PaszkPolRus.":"H. Paszkiewicz, Polityka ruska Kazimierza Wielkiego, Warszawa 1925",
    "PezzDok.":"Z. Perzanowski, Dokument i kancelaria sądu ziemskiego krakowskiego do polowy XV wieku, Kraków 1968",
    "PiekMMAD":"F. Piekosiński, Zbiór dokumentów średniowiecznych do objaśniania prawa ziemskiego służących, Monumenta Medii Aevi Diplomatica..., Kraków 1897",
    "PiekPiecz.":"F. Piekosiński, Pieczęcie polskie wieków średnich, cz. I: Doba piastowska, Kraków 1899",
    "PomPrawa":"Metryka Księstwa Mazowieckiego z XV-XVI wieku, t. I, Pomniki Prawa, t. V, Warszawa 1918",
    "Prochaska":"A. Prochaska, Materiały archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 roku, Lwów 1890",
    "Prz. Hist.":"“Przegląd Historyczny”",
    "PSB":"Polski słownik biograficzny, t. I-XXXI, Kraków 1935-1989 ",
    "PtaśnikStud.":"J. Ptaśnik, Studia nad patrycjatem krakowskim wieków średnich, cz. I, “Rocznik Krakowski” 15-16, 1913-14",
    "RachJag.":"Rachunki dworu króla Władysława Jagiełły i królowej Jadwigi z 1. 1388-1420, Kraków 1896",
    "RachKrak.":"Najstarsze księgi i rachunki miasta Krakowa, Kraków 1878",
    "RachKról.":"Rachunki królewskie z lat 1471-1472 i 1476-1478, Wrocław 1960",
    "RachLw.":"Księga przychodów i rozchodów miasta Lwowa, 1-2 (1404-14, 1414-26), wyd. A. Czołowski, Pomniki dziejowe Lwowa II-III, Lwów 1896-1905",
    "RAUhf":"“Rozprawy (Polskiej) Akademii Umiejętności. Wydział Historyczno-Filozoficzny”",
    "Rauscher":"Soudni knihy Osvetimské a Zátorské z roku 1440-1562, wyd. R. Rauscher, Bratislava 1931",
    "RegSchl.":"Regesten zur schlesischen Geschichte, t. I n., Breslau 1875 n. ",
    "Repertorium":"Repertorium polskich dokumentów doby piastowskiej, z. I do końca XII w., opr. Z. Kozłowska-Budkowa, Kraków 1937",
    "RutSąd.":"A. Rutkowska-Płachcińska, Sądeczyzna w XIII i XIV wieku, Wrocław 1961",
    "SemkAwd.":"W. Semkowicz, Ród Awdańców w wiekach średnich, “Roczniki Towarzystwa Przyjaciół Nauk Poznańskiego” 44-46, Poznań 1917-1920",
    "SemkNiezn.":"W. Semkowicz, Nieznane nadania na rzecz opactwa jędrzejowskiego, Kw. Hist. 24, 1910, s. 66-97",
    "Seruga":"J. Seruga, Dokumenty pergaminowe w zbiorach biblioteczno-muzealnych hr. Tarnowskich w Suchej, Kraków 1936",
    "SHGKr.":"Słownik historyczno-geograficzny województwa krakowskiego w średniowieczu, cz. I-II, Wrocław 1980 n.",
    "SikoraLis.":"F. Sikora, O rzekomej dominacji politycznej Lisów w Małopolsce w XIII w., czyli kilka uwag o rodzie Pobogów, St. Hist. 26, 1983, z. 1, s. 3-38",
    "SPPP":"Starodawne prawa polskiego pomniki, t. II, VII, VIII, Kraków 1870-1884",
    "SSNO":"Słownik staropolskich nazw osobowych, pod red. W. Taszyckiego, t. I n., Wrocław 1965 n.",
    "St. Hist":"“(Małopolskie) Studia Historyczne”, t. I n., Kraków ",
    "SułkDok.":"I. Sułkowska-Kurasiowa, Dokumenty królewskie i ich funkcja w państwie polskim za Andegawenów i pierwszych Jagiellonów, 1370-1444, Warszawa 1977",
    "ŚliwKrąg":"B. Śliwiński, Krąg krewniaczy biskupa krakowskiego Iwona Odrowąża, “Zeszyty Naukowe Wydziału Humanistycznego Uniwersytetu Gdańskiego”, Historia 14, Gdańsk 1984, s. 49-7l",
    "ŚliwMM":"B. Śliwiński, Mikołaj Mściwujowic, “Rocznik Gdański” 39, 1979, z. 1, s. 75-91",
    "TA":"Najdawniejsze zapiski ziemskie lubelskie z 1409 r., “Teki Archiwalne” 7, 1961, s. 11-68",
    "TB":"Terrestria Biecensia w APKr.",
    "TC":"Terrestria Cracoviensia w APKr. ",
    "TCzch.":"Terrestria Czchoviensia w APKr. ",
    "TL":"Terrestria Lublinensia w APL",
    "TLI":"Terrestria Lublinensia Inscriptionum w APL",
    "TPaw.":"Teki A. Pawińskiego, t. II: Liber quitantiarum regis Casimiri, Warszawa 1897",
    "TPilsn.":"Terrestria Pilsnensia w APKr. ",
    "TZ":"Terrestria Zatoriensia w APKr.",
    "U ":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, ",
    "UlanStan.":"B. Ulanowski, O założeniu i uposażeniu klasztoru benedyktynek w Staniątkach, RAUhf 28, 1892 i odbitka Kraków 1891",
    "Uruski":"S. Uruski, Rodzina, t. I-XV, Warszawa 1904-1931 ",
    "VL":"Volumina Iegum, t. I, Petersburg 1859",
    "VMPL":"Vetera monumenta Poloniae et Lithuaniae, t. I, Rzym 1860 ",
    "WdowGen.":"Z. Wdowiszewski, Genealogia Jagiellonów, Warszawa 1968 ",
    "Weise":"E. Weise, Die Staatsverträge des Deutschen Ordens in Preussen im 15. Jahrhundert, t. I-III, Königsberg 1939-Marburg 1966 ",
    "WierzbFragm.":"Dwa fragmenty ksiąg kancelaryjnych królewskich z 1-szej połowy XV wieku, wyd. T. Wierzbowski, Warszawa 1907",
    "WojcStud.":"Z. Wojciechowski, Ze studiów nad organizacją państwa polskiego za Piastów, Lwów 1924",
    "WojcUgrup.":"P. K. Wojciechowski, Ugrupowania polityczne w ziemi krakowskiej i sandomierskiej w latach 1280-1288, Prz. Hist. 70, 1979 s. 57-72",
    "WSB":"Wielkopolski słownik biograficzny, Poznań 1981 ",
    "WyrozDokRad.":"B. Wyrozumska, Dokumenty miasta Radomia z lat 1355-1450 [I], ... z lat 1444 do 1611 [II], “Biuletyn Kwartalny Radomskiego Towarzystwa Naukowego” III/4, 1966, XXI/4, 1984 (wyd. 1987)",
    "Zap. Hist.":"“Zapiski Historyczne” (przedtem “Zapiski Towarzystwa Naukowego w Toruniu”)",
    "ZakrzSzczyrzyc":"S. Zakrzewski, Najdawniejsze dzieje klasztoru cystersów w Szczyrzycu (1238-1382), Kraków 1901",
    "ZDKK":"Zbiór dokumentów katedry i diecezji krakowskiej, cz. I-II, Lublin 1965-1973",
    "ZDM":"Zbiór dokumentów małopolskich, t. I-VIII, Wrocław 1962- 1975 ",
    "Zeissberg":"H. Zeissberg, Kleinere Geschichtsquellen Polens im Mittelalter w: Archiv für österreichische Geschichte, 55, 1877"
}
