literatura = {
    "ABiMK" : "Archiwa, Biblioteki i Muzea Kościelne, Lublin 1959 n.",
    "AGAD" : "Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ" : "Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tzw. bernardyńskiego we Lwowie, t. I-XXV, Lwów 1868-1935",
    "AJZR" : "Arhiv Ugo-zapadnoj Rossii. cz. TV11I. Kiev 1859-1911",
    "Akta unii" : "Akta unii Polski z Litwą 1385-1791. wyd. S. Kutrzeba. W. Semkowicz, Kraków 1932",
    "Akty JZR" : "Akty otnosaśiesd k istorii Uźnoj i Zapadnoj Rossii. sobranye i izdannie Arheografićeskou Kommiseu. t. 1-XV. St. Petersburg 1863-1892",
    "APKr." : "Archiwum Państwowe w Krakowie",
    "APL" : "Archiwum Państwowe w Lublinie",
    "AR" : "Archiwum Radziwiłłów w AGAD",
    "ArchSang." : "Archiwum XX. Lubartowiczow Sanguszków w Sfawucie, t. I-VII, wyd. Z. L. Radzimiński, P. Skobielski. B. Gorczak, Lwów 1887-1910",
    "AS" : "Archiw um Sanguszków' w APKr.",
    "AZ" : "Archiw um Zamoyskich w AGAD",
    "AZR" : "Akty otnosdsiesd k istorii Zapadnoj Rossii sobranye i izdannye Arheografićeskou Kommiseu. t. I-V. St. Petersburg 1846-1853",
    "BCzart." : "Biblioteka XX. Czartoryskich w Krakowie",
    "BJ" : "Biblioteka Jagiellońska w Krakowie",
    "Bon." : "A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913, t.",
    "BPAU i PANKr." : "Biblioteka Naukowca Polskiej Akademii Umiejętności i Polskiej Akademii Nauk w- Krakowie",
    "CBus." : "Castrensia Buscensia w CDIAUL (f. 3)",
    "CDIAUK" : "Central'nij Derzavnij Istorićnij Arhiv Ukraini Kiiv",
    "CDIAUL" : "Central'nij Derzavnij istorićnij Arhiv Ukraini L'viv",
    "CLub." : "Castrensia Lublinensia w APL",
    "CodVit." : "Code.x epistolaris Vitoldi magni ducis Lithuaniae 1376-1430. wyd. A. Prochaska, Kraków' 1882",
    "CSand." : "Castrensia Sandecensia w APKr.",
    "CzepPe, Kamaryla" : "M. Czeppe, Kamatyła Pana z Dukli. Kształtowanie się obozu politycznego Jerzego Augusta Mniszcha 1750-1763. Warszawa 1998",
    "DanSkarb." : "I. Daniłowicz, Skarbiec dyplomatów papieskich, cesarskich, królewskich t. I-II. wyd. J. Sidorowicz, Wilno 1860-1862",
    "DATO" : "Derzavnij Arhiv Ternopils'koi'Oblasti w Tarnopolu",
    "DAŻO" : "Derzavnij Arhiv Żitomirs'ko! Oblasti w Żytomierzu",
    "DeputPodol." : "Derzavnij Arhiv Hmel'nickoi Oblasti w Chmielnickim [Płoskirowie], Akta Podolskiej Deputacji Szlacheckiej (f. 230. op. 1)",
    "DeputWoł." : "Akta Wołyńskiej Deputacji Szlacheckiej (f. 146. op. 1) w DAŻO",
    "DłAnn." : "Ioannis Dlugossii Annales seu cronicae incliti Regni Poloniae. lib. I-XII, Varsoviae 1964-2001. Cracoviae 2003-2005",
    "DMAMJ" : "Dokumenty Moskovskogo Arhiva Ministerstwa Usticii, t. I, Moskva 1897",
    "Dub." : "Księgi kontraktowe dubieńskie w CDIAUK (f. 35)",
    "Epist." : "Codex epistolaris saeculi decimi quinti, t. I-III. wyd. A. Sokołowski. J. Szujski, A. Lewicki. Kraków 1876-1894",
    "GK" : "księgi grodzkie krzemienieckie w CDIAUK (f. 21)",
    "GŁ" : "księgi grodzkie łuckie w CDIAUK (f. 25)",
    "Gorczak" : "B. Gorczak, Katalogpetgaminów znajdujących się w Archiwum X.X. Sanguszków w Sławucie, Sławuta 1912",
    "Gramoty XIV" : "Gramoli XIVst.. wyd. M. M. Pesak. KiiY 1974",
    "Gramoty XVI" : "Volins'ki granioti XVI st.. wyd. V. B. Zadorożnij i A. M. Matvienko, Kiev 1995",
    "Gramoty Vielikich Kniaziv" : "Gramoty' Velikih Knaziv Litovskih 1390-1569. izd. V. Antonowie. K. Karlovskij. Kiev 1868",
    "GW" : "Księgi grodzkie włodzimierskie w CDIAUK (f. 28)",
    "GŻyt." : "Księgi grodzkie żytomierskie w CDIAUK (f. 1L)",
    "Halecki. Ostatnie" : "O. Halecki, Ostatnie łata Swidtygiełły i sprawa wołyńska za Kazimierza Jagiellończyka, Kraków 1915",
    "Inwentarz" : "Inwentarz monasterów bazyliańskich w CDIAUL",
    "Jakovenko" : "N. M. Akovenko. U krain s'ka slahta z kinca XIV do seredini XVII st. (Volin' i Centrcil'na Ukraina), Kiiv 1993",
    "Jerlicz" : "J. Erlicz, Latopisiec albo kroniczka, wyd. K. Wł. Wójcicki, t. I-II, Warszawa 1853",
    "Kalendarzyk" : "Kalendarzyk polityczny dla Królestwa Polskiego i Wielkiego Księstwa Litewskiego.",
    "Katalog KAK" : "Katalog Kolckcii Dokumentiv Kins' koi Arheografićnoi Komisu (1369-1899 r.r.). wyd. J. R. Daskevic, L. A. Procenko. Z. S. Homutecka. Kiiv 1971",
    "Kempa. Ostrogski" : "T. Kempa. Konstanty Wasyl Ostrogski (ok. 1524/1525-1608). Wojewoda kijowski i marszałek ziemi wołyńskiej, Toruń 1997",
    "KK" : "Księgi Kanclerskie Metryki Koronnej w AGAD",
    "KonfWoł." : "Księgi sądów konfederackich województwa wołyńskiego (f. 18) w CDIAUK",
    "Kons. Lwowski" : "Księgi oficjalatu lwowskiego w Archiwum Kurii Metropolitalnej Lwowskiej w Krakowie",
    "Kremieniecki ziemski sud" : "Kremieniec'kij zemskij suci. Opisi aktovih bug. I-III, Kiiv 1959-1965",
    "KułKanc." : "P. Kulakovs'kij, Kancelaria Rus'koi (Volin skoi) Metriki 1569-1673 rr. Studia z istorii ukrains'kogo regionalizmu v Reći Pospolitii, Ostros - L'viv 2002",
    "KułMetr." : "Rus'ka (Volin'ska) Metrika. Kniga za 1652-1673 r.r. opr. R Kulakovs'kij, PanTatki istorii' shidnoi' Evropi, Dżerela XV-XVII st., Ostrog-Warszawa-Moskva 1999",
    "Lewicki, Powstanie" : "A. Lewicki, Powstanie Swidtygiełły, Kraków 1892",
    "Ljubavskij, Delenie" : "M. Lubavskij, Oblastnoje delenie i mestnoe upravlene Litovsko-russkogo gosudarsti'a ko vremeni izdania perrogo litovskogo statuta. Moskva 1892",
    "Ljubavskij, Sejm" : "M. Lubavskij, Litovsko-russkij sejm, Moskva 1900",
    "LM" : "Lietuvos Metrika, 1 .1 n., Vilnius 1993 n.",
    "Maksimejko, Sejmy" : "N. A. Maksimejko, Sejmy Litovsko-russkogo gosudarsrva do Lublins'koj Unii 1569 gHarkov 1902",
    "MK" : "Metryka Koronna w AGAD",
    "ML" : "Metryka Litewska (w RGADA f. 389, nr księgi)",
    "MW" : "Rus'ka (Volins'ka) Metrika. Regesti dokumentiv Koronnoi kancelarii dla ukrains' kih zemel (Volins'ke, Kiiv s'ke, Braclavs'ke, Cernigivs'ke vojevodst\'a) 1569-1673, wyd. H. Boriak, L. Demćenko. V. Kravcenko i in., Kiiv 2002",
    "Nies." : "K. Niesiecki, Herbarz polski, t. 1-X, wyd. J. N. Bobrowicz, Lipsk 1839-1846",
    "Pamjatniki Vrem. Kom." : "Pam'atniki izdannye Vremennou komissieu dla rozbora drevnih aktov , Kiev 1848, 1 . 1",
    "Pietkiewicz, Wielkie Księstwo" : "K. Pietkiewicz, Wielkie Księstw o Litewskie pod rządami Aleksandra Jagiellończyka, Poznań 1995",
    "Poczet" : "A. Boniecki, Poczet rodów w Wielkim Księstwie Litew skim w XV i XVI wieku, Warszawa 1887",
    "Podh." : "Archiwum Podhoreckie w APKr.",
    "PSB" : "Polski słownik biograficzny, 1 .1 n., Kraków 1935 n.",
    "Ptaszycki, Opisanie" : "S. Ptaszycki, Opisanie knig i aktov Litovskoj metriki, St. Petersburg 1887",
    "Radzimiński, Laudum" : "Z. L. Radzimiński. Laudumpienvszego i zarazem ostatniego sejmiku województwa włodzimierskiego 1794 R., Lwów 1917",
    "Radziwiłł. Memoriale" : "Albrycht Stanisław Radziwiłł, Memoriale rerum gestarum in Polonia 1632-1656A. 1-4, opr. A. Przyboś, R. Żelewski, Wrocław 1968-1975",
    "Rewizja zamków" : "Litovs'ka Metrika. Kniga 56J. Revizii ukrains'kih zamkiv 1545 roku. wyd. V. Kravcenko. Kiiv 2005",
    "RGADA" : "Rossijskij Gosudarstvennyj Arhiv Drevnih Aktov w Moskwie",
    "Sig." : "Księgi Sigillat MK w AGAD",
    "Sobczuk, Kremianiecka" : "V. Sobćuk. Krem'anec'ka volost' u XVIstolitti: teritorid i poseł'end. w: Zapiski Naukovogo Tovaristvaimeni Sevcenka, t. CCXXXI. Praei Komisii' special'nih (dopomiżnih) istorienih. L'viv 1996. s. 380-399",
    "Teodorowicz" : "N. I. Teodorowicz, Istońko-statistićeskoe opisane cerkvej i prihodov volins'koj eparhii. t. 1-3. Pocaev 1893",
    "TK" : "Materiały Trybunału Koronnego w CDIAUL (f. 773)",
    "Torgivlja" : "Torghld na Ukraini XIV - seredina XVII stol'ittd. Volin' i Naddniprdnsina. wyd. V. M. Kravcenko. N. M. Akovenko, Kiiv 1990",
    "Tzw.ML" : "Tak zwana Metryka Litewska w AGAD",
    "U" : "Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy. red. A. Gąsiorowski, t. 1 n., Wrocław-Kórnik 1985 n., t.",
    "Ur." : "S. Uruski, A. A. Kosiński. A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XV1, Warszawa 1904-1938, t.",
    "UWKL" : "Urzędnicy Wielkiego Księstwa Litewskiego. Spisy. red. A. Rachuba, 1 .1, IV, Warszawa 2003-2004",
    "VL" : "Volumina legum, wyd. J. Ohryzko i Z. Kaczmarczyk, t. 1-X. St. Petersburg 1859 - Poznań 1952",
    "WolffKniaz." : "J. Wolff, Kniaziowie litewsko-ruscy od końca czternastego wieku. Warszawa 1895",
    "WolffSenat." : "J. Wolff. Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "ZK" : "Księgi ziemskie krzemienieckie w CDIAUK (f. 22)",
    "ZŁ" : "Księgi ziemskie łuckie w CDIAUK (f. 26)",
    "ZW" : "Księgi ziemskie włodzimierskie w CDIAUK (f. 27)",
    "ZAK" : "Żizn' kndza Andrea Mihajlovica Kurbskogo v Litve i na Volyni. t. 1-2, Kiev 1849"
}