""" słownik skrótów literatury """

literatura = {
    "AAG":"Archiwum Archidiecezji Gnieźnieńskiej w Gnieźnie",
    "AAP":"Archiwum Archidiecezji Poznańskiej w Poznaniu",
    "ACap.":"Acta capitulorum nec non iudiciorum ecclesiasticorum selecta, wyd. B. Ulanowski, t. I-III, Kraków 1894-1918",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, t. I n., Lwów 1868 n.",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "Akta Aleksandra":"Akta Aleksandra króla polskiego, wielkiego księcia litewskiego itd. (1501-1506), wyd. F. Papee, Kraków 1927",
    "Akta unii":"Akta unii Polski z Litwą, wyd. S. Kutrzeba i W. Semkowicz, Kraków 1932",
    "AFP":"Wojewódzkie Archiwum Państwowe w Poznaniu",
    "ASPrus.":"Akta stanów Prus Królewskich, wyd. K. Górski, M. Biskup, I. Janosz-Biskupowa, t. I n., Toruń 1955 n.",
    "BielKanc.":"M. Bielińska, Kancelarie i dokumenty wielkopolskie XIII wieku, Wrocław 1967",
    "BienWlkp.":"J. Bieniak, Wielkopolska, Kujawy, ziemie łęczycka i sieradzka wobec problemu zjednoczenia państwowego w la­tach 1300-1306, Toruń 1969",
    "Codex Vitoldi":"Codex epistolaris Vitoldi, magni ducis Lithuaniae 1376-1430, wyd. A. Prochaska, Kraków 1882",
    "Długosz":"Joannis Długosii seu Longini canonici Cracoviensis Historiae Polonicae libri XII, [w:] tegoż, Opera omnia, t. XII­-XIV, Kraków 1876-1878",
    "Epist.":"Codex epistolaris saeculi decimi quinti, wyd. A. Sokołowski, J. Szujski, A. Lewicki, t. I-III, Kraków 1876-1894",
    "GnG":"Księgi grodzkie gnieźnieńskie w APP ",
    "GnZ":"Księgi ziemskie gnieźnieńskie w APP",
    "GStar.":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej, Warszawa 1981",
    "GUrz.":"A. Gąsiorowski, Urzędnicy wielkopolscy 1385--1500. Spisy, Poznań 1968",
    "Jasiński, Wlkp.":"K. Jasiński, Studia nad wielkopolskim stronnictwem książęcym w połowie XIII w. Współpracownicy Przemysła I do 1253 r., [w:] Społeczeństwo Polski średniowiecznej, t. I, Warszawa 1981, s. 161-201.",
    "KalG":"Księgi grodzkie kaliskie w APP",
    "KalZ":"Księgi ziemskie kaliskie w APP ",
    "KcG":"Księgi grodzkie kcyńskie w APP ",
    "KcZ":"Księgi ziemskie kcyńskie w APP",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej S. Wacława, wyd. F. Piekosińśki, cz. I-II, Kraków 1883",
    "KDM":"Kodeks dyplomatyczny Małopolski, wyd. F. Piekosiński, t. I-IV, Kraków 1876-1905",
    "KDŚl.":"Kodeks dyplomatyczny Śląska, wyd. K. Maleczyński, A. Skowrońska, t. I-III Wrocław 1956-1964",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, t. I-IV, Poznań 1877-1881, t. V, wyd. F. Piekosiński, Poznań 1908, t. VI­-VII, wyd. A. Gąsiorowski, H. Kowalewicz, R. Walczak, War­szawa 1982-1984, seria nowa (s.n.), t. I, wyd. Z. Perzanow­ski, Poznań 1975",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa, cz. I-IV, wyd. F. Piekosiński, Kraków 1879-1882",
    "KMaz.":"Kodeks dyplomatyczny księstwa mazowieckiego, Warszawa 1863",
    "Knigi":"Knigi polskoj koronnoj mietriki XV stoletija (Matricularum Regni Poloniae codices saeculo XV conscripti), t. I, Warszawa 1914",
    "KonG":"Księgi grodzkie konińskie w APP ",
    "KonZ":"Księgi ziemskie konińskie w APP",
    "KoścG":"Księgi grodzkie kościańskie w APP ",
    "KoścZ":"Księgi ziemskie kościańskie w APP",
    "KPol.":"Kodeks dyplomatyczny Polski, t. I-IV, wyd. L. Rzyszczewski, A. Muczkowski, J. Bartoszewicz, M. Bobowski, War­szawa 1847-1887",
    "Kr. 1":"Księga sądowa Wojciecha Malskiego namiestnika królewskiego na Wielkopolskę w APP",
    "KrzyżDypl.":"S. Krzyżanowski, Dyplomy i kancelaryja Przemysława II. Studium z dyplomatyki, Pamiętnik Akademii Umie­jętności, Wydziały Filologiczny i Historyczno-Filozoficzny, VIII, 1980, s. 122-192",
    "KTyn.":"Codex diplomaticus monasterii Tynecensis, wyd. W. Kętrzyński, S. Smolka, cz. I, Lwów 1875",
    "Leksz. II":"Die altesten grosspolnischen Grodbucher, cz. II, wyd. J. Lekszycki, Leipzig 1889",
    "Lites":"Lites ac res gestae inter Polonos Ordinemque Cruciferorum. Editio altera, t. I, Poznań 1890",
    "MaleczSt.":"K. Maleczyński, Studia nad dyplomami i kancelarią Odonica i Laskonogiego 1202-1239, Lwów 1928",
    "MK":"Metryka koronna: księgi wpisów w AGAD",
    "MPH":"Monumenta Poloniae historica, t. II-VI, Lwów-Kraków 1872-1893, seria II (s.n.), t. I n.",
    "MRPS":"Matricularum Regni Poloniae summaria, t. I-V, Warszawa 1905-1961",
    "NakG":"Księgi grodzkie nakielskie w APP ",
    "NakZ":"Księgi ziemskie nakielskie w APP",
    "PakNał.":"J. Pakulski, Nałęcze wielkopolscy w średniowieczu. Genealogia, uposażenie i rola polityczna w XII-XIV w., War­szawa 1.982",
    "PakZar.":"J. Pakulski, Ród Zarembów w Wielkopolsce w XIII i początkach XIV wieku, Prace Komisji Historii Bydgoskiego Towarzystwa Naukowego, XI, 1975, s. 103-137",
    "PiekWyb.":"F. Piekosiński, Wybór zapisek sądowych grodzkich i ziemskich wielkopolskich z XV wieku, t. I, z. 1, [w:] tegoż, Studia, rozprawy i materiały z dziedziny historii polskiej i prawa polskiego, t. VI, z. 1, Warszawa 1902",
    "PozG":"Księgi grodzkie poznańskie w APP ",
    "PozZ":"Księgi ziemskie poznańskie w APP",
    "Pozn. I":"Die altesten grosspolnischen Grodbucher, cz. I, wyd. J. Lekszycki, Leipzig 1887",
    "Pozn. II":"Księga ziemska poznańska 1400-1407, wyd. K. Rzyski, K. Kaczmarczyk, Poznań 1960",
    "PSB":"Polski słownik biograficzny, t. I-XXVII, Kraków 1935-1983",
    "PyzG":"Księgi grodzkie pyzdrskie w APP",
    "PyzZ":"Księgi ziemskie pyzdrskie w APP",
    "Raczyński, Lit.":"Kodex dyplomatyczny Litwy, wyd. E. Raczyński, Wrocław 1845",
    "Raczyński, Wlkp.":"Kodex dyplomatyczny Wielkiej Polski, wyd. E. Raczyński, Poznań 1840",
    "Reg. Teut.":"Regesta historico-diplomatica Ordinis S. Mariae Theutonicorum, t. I-II, wyd. E. Joachim, W. Hubatsch, Göt­tingen 1948-1950",
    "Roty":"Wielkopolskie roty sądowe XIV-XV wieku, t. I-V, wyd: H. Kowalewicz, W. Kuraszkiewicz, Poznań-Wrocław 1959-1981",
    "RTPNP":"Roczniki Towarzystwa Przyjaciół Nauk Poznańskiego",
    "Semkowicz, Wywody":"Wywody szlachectwa w Polsce XIV-XVII w., wyd. W. Semkowicz, Rocznik Towarzystwa He­raldycznego we Lwowie, 3, 1911-1912, Lwów 1913",
    "Sikora, Dok.":"F. Sikora, Dokumenty i kancelaria Przemysła I oraz Bolesława Pobożnego 1239-1279 na tle współczesnej dyplomatyki wielkopolskiej, Wrocław 1969",
    "SPPP":"Starodawne prawa polskiego pomniki, t. II n., Kraków 1870 n.",
    "Tęgowski":"J. Tęgowski, O włodarzach w Polsce XIII wieku, Studia i Materiały do Dziejów Wielkopolski i Pomorza, 15, z. 1, 1983, s. 5-17",
    "Toeppen AS":"Acten der Standetage Preussens unter der Herrschaft des Deutschen Ordens, wyd. M. Toeppen, t. I-V, Leip­zig 1878-1886",
    "TPaw.":"Teki A. Pawińskiego, t. I n., Warszawa 1897 n.",
    "VL":"Volumina legum (przedruk J. Ohryzki), t. I, Petersburg 1859",
    "Warschauer":"Stadtbuch von Posen, wyd. A. Warschauer, t. I,. Posen 1892",
    "WSB":"Wielkopolski słownik biograficzny, Poznań 1981",
    "WschG":"Księgi grodzkie wschowskie w APP",
    "WschZ":"Księgi ziemskie wschowskie w APP",
    "Wuttke, Stadtebuch":"Stadtebuch des Landes Posen, wyd. H. Wuttke, Leipzig 1864",
    "ZDM":"Zbiór dokumentów małopolskich, t. I-VIII, wyd. S. Kuraś, I. Sułkowska-Kuraś, Wrocław 1962-1975"
}