""" słownik skrótów literatury """

literatura = {
    "ABernKr":"Archiwum Bernardynów w Krakowie ",
    "ADCh":"Archiwum Diecezji Chełmińskiej w Pelplinie ",
    "AGAD":"Archiwum Główne Akt Dawnych",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, t. I-XXV, Lwów 1868-1935 ",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "Akta Aleksandra":"Akta Aleksandra króla polskiego, wielkiego księcia litewskiego itd. (I501-l506), wyd. F. Papée, Kraków 1927",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "APB":"Archiwum Państwowe w Bydgoszczy",
    "APP":"Archiwum Państwowe w Poznaniu",
    "APT":"Archiwum Państwowe w Toruniu",
    "ASczan":"Akta Sczanieckich z Nawry w APT",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "ASWojKr":"Akta sejmikowe województwa krakowskiego, wyd. S. Kutrzeba, A. Przyboś, t. I-V, Kraków 1932-1984",
    "ASWojPoz":"Akta sejmikowe województw poznańskiego i kaliskiego, wyd. W. Dworzaczek, t. I (1572-1632), cz. 1 (1572-1616), Poznań 1957, cz. 2 (1616-1632), Poznań 1962",
    "ATom.":"Acta Tomiciana, t. I i n., Poznań 1852 i n.",
    "Bär":"M. Bär, Westpreussen unte.· Friedrich dem Grossen, t. I-II, Leipzig 1901",
    "BCzart.":"Muzeum Narodowe w Krakowie - Biblioteka Czartoryskich",
    "Biliński":"A. Biliński, Szlachta ziemi dobrzyńskiej za ostatnich JagieIlonów, Warszawa 1932",
    "BJag.":"Biblioteka Jagiellońska w Krakowie",
    "BKórn.":"Biblioteka Kórnicka Polskiej Akademii Nauk w Kórniku",
    "BKórn.Kat.":"Katalog rękopisów staropolskich Biblioteki Kórnickiej XVI XVIII w., t. I-II, opr. R. Marciniak, M. Muszyński, J. Wiesiołowski, Wrocław 1971-1985",
    "Błeszczyński":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII wieku, (w:) S. K. Kossakowski, Monografie historyczno genealogiczne, t. III, Warszawa 1872",
    "BobrAkWiecz":"Księgi grodzkie bobrownickie (akta wieczyste) w AGAD",
    "BobrGDec":"Księgi grodzkie bobrownickie (dekrety) w AGAD",
    "BobrGRel":"Księgi grodzkie bobrownickie (relacje) w AGAD",
    "BobrGW":"Księgi grodzkie bobrownickie (wypisy) w AGAD",
    "BobrZObl":"Księgi ziemskie bobrownickie (oblaty) w AGAD ",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "BrzGDec":"Księgi grodzkie brzeskie (dekrety) w AGAD",
    "BrzGDiss":"Księgi grodzkie brzeskie (dissoluta) w AGAD",
    "BrzGInscr":"Księgi grodzkie brzeskie (inskrypcje) w AGAD",
    "BrzGObl":"Księgi grodzkie brzeskie (oblaty) w AGAD",
    "BrzGRec":"Księgi grodzkie brzeskie (rekognicje) w AGAD",
    "BrzGRel":"Księgi grodzkie brzeskie (relacje) w AGAD ",
    "BrzGRelDec":"Księgi grodzkie brzeskie (relacje i dekrety) w AGAD",
    "BrzZ":"Księgi ziemskie brzeskie w AGAD",
    "BrzZKopie":"Księgi ziemskie brzeskie (kopie) w AGAD",
    "BUMK":"Biblioteka Uniwersytetu Mikołaja Kopernika w Toruniu",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego",
    "BydG":"Księgi grodzkie bydgoskie w APP",
    "BydZ":"Księgi ziemskie bydgoskie w APP",
    "ChełM":"Akta miasta Chełmży w APT",
    "Chodyński":"A. Chodyński, Kościół i klasztor 00. Reformatów w Kaliszu, Warszawa 1874",
    "CIP":"Corpus iuris Polonici, wyd. O. Balzer, t. III, Kraków 1906",
    "Corpus IV/1-2":"Corpus Inscriptionum Poloniae, t. 4: Województwo włocławskie, opr. A. Mietz i J. Pakulski, cz. 1: Kujawy brzeskie, Włocławek 1985, cz. 2: Ziemia dobrzyńska, Włocławek 1987",
    "CPH":"Czasopismo Prawno-Historyczne",
    "Diariusz 1566":"I. Kaniewska, Diariusz sejmu lubelskiego 1566r., Wrocław 1980",
    "Dw Mat.":"wypisy z ksiąg metrykalnych prof. W. Dworzaczka w BKórn. ",
    "Dworzaczek":"W. Dworzaczek, Genealogia, Warszawa 1959",
    "Elektorowie":"Elektorowie Władysława N, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, wyd. J. Dunin-Borkowski i M. Dunin-Wąsowicz, RTH, t. I, Lwów 1910",
    "Gawarecki":"W. H. Gawarecki, Opis topograficzno-historyczny ziemi dobrzyńskiej, Płock 1825",
    "GnG":"Księgi grodzkie gnieźnieńskie w APP ",
    "GnZ":"Księgi ziemskie gnieźnieńskie w APP",
    "GolM":"Akta miasta Golubia w ADCh",
    "Inow Franc.":"Archiwum franciszkanów z Inowrocławia w APB",
    "InowG":"Księgi grodzkie inowrocławskie w APP",
    "InowP":"Księgi podkomorskie inowrocławskie w APP",
    "InowZ":"Księgi ziemskie inowrocławskie w APP",
    "Kalendarzyk":"Kalendarzyk polityczny na rok przybyszowy 1794,Warszawa 1793 ",
    "KBB":"Kronika Bernardynów Bydgoskich, wyd. K. Kantak, 'Roczniki Towarzystwa Przyjaciół Nauk Poznańskiego', T. XXXIII, Poznań 1907, s. 1-333",
    "KDKK":"Kronika Diecezji Kujawsko - Kaliskiej",
    "KodDypl. UJ":"Kodeks dyplomatyczny Uniwersytetu Jagiellońskiego",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-genealogiczne, t. I-III, Warszawa 1859-1872",
    "KowGRec":"Księgi grodzkie kowalskie (rekognicje) w AGAD",
    "KowZ":"Księgi ziemskie kowalskie w AGAD",
    "KruszZ":"Księgi ziemskie kruszwickie w AGAD.",
    "KTKP":"Księgi Trybunału koronnego w Piotrkowie (wypisy prof. W. Dworzaczka w BKórn.)",
    "Kubala":"J. Kubala, Jerzy Ossoliński, Warszawa 1924",
    "Lasocki":"Z. Lasocki, Dostojnicy i urzędnicy ziemi dobrzyńskiej w XIV i XV wieku, 'Miesięcznik Heraldyczny', t. 13, 1934",
    "Lauda dobrz.":"Lauda sejmików ziemi dobrzyńskiej, wyd. F. Kluczycki, Acta historica res gestas Poloniae illustrantia, t. X, Kraków 1887",
    "Lengnich":"G. Łengnich, Geschichte der Preussischen Landes Koniglich Polnis-chen Antheil, Bd. I-IX, Danzig 1722-1755",
    "LM":"Księgi zgonów parafii katolickich w Archiwum Diecezjalnym we Włocławku",
    "Ludwig":"M. Ludwig, Besteuerung und Verpfändung königlicher Städte im spätmittelalterlichen Polen, Giessener Abhandlungen, Bd. 126: 1984",
    "LWWK 1565":"Lustracja województw wielkopolskich i kujawskich 1564-1565, cz. II, wyd. A. Tomczak, Bydgoszcz 1963",
    "LWWK 1616-1620":"Lustracja województw wielkopolskich i kujawskich 1616-1620 w ASK w AGAD",
    "LWWK 1628-1632":"Lustracja województw wielkopolskich i kujawskich 1628-1632, wyd. Z. Guldon, t. I-III, Wrocław 1967-1969",
    "LWWK 1789":"Lustracja województw wielkopolskich i kujawskich 1789, cz. 3: Województwa łęczyckie i brzesko-kujawskie, wyd. A. Tomczak, Warszawa 1977",
    "ŁęczG":"Księgi grodzkie łęczyckie w AGAD",
    "ŁęczGInscr":"Księgi grodzkie łęczyckie (inskrypcje) w AGAD",
    "MHDW":"Monumenta historica dioeceseos Wladislaviensis, t. I-XXVI: 1891-1946",
    "Michałowski":"J. Michałowski, Księga pamiętnicza, Kraków 1864 ",
    "MK":"Metryka koronna w AGAD",
    "MMAH":"Monuntenta medii aevi historica res gestas Poloniae illustrantia, t. I-XIX, Kraków 1875-1927",
    "MPH":"Monumenta Poloniae historica",
    "MRPS":"Matriculanem Regni Poloniae surmmaria, t. I-V, Warszawa 1905-1961",
    "NakG":"Księgi grodzkie nakielskie w APP",
    "Nies.":"K. Niesiecki, Herbarz polski powiększony dodatkami z późniejszych autorów, rękopis, dowodów urzędowych i wydany przez Jana Nep. Bobro­wicza, t. I-X, Lipsk 1839-1845",
    "Ochmann":"S. Ochmann, Sejm koronacyjny Jana Kazimierza w 1649 roku, Wrocław 1985",
    "OrłZ":"Księgi ziemskie orłowskie w AGAD",
    "Orzelski":"Świętosława Orzelskiego bezkrólewia ksiąg ośmioro 1572-1576, wyd. E. Kuntze, SRP, t. XXII, Kraków 1917",
    "PANKr.":"Biblioteka PAN w Krakowie",
    "Paw.":"A. Pawiński, Dzieje ziemi kujawskiej oraz akta historyczne do nich należące, t. I-V, Warszawa 1888",
    "Pietrzak":"J. Pietrzak, Po Cecorze i podczas wojny chocimskiej. Sejmy z lat 1620-1621, Wrocław 1983",
    "Pisma":"Pisma do wieku i spraw Jana Sobieskiego, wyd. F. Kluczycki, t. I-II, Kraków 1880-1881",
    "PłockGW":"Księgi grodzkie płockie w AGAD",
    "Portret":"J. Kruszelnicka, Portret na ziemi chełmińskiej, Toruń 1982-1983",
    "PozG":"Księgi grodzkie poznańskie w APP",
    "PrzedGRec":"Księgi grodzkie przedeckie (rekognicje) w AGAD",
    "PrzedZ":"Księgi ziemskie przedeckie w AGAD",
    "PSB":"Polski słownik biograficzny, t. I-XXXI, Kraków 1935-1988",
    "RadzGRel":"Księgi grodzkie radziejowskie (relacje) w AGAD",
    "Radziwiłł":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia 1632-1656, opr. A. Przyboś i R. Żelewski, t. I-IV, Warszawa 1968-1974",
    "RadzZ":"Księgi ziemskie radziejowskie w AGAD",
    "RTH":"Rocznik Polskiego Towarzystwa Heraldycznego we Lwowie",
    "Rozdrażewski":"Korespondencja Hieronima Rozdrażewskiego, wyd. P. Czaplewski, t. I-II, Toruń 1937-1939, Fontes 30-31",
    "SierGInscr":"Księgi grodzkie sieradzkie (inskrypcje) w AGAD",
    "SierGRes":"Księgi grodzkie sieradzkie (rezygnacje) w AGAD",
    "Sig.":"Księgi sigillat w AGAD",
    "Skępe":"Wykaz dobrodziejów, których tu ciała spoczywają tak w grobach kościelnych jako też i na kalwaryi przy kościele - tablica w kościele Bernardynów w Skępem",
    "Sozański":"A. Sozański, Imienne spisy osób duchownych, świeckich i wojskowych, które w pierwszych ośmiu latach panowania króla Stanisława Poniatowskiego od 1764-1772 r., w rządzie lub przy administracji Rzeczypospolitej udział brały, Kraków 1866",
    "SRP":"Scriptores rerum Polonicarum",
    "Starowolski":"S. Starowolski, Monumenta Sarmatarum viam universae carnis ingressorum, Cracoviae 1655",
    "Teki Narusz.":"Teki Naruszewicza w BCzart.",
    "TPaw":"Teki Pawińskiego, t. I n., Warszawa 1897 n.",
    "TorM":"Akta miasta Torunia w APT",
    "U I/2":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy. T. I, z. 2: Urzędnicy wielkopolscy XVI-XVIII wieku, opr. A. Bieniaszewski, Wrocław 1987",
    "Uruski":"S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XXI, Warszawa 1904-1938",
    "VL":"Volumina legum, wyd. J. Ohryzko i Z. Kaczmarczyk, t. I-X, Petersburg 1859 i n.",
    "WielGInscr":"Księgi grodzkie wieluńskie (inskrypcje) w AGAD",
    "ZDiLPł":"Zbiór dokumentów i listów miasta Płocka, t. II (1495-1586), wyd. S. M. Szacherska, Warszawa 1987",
    "ZHist.":"Zapiski Historyczne",
    "Zielińscy":"G. J. Zielińscy, Wiadomości historyczne o rodzie Świnków oraz rodowód pochodzącej od nich rodziny Zielińskich herbu Świnka, cz. II-III, Toruń 1881",
    "Źr.dziej.":"Źródła dziejowe",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. I-XXX, Poznań 1879-1908"
}