""" słownik skrótów literatury """

literatura = {
    "ADS":"Archiwum Diecezjalne w Siedlcach",
    "AG AD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego Bernardyńskiego we Lwowie, 1.1 n„ Lwów 1868 n.",
    "AJZR":"Akty otnosjasćijesja k istorii Jużnoj i Zapadnoj Rossii, 1.1 n., S. Peterburg 1863 n.",
    "AKW":"Archiwum Koronne Warszawskie w AGAD",
    "ALM":"Akty Litovskoj Metriki sobrannyje F. I. Leontovicem, t. I-II, Warszawa 1896-1897",
    "ALRG":"Akty Litovsko-russkogo gosudarstva izd. M. Dovnar Zapolskim, t. I, Moskva 1900",
    "AR":"Archiwum Radziwiłłów w AGAD",
    "Arch. Roskie kores. supl.":"Archiwum Roskie, suplement do korespondencji w AGAD",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "AU":"Akta unii Polski z Litwą 1385-1791, wyd. S. Kutrzeba i W. Semkowicz, Kraków 1932",
    "AWAK":"Akty izdavaemye Vilenskoju Archeograficeskoju Kommissieju, t. I-XXXV, Vilna 1878-1909",
    "AWH":"Archiwum Woronieckich z Huszlewa w Archiwum Państwowym w Lublinie",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BLAN Wil.":"Biblioteka Litewskiej Akademii Nauk w Wilnie",
    "Błeszczyński":"J. Bleszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII w., w: S. Kossakowski,Monografie historyczno-genealogiczne, t. III, Warszawa 1872",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913",
    "BPAN Kr.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego",
    "CBiel.":"Księgi grodzkie bielskie w AGAD",
    "CBran.":"Księgi grodzkie brańskie w AGAD",
    "CBran. 1640-41":"Księga grodzka brańska 1640-41 w Archiwum Państwowym w Białymstoku",
    "CDroh.":"Księgi grodzkie drohickie w AGAD",
    "CDV":"Codex diplomatics ecclesiae catliedralis necnon dioeceseos Vilnensis, 1.1 (1387-1507), wyd. J. Fijałek i W. Semkowicz, Kraków 1932-1948",
    "Chrapowicki":"J. A. Chrapowicki, Diariusz. Część pierwsza: lata 1656-1664, oprać. T. Wasilewski, Warszawa 1978; Część druga: lata 1665-1669, oprac. A. Rachuba i T. Wasilewski, Warszawa 1988",
    "CMieln.":"Księgi grodzkie mielnickie w AGAD",
    "CNak. Rei.":"Księgi grodzkie nakielskie w AGAD",
    "CPrzed. Rei.":"Księgi grodzkie przedeckie w AGAD",
    "CSirl":"Castrensia Siradiensia Inscriptiones w AGAD",
    "CVIA":"Centralne Państwowe Archiwum Historyczne w Wilnie",
    "Czart.":"Biblioteka Czartoryskich w Krakowie",
    "Czubek":"J. Czubek, Katalog rękopisów Akademii Umiejętności w Krakowie, Dodatek I, Kraków 1912",
    "Dworzaczek":"W. Dworzaczek, Genealogia, tablice, Warszawa 1959",
    "Dzięgielewski, Izba":"J. Dzięgielewski, Izba poselska w systemie władzy Rzeczypospolitej w czasach Władysława IV, Warszawa 1992",
    "Elektorowie":"Elektorowie królów Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, wyd. J. Dunin-Borkowski i M. Dunin-Wąsowicz, RTH I, 1908-1909",
    "Elektorów poczet":"Elektorów poczet, wyd. O. Pietruski, Lwów 1845",
    "Glinka, Ród":"J. Glinka, Ród Klausucia w wiekach XIII-XVI, „Studia Źródioznawcze”, 5, 1960",
    "Gloger":"Archiwum i zbiory Zygmunta Glogera w Archiwum Państwowym w Krakowie",
    "G. Rz.":"„Gazeta Rządowa”",
    "Grzybowski":"Materiały do dziejów ziemi płockiej. Z archiwaliów diecezjalnych płockich XVIII w., t. III, przyg. M. M. Grzybowski, Płock 1984",
    "Halecki":"O. Halecki, Przyłączenie Podlasia, Wołynia i Kijowszczyzny do Korony wr. 1569, Kraków 1915",
    "Inventarium":"Inventarium omnium et singulorum privilegiorum..., wyd. E. Rykaczewski, Paryż 1862",
    "lura Masov.":"lura Masoviae terrestria, opr. J. Sawicki, 1.1, Warszawa 1972",
    "Kalendarz":"Kalendarz polityczny dla Królestwa Polskiego i Wielkiego Księstwa Litewskiego..., Warszawa 1972",
    "Kam.":"Archiwum Kameralne Metryki Koronnej w AGAD",
    "Kapie.":"Kapicjana w AGAD",
    "Kapica":"1. Kapica Milewski, Herbarz, Kraków 1870",
    "Kat. dok. Oss.":"Katalog dokumentów Zakładu Narodowego im. Ossolińskich, t. II, wyd. A. Fastnacht, Wroclaw 1969",
    "KDKW":"Kodeks dyplomatyczny katedry i diecezji wileńskiej, wyd. J. Fijalek i W. Semkowicz, 1.1, Kraków 1948",
    "Kersten, Radziejowski":"A. Kersten, Hieronim Radziejowski. Studium władzy i opozycji, Warszawa 1988",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "Korytkowski":"J. Korytkowski, Prałaci i kanonicy katedry metropolitalnej gnieźnieńskiej..., 1.1, Gniezno 1883",
    "Kras.":"F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji lir. Krasińskich, w: Biblioteka Ordynacji Krasińskich i Muzeum Konstantego Swidzińskiego, t. XXIII-XXIX, Warszawa 1915",
    "Królik":"L. Królik, Organizacja diecezji łuckiej i brzeskiej od XVI-XVIII w., Lublin 1983",
    "Ks. ref.":"Księgi sądu referendarskiego w AGAD",
    "Ks. ref. Sum.":"Księgi Referendarii Korotmej z czasów saskich, opr. M. Woźniakowa, t. I-II, Warszawa 1969-1970",
    "Kubala, Wojny duńskie":"L. Kubala, Wojny duńskie i pokój oliwski 1657-1660, w tegoż Szkice historyczne, seria VI, Lwów 1922",
    "Kurczewski":"J. Kurczewski, Biskupstwo wileńskie, Wilno 1912",
    "Listy":"Listy oryginalne Zygmunta Augusta do Mikołaja Radziwiłła Czarnego wojewody wileńskiego, wyd. S. Lachowicz, Wilno 1842",
    "Ljubavskij":"M. Ljubavskij, Litovsko-russkij sejm, Moskva 1900",
    "LM":"Lietuvos Metrika (1427-1506), Knyga nr 5, par. A. Banionis, Vilnius 1993",
    "Łappo II":"I. I. Łappo, Velikoje kniazestvo Litovskoje vo vtoroj polovinie XVI stoletja, t. II: Litovsko-russkij povet i jego sejmik, Jurjev 1911",
    "Maleczyński":"K. Maleczyński, Urzędnicy grodzcy i ziemscy lwowscy w latach 1352-1783, Lwów 1938",
    "Mat. Dworz.":"Materiały Włodzimierza Dworzaczka w Bibliotece Kórnickiej PAN",
    "Mat. Wiśniewskiego":"Materiały prof. Jerzego Wiśniewskiego (kartoteka urzędników podlaskich) w posiadaniu p. Krystyny Wiśniewskiej w Krakowie",
    "Matuszewicz":"M. Matuszewicz, Diariusz życia mego, t. I-II, oprać. B. Królikowski, Warszawa 1986",
    "MI I":"„Miesięcznik Heraldyczny”",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka Litewska (kopie) w AGAD",
    "ML Sig.":"Metryka Litewska. Księga Sigillat, opr. A. Rachuba, Warszawa 1987",
    "MRPS":"Matricularum Regni Poloniae summaria, cz. I-V, wyd. T. Wierzbowski i in., Warszawa 1905-1961",
    "Najdawniejsze":"Najdawniejsze księgi sądowe mazowieckie, t. III, wyd. K. Tymieniecki, Warszawa 1920",
    "NakGRel.":"Księgi grodzkie nakielskie w Archiwum Państwowym w Poznaniu",
    "NAM":"Nacyianalny Archiu Belarusi w Mińsku: F. 1706 (Bielskie grodzkie), F. 1708 (Brańskie grodzkie),F. 1712 (Goniądzkie grodzkie), F. 1715 (Drohickie grodzkie), F. 1726 (Mielnickie grodzkie), F. 1744 (Bielskie ziemskie), F. 1759 (Drohickie ziemskie), F. 1867 (Bielska sądów kapturowych)",
    "Nieś.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-X, Lipsk 1839-1846",
    "Ochmann, Sejm koronacyjny":"S. Ochmann, Sejm koronacyjny Jana Kazimierza w 1649 r., Warszawa 1985",
    "Ochmann, sejmy 1661-62":"S. Ochmann, Sejmy lat 1661-1662. Przegrana batalia o reformę ustroju Rzeczypospolitej, Wroclaw 1977",
    "Ossol.":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "Ossol. Lw.":"Biblioteka Akademii Nauk Ukrainy we Lwowie (fotokopie ksiąg Sigillat w AGAD)",
    "Ossoliński, Pamiętnik":"Z. Ossoliński, Pamiętnik, opr. J. Długosz, Warszawa 1983",
    "Ostatnie lata":"O. Halecki, Ostatnie lata Świdrygiełły i sprawa wołyńska za Kazimierza Jagiellończyka, Kraków 1915",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, Kraków 1858",
    "Pociecha":"W. Pociecha, Królowa Bona (1494-1557). Czasy i ludzie Odrodzenia, t. III, Poznań 1958",
    "Poczet":"A. Boniecki, Poczet rodów w Wielkim Księstwie Litewskim w XV i XVI wieku, Warszawa 1887",
    "PSB":"Polski słownik biograficzny, 1 . 1 n., Kraków 1935 n.",
    "Pułaski":"Kronika polskich rodów szlacheckich Podola, Wołynia i Ukrainy. Monografia i wzmianki, t. I-II, Brody 1914",
    "Rachunki":"Archiwum Skarbu Koronnego, Oddział 1. Rachunki królewskie w AGAD",
    "Radziwiłł, Autobiografia":"B. Radziwiłł, Autobiografia, opr. T. Wasilewski, Warszawa 1979",
    "Radziwiłł, Memoriale":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia 1632-1656, opr. A. Przyboś i R. Żelewski, t. I-V, Wrocław 1968-1975",
    "Regesty":"E. Suchodolska, Regesty dokumentów mazowieckich z lat 1248-1345, Warszawa 1980",
    "RIB":"Russkaja lstorićeskaja Biblioteka, t. XX, Petersburg 1903; t. XXXIII, Petrograd 1915",
    "RTH":"„Rocznik (Polskiego) Towarzystwa Heraldycznego”",
    "Sap.":"Fond Sapiehów w Bibliotece Akademii Nauk Ukrainy we Lwowie",
    "Sbomik":"Sbornik matieriałow otnosjasćichsja k istorii panov rady Vielikago Knjaiestva Litovskago, wyd. M. Malinowskij, Tomsk 1901",
    "Seredyka, Parlamentarzyści":"J. Seredyka, Parlamentarzyści drugiej połowy panowania Zygmunta III Wazy, Opole 1989",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "Skarbiec":"T. Daniłowicz, Skarbiecdiplomatów..., t. I-II, Wilno 1860-1862",
    "SRP":"Scriptores rerum Polonicarum, t. I-XXII, Kraków 1872 i n.",
    "Starzeński, Na schyłku dni":"[M. Starzeński], Na schyłku dni Rzeczypospolitej. Kartki z pamiętnika..., 1757-1795, Warszawa 1914",
    "Sum.":"Sumariusz Metryki Litewskiej w Archiwum Publicznym Potockich w AGAD",
    "TBiel.":"Księgi ziemskie bielskie w AGAD",
    "TDroh.":"Księgi ziemskie drohickie w AGAD",
    "Teki Pawińskiego":"Teki Adolfa Pawińskiego w BPAN Kr.",
    "TG":"Teki Glinki w Ośrodku Dokumentacji Zabytków w Warszawie",
    "TSur.":"Księgi ziemskie suras kie w AGAD",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, 1.1 n., Wrocław-Kómik 1985 n.",
    "Vitoldiana":"Vitoldiana. Codex privilegiorum Vitoldi magni ducis Lithuaniae 1386-1430, wyd. J. Ochmański, Warszawa 1986",
    "VL":"Volumina legum, t. I-X, Warszawa 1732 i n.",
    "Wielądko":"W. Wielądko, Heraldyka, czyli opisanie herbów..., t. I-V, Warszawa 1792-1798",
    "Wierzbowski, Materiały":"Materiały do dziejów piśmiennictwa polskiego i biografii pisarzów polskich, wyd. T. Wierzbowski, 1.1, Warszawa 1900",
    "Wimmer, Wiedeń":"J. Wimmer, Wiedeń 1683, Warszawa 1983",
    "Włodarski, Ród Jaruzelskich":"A. Włodarski, Ród Jaruzelskich h. Ślepowron, Warszawa 1927",
    "Włodarski, Ród Krasnodębskich":"A. Włodarski, Ród Krasnodębskich h. Krzywda, Warszawa 1926",
    "Wolff, Senatorowie":"J. Wolff, Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "Zamek":"Biblioteka Zamku Królewskiego w Warszawie",
    "Zbiór":"Zbiór praw litewskich, wyd. A. T. Działyński, Poznań 1841",
    "Zielińska":"T. Zielińska, Rody urzędami zaszczycone. Próba sondażu, w: Społeczeństwo staropolskie, t. II, Warszawa 1979, s. 193-227",
    "Z. Dz.":"Źródła dziejowe, t. XVII, cz. 1-3, Polska XVI wieku pod względem geograficznym i statystycznym, T. VI, Podlasie (województwo), wyd. A. Jabłonowski, Warszawa 1908-1910",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, 1.1 n. Poznań 1879 n."
}