""" słownik skrótów literatury """

literatura = {
    "ABern. Kr.":"Archiwum Bernardynów w Krakowie",
    "AD":"Archiwum miasta Drohobycza. Zbiór przywilejów, wyd. F. Gątkiewicz, Drohobycz 1906",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGB":"Archiwum Greckokatolickiego biskupstwa przemyskiego w WAPrz. (inf. pochodzą od dra Jerzego Motylewicza z Przemyśla)",
    "AGP":"Akta grodzkie przemyskie w CPAH (inf. pochodzą od dra Zdzisława Budzyńskiego z Przemyśla)",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tzw. bernardyńskiego we Lwowie, t. I-XXV, Lwów 1868-1935 ",
    "AJZR":"Archiw jugo-zapadnoj Rossii izdawajemyj Kommissiju dla razbora driewnich aktow, cz. 1-8, Kiew 1859-1911",
    "AKH":"'Archiwum Komisji Historycznej Akademii Umiejętności' t. III, Kraków 1886 (S. Kwiatkowski, Wykaz dostojników duchownych i świeckich. 1434-1444, s. 61-118); t. VIII, Kraków 1898 (K. Fedorowicz, Dostojnicy i urzędnicy świeccy województwa krakowskiego w latach 1374 do 1506, w dodatku: Dostojnicy i urzędnicy innych ziem polskich, s. 1-290)",
    "Akta Aleksandra":"Akta Aleksandra króla polskiego, wielkiego księcia litewskiego itd. (1501-1506), wyd. F. Papee, Kraków 1927",
    "Akta unii":"Akta unii Polski z Litwą 1385- 1791, wyd. S. Kutrzeba i W. Semkowicz, Kraków 1932",
    "APKr.":"Archiwum Państwowe Miasta Krakowa i Województwa Krakowskiego w Krakowie",
    "APPInow.":"Archiwum Państwowe w Poznaniu. Księgi grodzkie inowrocławskie",
    "AS":"Archiwum książąt Lubartowiczów Sanguszków w Slawucie, wyd. Z. L. Radzimiński, P. Skobielski, B. Gorczak, t. II, V, Lwów 1888, 1897",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "ASwoj. kr.":"Akta sejmikowe województwa krakowskiego, wyd. S. Kutrzeba, A. Przyboś, t. I-V, Kraków 1932-1984",
    "AZP":"Akta ziemskie przemyskie w CPAH (inf. pochodzą od dra Zdzisława Budzyńskiego z Przemyśla)",
    "Białkowski":"L. Białkowski, Urzędnicy ziemscy podolscy wieku XVI i początku XVII, RTH, t. VIII, Lwów 1926-1927, s. 174-180",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "Błeszczyński":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII wieku, [w:] S. K. Kossakowski, Monografie historyczno-genealogiczne, t. III, Warszawa 1872",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913 ",
    "Borzemski":"A. Borzemski, Archiwa w Sanoku, Jaśliskach, Króliku Wołoskim, Hłomczy, Łodzinie i Klimkówce, Sanok 1906",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu ",
    "CB":"Castrensia Biecensia w APKr.",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CChR":"Castrensia Chelmensia Relationes w WAPL ",
    "CCI":"Castrensia Cracoviensia Inscriptiones w APKr. ",
    "CCP":"Castrensia Cracoviensia Plenipotentiae w APKr. ",
    "CCR":"Castrensia Cracoviensia Relationes w APKr. CCrasnR-Castrensia Crasnostaviensia Relationes w WAPL",
    "CDBOW":"A. Fastnacht, Catalogus diplomatum Bibliotecae Instituti Ossoliniani, Supplementum I, 1279-1506, Wrocław 1951",
    "CIP":"Corpus iuris Polonici, wyd. O. Balzer, t. III-IV, Kraków 1906-1910",
    "CPAH":"Centralne Państwowe Archiwum Historyczne USRR we Lwowie ",
    "CSR":"Castrensia Sandecensia Relationes w APKr.",
    "Czart.":"Biblioteka Czartoryskich w Krakowie",
    "DąbKP":"P. Dąbkowski, Księgi sądowe przemyskie i przeworskie w dawnej Polsce, 'Roczniki Towarzystwa Przyjaciół Nauk w Przemyślu', R. VIII, Przemyśl 1928-1937",
    "DąbKT":"P. Dąbkowski, Palestra i księgi sądowe trembowelskie za czasów polskich, [w:] Przegląd prawa i administracji, Lwów 1919",
    "DąbKŻ":"P. Dąbkowski, Z przeszłości ksiąg grodzkich i ziemskich żydaczowskich, [w:] Księga pamiątkowa ku czci Bolesława Orzechowicza,. Lwów 1916",
    "DąbPS":"P. Dąbkowski, Palestra i księgi sądowe sanockie w dawnej Polsce, 'Pamiętnik Historyczno-Prawny', t. I, z. 6, Lwów 1925",
    "Długosz":"Joannis Dlugossii seu Longini canonici Cracoviensis Historiae Polonicae libri XII, wyd. I [Ż] Pauli, t. II-IV, Kraków 1873-1877 ",
    "DSZK":"Dokumenty sądu ziemskiego krakowskiego 1302-1453, wyd. Z. Perzanowski, Wrocław 1971",
    "Dunikowski":"J. Dunikowski, Rodowód rodziny z Urska Dunikowskich, Lwów 1900",
    "Dworzaczek":"W. Dworzaczek, Leliwici Tarnowscy, Warszawa 1971 ",
    "DworzGen.":"W. Dworzaczek, Genealogia, Warszawa 1959",
    "Dziwik":"K. Dziwik, Katalog dokumentów Biblioteki PAN w Krakowie, t. I-III, Wrocław 1966-1970",
    "Ehrlich":"L. Ehrlich, Starostwa w Halickiem w stosunku do starostwa lwowskiego w wiekach średnich, 1390-1501, 'Studia nad Historią Prawa Polskiego', t. VI, z. 1, Lwów 1914",
    "El.":"Elektorowie Władysława IV Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, wyd. J. Dunin-Wąsowicz i M. Dunin-Wąsowicz, RTH, t. I, Lwów 1910",
    "Epist.":"Codex epistolaris saeculi decimi quinti, wyd. A. Sokołowski, J. Szujski, A. Lewicki, t. I-III, Kraków 1876-1894",
    "Fijałek":"J. Fijałek, Tarłowie, znamienitego rodu początki i świetność, 'Przegląd Historyczny', t. VIII, 1909, s. 63-88, 167-197, 284-312; t. X, 1910, s. 34-65, 168-205, 310-350",
    "Gerczak":"B. Gerczak, Katalog rękopisów archiwum XX. Sanguszków w Sławucie, Sławuta 1902",
    "Gilewicz":"A. Gilewicz, Stanowisko i działalność gospodarcza W1adyslawa Opolczyka na Rusi w latach 1372-1378, [w:] Prace historyczne wydane ku uczczeniu 50-lecia Akademickiego Koła Historyków Uniwersytetu Jana Kazimierza we Lwowie, Lwów 1929, s. 71-105",
    "Górski":"K. Górski, Ród Odrowążów w wiekach średnich, RTH, t. VIII, 1926- 1927, s. 1-106",
    "IRBOW":"Inwentarz rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich we Wrocławiu, opr. pod red. J. Turskiej, t. I-II, Indeks, Wrocław 1948-1962",
    "Kam.":"Kameralia w AGAD",
    "Kaniewska":"I. Kaniewska, Małopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa-Kraków 1974 ",
    "Katalog":"Katalog rękopisów Biblioteki Narodowej. Zbiory Morstinów, Radziwiłłów, Potockich, opr. pod red. K. Muszyńskiej, t. VII, Warszawa 1969",
    "KatCzart.":"W. Szelińska, J. Tomaszewicz, Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, cz. I (1148-1506), Kraków 1975",
    "KCz.":"Kolekcja Czołowskiego w Lwowskiej Naukowej Bibliotece Akademii Nauk USRR (dawne Ossolineum) (inf. pochodzą od dra Zdzisława Budzyńskiego z Przemyśla)",
    "KDBOW":"Katalog dokumentów Biblioteki Zakładu Narodowego im. Ossolińskich, opr. A. Fastnacht, t. I-II, Wrocław 1953-1969 ",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej, wyd. F. Piekosiński, t. I, Kraków 1879",
    "KDM":"Kodeks dyplomatyczny Małopolski, wyd. F. Piekosiński, t. I-IV, Kraków 1876-1905; t. V -materiały w Pracowni Słownika Historyczno-Geograficznego PAN w Krakowie",
    "KDP":"Kodeks dyplomatyczny Polski, wyd. L. Rzyszczewski i inni, t. I-IV, Warszawa 1847-1887",
    "Kętrzyński":"W. Kętrzyński, Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich, t. I-III, Lwów 1880-1898",
    "KGP":"Księgi grodzkie przemyskie w CPAH (inf. pochodzą od dra Józefa Motylewicza z Przemyśla)",
    "KGS":"Księgi grodzkie sanockie w CPAH (inf. pochodzą od dra Józefa Motvlewicza z Przemyśla)",
    "KK":"Księgi kanclerskie MK w AGAD",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa, wyd. F. Piekosiński, t. I-IV, Kraków 1879-1882",
    "Knigi":"Knigi polskoj koronnej mietriki XV stoletija, t. I, Warszawa 1914",
    "Korzeniowski":"Catalogus codicum manu scriptorum Musei Principum Czartoryski Cracoviensis, opr. J. Korzeniowski, S. Kutrzeba, K. Piotrowicz, t. I-II, Indeks, Kraków-Cieszyn 1887-1931",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-genealogiczne t. I-III, Warszawa 1859-1872",
    "KP":"Księgi podskarbińskie z czasów Stefana Batorego I576-1586, wyd. A. Pawiński, Źródła dziejowe, t. IX, Warszawa 1881",
    "KR":"Księgi referendarskie, wyd. J. T. Baranowski, t. I (158?-1602), Warszawa 1910",
    "KRK":"Księgi Referendarii Koronnej z czasów saskich, opr. M. Woźniakowa, t. I-II, Warszawa 1969-1970",
    "KRSBK":"Katalog rękopisów staropolskich Biblioteki Kórnickiej XVI-XVIII w., opr. R. Marciniak, M. Muszyński, J. Wiesiołowski, t. I-II, Wrocław 1971-1985",
    "KZab.":"Katalog zabytków sztuki w Polsce. t. XIII, z. 2, Seria Nowa: t. I, z. 1 -2, t. III, z. 1",
    "Lrus. 1661":"Lustracja województwa ruskiego 1661-1665, wyd. K. Arłamowski, W. Kaput, E. Arłamowska, t. I-III, Wrocław 1970-1976 ",
    "Łaszczyńska":"O. Łaszczyńska, Ród Herburtów w wiekach średnich, 'Poznańskie Towarzystwo Przyjaciół Nauk, Prace Komisji Historycznej', t. XIV, z. 4, Poznań 1948",
    "Łoziński":"W. Łoziński, Prawem i lewem, t. I-II, Kraków 1957 ",
    "MalUGZL":"K. Maleczyński, Urzędnicy grodzcy i ziemscy lwowscy w latach 1352-1783, Lwów 1938",
    "MalUT":"K. Maleczyński, Urzędnicy grodzcy trembowelscy 1403-1783, 'Ziemia Czerwieńska', R. II, z. 1, Lwów 1936, s. 302-317",
    "MAML":"Materiały archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 r., wyd. A. Prochaska, Lwów 1890",
    "Materiały":"Materiały do historii miasta Sambora I390-1795, wyd. A. Dörflerówna, Lwów 1936",
    "Michałowski":"J. Michałowski, Księga pamiętnicza, Kraków 1864 ",
    "MK":"Metryka Koronna w AGAD",
    "MRPS":"Matricularum Regni Poloniae summaria, wyd. T. Wierzbowski i inni, t. I-V, Warszawa 1905-1961",
    "Nies.":"K. Niesiecki, Herbarz polski, t. I-X, Lipsk 1839-1846",
    "Opis":"Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, opr. F. Pułaski, Warszawa 1915",
    "Opysy":"Opysy koroliwszczyn w zemlach rus'kych XVI wiku, wyd. M. Hruszews'ki, t. I-IV, Lwów I895-1903, [w:] Żereła do istorii Ukrainy-Rusy, t. I-III, VII",
    "PAN Kr.":"Biblioteka Polskiej Akademii Nauk w Krakowie ",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, Kraków 1858 ",
    "PESz.":"Polska encyklopedia szlachecka, t. I-XII, Warszawa 1935-1938 ",
    "Pisma":"Pisma do wieku i spraw Jana Sobieskiego, wyd. F. Kluczycki, t. I-II, Kraków 1880-1881",
    "Poczet":"Elektorów poczet, wyd. O. Pietruski, Lwów 1845",
    "Pohorecki":"F. Pohorecki, Catalogus diplomatum Bibliothecae Instituti Ossoliniani nec non Bibliothecae Pawlikowianae 1227-1505, Lwów 1937",
    "PSB":"Polski słownik biograficzny, t. I-XXVIII, Kraków 1935-1985 ",
    "Rach. król.":"Rachunki królewskie z lat 1471-1472 i 1476-1478, opr. S. Gawęda, Z. Perzanowski, A. Strzelecka, Wrocław-Kraków 1960 ",
    "Radziwiłł":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia, opr. A. Przyboś i R. Żelewski, t. I-V, Wrocław 1968-1975",
    "Regestr":"Regestr złoczyńców grodu sanockiego 1554-1638, wyd. O. Balzer, [w:] Materiały historyczne, t. I, Lwów 1891",
    "Rolny":"Acta officii consistorialis Leopoliensis antiquissima, t. I-II, wyd. W. Rolny, Lwów 1927-1930",
    "RTAV":"Regestra thelonei aquatici Vladislaviensis saeculi XVI, wyd. S. Kutrzeba i F. Duda, Kraków 1915",
    "RTH ":"'Rocznik Towarzystwa Heraldycznego we Lwowie'",
    "Sig.":"Sigillata w AGAD",
    "Smołka":"J. Smołka, Katalog archiwum aktów dawnych miasta Przemyśla, Przemyśl 1927",
    "Sochaniewicz":"K. Sochaniewicz, A. Wolff, Urzędnicy województwa bełskiego do połowy XVI w., 'Miesięcznik Heraldyczny', t. X, 1931 ",
    "Sozański":"A. Sozański, Imienne spisy osób duchownych, świeckich i wojskowych, które w pierwszych ośmiu latach panowania króla Stanisława Poniatowskiego od 1764-1772 r. w rządzie lub przy administracji Rzeczypospolitej udział brały, Kraków 1866",
    "SPPP":"Starodawne prawa polskiego pomniki, wyd. A. Z. Helcel i inni, t. II, VII, VIII, Kraków 1870-1884",
    "SRP":"Scriptores rerum Polonicarum, t. XIV, Kraków 1899",
    "Sucheni-Grabowska":"A. Sucheni-Grabowska, Monarchia dwu ostatnich Jagiellonów a ruch egzekucyjny, t. I, Wrocław 1974",
    "SŹ":"Z. Spieralski, Z dziejów Archiwum Koronnego Krakowskiego, Kopiariusz Jana Łaskiego (około 1505), 'Studia Źródłoznawcze' R, XXIV, 1979, Aneks",
    "TC":"Terrestria Cracoviensia w APKr. ",
    "TP":"Teki Pawińskiego w PAN Kr.",
    "TPaw.":"Teki Pawińskiego, t. 1: Liber quitantiarum Alexandri regis ab a. 1502 ad 1506, Warszawa 1897; t. II: Liber quitantiarum regis Casimiri, Warszawa 1897",
    "TU":"Teki Ulanowskiego w PAN Kr.",
    "Uruski":"S. Uruski, Rodzina, t. I-XV, Warszawa 1904-1931",
    "VL":"Volumina legum, wyd. J. Ohryzko i Z. Kaczmarczyk, t. I-X, Petersburg 1859-Poznań 1952",
    "VMPL":"Vetera monumenta Poloniae et Lithuaniae, wyd. A. Theiner. t. I, Rzym 1860",
    "WAPL":"Wojewódzkie Archiwum Państwowe w Lublinie ",
    "WAPrz.":"Wojewódzkie Archiwum Państwowe w Przemyślu",
    "Wielądko":"W. Wielądko, Heraldyka, t. I-V, Warszawa 1792-1798 ",
    "ZDKDK":"Zbiór dokumentów katedry i diecezji krakowskiej, 1476-1450, wyd. S. Kuraś, cz. II, Lublin 1973",
    "ZDM":"Zbiór dokumentów małopolskich, wyd. S. Kuraś i I. Sułkowska-Kuraś, t. I-VIII, Wrocław 1963-1976",
    "ŹD":"Źródła dziejom, t. XVIII, Polska XVI wieku pod względem geograficzno-statystycznym, t. VII, Ziemie ruskie, Ruś Czerwona, opisana przez A. Jabłonowskiego, Warszawa 1902",
    "Żychliński":"T. Żychliński, Złota księga szlachty polskiej, t. I-XXX, Poznań 1879- 1908"
}