""" słownik skrótów literatury """

literatura = {
    "AA":"Acta Actorum w Archiwum Kapituły Krakowskiej",
    "Acta Tom.":"Acta Tomiciana..., t. I-XVI, Poznań-Wrocław-Kraków 1852-1960",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej polskiej z archiwum tak zwanego Bernardyńskiego we Lwowie. . ., wyd. O. Pietruski, L. Tatomir, X. Liske, A. Prochaska, W. Hejnosz, t. 1-25, Lwów 1868-1935",
    "AJG":"Archiwum Jasnogórskie klasztoru OO. Paulinów w Częstochowie",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "Akta podkanclerskie II":"Akta podkanclerskie Franciszka Krasińskiego 1569-1572, cz. II, wyd. W. Krasiński, Warszawa 1870",
    "APKr.":"Archiwum Państwowe Miasta Krakowa i Województwa Krakowskiego w Krakowie",
    "Arch. Bernardynów":"Archiwum Prowincji OO. Bernardynów w Krakowie",
    "Arch. Dembińskich":"Archiwum Dembińskich z Przysuchy w APKr.",
    "Arch. Dominikanów":"Archiwum Prowincji OO. Dominikanów w Krakowie",
    "Arch. dz. lit.":"Archiwum do dziejów literatury i oświaty w Polsce, t. 1-19, Kraków 1878-1937",
    "Arch. Franciszkanów":"Archiwum klasztoru OO. Franciszkanów w Krakowie",
    "Arch. Kapucynów":"Archiwum klasztoru OO. Kapucynów w Krakowie",
    "Arch. Karmelitów":"Archiwum Prowincji OO. Karmelitów Bosych w Czernej",
    "Arch. Lanckorońskich":"Archiwum Lanckorońskich w APKr. ",
    "Arch. Norbertanek":"Archiwum klasztoru PP. Norbertanek na Zwierzyńcu w Krakowie",
    "Arch. par. NMP":"Archiwum parafii Najświętszej Marii Panny w Krakowie",
    "Arch. par. WW":"Archiwum parafii Wszystkich Świętych w Krakowie",
    "Arch. Podhoreckie":"Archiwum Podhoreckie Rzewuskich w APKr.",
    "Arch. Radziwiłłów":"Archiwum Radziwiłów w AGAD",
    "Arch. Reformatów, Kronika":"Archiwurn klasztoru OO. Reformatów w Krakowie, tzw. Archivum Antiquum, bez paginacji",
    "ArchSang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, wyd. Z. L. Radzimiński, P. Skobielski, B. Gorczak, t. II, V, Lwów 1888, 1897",
    "Arch. Sanguszków":"Archiwum Sanguszków w APKr.",
    "Arch. UJ":"Archiwum Uniwersytetu Jagiellońskiego w Krakowie",
    "Arch. Walewskich":"Archiwum Walewskich w Archiwum Państwowym w Łodzi",
    "Arch. Załuskich":"Archiwum Siedliszowickie Załuskich w APKr. ",
    "Arch. Zam.":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, wyd. W. Sobieski, J. Siemieński, K. Lepszy, t. II, Warszawa 1909",
    "ASejmKr.":"Akta sejmikawe województwa krakowskiego, wyd. S. Kutrzeba i A. Przyboś, t. IV, Kraków-Wrocław-Warszawa 1932-1984",
    "BartTabl.":"Tablice historyczne Juliana Bartoszewicza, Bibl. Warsz. 1861, 1863, 1865, 1880",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwum Czartoryskich",
    "Bibl. Krak.":"Biblioteka Krakowska ",
    "Bibl. Warsz.":"Biblioteka Warszawska",
    "Bielski":"Joachima Bielskiego dalszy ciąg Kroniki, Warszawa 1851",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "Błeszczyński":"Spis senatarów i dygnitarzy koronnych świeckich z XVIII wieku, ułożył J. Błeszczyński, w: Monografie historyczno-genealogiczne niektórych rodzin polskich przez Stanisława Kazimierza Kossakowskiego, t. III, Warszawa 1872",
    "BNar.":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. 1-17, Warszawa 1899-1913",
    "Bostel":"F. Bostel, Sądownictwo ziemskie oświęcimskie i zatorskie od r. 1440-1565, w: Przewodnik Naukowy i Literacki, 1888",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "Budka":"W. Budka, Pieczęcie grodu krakowskiego z wieku XVI-XVIII, w: Studia historyczne ku czci Stanisława Kutrzeby, t. II, Kraków 1938",
    "CB":"Castrensia Biecensia w APKr. ",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CCI":"Castrensia Cracoviensia Inscriptiones w APKr. ",
    "CCR":"Castrensia Cracoviensia Relationes w APKr.",
    "Cercha":"Pomniki Krakowa Maksymiliana i Stanisława Cerchów z tekstem Feliksa Kopery, t. 1-3, Kraków 1904",
    "Chłapowski":"K. Chłapowski, Starostowie w Małopolsce 1565-1668, w: Społeczeństwo staropolskie pod red. A. Wyczańskiego, t. IV, Warszawa 1986",
    "Chmiel":"Wawel II, Materiały archiwalne do budowy zamku, wyd. A. Chmiel, Teka grona konserwatorów Galicji Zachodniej, t. V, Kraków 1913",
    "Chrapowicki":"J. J. Chrapowicki, Diariusz, cz. I lata 1656-1664, oprac. T. Wasilewski, Warszawa 1978",
    "Chudzińska":"Materiały do Corpus Inscriptionum Poloniae (Franciszkanie i Reformaci) zebrała Barbara Chudzińska (maszynopis w Zakładzie Nauk Pomocniczych Uniwersytetu Jagiellońskiego w Krakowie)",
    "CIP":"Corpus iuris Polonici, wyd. O. Balzer, t. III, Cracoviae 1906",
    "CO":"Castrensia Osviencimensia w APKr.",
    "Cod. dipl. Vielic.":"Codex diplomaticus Vielicensis, Lwów 1872 ",
    "CS":"Castrensia Sandecensia w APKr.",
    "Czemeryński":"O dobrach koronnych byłej Rzeczypospolitej polskiej wedle źródeł wiarogodnych., skreślił Kornel Czemeryński, Lwów 1870",
    "Dod. Gaz. Lw.":"Dodatek Tygodniowy do Gazety Lwowskiej, Lwów 1852 i nast.",
    "Dunin-Borkowski":"J. S. h. Dunin Borkowski, Genealogia żyjących utytułowanych rodzin polskich, Lwów 1895",
    "DwGen.":"W. Dworzaczek, Genealogia. Tablice, Warszawa 1959 ",
    "DwTarn. I-II":"W. Dworzaczek, Leliwici Tarnowscy, Warszawa 1971; W. Dworzaczek, Hetman Jan Tarnowski, Warszawa 1985",
    "Dzieje Krakowa":"J. Bieniarzówna, J. Małecki, Dzieje Krakowa, t. 2, Kraków w wiekach XVI-XVIII, Kraków 1984",
    "Elementa":"Elementa ad fontium editiones I-LXX, Romae 1960-1987",
    "Estreicher":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografia polska, stulecie XV-XVIII, t. 8-9, 12-34, Kraków 1882-1951",
    "Fastnacht":"A. Fastnacht, Katalog dokumentów Biblioteki Zakładu Narodowego im. Ossolińskich, cz. I, dokumenty z lat 1507-1700, Wrocław 1953",
    "Hartleb":"K. Hartleb, Jan z Ocieszyna Ocieski, jego działalność polityczna i diariusz podróży do Rzymu, Lwów 1917 ",
    "Hoszowski":"K. Hoszowski, O znakomitych zasługach w kraju rodziny Korycińskich, Kraków 1862 ",
    "IT":"Inwentarz tymczasowy w APKr.",
    "Jabłonowski":"Jabłonowski Jan Stanisław kasztelan krakowski, Dziennik 1694-1695, wyd. W. Chomętowski, Warszawa 1865 ",
    "Jerlicz":"Latopisiec albo kroniczka Joachima Jerlicza, z rękopisu wydał K. Wł. Wójcicki, t. II, Warszawa 1853",
    "Kaczmarczyk":"K. Kaczmarczyk, Katalog dyplomów pergaminowych OO. Dominikanów w Krakowie (1227-1894) w APKr., Fragmenty 180",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD ",
    "Kaniewska":"I. Kaniewska, Małopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa-Kraków 1974",
    "Kętrzyński":"Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich, wyd. W. Kętrzyński, t. I-III, Lwów 1881 -1898",
    "Kierst":"W. Kierst, Wielkorządy krakowskie w XIV-XVI st., w: Przegląd Historyczny 10, 1910",
    "Kieszkowski":"J. Kieszkowski, Kanclerz Krzysztof Szydłowiecki, t. I-III, Poznań 1912",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD ",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa 1257-1506, wyd. F. Piekosiński, cz. 1, 2-4, Kraków 1879-1882",
    "Kluczycki":"Pisma do wieku i spraw Jana Sobieskiego zebrał i wydał F. Kluczycki, t. I, 1629-1670, t. II, 1672-1674, Kraków 1880-1881",
    "Komoniecki":"Chronologia albo dziejopis żywiecki... Andrzeja Komonieckiego, wyd. S. Grodziski i I. Dwornicka, Żywiec 1987",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-genealogiczne, t. I-III, Warszawa 1859-1872",
    "Krasicka":"J. Krasicka, Kraków i ziemia krakowska wobec konfederacji barskiej, Bibl. Krak. 68, Kraków 1929",
    "Kraszewski":"K. Kraszewski, Raptularzyk rodziny Korycińskich od 1541 do 1649 r., w: Bibl. Warsz. 1886, t. III, s. 230-242 ",
    "KutrzKat.":"S. Kutrzeba, Katalog krajowego archiwum aktów grodzkich i ziemskich w Krakowie, w: Teka grona konserwatorów Galicji Zachodniej, t. III, Kraków 1909.",
    "KutrzPrawa":"S. Kutrzeba, Prawa, przywileje, statuty i lauda księstw oświęcimskiego i zatorskiego, w: AKPr. IX, Kraków 1913",
    "KutrzStud.":"S. Kutrzeba, Studia do historii sądownictwa w Polsce, Seria I, Lwów 1901, Seria II, Lwów 1903, odbitka z Przeglądu prawa i administracji, R. 26, 27, 28",
    "KZab. Seria Nowa":"Katalog zabytków sztuki w Polsce",
    "LMMC":"Liber mortuorum monasterii Coronoviensis ordinis Cisterciensis, wyd. A. Mańkowski, Toruń 1931, Fontes 25 ",
    "Lustr. 1564":"Lustracja województwa krakowskiego 1564, wyd. J. Małecki, t. 1-2, Warszawa 1964",
    "Lustr. 1660":"Lustracja województwa krakowskiego 1659-1663, AGAD, Archiwum Skarbu Koronnego XVIII/24",
    "Lustr. 1765":"Lustracja województwa krakowskiego 1765, cz. I, powiaty sądecki, szczyrzycki, biecki, czchowski oraz księstwa zatorskie i oświęcimskie, wyd. A. Falniowska-Gradowska, Kraków 1973",
    "Lustr. 1789":"Lustracja województwa krakowskiego 1789, cz. I-II, wyd. A. Falniowska-Gradowska i I. Rychlikowa, Kraków 1962-1963",
    "Łuszczyński":"Spis sędziów, podsędków i pisarzy ziemskich krakowskich sporządzony przez J. Łuszczyńskiego, w APKr., Varia 96",
    "MBiecza":"Materiały do historii miasta Biecza 1361-1632, wyd. F. Bujak, Kraków 1914",
    "Michałowski":"Jakuba Michałowskiego wojskiego lubelskiego, a później kasztelana bieckiego księga pamiętnicza z dawnego rękopisu wydana przez A. Z. Helcla, Kraków 1864",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka tzw. Litewska w AGAD ",
    "MPH":"Monumenta Poloniae Historica",
    "MRPS":"Matricularum Regni Poloniae summaria, wyd. T. Wierzbowski, cz. 1-5, Warszawa 1905-1961",
    "MŻywca":"F. Lenczowski, Materialy do dziejów miasta Żywca od XV do XVIII wieku, Kraków 1957",
    "Nies.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. 1-10, Lipsk 1839-1846",
    "Nowy Korbut":"Bibliografia literatury polskiej Nowy Korbut, t. 1-6, Warszawa 1963-1973",
    "OpisLitMetr.":"Opisanie knig i aktov litevskoj metriki, wyd. S. Ptaszycki, Sankt Petersburg 1887",
    "Orgelbrand":"S. Orgelbranda, Encyklopedia powszechna, t. 1-18, Warszawa 1898-1912",
    "Orzelski":"Sventoslai Orzelski Interregni Poloniae libros 1572-1576, ed. E. Kuntze, Kraków 1917",
    "Oświęcim":"Stanisława Oświęcima diariusz 1643-1651, wy d. W. Czermak, Kraków 1907, w: Scriptores Rerum Polonicarum t. XIX",
    "Otfinowski":"Otfinowski (Anonim), Dzieje Polski pod panowaniem Augusta II, 1849",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVI wieku, Warszawa 1962 ",
    "Pamiętniki o Koniecpolskich":"Pamiętniki o Koniecpolskich. Przyczynek do dziejów polskich XVI1 wieku, wyd. S. Przyłęcki, Lwów 1842",
    "PANKr.":"Biblioteka PAN w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, wyd. K. J. Turowski, Kraków 1858",
    "Pasiecznik":"J. Pasiecznik OFN, Kościół i klasztor Franciszkanów Reformatów w Bieczu, Kraków 1984",
    "Piech":"Corpus inscriptionum Poloniae, t. VIII, zesz. 2, Bazylika Mariacka w Krakowie, oprac. Z. Piech, Kraków 1987", 
    "Piekosiński":"F. Piekosiński, Rycerstwo polskie wieków, średnich, t. I, Kraków 1896",
    "Pociecha":"W. Pociecha, Królowa Bona (1494-1557). Czasy i ludzie Odrodzenia, t. I-IV, Poznań 1949-1958",
    "Prawa, przywileje":"Prawa, przywileje i statuta miasta Krakowa (1507-1795), wyd. F. Piekosiński, S. Krzyżanowski, t. 1-2, Kraków 1885-1909",
    "Prochaska":"Materiały archiwalne wyjęte głównie z metryki litewskiej, wyd. A. Prochaska, Lwów 1890",
    "Przyboś-Walaszek":"K. Przyboś, A. Walaszek, Reprezentacja sejmowa województwa krakowskiego w XVII wieku, Studia Historyczne 20, 1977",
    "Przybyszewski":"B. Przybyszewski, Wypisy źródłowe do dziejów Wawelu z archiwów kapitulnych i kurialnych, w: Źródła do dziejów Wawelu, t. III, IV, V, Kraków 1960-1970",
    "PSB":"Polski słownik biograficzny, t. I-XXXII, Kraków 1935-1989",
    "Pułaski":"F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, w: Muzeum Konstantego Świdzińskiego, t. 23-29, Warszawa 1915",
    "Radziwiłł":"Albrycht Stanisław Radziwiłł, Pamiętnik o dziejach w Polsce, przełożyli i opracowali A. Przyboś i R. Żelewski, t. 1-3, Warszawa 1980",
    "Rauscher":"Soudni knihy Osvetimske a Zátorské z roku 1440-1562, wyd. R. Rauscher, Praha 1931",
    "Rep. Kutrzeby":"Repertorium Kutrzeby w APKr.",
    "Reszka":"Stanislai Rescii Diarium 1583-1589, wyd. J. Czubek, w: Arch. dz. lit., t. XV, cz. I, Kraków 1915",
    "Rykaczewski":"Inventarium omnium et singulorum privilegio rum, litterarum, diplomatum, scripturarum et monuementorum quaecunque in archivo Regni in arce Cracoviensi continentur, ed. E. Rykaczewski, Lutetiae Parisiorum 1862",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego, Diariusz i relacje z lat 1691-1696, wyd. J. Woliński, Wrocław 1958",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "Sozański":"A. Sozański, Imienne spisy osób, które w pierwszych ośmiu latach panowania Stanisława Augusta w rządzie... udział brały, Kraków 1866",
    "SPPP":"Starodawne prawa polskiego pomniki, t. II. wyd. A. Z. Helcel, Kraków 1870",
    "SrP":"Scriptores Rerum Polonicarum, t. 1-22, Kraków 1872-1917",
    "Starowolski":"Simon Starovolscius, Monumenta Sarmatarum, viam universae carnis ingressorum, Cracoviae 1655",
    "Straty archiwów":"Straty archiwów i bibliotek warszawskich w zakresie rękopiśmiennych źródeł historycznych, t. I-III, Warszawa 1957, 1956, 1955",
    "Stupnicki":"H. Stupnicki, Herbarz polskich i imionopis zasłużonych w Polsce ludzi, t. I-III, Lwów 1855-1862 ",
    "SuchGrabElita":"A. Sucheni-Grabowska, Badania nad elitą władzy w latach 1551-1502, w: Społeczeństwo staropolskie I, Warszawa 1976",
    "SuchGrabMon.":"A. Sucheni-Grabowska, Monarchia dwu ostatnich Jagiellonów a ruch egzekucyjny, Wrocław 1974. ",
    "SuchGrabOdb.":"A. Sucheni-Grabowska, Odbudowa domeny królewskiej w Polsce z 1504-1548, Wrocław 1967",
    "Swada polska":"J. Ostrowski-Daneykowicz, Swada polska i łacińska, albo miscellanea oratorskie seymowe, weselne . . . pogrzebowe . . ., t. 1-2, Lwów 1744-1747",
    "SygMetr.":"Ks. J. Sygański, Z dawnych metryk kościoła mariackiego w Krakowie i katedry na Wawelu, Lwów 1911",
    "SygSącz":"Ks. J. cygański, Historia Nowego Sącza od wstąpienia Wazów do pierwszego rozbioru Polski, t. 1-3, Lwów 1901 ",
    "Święcicki":"Tomasza Święcickiego historyczne pamiątki znamienitych rodzin i osób dawnej Polski przejrzał w rękopisie, objaśnił i uzupełnił przypisami J. Bartoszewicz, t. I-II, Warszawa 1858-1859 ",
    "TB":"Terrestria Biecensia w APKr. ",
    "TC":"Terrestria Cracoviensia w APKr.",
    "TCN":"Terrestria Cracoviensia Nova w APKr. ",
    "Teut.":"Teutonicalia w APKr.",
    "Tomczak":"A. Tomczak, Walenty Dembiński, kanclerz egzekucji (ok. 1504-1548), Toruń 1963",
    "Tomkowicz":"S. Tomkowicz, Inwentaryzacja zabytków powiatów grybowskiego i gorlickiego, w: Teka grona konserwatorów Galicji Zachodniej, t. I, Kraków 1900",
    "TOZ":"Terrestria Osvencimensia et Zatoriensia w APKr.",
    "TPaw.":"Teki Aäolfa Pawińskiego, t. I, Liber quitantiarum regis Alexandri (1502-1506), wyd. J. Kochanowski, Warszawa 1897 ",
    "TX":"Terrestria Xiążnensia w APKr.",
    "TZ":"Terrestria Zatoriensia w APKr.",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, t. I n.",
    "Uchansciana":"Uchansciana czyli zbiór dokumentów wyjaśniających życie i działalność Jakuba Uchańskiego, wyd. T. Wierzbowski, t. I-V, Warszawa 1884-1895",
    "Uruski":"S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. 1-21, Warszawa 1904-1938",
    "UrzSąd.":"S. Cynarski, A. Falniowska-Gradowska, Szlachta urzędnicza w mieście. Urzędnicy i oficjaliści ziemscy i grodzcy sądeccy w XVI do XVIII wieku, w: Dzieje Nowego Sącza, t. I, w druku",
    "VL":"Volumina legum, t. V-VIII, wyd. J. Ohryzko, Petersburg 1860; t. IX, Kraków 1889",
    "Wielądko":"W. W. Wielądko, Heraldyka, czyli opisanie herbów w jakim który jest kształcie . . ., t. 1-5, Warszawa 1792-1798 ",
    "Wielewicki":"Ks. Jana Wielewickiego, Dziennik spraw domu zakonnego oo. jezuitów u św. Barbary w Krakowie, w: Scriptores rerum Polonicarum, t. VII, X, XIV, Kraków 1881, 1886, 1889",
    "Wierzbowski":"Konnotata wypadków w domu i kraju zaszłych od 1634 do 1689 r., skreślona przez Stanisława Wierzbowskiego starostę łęczyckiego i barwałdzkiego, chorążego łęczyckie go, z rękopisu przechowywanego w archiwum rodzinnym do druku podał i objaśnienia dołożył J. K. hr. Załuski, Lipsk 1856",
    "WiśnJędrz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w Jędrzejowskiem, Marjówka 1930",
    "WiśnKon.":"Ks. J. Wiśniewski, Dekanat konecki, Radom 1913 ",
    "WiśnOlk.":"Ks. J. Wiśniewski, Dzieje miasta Olkusza, jego kościołów i pamiątek, Marjówka 1935",
    "WiśnPil.":"Ks. J. Wiśniewski, Historyczny opis miasta Pilicy, Marjówka 1933",
    "WiśnPińcz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w pińczowskiem, skalbmierskiem i wiślickiem, Marjówka 1927",
    "WiśnStopn.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w Stopnickiem, Marjówka 1929 ",
    "WiśnWłoszcz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w powiecie włoszczowskim, Marjówka Opoczyńska 1932",
    "Wittyg":"Nieznana szlachta polska i jej herby, oprac. W. Wittyg przy współudziale St. Dziadulewicza, Kraków 1908",
    "Wolff":"J. Wolff, Kniaziowie litewscy do końca XV1 wieku, Warszawa 1895",
    "Wyczawski":"Ks. H. E. Wyczawski OFM, Kalwaria Zebrzydowska. Historia klasztoru Bernardynów i kalwaryjskich dróżek, Kalwaria Zebrzydowska 1987",
    "Zakrzewski":"W. Zakrzewski, Dyaryusz zjazdu protestantów w Radomiu 1591 r., AKH IX",
    "Zbiory Popielów":"Zbiory Popielów w AGAD",
    "Zbiór dypl. mog.":"Zbiór dyplomatów klasztoru mogilskiego przy Krakowie, Kraków 1865",
    "Żychliński":"T. Żychliński, Złota księga szlachty polskiej, t. 1-31, Poznań 1879-1908"
}