""" słownik skrótów literatury """

literatura = {
    "AAG":"Archiwum Archidiecezji Gnieźnieńskiej w Gnieźnie",
    "ACap.":"Acta capitulorum nec non iudiciorum ecclesiasticorum selecta, wyd. B. Ulanowski, t. I-III, Kraków 1894-1918",
    "ADW":"Archiwum Diecezji Włocławskiej",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, t. I­-XVIII, Lwów 1868-1903",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AP":"Album paleographicum, wyd. S. Kętrzyński, Kraków 1935",
    "APP":"Wojewódzkie Archiwum Państwowe w Poznaniu",
    "Arch. Publ. Pot.":"Archiwum Publiczne Potockich w AGAD",
    "ASPrus.":"Akta stanów Prus Królewskich, wyd. K. Górski, M. Biskup, I. Janosz-Biskupowa, t. I-VI, Toruń 1955-1979",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka Czartoryskich",
    "BiełKanc.":"M. Bielińska, Kancelarie i dokumenty wielkopolskie XIII wieku, Wrocław 1967",
    "BienWlkp.":"J. Bieniak, Wielkopolska, Kujawy, ziemie łęczycka i sieradzka wobec problemu zjednoczenia państwowego w latach 1300-1306, Toruń 1969",
    "BKórn.":"Biblioteka Kórnicka PAN",
    "Boniecki":"A. Boniecki, Herbarz polski, t. I-XVI Warszawa 1899-1913",
    "BrzezZ":"AGAD, Księgi ziemskie brzezińskie 1396-1515",
    "Cetwiński":"M. Cetwiński, Rycerstwo śląskie do końca XIII w. Biogramy i rodowody, Wrocław 1982",
    "Codex Vitoldi":"Codex epistolaris Vitoldi, magni ducis Lithuaniae 1376-1430, wyd. A. Prochaska, Kraków 1882",
    "Długosz":"Joannis Dlugossi seu Longini canonici Cracoviensis Historiae Polonicae libri XII, [w;] Opera omnia, t. XII-XIV, Kraków 1876-1878",
    "Dok. Kuj. Dobrz.":"Dokumenty do dziejów Kujaw i ziemi dobrzyńskiej XIV-XIX w., wyd. Z. Guldon, R. Kabaciński, M. Kallas, J. Wójcik, Warszawa-Poznań 1974",
    "Dok. Paul.":"Zbiór dokumentów oo. paulinów w Polsce (1328-1464), wyd. J. Fijałek, Kraków 1938",
    "DworzGen.":"W. Dworzaczek, Genealogia. Tablice, Warszawa 1959",
    "Epist.":"Codex epistolaris saeculi decimi quinti, wyd. A. Sokołowski, J. Szujski, A. Lewicki, t. I-III, Kraków 1876-1894",
    "GStar.":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej, Warszawa-Poznań 1981",
    "GUrz.":"A. Gąsiorowski, Urzędnicy wielkopolscy 1385-1500. Spisy, Poznań 1968",
    "Gieysztor":"A. Gieysztor, Owies w daninach łowieckich w Polsce średniowiecznej, “Kwartalnik Historii Kultury Materialnej”, t. XI, 1963",
    "Grzegorz":"M. Grzegorz, Analiza dyplomatyczno-sfragistyczna dokumentów traktatu toruńskiego 1466 r., Toruń 1970",
    "Hube":"R. Hube, Sądy, ich praktyka i stosunki prawno-społeczne w Polsce ku schyłkowi  XIV w., Warszawa 1886",
    "Inventarium":"Inventarium omnium et singulorum privilegiorum litterarum, diplomatum, scripturarum et monumentorum quaecunque in, archivo regni in arce Cracoviensi continentur, wyd. E. Rykaczewski, Lutetiae Parisiorum 1862",
    "KalG":"Księgi grodzkie kaliskie w APP",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej Ś.Wacława, wyd. F. Piekosiński, cz. I-II, Kraków 1874-1883",
    "KDKM":"Kodeks dyplomatyczny księstwa mazowieckiego, wyd. T. Lubomirski, Warszawa 1863",
    "KDM":"Kodeks dyplomatyczny Małopolski, wyd. F. Piekosiński, t. I-IV, Kraków 1876-1905",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, t. I-IV, [wyd. I. Zakrzewski], Poznań 1877-1881; t. V, wyd. F. Piekosiński, Poznań 1908; t. VI-VII, wyd. A. Gąsiorowski, H. Kowalewicz, R. Walczak, Warszawa 1982-1984",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa 1257-1506, wyd. F. Piekosiński, cz. 1-4, Kraków 1879-1882",
    "KMaz. I":"Zbiór ogólny przywilejów i spominków mazowieckich, wyd. J. K. Kochanowski, Warszawa 1919",
    "KMaz. II":"Kodeks dyplomatyczny Mazowsza (w druku)",
    "KMog.":"Zbiór dyplomów klasztoru mogilskiego, wyd. E. Janota, Kraków 1867",
    "Knigi":"Knigi polskoj koronnoj mietriki XV stoletija. Matricularum Regni Poloniae codices saeculo XV conscripti, wyd. A. Mysłowski, W. Graniczny, t. I, Warszawa 1914",
    "Kop. Dom. Sier.":"Archiwum OO. Dominikanów w Krakowie. Kopiariusz dominikanów sieradzkich",
    "Kozierowski":"S. Kozierowski, Nieznane zapiski heraldyczne, cz. I-II, “Rocznik [Polskiego] Towarzystwa Heraldycznego we Lwowie”, t. VI, VIII, 1921-1923, 1926-1927",
    "KPol.":"Kodex dyplomatyczny Polski, wyd. L. Rzyszczewski, A. Muczkowski, A. Z. Helcel, J. Bartoszewicz, M. Bobowski, t. I-IV, Warszawa 1847-1887",
    "Kr. 1":"Księga sądowa Wojciecha Malskiego namiestnika królewskiego na Wielkopolskę w APP",
    "KRSW":"AGAD, Komisja Rządowa Spraw Wewnętrznych",
    "KrzyżKanc.":"J. Krzyżaniakowa, Kancelaria królewska Władysława Jagiełły. Studium z dziejów kultury politycznej w XV wieku, cz. II,  Urzędnicy, Poznań 1979",
    "KTyn.":"Codex diplomaticus monasterii Tynecensis, wyd. W. Kętrzyński i S. Smolka, cz. I, Lwów 1875",
    "Kutrzeba":"S. Kutrzeba, Urzędy koronne i nadworne w Polsce, ich początki i rozwój do roku 1504, “Przewodnik Naukowy i Literacki”, t. XXXI, 1903",
    "Kutrzebianka":"A. Kubrzebianka, Vesnica- danina miodowa, “Roczniki Dziejów Społecznych i Gospodarczych”, t. VII, 1938",
    "Lasocki":"Z. Lasocki, Dostojnicy i urzędnicy ziemi dobrzyńskiej w XIV i XV wieku, “Miesięcznik Heraldyczny”, R. XIII, 1934",
    "Lelewel":"J. Lelewel, Polska, dzieje i rzeczy jej, t. III-IV, Poznań 1856",
    "Lites":"Lites ac res gestae inter Polonos Ordinemque Cruciferorum, wyd. I. Zakrzewski, t. I-II, Poznań 1890-1892 ",
    "Łaguna":"S. Łaguna, Nieznane zapiski heraldyczne średniowieczne polskie, głównie sieradzkie, [w:] tegoż, Pisma, Warszawa 1915",
    "ŁęczG":"Księgi grodzkie łęczyckie 1461-1508 w AGAD",
    "ŁęczZ":"Księgi ziemskie łęczyckie 1385-1513 w AGAD",
    "MaleczKil.":"K. Maleczyński, Kilkanaście dokumentów Władysława Łokietka z lat 1296-1329, “Studia Źródłoznawcze”, t. VI, 1961",
    "MitkKanc.":"J. Mitkowski, Kancelaria Kazimierza Konradowica księcia kujawsko-łęczyckiego (1233-1267), Wrocław 1968",
    "MitkPocz.":"J. Mitkowski, Początki klasztoru cystersów w Sulejowie. Studia nad dokumentami, fundacją i rozwojem uposażenia do końca XIII  wieku, Poznań 1949",
    "MK":"Metryka Koronna, Księgi wpisów w AGAD",
    "Mosbach":"Wiadomości do dziejów polskich z Archiwum Prowincyi Szląskiej, wyd. A. Mosbach, Wrocław 1860",
    "MPH":"Monumenta Poloniae historica, wyd. A. Bielowski i in., t. II-V, Lwów 1872-1893; nowa seria (s.n.), t. V, VI, X",
    "MRPS":"Matricularum Regni Poloniae summaria, wyd. T. Wierzbowski i in., t. I-V, Warszawa 1905-1961",
    "Niesiecki":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-X, Lipsk 1839-1845",
    "Niwiński":"M. Niwiński, Dokumenty Łokietka dla dóbr łęczyckich opactwa wąchockiego, “Kwartalnik Historyczny”, R. XLVI, 1932",
    "OrłZ":"Księgi ziemskie orłowskie 1410-1498 w AGAD",
    "OstrzG":"Księgi grodzkie ostrzeszowskie 1419-1508 w AGAD",
    "OstrzZ":"Księgi ziemskie ostrzeszowskie 1467-1530 w AGAD",
    "PakZar.":"J. Pakulski, Ród Zarembów w Wielkopolsce w XIII i początkach XIV wieku, “Prace Komisji Historii Bydgoskiego Towarzystwa Naukowego”, t. XI, 1975, s. 103-137",
    "PAN Kr.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, wyd. K. J. Turowski, Kraków 1858",
    "Parczewski":"A. J. Parczewski, Monografia Szadku, Warszawa 1870",
    "Perzanowski":"Dokumenty sądu ziemskiego krakowskiego 1302-1453, wyd. Z. Perzanowski, Wrocław 1971",
    "PiotrDos.":"T. Piotrowski, Dostojnicy województwa łęczyckiego za pierwszych Jagiellonów, Warszawa 1935",
    "Pozn. I":"Die ältesten grosspolnischen Grodbiicher, cz. I, wyd. J. Lekszycki, Leipzig 1887",
    "Pozn. II":"Księga ziemska poznańska 1400-1407, wyd. K. Kaczmarczyk i K. Rzyski, Poznań 1960",
    "PozG":"Księgi grodzkie poznańskie w APP",
    "PozZ":"Księgi ziemskie poznańskie w APP",
    "PSB":"Polski słownik biograficzny, t. I-XXVII, Kraków 1935-1983",
    "Reg. Schles.":"Regesten zur Schlesischen Geschichte, wyd. C. Grunhagen, K. Wutke, Codex diplomaticus Silesiae, t. VII, XVI, XVIII, XXII, XXIX, Breslau 1876-1923",
    "Reg. Teut.":"Regesta historico-diplomatica Ordinis S. Mariae Theutonicorum, t. I-II, wyd. E. Joachim, W. Hubatsch, Göttingen 1948- 1950",
    "Rep. Germ.":"Repertorium Germanicum, wyd. v. Deutschen Historischen Institut in Rom, t. II-III, Berlin 1933",
    "Rus.":"Archiwum Państwowe w Krakowie, Zbiory Rusieckich, Dyplomy pergaminowe ",
    "SierG":"Księgi grodzkie sieradzkie 1405-1502 w AGAD",
    "SierZ":"Księgi ziemskie sieradzkie 1386-1502 w AGAD",
    "SPPP":"Starodawne prawa polskiego pomniki, t. II i n., Kraków 1870 i n.",
    "SułkDok.":"I. Sułkowska-Kurasiowa, Dokumenty królewskie i ich funkcja w państwie polskim za Andegawenów i pierwszych Jagiellonów. 1370-1444, Warszawa 1977",
    "SułkPol.":"I. Sułkowska, Polska kancelaria królewska w latach 1447-1506, Wrocław 1967",
    "Szacherska":"S. M. Szacherska, Z dziejów kancelarii książąt kujawskich w XIII w. Dwa nieznane dokumenty szpetalskie, “Studia Źródłoznawcze”, t. V, 1960",
    "SzadZ":"Księgi ziemskie szadkowskie 1417-1507 w AGAD",
    "Szaniawski":"Spis chronologiczny przywilejów w archiwum akt dawnych w Sieradzu w roku 1850 się znajdujących, opr. P. Szaniawski, “Biblioteka Starożytna Pisarzy Polskich”, t. II, Warszawa 1854",
    "TPaw.":"Teki A. Pawińskiego, wyd. J. Kochanowski, Warszawa 1897-1905",
    "UdBC":"Urkundenbuch des Bisthums Culm, wyd. C. P. Woelky, t. I-II, Danzig 1885-1887",
    "VL":"Volumina legum, t. I, przedruk J. Ohryzko, Petersburg 1859",
    "WAP":"Wojewódzkie Archiwum Państwowe",
    "WielG":"Księgi grodzkie wieluńskie 1456-1469, 1496-1516 w AGAD",
    "WielP":"Księgi podkomorskie wieluńskie w AGAD",
    "WielZ":"Księgi ziemskie wieluńskie 1496-1516 w AGAD",
    "Wiesiołowski":"J. Wiesiołowski, Ambroży Pampowski- starosta Jagiellonów. Z dziejów awansu społecznego na przełomie średniowiecza i Od-rodzenia, Wrocław 1976",
    "WSB":"Wielkopolski słownik biograficzny, Poznań 1981",
    "ZDM":"Zbiór dokumentów małopolskich, cz. I-III, wyd. S. Kuraś; t. I V-VIII, wyd. I. Sułkowska-Kuraś i S. Kuraś, Wrocław 1962-1975",
    "Zielińscy":"G. i J. Zielińscy, Wiadomość historyczna o rodzie Świnków oraz rodowód pochodzącej od nich rodziny Zielińskich herbu Świnka, Toruń 1880"
}
