""" słownik skrótów literatury """

literatura = {
    "Acta Brandenburgica":"Brandenburgische Regierungsakten seit der Begriindung des Geheimes Rates, Bd. I, 1604-1605, Berlin 1927",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, t. 1 n., Lwów 1868 n.",
    "AKH":"Archiwum Komisji Historycznej Polskiej Akademii Umiejętności, t. XV, Warszawa 1939",
    "Akta sejm. pozn. i kal.":"Akta sejmikowe województwa poznańskiego i kaliskiego, t. I, cz. 1, Poznań 1957",
    "APKw":"Archiwum Państwowe w Krakowie",
    "APŁ":"Archiwum Państwowe w Łodzi",
    "APPA":"Archiwum Państwowe w Poznaniu",
    "Arch. Ostr.":"Archiwum Potockich i Ostrowskich z Maluszyna w APŁ",
    "Arch. Wal.":"Archiwum Kazimierza Walewskiego z Tubądzina w APŁ",
    "Arch. Zamoyskiego":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, t. I-IV, Warszawa 1904, 1909, 1913, 1948",
    "ASejmWojKr":"Akta sejmikowe województwa krakowskiego, t. I, Warszawa 1932",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwum Czartoryskich",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. I n., Warszawa 1899 n.",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BZ":"Brzezińskie księgi ziemskie w AGAD",
    "Cieszkowski":"S. Cieszkowski, Senatorowie Księstwa Warszawskiego i Królestwa Kongresowego 1807-1815-1630, Warszawa 1891",
    "Corp. Ins. Pol.":"Corpus inscriptionum Poloniae, t. I n., Kielce 1 in. 1975 n.",
    "DworzGen.":"W. Dworzaczek, Genealogia. Tablice, Warszawa 1959",
    "DworzTarn. II":"W. Dworzaczek, Hetman Jan Tamtowski, Warszawa 1985",
    "DworzTryb.":"Księgi Trybunału Koronnego w Piotrkowie - wypisy prof. W. Dworzaczka w Bibliotece Kórnickiej Polskiej Akademii Nauk w Kórniku",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD",
    "Kobicrzycki":"J. Kobierzycki, Przyczynki do dziejów ziemi sieradzkiej, cz. 1--1I, Warszawa 1915",
    "Kossakowski":"$. K, Kossakowski, Monografie historyczno-genealogiczne niektórych rodów polskich, t. I - III, Warszawa 1859—1872",
    "ŁGI":"Łęczyckie księgi grodzkie - inskrypcje w AGAD",
    "ŁGO":"Łęczyckie księgi grodzkie - oblaty w AGAD",
    "ŁGR":"Łęczyckie księgi grodzkie - relacje w AGAD",
    "ŁP":"Łęczyckie księgi podkomorskie w AGAD",
    "ŁZ":"Łęczyckie księgi ziemskie w AGAD",
    "Michałowski":"Jakuba Michałowskiego wojskiego lubelskiego, a później kasztelana bieckiego księga pamiętnicza..., Kraków 1864",
    "MK":"Metryka koronna w AGAD",
    "ML":"Metryka tzw. litewska w AGAD",
    "MPH":"Monumenta Poloniae Historica, t. I n.",
    "MRPS":"Matricularum Regni Poloniae summaria, t.1-V, Warszawa 1905-1961",
    "Nies.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-X, Lipsk 1839-1846",
    "Ochmann, Sejm 1649":"S$. Ochmann, Sejm koronacyjny Jana Kazimierza w 1649 r., Wrocław 1985",
    "OG":"Ostrzeszowskie księgi grodzkie w AGAD",
    "OGI":"Ostrzeszowskie księgi grodzkie - inskrypcje w AGAD",
    "OGR":"Ostrzeszowskie księgi grodzkie - relacje w AGAD",
    "OGRO":"Ostrzeszowskie księgi grodzkie - relacje i oblaty w AGAD",
    "OrłZ":"Orłowskie księgi ziemskie w AGAD",
    "Orzelski":"Świętosława Orzelskiego bezkrólewia ksiąg ośmioro 1572-1576, Kraków 1917",
    "Ossol.":"Biblioteka Ossolineum we Lwowie",
    "Oświęcim":"Stanisława Oświęcima diariusz 1643-1651, Kraków 1907",
    "OZ":"Ostrzeszowska księga ziemska w AGAD",
    "PamKon.":"Pamiętniki o Koniecpolskich. Przyczynek do dziejów polskich XVII wieku, Lwów 1842",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, wyd. K. J. Turowski, Kraków 1858",
    "PSB":"Polski słownik biograficzny, t. I-XXXIII, Kraków 1935 n.",
    "Radziwiłł":"A. S$. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I-IV, Wrocław 1968—1974",
    "Rawita-Witanowski":"M. Rawita-Witanowski, Kłodawa i jej okolice pod względem historyczno-ludoznawczym, Warszawa 1905",
    "SG":"Sieradzkie księgi grodzkie (Acta castrensia) w AGAD",
    "SGI":"Sieradzkie księgi grodzkie - inskrypcje w AGAD",
    "SGR":"Sieradzkie księgi grodzkie - relacje w AGAD",
    "Sig.":"Księgi Sigillat Metryki koronnej w AGAD",
    "SP":"Sieradzkie księgi podkomorskie w AGAD",
    "SSRP":"Scriptores Rerum Polonicarum",
    "Starowolski":"Simon Starovolscius, Monurnenta Sarmatarum, viam universae carnis ingressorum, Cracoviae 1655",
    "Steinwehr":"Zbiór rękopiśmienny Steinwehra w Bibliotece Uniwersytetu Wrocławskiego",
    "SuchGrabMon.":"A. Sucheni-Grabowska, Monarchia dwu ostatnich Jagiellonów a ruch egzekucyjny, Wrocław 1974",
    "SuchGrabOdb.":"A. Sucheni-Grabowska, Odbudowa domeny królewskiej w Polsce 1504-1548, Wrocław 1967",
    "SZ":"Sieradzkie księgi ziemskie w AGAD",
    "SzadZ":"Szadkowskie księgi ziemskie w AGAD",
    "Temberski":"Stanistawa Temberskiego Roczniki 1647-1656, Kraków 1897",
    "TP":"Teki Adolfa Pawińskiego w Bibliotece PAN w Krakowie",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku, t. I n., Wrocław 1985 n., Kórnik 1990 n.",
    "Ur.":"S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XXI, Warszawa 1904-1938",
    "VL":"Vołumina legum, t. II n., wyd. J. Ohryzko, Petersburg 1859 n.",
    "WGI":"Wieluńskie księgi grodzkie - inskrypcje w AGAD",
    "WGO":"Wieluńskie księgi grodzkie - oblaty w AGAD",
    "WGPR":"Wieluńskie księgi grodzkie - protokoły relacji w AGAD",
    "WGR":"Wieluńskie księgi grodzkie - relacje w AGAD",
    "Wierzbowski":"Konnotata wypadków w domu i kraju zaszłych od 1634 do 1689r. skreślona przez Stanisława Wierzbowskiego..., Lipsk 1856",
    "Wiesiołowski":"J. Wiesiołowski, Arnbroży Pampowski - starosta Jagiellonów. Z dziejów awansu społecznego na przełomie średniowiecza i odrodzenia, Wrocław 1976"
}