""" słownik skrótów literatury """

literatura = {
    "A.Branickich":"Zbiór Branickich z Suchej w APK",
    "ADP":"Archiwum Diecezjalne w Pelplinie",
    "ADPot.":"Archiwum Domowe Potockich w AGAD",
    "ADrohoj.":"Kronika Drohojowskich, oprać. J. Drohojowski, cz. I-II, Kraków 1904",
    "A.Faszczów":"Archiwum Faszczów w AGAD",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie..., t. I-XXV, Lwów 1868-1935",
    "AJZ":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, t. I-IV, Warszawa-Kraków 1904-1948",
    "A.Krokowskich":"Archiwum Krokowskich z Krokowej w APG",
    "AMCh":"Archiwum Mlynowskie Chodkiewiczów w APK",
    "AMChehnży":"Akta miasta Chełmży w APT",
    "AMChojnic":"Akta miasta Chojnic w APB",
    "AMG":"Akty moskovskogo gosudarstva, izdannyje imperatorskoju Akademiju Nauk, wyd. N. A. Popov, t. II-III, Sktpetersburg 1894-1901",
    "AMGolubia":"Akta miasta Gołubia w ADP",
    "AMKowalewa":"Akta miasta Kowalewa w APT",
    "AML":"Archiwum miasta Lublina w APL",
    "AMNowego":"Akta miasta Nowego w APB",
    "AMTor.":"Akta miasta Torunia w APT",
    "APB":"Archiwum Państwowe w Bydgoszczy",
    "APG":"Archiwum Państwowe w Gdańsku",
    "A.Piłsud.":"Archiwum Piłsudskich-Giniatowiczów w AGAD",
    "APK":"Archiwum Państwowe w Krakowie",
    "APL":"Archiwum Państwowe w Lublinie",
    "A.Platerów":"Archiwum Platerów z Antuzowa w AGAD",
    "A.pleb.nowogr.":"Archiwum plebanów nowogródzkich w Archiwum Zamku Królewskiego w Warszawie",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APPoz.":"Archiwum Państwowe w Poznaniu",
    "A.Prozorów":"Archiwum Prozorów w AGAD",
    "A.Przezdz.":"Archiwum Przezdzieckich w AGAD",
    "APT":"Archiwum Państwowe w Toruniu",
    "AR":"Archiwum Radziwiłłów w AGAD",
    "Archiv JZR":"Archiv Jugo-Zapadnoj Rossii, izdavaemyj Wremennoju Kommissieju dlja rozbora drevnich aktov, 1 1-VI, Kiev 1859-1911",
    "Arndt":"J. G. Arndt, Der Lieflaendischen Chronik Anderer Theil, Halle 1753",
    "A.Rusieckich":"Zbiory Rusieckich w APK",
    "A.Sang.":"Archiwum Sanguszków w APK",
    "ASczan.":"Archiwum Sczanieckich z Nawry w APT",
    "ASD":"Archeograficeskij Sbomik Dokumentov Otnosjascichsja k Istorii Severo-Zapadnoj Rusi, t, I-XIV, Vilna 1867-1904",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "ASWK":"Akia sejmikowe województwa krakowskiego, wyd. S. Kutrzeba, A. Przyboś, t. I-V, Kraków 1932-1984",
    "AUGChel.":"Album uczniów chełmińskiego gitnnazjum akademickiego 1692-1816, wyd. Z. Nowak i P. Szafran, Wrocław 1975",
    "AVAK":"Akty izdavaemye Kommissieju VysoćajSe ućrezdennoju dlja razbora drevnich aktov v Vilne (od t. XIII): Akty izdavaemye Vilenskoju Archeografićeskoju Kommissieju, t. I-XXXIX, Vilna 1865-1915",
    "AWH":"Archiwum Woronieckich z Huszlewa w APL",
    "A.Zabiełłów":"Archiwum Zabiellów w AGAD",
    "AZGlog.":"Archiwum Zygmunta Glogera w APK",
    "Bar":"M. Bar. Westpreussen unter Friedrich dem Grossen, Bd. II, Leipzig 1909",
    "Barącz, Rys":"S. Barącz, Rys dziejów zakonu kaznodziejczego w Polsce, t. I-II, Lwów 1861",
    "BCzart.":"Muzeum Narodowe w Krakowie - Biblioteka Czartoryskich",
    "Belorus.":"Belorussia v epochu feodalizma. Sbornik dokumentov i materialov, Minsk 1959",
    "BFMitt.":"Baltisch Fatniliengeschichłliche Mitteilungen, t. I-IX, Tartu 1932-1941",
    "Birżu dvaro":"Biriu dvaro teismo knygos 1620-1745, wyd. V. Raudeliunas i R. Firkovićius, Vilnius 1982",
    "BJag.":"Biblioteka Jagiellońska w Krakowie",
    "BKóm.":"Biblioteka Kórnicka PAN w Kórniku",
    "Błesz.":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII wieku, [w:] S. K. Kossakowski, Monografie historyczno-genealogiczne..., t. III. Warszawa 1876 n.",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bodeckers Cbronick":"Bodeckers Chronick Livlaendischer und Rigascher Ereignisse 1592-1638, hrsg. J. G. L. Napiersky, Riga 1890",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XV, Warszawa 1899-1912",
    "Borkowski":"J. S. Dunin-Borkowski, Rocznik szlachty polskiej, t I-II, Lwów 1899-1912",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "BOZ":"Biblioteka Ordynacji Zamoyskich w BN",
    "BRacz.":"Miejska Biblioteka Publiczna im. Edwarda Raczyńskiego w Poznaniu",
    "Breżgo, Latg. inventari":"B. Breżgo, Latgolas inventori un generalnereisonas zam’u aproksti 1695-1784, Daugavpils 1943",
    "Breżgo LVM":"B.Breżgo, Latgolas vestures materiali, 1.1, Daugavpils 1944",
    "BSS":"Gosudarstvennaja biblioteka im. Sałtykowa-Scedrina w Sankt Petersburgu",
    "BUANLw.":"Biblioteka Ukraińskiej Akademii Nauk im. Stefanika we Lwowie",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego",
    "Chłapowski, Starostowie":"K. Chłapowski, Starostowie w Malopolsce 1565-1668, [w:] Społeczeństwo staropolskie, t. IV, Warszawa 1986",
    "Chrapowicki":"J. A. Chrapowicki, Diariusz. Część pierwsza: lata 1656-1664, oprac. T. Wasilewski, Warszawa 1978; Część druga: lata 1665-1669, oprac. A. Rachuba, T. Wasilewski, Warszawa 1988",
    "CIP":"Corpus inscriptionum Poloniae",
    "Czapiewski":"P. Czapiewski, Senatorowie świeccy, podskarbiowie i starostowie Prus Królewskich 1454-1772, Roczniki TNT 26-28:1919-1921, Toruń 1921",
    "Czołow.":"Zbiór Czołowskiego w AGAD",
    "Dachnowski":"[J. K. Dachnowski, Herbarz szlachty pruskiej], AMTor. II, XII/13 w APT",
    "Diariusz sejmu 1701-2":"Diariusz Sejmu Walnego Warszawskiego 1701-1702, wyd. P. Smolarek, Warszawa 1962",
    "Diariusz WRWarsz.":"Diariusz Walnej Rady Warszawskiej z r. 1710, wyd. R. Mienicki, Wilno 1928",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae, t. V, wyd. M. Dogiel, Wilno 1769",
    "Dom.Tor.":"Akta klasztoru dominikanów z Torunia w APT",
    "Druszkiewicz":"S. Z. Druszkiewicz, Pamiętnik... stolnika pamawskiego, dziennik Literacki”, 1856, t. 2",
    "Dubr.":"Sobranije Dubrovskogo w BSS",
    "Duńczewski":"S. Duńczewski, Herbarz wielu domów Korony Polskiej i W. X. Litewskiego..., Kraków 1757",
    "Dziennik J. P. Sapiehy":"J. P. Sapieha, Dziennik...,, [w:] Polska a Moskwa w połowie wieku XVII, wyd. A. Hirschberg, Lwów 1901",
    "Dzierz.G.":"Księgi grodzkie dzierzgońskie w APG",
    "Elekt":"J. Dunin-Borkowski, M. Dunin-Wąsowicz, Elektorowie królów Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, Lwów 1910;",
    "Elektorowie":"O. Pietruski, Elektorów poczet, którzy niegdyś głosowali na elektorów Jana Kazimierza roku 1648, Jana III roku 1674, Augusta II roku 1697 i Stanisława Augusta roku 1764, Lwów 1845",
    "Estr.":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografia polska, stulecie XV-XVIII, t. I-XXXIX, Kraków 1870-1952",
    "F.Czołow.":"Zbiór Czołowskiego w BUANLw.",
    "Fahne":"R. A. Fahne, Die Herren und Freiherren von Hovel, Kóln I860",
    "FHLSJ":"Fontes Historiae Latviae Societatis Jesu (lot. Latvijos vesturas avoti jezuitu ordena archivos), wyd. J. Kleintjenss, t. I-Il, Riga 1940-1941",
    "Fontes":"Fontes Towarzystwa Naukowego w Toruniu”",
    "F.Oss.":"Fond Ossolińskich w BUANLw.",
    "F.Sapiehów":"Fond Sapiehów w BUANLw.",
    "Fundacja Ciechanowieckich":"Archiwum Fundacji Ciechanowieckich na Zamku Królewskim w Warszawie",
    "Gadebusch, Livi. Jbr.":"F. K. Gadebusch, Livlandische JahrbUcher, t. II, Riga 1781",
    "Gadebusch, Versuche":"F. K. Gadebusch, Versuche in der livlaendischen Geschichtskunde und Rechtsgelehrsamkeit, Bd. 1, Riga 1779",
    "Genealogia Mohlów":"Genealogia rodziny von der Mohlów, maszynopis w posiadaniu rodziny",
    "GH Kurland":"Genealogisches Handbuch de r kurlćindischenRitte rschafi, bearb. von O. Stavenhagen, W. v. d. Osten-Sacken, H. v. zur Miihlen, Bd. I-II, Górlitz [1930] n.",
    "GStA":"Geheimes Staatsarchiv Preussischer Kulturbesitz, Berlin-Dahlem",
    "Hagemeister, Materialen":"H. v. Hagemeister, Materialen zu einer Geschichte der Landgliter Livlands, t. I-II, Riga 1836-1837",
    "Herbarz inll.":"Herbarz szlachty Inflant Polskich z 1778 roku, oprać. A. Heymowski, [w:] Materiały do biografii, genealogii i heraldyki polskiej, t. II. Buenos Aires 1964",
    "Herbst, Wojna 1600-1602":"S. Herbst, Wojna inflancka 1600-1602, Warszawa 1938",
    "Index corporis":"Index corporis historico-diplomatici Livoniae, Esthoniae, Curoniae..., ed. C. Napiersky, Riga u. Dorpat 1835",
    "Instrukcijos feodalniu":"Instrukcijos feodalniu valdu administracijai Lietuvoje XVII-XIXa., wyd. Z. Kiaupa, J. Kiaupiene, Vilnius 1985",
    "UM":"Istoriko-juridiceskije materiały izylecennyje iz aktovych knig gubemij Vitebskoj i Mogilevskoj, chraniaśćichsja v centralnom archivie v Vitebske, t. I-XXXU, Vitebsk 1871-1906",
    "Inow.G.":"Księgi grodzkie inowrocławskie w APPoz.",
    "Jankowski":"Cz. Jankowski, Powiat oszmiański. Materiały do dziejów ziemi i ludzi, t. I-IV, Petersburg 1896-1900",
    "Jankowski, KorRadz.":"Korespondencja Karola Stanisława Radziwiłła, wyd. C. Jankowski, Kraków 1898",
    "JfG":"„Jahrbuch fiir Genealogie, Heraldik und Sphragistik”, Jg. 1893-1914, Mitau 1894-1930",
    "Kai.":"Kalendarze polityczne (na poszczególne lata)",
    "Kam.":"Archiwum Kameralne w AGAD",
    "Kapicjana":"Kapicjana w AGAD",
    "Kat. A.Sang. w Sławucie":"Katalog pergaminów znajdujących się w archiwum X. X. Sanguszków w Sławucie, wyd. B. Gorczak, Sławuta 1912",
    "Kelch":"Ch. Kelch, Lieflaendische historia oder Kurze Beschreibung der Denkwuerdigsten Kriegs- und Friedens Geschichte Est- Lief- und Lettlandes, Frankfurt 1695",
    "KK":"Księgi kanclerskie MK w AGAD",
    "Klopmann":"F. v. Klopmann, Kuerlaendische Gtiter-Chroniken nach urkundlichen Quellen, t. I-II, Mitau 1856-1894",
    "Kochowski, Roczników kiimakter IV":"W. Kochowski, Roczników polskich klimakter IV, Lipsk 1853",
    "Kojałowicz, Compendium":"W. Wijuk Kojałowicz, Herbarz rycerstwa W. X Litewskiego tak zwany Compendium, wyd. F. Piekosiński, Kraków 1897",
    "Kojałowicz, Nomenclator":"W. Wijuk Kojałowicz, Herbarz szlachty W. Księstwa Litewskiego zwany Nomenclator, wyd. F. Piekosiński, „Herold Polski”, 1905",
    "Konarski, Platerowie":"S. Konarski, Platerowie, [w:] Materiały do biografii, genealogii i heraldyki polskiej, t. IV, Buenos Aires 1967",
    "Konarski, Szlachta":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Koresp. J.Chodkiewicza":"Korespondencja Jana Karola Chodkiewicza, wyd. W. Chomętowski, Biblioteka Ordynacji Krasińskich, Warszawa 1875",
    "Kossakowski":"S.Kossakowski, Monografie historyczno-genealogiczne niektórych rodzin polskich, t. I-III, Warszawa 1859-1872",
    "Kraushar, Ks. Repnin":"A. Kraushar, Książę Repnin i Polska w pierwszym czteroleciu panowania Stanisława Augusta (1764-1768), Warszawa 1900",
    "Krupowicz":"Zbiór dyplomatów rządowych i aktów prywatnych, posługujących do rozjaśnienia dziejów Litwy i złączonych z nią krajów (od 1387 do 1710), wyd. M. Krupowicz, cz. 1, Wilno 1858",
    "Ks. ref. kor.":"Księgi referendarii koronnej z czasów saskich, opr. M. Woźniakowa, t. I-II, Warszawa 1969-1970",
    "Ks. Sigillat":"Metryka Litewska. Księga Sigillat 1709-1719, oprac. A. Rachuba, Warszawa 1987",
    "Kuntze":"E. Kuntze, Organizacja Inflant w czasach polskich, [w:l Polska a Inflanty, Gdynia 1939, s. 1-53",
    "KZS":"Katalog zabytków sztuki w Polsce",
    "Leźno":"Akta majątku Leźno w APG",
    "Liet, inventor. XVII a.":"Lietuvos inventoried XVII a. Dokumentu rinkinys, wyd. K. Jablonskis i M. Juóas, Vilnius 1962",
    "Ljetopis Niensztedta":"Livonskaja Ijetopis Franca Niensztedta, [w:] Sbomik materialov i statjej po istorii Pribałtijskogo kraja, t. IV, Riga 1882",
    "Ljetopis Rjussowa":"B. Rjussov, Livonskaja chronika, [w:] Sbomikmaterjalov i statjej po istorii Pribałtijskogo kraja, t. in, Riga 1880",
    "LMAB":"Lietuvos Mosklu Akademijos centrines bibliotekos rankraSciu skyrius",
    "LNB":"Lietuvos nacionalines M. Mazvydo bibliotekos rankraSciu skyrius",
    "Lockwood Library":"Lockwodd Library State University of New York (mikrofilm dokumentów Jana Kazimierza dotyczących historii Wielkiego Księstwa Litewskiego w BN)",
    "LVIA":"Lietuvos valstybinis istorijos archyvas w Wilnie",
    "Łappo, Velik. kn. lit.":"1.1. Łappo, Velikoje kniazestvo Litovskoje vo vremja ot zakljućenija Ljublinskoj Unii do smerd Stefana Batorija 1569-1586, Petersburg 1901",
    "Ławno":"Acta Stanów Wielkiego Xięstwa Litewskiego na pospolite ruszenie vigore laudum Wileńskiego 14 Augusti 1698postanowionego między Ławnem a Puzewiczami... 1698 21 Decembris, Wilno 1699",
    "Łop.":"Biblioteka Publiczna im. Łopacińskich w Lublinie. Dział rękopisów",
    "Manteuffel":"G. Schmidt, Die Familie von Manteuffel II Abt. Freiherrliche Kurlandische Linie, Berlin 1909",
    "Manteuffel, Inflanty":"G. Manteuffel, Inflanty polskie; poprzedzone ogólnym rzutem oka na siedmiowiekową przeszłość całych Inflant, Poznań 1879",
    "Manteuffel, Familiennotizien":"G. Manteuffel, Familiennodzen aus dem Bersegall Drytzanschen FamilienArchiv, Ryga 1907",
    "Manteuffel, O szlachcie":"G. Manteuffel, O starodawnej szlachcie krzytacko-rycerskiej na kresach inflanckich, Lwów 1910",
    "Mater, po ist. Pribałt. kraja":"Sbomik materialov i statjej po istorii Pribałtijskogo kraja, t. 1-4, Riga 1877-1882",
    "Matuszewicz":"M. Matuszewicz, Diariusz tycia mego, t. I-II, oprać. B. Królikowski, Warszawa 1986",
    "Meck":"H. Lange, Die Familie von Meek in Livland, Riga 1943",
    "Metryka w Obolcach":"Wypisy z metryki kościoła w Obolcach (w posiadaniu Tadeusza Wasilewskiego)",
    "Meysztowicz, Kaipiowie":"A. Meysztowicz, Karpiowie herbu własnego, Wilno 1906",
    "Michałowski":"Jakuba Michałowskiego wojskiego lubelskiego a później kasztelana bieckiego księga pamiętnicza, Kraków 1864",
    "Mienicki, Rejestr":"Rejestr popisowy województwa połockiego z dn. 30 IX 1765, wyd. R. Mienicki, Ateneum Wileńskie, XI, 1936",
    "Mincer":"F. Mincer, Sprawa wakansów na sejmie brzeskim 1653 r., „Sprawozdania. Opolskie Towarzystwo Przyjaciół Nauk”. Wydz. I. Nauki Historyczno-Społeczne, seria A, nr 3,1965",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka Litewska w Rossijskom gosudarstvennom archive drevnich aktov w Moskwie, Fond 389",
    "MLA":"Monumenta Livoniae Antiquae, t.I-IV,Riga-Dorpai-Leipzig 1835-1844",
    "MLG":".Mittheilungen aus dem Gebiete der Geschichte Liv-, Esth-, und Kurland’s”, t. I-XXV, Riga 1837-1937",
    "MNKr.":"Muzeum Narodowe w Krakowie, depozyt Biblioteki Czartoryskich",
    "NAB Mińsk":"Nacyjanalnyj archiv Belarusi w Mińsku",
    "Neue Nordische Miscellaneen":"Neue Nordische Miscellaneen, wyd. A. W. Hupel, 1.1-18",
    "Nies.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-IX, Lipsk 1839-1845",
    "Niesiołowski":"J. Niesiołowski, Otia domestica, 1752",
    "Olkienniki":"Postanowienie Generalne Stanów WXLit.... na Zjeździe Walnym woiewództw y powiatów, pospolitym ruszeniem pod Olkiennikami uchwalone, RP1700, Wilno 1700",
    "Oracki":"T. Oracki, Słownik biograficzny Warmii, Prus Książęcych i Ziemi Malborskiej od połowy XV do końca XVIII wieku, t. I-II. Olsztyn 1984-1988",
    "Ostr.":"Archiwum Ostrowskich z Ujazdu",
    "Pacowie":"J. Wolff, Pacowie, Petersburg 1885",
    "PAN Kr.":"Biblioteka PAN w Krakowie",
    "Pawiński V":"A. Pawiński, Dzieje ziemi kujawskiej oraz akta historyczne do nich służące, t. V, Warszawa 1888",
    "Pelplin":"Akta klasztoru cystersów z Pelplina w ADP",
    "Piaskowski, Pamiętnik":"F. Junosza Piaskowski, Pamiętnik... podstolego podlaskiego, majora J. K. Mości, począwszy od roku 1690, Lwów 1865",
    "Pietrzak, Po Cecorze":"J. Pietrzak, Po Cecorze i podczas wojny chocimskiej. Sejmy z lat 1620 i 1621, Wroclaw 1983",
    "Poczobut":"J. W. Poczobut Odlanicki, Pamiętnik (1640-1684), oprać. A. Rachuba, Warszawa 1987",
    "Poszukiwania":"Poszukiwania. Studia o dawnej Polsce, 1.1, Buenos Aires - New York 1968",
    "PSB":"Polski słownik biograficzny, t. I n.",
    "Ptaszycki, Kn. Puzyny":"S. L. Ptaszycki, Kniazja Puzyny lstoriko-geneałogićeskije materiali, Skt Petersburg 1899",
    "Pulvis":"G. Pulvis, Tablice rodowodowe familii de Broel-Plater (w oparciu o: Konarski, Platerowie)",
    "Pułaski":"F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, Warszawa 1915",
    "Radziwiłł, Memoriale":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia, wyd. A. Przyboś i R. Żelewski, Wrocław 1968-1975",
    "Radziwiłł, Sprawy wojenne":"Księcia Krzysztofa Radziwiłła [...] sprawy wojenne i polityczne 1621-1632, Paryż 1859",
    "Radziwiłł, Zebranie dni":"K. S. Radziwiłł, Zebranie dni z Kalendarzów, rps w AGAD, AR, dz. VI, nr 11-79",
    "Raganu teismai":"Raganu teismai Lietuvoje, wyd. K. Jablonskis, R. Jasas, Vilnius 1987",
    "Ramm-Helmsing":"H. Ramm-Helmsing, Dawid Hilclien 1561-1610, Syndicus der Stadt Riga, Poznań 1936",
    "RA Stockholm":"Riksarkivet Stockholm",
    "Rejestry podymnego":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo wileńskie 1690 r., oprać. A. Rachuba, Warszawa 1989",
    "RGA StPet.":"Russkij gosudarstvennyj archiv w Sankt Petersburgu",
    "RH":"„Rocznik (Polskiego) Towarzystwa Heraldycznego we Lwowie”",
    "Roś":"Archiwum Roskie (majątkowe i korespondencja) w AGAD",
    "Sadkowska, Słuszkowie":"Cz. Sadkowska, Genealogia rodu Słuszków i ich archiwum (Szkic genealogiczno-archiwalny), „Archeion”, t. 52,1969",
    "Sapieha, Monumenta":"J. F. Sapieha, Monumenta albo zebranie starożytnych ozdob. Warszawa 1723",
    "Sapiehowie":"Sapiehowie. Materiały historyczno-genealogiczne i majątkowe, t. I-III, Petersburg 1890-1894",
    "Sbomik":"Sbomik dokumentov kasajusćichsja administrativnogo ustrojstva severo-zapadnogo kraja pri Jekaterinie 11(1792-1796), Vilna 1903",
    "S...cki":"S...cki, Dostojnicy litewscy, „Ateneum”, 1886,1.1, s. 150-164",
    "Semrau, Die Grabdenkmaler":"A. Semrau, Die Grabdenkmtiler der Marienkirche zu Thorn, Thom 1892",
    "SGKP":"Słownik geograficzny Królestwa Polskiego i innych krajów słowiańskich, t. I-XV, Warszawa 1880-1902",
    "Sier.G.Inscr.":"Księgi grodzkie sieradzkie - inskrypcje w AGAD",
    "Sig.":"Sigillata Metryki Koronnej w AGAD",
    "Socj.-polit. borba":"SocjaTno-politićeskaja borba narodnych mass Belorussii. Koniec XIV v. - 1648, 1.1, Minsk 1988",
    "Sołikowski, Ad Livones":"J. D. Solikowski, Ad Livones paterna et amica paraenesis, Samosci 1600",
    "Sprawy wojenne":"Sprawy wojenne króla Stefana Batorego, Dyariusze, relacje, listy i akta z lat 1576-1586, wyd. J. Polkowski, Cracoviae 1887",
    "Starowolski":"Simon Starovolscius, Monumenta Sarmatarum, viam universae camis ingressorum, Cracoviae 1655",
    "Stryck, Beitrage":"L. v. Stryck, Beitrage zur Geschichte der RittergUter Livlands, L 1, Dorpat 1877; t. II, Dresden 1885",
    "Szczepaniec":"J. Szczepaniec, Mejerowie z Wolda w Wielkim Księstwie Litewskim w XVII i XVIII wieku, „Ze skarbca kultury”, 32,1979",
    "TNT":"Towarzystwo Naukowe w Toruniu",
    "Tr.G.":"Księgi grodzkie trockie w VUB",
    "T.Sang.":"Teki Sanguszków w APK",
    "Tyszkiewicz, Wiadomość":"E. Tyszkiewicz, Wiadomość historyczna o zgromadzeniach i fundacjach męskich i żeńskich rzymsko-katolickich klasztorów w diecezji wileńskiej, „Teka Wileńska”, 1858",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, pod red. A. Gąsiorówskiego, t. I-X",
    "Ungem-Stemberg":"R. v. Ungem-Stemberg, Nachrichten Uberdas Geschlecht der Ungern-Sternberg, Bd. I, Breslau 1875; Bd. II, Abt. 1, Rewal 1872; Bd. II, Abt. 2, Rewal 1875; Nachtrag 1, Dorpat 1911; Nachtrag 2, Dresden 1922; Nachtrag 3, Tartu 1936; Nachtrag 4, Tartu 1939",
    "Ur.":"S. Uruski, A. A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XIX, Warszawa 1907-1935",
    "VL":"Volumina legum, t. I-X, Warszawa 1732 n. (Petersburg 1859)",
    "VUB":"Vilniaus universiteto mokslines bibliotekos rankraSciu skyrius",
    "Wagner":"M. Wagner, Kadra oficerska armii koronnej w drugiej połowie XVII wieku, Toruń 1992",
    "Weyssenhoff":"J. Weyssenhoff, Kronika rodziny Weyssów Weyssenhoffów, Wilno 1935",
    "Wielądek":"W. W. Wielądek, Heraldyka czyli opisanie herbów..., t. 1-3, Warszawa 1792-1798",
    "Wilczyński":"J. K. Wilczyński, Herbarz starodawnej szlachty podług heraldyków polskich z dopełnieniem do czasów obecnych, Paryż bez daty",
    "Wisner, Wojna inflancka":"H. Wisner, Wojna inflancka 1625-1629, „Studia i Materiały do Historii Wojskowości”, t. XVI, cz. 1,1970",
    "Włodarski":"A. Włodarski, Ród Poraitów-Pstrokońskich comesów z Bużenina, Warszawa 1928",
    "Wolff":"J. Wolff, Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "Wolff, Kn.":"J. Wolff, Kniaziowie litewsko-ruscy od końca czternastego wieku. Warszawa 1895",
    "ZbMN":"Zbiór Muzeum Narodowego w AGAD",
    "ZGAE":"„Zeitschrift fur die Geschichte und Altertumskunde Ennlands”",
    "ZHist.":".Zapiski Historyczne” (do t. XX .Zapiski Towarzystwa Naukowego w Toruniu”)",
    "ZHMar.":".Zeitschrift des historischen Vereins fur den Regirungs-Bezirk Marienwerder”",
    "Zielińska, Szlacheccy właściciele":"T. Zielińska, Szlacheccy właściciele nieruchomości w miastach XVIII w., Warszawa 1987",
    "ŹD":"Źródła dziejowe, t. XXIV: Rewizja inflancka 1599 roku, wyd. J. Jakubowski, J. Kordzikowski, Warszawa 1915",
    "ZmKapt.":"Księgi kaptura żmudzkiego w VUB",
    "Żm.G.":"Księgi grodzkie żmudzkie w VUB",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. I-XXXI, Poznań 1879-1908"
}