""" słownik skrótów literatury """

literatura = {
    "Acta Tom.":"Acta Tomiciana, t. 1-17, Poznań 1852-1966",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego Bernardyńskiego we Lwowie..., wyd. O. Pietruski, L. Tatomir, X. Liske, A. Prochaska, W. Hejnosz, t. 1-25, Lwów 1868-1935",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "Akta Aleksandra":"Akta Aleksandra, wyd. F. Papee, Kraków 1927",
    "APKr.":"Archiwum Państwowe Miasta Krakowa i Województwa Krakowskiego w Krakowie",
    "APL":"Archiwum Państwowe w Lublinie",
    "APR":"Archiwum Państwowe w Radomiu",
    "Arch. Bernardynów":"Archiwum Prowincji 00. Bernardynów w Krakowie",
    "Arch. dz. lit.":"Archiwum do dziejów literatury i oświaty w Polsce",
    "Arch. Franciszkanów":"Archiwum klasztoru 00. Franciszkanów w Krakowie",
    "Arch. Lanckorońskich":"Archiwum Lanckorońskich w APKr.",
    "Arch. Norbertanek":"Archiwum klasztoru PP. Norbertanek na Zwierzyńcu w Krakowie",
    "Arch. par. NMP":"Archiwum parafii Najświętszej Marii Panny w Krakowie",
    "Arch. Reformatów, Kronika":"Archiwum klasztoru 00. Reformatów w Krakowie, tzw. Archivum Antiquum",
    "ArchSang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. V, wyd. B. Gorczak, Lwów 1897",
    "Arch. Sanguszków":"Archiwum Sanguszków w APKr.",
    "Arch. Walewskich":"Archiwum Walewskich w APŁódź",
    "Arch. Załuskich":"Archiwum Siedliszowickie Załuskich w APKr.",
    "ASejmKr.":"Akta sejmikowe województwa krakowskiego, wyd. S. Kutrzeba i A. Przyboś, t. 1-5, Kraków-Wrocław-Warszawa 1932-1984",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "BastrzGóry":"A. Bastrzykowski, Monografia historyczna parafii Góry Wysokie Sandomierskie, Sandomierz 1936",
    "BastrzJank":"A. Bastrzykowski, Monografia historyczna parafii Jankowice Kościelne Sandomierskie, Warszawa 1927",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwum Czartoryskich",
    "Bibl. Warsz.":"Biblioteka Warszawska",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. 1-17, Warszawa 1899-1913",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BUAM":"Biblioteka Uniwersytetu im. Adama Mickiewicza w Poznaniu",
    "Buliriski":"M. Buliński, Monografia miasta Sandomierza, Warszawa 1879",
    "CB":"Castrensia Biecensia w APKr.",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CCR":"Castrensia Cracoviensia Relationes w APKr.",
    "Chrapowicki":"J. J. Chrapowicki, Diariusz, cz. 1, lata 1656-1664, oprac. T. Wasilewski, Warszawa 1978",
    "CIP":"Corpus luris Polonici, t. 3-4, wyd. O. Balzer, Kraków 1906-1910",
    "CLD":"Castrensia Lublinensia, Decreta w APL",
    "CLI":"Castrensia Lublinensia, Inscriptiones w APL",
    "CO":"Castrensia Osviencimensia w APKr.",
    "Cochanoviana":"Cochanoviana. Źródła urzędowe do biografii Jana Kochanowskiego, wyd. M. Garbaczowa i W. Urban, Wrocław 1985",
    "Cod. dipl. Vielic.":"Codex diplomaticus Vielicensis, Lwów 1872",
    "Corp. insc.":"Corpus inscriptionum Poloniae, pod red. J. Szymańskiego, t. 1, cz. 1-5, Kielce 1975-1986",
    "CPilz.":"Castrensia Pilznensia w APKr.",
    "CS":"Castrensia Sandecensia w APKr.",
    "DMyszk,":"Dziennik biskupa Piotra Myszkowskiego 1555-1568, wyd. Ł. Kurdybacha, Kwartalnik Historyczny 47, 1933, s. 447-468",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae, t. 1-5, wyd. M. Dogiel, Wilno 1758-1764",
    "DwGen.":"W. Dworzaczek, Genealogia, tablice, Warszawa 1959",
    "DwTarn.":"W. Dworzaczek, Hetman Jan Tarnowski. Z dziejów możnowładztwa małopolskiego, Warszawa 1985",
    "Estreicher":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografia polska, stulecie XV-XVIII, t. 8-9, 12-34, Kraków 1882-1951",
    "Fastnacht":"Katalog dokumentów Biblioteki Zakładu Narodowego im. Ossolińskich, cz. 1-2, wyd. A. Fastnacht, Wrocław 1953, 1973",
    "Grzeliński":"Ks. W. Grzeliński, Monografia Chęcin, Kielce 1908",
    "Gacki":"J. Gacki, O rodzinie Jana Kochanowskiego, o jego majętnościach i fundacjach kilkanaście pism urzędowych, Warszawa 1869",
    "Heidenstein":"R. Heidenstein, Dzieje Polski od śmierci Zygmunta Augusta do r. 1594, wyd. M. Gliszczyński, Petersburg 1857",
    "IT":"Inwentarz tymczasowy w APKr.",
    "Jerlicz":"Latopisiec albo kroniczka Joachima Jerlicza, z rękopisu wydał K. Wł. Wójcicki, t. 1-2, Warszawa 1853",
    "Kalendarzyk":"Kalendarzyk polityczny na rok przybyszowy 1794, Warszawa [1793]",
    "Kaniewska":"I. Kaniewska, Małopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa-Kraków 1974",
    "KatCzart.":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich, cz. 2, Dokumenty z lat 1506-1828, wyd. J. Tomaszewicz, Kraków 1991",
    "KatKórn.":"Katalog rękopisów staropolskich Biblioteki Kórnickiej XVI-XVIII w., t. 2, Wrocław 1985",
    "Kat. zab.":"Katalog zabytków sztuki w Polsce. Seria nowa",
    "Kersten":"A. Kersten, Stefan Czarniecki (1599-1665), Warszawa 1963",
    "Kętrzyński":"Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich, wyd. W. Kętrzyński, t. 1-3, Lwów 1881-1898",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "Kluczycki":"Pisma do wieku i spraw Jana Sobieskiego, zebrał i wydał F. Kluczycki, t. 1-2, Kraków 1880-1881",
    "Komoniecki":"Chronologia albo dziejopis żywiecki... Andrzeja Komonieckiego, wyd. S. Grodziski i I. Dwornićka, Żywiec 1987",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-genealogiczne, t. 1-3, Warszawa 1859-1872",
    "Księga domowa":"Jan Karol Korwin Kochanowski, Księga domowa Leona i Hieronima Kochanowskich (1763-1855), Przegląd Historyczny 20, 1916, s. 175-197, 370-378",
    "LMMC":"Liber mortuorum monasterii Coronoviensis ordinis Cisterdensis, wyd. A. Mańkowski, Toruń 1931, Fontes 25",
    "Lustr. 1660":"Lustracja województwa sandomierskiego 1660-1664, cz. 1-2, wyd. H. Oprawko i K. Szuster, Wrocław 1971-1977",
    "Lustr. 1765":"Lustracja województwa sandomierskiego 1765 r. w AGAD, ASK XVIII/35",
    "Lustr. 1789":"Lustracja województwa sandomierskiego 1789, wyd. H. Madurowicz-Urbańska, cz. 1-4, Wrocław 1965-1971",
    "Mat. do MWS":"Materiały do mapy województwa sandomierskiego w dobie Sejmu Czteroletniego w Pracowni Słownika Historyczno-Gcograficznego Instytutu Historii PAN w Krakowie",
    "Mat. do powstania":"Materiały do powstania Kostki Napierskiego 1651 r., wyd. A. Przyboś, Wrocław 1951",
    "Matwijowski":"K. Matwijowski, Pierwsze sejmy z czasów Jana III Sobieskiego, Wrocław 1976",
    "MBiecza":"Materiały do historii miasta Biecza 1361-1632, wyd. F. Bujak, Kraków 1914",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka tzw. Litewska w AGAD",
    "MPH":"Monumenta Poloniae Historica, t. 5, Warszawa 1888",
    "MRPS":"Matricularum Regni Poloniae summaria, wyd. T. Wierzbowski i in., cz. 1-5, Warszawa 1905-1961",
    "MSambora":"Materiały do dziejów miasta Sambora 1390-1795, wyd. A. Dórflerówna, Lwów 1936",
    "MŻywca":"F. Lenczowski, Materiały do dziejów miasta Żywca od XV do XVIII wieku, Kraków 1957",
    "Nieś.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. 1-10, Lipsk 1839-1846",
    "Orgelbrand":"S. Orgelbranda Encyklopedia powszechna, t. 1-18, Warszawa 1898-1912",
    "Orzelski":"S. Orzelski, Bezkrólewia ksiąg ośmioro 1572-1576, wyd. E. Kunze, Kraków 1917",
    "Ossol.":"Biblioteka Ossolineum we Lwowie",
    "Oświęcim":"S. Oświęcim, Diariusz 1643-1651, wyd. W. Czermak, Kraków 1907",
    "Otfinowski":"Otfinowski (Anonim), Dzieje Polski pod panowaniem Augusta II, 1849",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVI wieku, Warszawa 1962",
    "Pam. rei- mor-":"Pamiętnik Religijno-Moralny",
    "PamZOssol.":"Zbigniew Ossoliński. Pamiętnik, oprać, i wyd. J. Długosz, Warszawa 1983",
    "PANKr.":"Biblioteka PAN w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, wyd. K. J. Turowski, Kraków 1858",
    "Pasek":"J. Ch. Pasek, Pamiętniki, wyd. W. Czapliński, Wrocław 1968",
    "Pasiecznik":"J. Pasiecznik OFN, Kościół i klasztor Franciszkanów-Reformatów w Bieczu, Kraków 1984",
    "Popiel":"P. Popiel, Rodzina Popielów herbu Sulima z przydomkiem Chościak, Kraków 1936",
    "Prawa, przywileje":"Prawa, przywileje i statuta miasta Krakowa (1507-1795), wyd. F. Piekosiński i S. Krzyżanowski, t. 1-2, Kraków 1885-1909",
    "Prochaska":"Materiały archiwalne wyjęte głównie z Metryki Litewskiej",
    "PSB":"Polski słownik biograficzny, t. 1-35, Kraków 1935 n.",
    "Pszonka":"J. Pszonka, Pamiętnik, wyd. A. Bielowski, Lwów 1874",
    "Pułaski":"F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, w: Muzeum Konstantego Świdzińskiego, t. 23-29, Warszawa 1915",
    "Radziwiłł":"Albrycht Stanisław Radziwiłł, Pamiętnik o dziejach w Polsce, przełożyli i opracowali A. Przyboś i R. Żelewski, t. 1-3, Warszawa 1980",
    "Reg. thel.":"Regestra thelonei aquatici Wladislaviensis saeculi XVI, wyd. S. Kutrzeba i F. Duda, Kraków 1915",
    "RejPobRr.":"Rejestr poborowy województwa krakowskiego z roku 1680, oprać. E. Trzyna i S. Żyga pod red. S. Inglota, Wrocław 1959",
    "Rykaczewski":"Inventarium omnium et singulorum privilegiorum..., wyd. E. Rykaczewski, Lutetiae Parisiorum 1862",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego. Diariusz i relacje z lat 1691-1696, wyd. J. Woliński, Wrocław 1959",
    "Seruga":"Dokumenty pergaminowe w zbiorach biblioteczno-muzealnych hr. Tarnowskich w Suchej, wyd. J. Seruga, Kraków 1936",
    "Siarczyński":"Fr. Siarczyński, Opis powiatu radomskiego, wyd. T. Lipiński, Warszawa 1847",
    "Sig-":"Księgi Sigillat Metryki Koronnej w AGAD",
    "SPpp":"Starodawne prawa polskiego pomniki, t. 2 n.",
    "Sprawy wojenne":"Sprawy wojenne króla Stefana Batorego. Diariusze, relacje, listy i akta z lat 1576-1586, wyd. J. Polkowski, Kraków 1887",
    "Starowolski":"S. Starowolski, Monumenta Sarmatarum..., Cracoviae 1655",
    "Straty archiwów":"Straty archiwów i bibliotek warszawskich w zakresie rękopiśmiennych źródeł historycznych, t. 1-3, Warszawa 1955-1957",
    "SuchGrabMon.":"A. Sucheni-Grabowska, Monarchia dwu ostatnich Jagiellonów a ruch egzekucyjny, cz. 1, Wrocław 1974",
    "SygMetr.":"Ks. J. Sygański, Z dawnych metryk kościoła Mariackiego w Krakowie i katedry na Wawelu, Lwów 1911",
    "Święcicki":"Tomasza Święcickiego historyczne pamiątki znamienitych rodzin i osób dawnej Polski, przejrzał w rękopisie, objaśnił i uzupełnił przypisami J. Bartoszewicz, t. 1-2, Warszawa 1856-1859",
    "Taylor":"E. Taylor, Rolicze z Trojanowych Rożyc Różyccy, Poznań 1936",
    "TC":"Terrestria Cracoviensia w APKr.",
    "TCN":"Terrestria Cracoviensia Nova w APKr.",
    "Temberski":"Stanisława Temberskiego roczniki 1647-1656, wyd. W. Czermak, Kraków 1897",
    "TL":"Terrestria Lublinensia w APL",
    "Tomczak":"A. Tomczak, Walenty Dembiński kanclerz egzekucji (ok. 1504-1584), Toruń 1963",
    "TPilz.":"Terrestria Pilznensia w APKr.",
    "Trawicka":"Z. Trawicka, Sejmik województwa sandomierskiego w latach 1572-1696, Kielce 1985",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, t. 1 n., Wrocław-Kórnik 1985 n.",
    "Urban":"W. Urban, Daty życia niektórych osób z XVI w. związanych z Krakowem, Przyczynki źródłowo-biograficzne, w: Biuletyn Biblioteki Jagielloń­skiej 41, 1991, s. 81-99",
    "Uruski":"S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. 1-21, Warszawa 1904-1938",
    "VL":"Volumina legum, t. 1-8, wyd. J. Ohryzko, Petersburg 1860; t. 9, Kraków 1889; t. 10, Poznań 1952",
    "Wadowski":"J. A. Wadowski, Kościoły lubelskie, Kraków 1907",
    "Wielądko":"W. W. Wielądko, Heraldyka czyli opisanie herbów w jakim który jest kształcie..., t. 1-5, Warszawa 1792-1798",
    "Wielewicki":"Ks. Jana Wielewickiego Dziennik spraw domu zakonnego oo. jezuitów u Św. Barbary w Krakowie, w: Scriptores rerum Polonicarum, t. 7, 10, 14, Kraków 1881, 1886, 1889",
    "WierzbMat.":"Materiały do dziejów piśmiennictwa polskiego i biograjii pisarzów polskich, wyd. T. Wierzbowski, t 1-2, Warszawa 1900",
    "Wierzbowski":"S. Wierzbowskiego Konnotata wypadków w domu i kraju zaszłych od 1634 do 1689 r...., wyd. J. K. hr. Załuski, Lipsk 1856",
    "Wiśnlłż.":"Ks. J. Wiśniewski, Dekanat iłżecki, Radom 1909-1911",
    "WiśnJędrz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w Jędrzejowskiem, Marjówka 1930",
    "WiśnKoz.":"Ks. J. Wiśniewski, Monografia dekanatu kozienickiego, Radom 1913",
    "WiśnOpat.":"Ks. J. Wiśniewski, Dekanat opatowski, Radom 1907",
    "WiśnPincz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w Pińczowskiem, Skalbmierskiem i Wiślickiem, Marjówka 1927",
    "WiśnRad.":"Ks. J. Wiśniewski, Dekanat radomski, Radom 1911",
    "WiśnStop.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w Stopnickiem, Maijówka 1929",
    "WiśnWłosz.":"Ks. J. Wiśniewski, Historyczny opis kościołów, miast, zabytków i pamiątek w powiecie włoszczowskiem, Marjówka Opoczyńska 1932",
    "Wittyg":"Nieznana szlachta polska i jej herby, oprać. W* Wittyg przy współudziale St. Dziadulewicza, Kraków 1908",
    "Wyczawski":"Ks. H. E. Wyczawski OFM, Kalwaria Zebrzydowska. Historia klasztoru Bernardynów i kalwaryjskich dróżek, Kalwaria Zebrzydowska 1987",
    "Załuscy, Bibliografia":"Załuscy. Bibliografia odnosząca się do Załuskich z wieku XVII i XVIII, oprać. K. Estreicher, Kraków 1952",
    "Zielińska":"T. Zielińska, Magnateria polska epoki saskiej, Wrocław 1977",
    "Źr. Dz.":"Źródła dziejowe, t. 1-17, Warszawa 1883-1897",
    "Zr. Urz.":"Źródła urzędowe do dziejów rodziny Jana Kochanowskiego, wyd. M. Garbaczowa i W. Urban, Kielce 1984",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. 1-31, Poznań 1879-1908"
}