""" słownik skrótów literatury """

literatura = {
    "Acta Tom.":"Acta Tomiciana, t. I-XVII, Poznań 1852-1966",
    "AD":"Z archiwum miasta Drohobycza. Zbiór przywilejów..., wyd. F. Gątkiewicz, Drohobycz 1906",
    "AGAD":"Archiwum Główne Akt Dawnych, Warszawa",
    "AGAD tzw. ML":"Tzw. Metryka Litewska w AGAD, sygn. IV. B 17",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z Archiwum tzw. Bernardyńskiego we Lwowie, t. I-XIX, wyd. O. Pietruski, X. Liske, A. Prochaska, Lwów 1870-1906",
    "AJZR":"Archiv jugo-zapadnoj Rossii, cz. I-VIII, Kiev 1858-1911",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKP":"Archiwum Krzeszowickie Potockich w APKr.",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności",
    "Akta Aleksandra":"Akta Aleksandra króla polskiego, wielkiego księcia litewskiego(1501-I506), wyd. F. Papee, Kraków 1927",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "Akty powstania":"Akty powstania Kościuszki, t. I-III, opr. S. Askenazy, W. Dzwonkowski, E. Kipa, R. Morcinek, Kraków-Wroclaw 1918-1955",
    "Album stud.":"Album studiosorum Universitatis Cracoviensis, t. V, wyd. K. Lewicki. Kraków 1956",
    "APKr.":"Archiwum Państwowe w Krakowie",
    "APL":"Archiwum Państwowe w Lublinie",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APPn.":"Archiwum Państwowe w Poznaniu",
    "AR":"Archiwum Radziwiłłów w AGAD",
    "Archeografićeskij sbomik":"Archeografićeskij sbomik dokumentov otnosjaśćychsja k istorii sievierozapadnoj Rusy, izd. Vilenskavo UĆelnavo Okruga, t. VII, Vilno 1870",
    "ArchSang.":"Archiwum XX. Lubartowiczów Sanguszków w Sławucie, t. I-VII, wyd. Z. L. Radzimiński, P. Skobielski, B. Gorczak, Lwów 1887-1910",
    "ArchZam.":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, wyd. W. Sobieski, J. Siemieński, t. I-III, Warszawa 1904-1913",
    "AS":"Archiwum Sanguszków w APKr.",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "ASWK":"Akta sejmikowe województwa krakowskiego, wyd. S. Kutrzeba, A. Przyboś, t. I-V, Kraków-Wrocław-Warszawa 1932-1984",
    "AVAK":"Akty izdavaemye Vilenskoju Kommissieju dlja razboradrevnich aktov, 1.1 n., Vilna 1865 n.",
    "AZ":"Archiwum Zamoyskich w AGAD",
    "AZR":"Akty otnosjascyjesja k istorii zapadnoj Rossii sobrannyje i izdannyje Archeografxczeskoju Kommissieju, 1.1 (1340-1506), St. Petersburg 1846",
    "BCzart.":"Biblioteka XX. Czartoryskich w Krakowie",
    "BiałkPod.":"L. Białkowski, Podole w XVI wieku. Rysy społeczne i gospodarcze, Warszawa 1920",
    "BiałkUrz.":"L. Białkowski, Urzędnicy ziemscy podolscy wieku XVI i początku XVII, RTH, t. VIII, 1928, s. 174-180",
    "Bielski":"Joachima Bielskiego dalszy ciąg Kroniki, Warszawa 1851",
    "BJ":"Biblioteka Jagiellońska",
    "BKórn.":"Biblioteka PAN w Kórniku",
    "BN":"Biblioteka Narodowa w Warszawie",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BPANKr.":"Biblioteka PAN w Krakowie",
    "BUANLw.":"Biblioteka Ukraińskiej Akademii Nauk im. W. Stefanyka we Lwowie",
    "CB":"Castrensia Biecensia w APKr.",
    "CBel.":"Castrensia Belsensia w CPHA",
    "CBus.":"Castrensia Buscensia w CPHA",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CCam.":"Castrensia Camenecensia w CDIAU",
    "CCam. Synaj":"Castrensia Camenecensia z klasztoru na Synaju - mikrofilm ze zbiorów AGAD",
    "CChelm.":"Castrensia Chelmensia Relationes, RMO w APL",
    "CCrasn.":"Castrensia Crasnostaviensia w APL",
    "CDIAU":"Centralnyj Derzavnyj Istoryćnyj Archiv Ukrainy w Kijowie",
    "CGrab.":"Castrensia Graboviecensia w APL",
    "CHal.":"Castrensia Halicensia w CPHA",
    "ChłStar.":"K. Chłapowski, Starostowie wMałopolsce 1565-1668, w: Społeczeństwo staropolskie, t. IV, Warszawa 1986, s. 105-178",
    "Chmiel":"Zbiór dokumentów znajdujących się w Bibliotece hr. Przeździeckich w Warszawie, wyd. A. Chmiel, Kraków 1890",
    "CIP":"Corpus iuris Polonici, t. III, IV/1, wyd. O. Balzer, Kraków 1906-1910",
    "CL":"Castrensia Leopoliensia w CPHA",
    "CLanc.":"Castrensia Lanciciensia Oblationes w AGAD",
    "CLat.":"Castrensia Latyczoviensia w CDIAU",
    "CLub.":"Castrensia Lublinensia w APL",
    "CodVit.":"Codex epistolaris Vitoldi magni ducis Lithuaniae 1376-1430, wyd. A. Prochaska, Kraków 1882",
    "Corfus":"I. Corfus, Documente privatoare la istoria Romniei culese din arhivele polone. Secolul al XVI-lea, Bucareti 1979",
    "CPHA":"Centralnyj Derzavnyj Istoryćnyj Archiv we Lwowie",
    "Czamańska, Mołdawia":"I. Czamańska, Mołdawia i Wołoszczyzna wobec Polski, Węgier i Turcji w XIV i XV wieku, Poznań 1996",
    "DanSkarb.":"I. Daniłowicz, Skarbiec dyplomatów papieskich, cesarskich, królewskich..., t. I-II, wyd. J. Sidorowicz, Wilno 1860-1862",
    "Dąbkowski":"P. Dąbkowski, Księgi sądowe lwowskie w dawnej Polsce, Lwów 1937",
    "Diariusze":"Diariusze sejmowe z XVIII w., wyd. W. Konopczyński, t. I-III, Warszawa 1911-1937",
    "DłAnn.":"Joannis Dlugossii Annales seucronicae incliti Regni Poloniae, lib. I-X, Warszawa 1964-1985",
    "DłHist.":"Joannis Dlugossii seu Longini canonici Cracoviensis Historiae Polonicae libriXII, wyd. Ż. Pauli, t. I-V, w tegoż, Operaomnia, t. X-XIV, Kraków 1873-1877",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae, wyd. M. Dogiel, t. I-V, Wilno 1758-1764",
    "DokChmiel.":"Dokumenty Bohdana Chmelnyckoho 1648-1657, wyd. I. Krypjakewicz, I. Buticz, Kijów 1961",
    "Drohojowski":"J. Drohojowski, Kronika Drohojowskich, cz. I-II, Kraków 1904",
    "Dunin-Borkowski":"J. S. Dunin-Borkowski, Genealogia żyjących utytułowanych rodzin polskich, Lwów 1895",
    "DunSwier.":"J. Dunikowski, O rodzie Świerczków na Rusi w wieku XV i początkach rodziny Dunikowskich, MiesHerald. X, 1931, s. 202-210, 217-227",
    "DwGen.":"W. Dworzaczek, Genealogia, Warszawa 1959",
    "DwLel.":"W. Dworzaczek, Leliwici Tarnowscy, Warszawa 1971",
    "Dzieduszycki":"M. Dzieduszycki, Kronika domowa Dzieduszyckich, Lwów 1865",
    "Dziwik":"Katalog dokumentów pergaminowych Biblioteki Polskiej Akademii Nauk w Krakowie, cz. I-III, opr. K. Dziwik, Kraków-Wrocław 1966-1970",
    "Elektorowie":"Elektorowie Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, wyd. J. Dunin-Wąsowicz i M. Dunin-Wąsowicz, RTH, 1 .1, 1910",
    "Epist.":"Codex epistolaris saeculi decimi quinti, t. I-M, wyd. A. Sokołowski, J. Szujski, A. Lewicki, Kraków 1876-1894",
    "Gawęda, Możnowładztwo":"S. Gawęda, Możnowładztwo małopolskie w XIV i w pierwszej połowie XV wieku, Kraków 1966",
    "Gąsiorowski, Gwaranci":"A. Gąsiorowski, Polscy gwaranci traktatów z Krzyżakami XIV-XVwieku, Komunikaty Mazursko-Warmińskie 1971, nr 2-3 (112-113)",
    "Gąsltin.":"A. Gąsiorowski, Itinerarium króla Władysława Jagiełły J386-1434, Warszawa 1972",
    "Gorczak":"B. Gorczak, Katalog pergaminów znajdujących się w Archiwum XX Sanguszków w Sławucie, Sławuta 1912",
    "GórskiOdr.":"K. Górski, Ród Odrowążów w wiekach średnich, RTH, t. VIII, 1927",
    "GórskiPow.":"W. Górski, Powiat mohylewski w guberni podolskiej, Kraków 1903",
    "Grzegorz":"M. Grzegorz, Analiza dyplomatyczno-sfragistyczna dokumentów traktatu torumkiego 1466 r., Toruń 1970",
    "Haisig":"M. Haisig, Sfragistyka szlachecka doby średniowiecznej w świetle archiwów lwowskich, Lwów 1938",
    "Halecki, Dzieje":"O. Halecki, Dzieje unii jagiellońskiej, 1.1, Kraków 1919",
    "Halecki, Ostatnie lata":"O. Halecki, Ostatnie lata Świdrygiełły i sprawa wołyńska za Kazimierza Jagiellończyka, Kraków 1915",
    "HDPol.":"Historia dyplomacji polskiej, t. II, pod red. Z. Wójcika, Warszawa 1982",
    "IJM":"Istoriko-juridiceskije materiały izvleconnyje iz aktowych knig gubernij Vitebskoj i Mogilevskoj, wyd. A. Sazonov, t. I-XXXII, Vitebsk 1871-1906",
    "Imbr.":"Dokumenty klasztoru PP. Norbertanek w Imbramowicach, wyd. Z. Kozłowska-Budkowa, AKH XVI (seria II, t. IV), Kraków 1948",
    "Inv.":"Inventarium omnium et singulorum privilegiorum... in Archivo Regni in arce Cracoviensi continentur, wyd. E. Rykaczewski, Lutetiae Parisiorum 1862",
    "IRBJ":"Inwentarz rękopisów Biblioteki Jagiellońskiej, oprać. A. Jałbrzychowska i inni, Kraków 1962-1982",
    "IRBOW":"Inwentarz rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich we Wrocławiu, oprać, pod red. J. Turskiej, t. I-II, Wrocław 1949-1962",
    "Jerlicz":"J. Jerlicz, Latopisiec albo kroniczka, wyd. K. W. Wójcicki, t. I-II, Warszawa 1853",
    "Kalendarz":"Kalendarz polityczny dla Królestwa Polskiego, Wielkiego Księstwa Litewskiego na rok Pański 1793, Warszawa 1793",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD",
    "Kaniewska":"I. Kaniewska, Małopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa-Kraków 1974",
    "KatArchLvov.":"Katalog pergamentnich dokumentiv Centralnogo Derzavnogo Istorycnogo Archiva URSR u Lvovi 1233-1799, opr. O. A. Kupćinśkij, E. J. Rużićkij, Kiev 1972",
    "KatBCzart.":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, t. I-II, opr. W. Szelińska, J. Tomaszewicz, Kraków 1975-1991",
    "KatKomArch.":"Katalog kolekcii dokumentiv Kytvsko Archeografićnoi Komisii 1369-1899, Kiev 1971",
    "KatKóm.":"Katalog rękopisów staropolskich Biblioteki Kórnickiej, t. I-II, opr. R. Marciniak, M. Muszyński, J. Wiesiołowski, Wrocław 1971-1985",
    "KatOssol.":"Katalog dokumentów Biblioteki Zakładu Narodowego im. Ossolińskich , cz. I-II, opr. A. Fastnacht, Wrocław 1953-1969",
    "KatZab.":"Katalog zabytków sztuki w Polsce",
    "KDM IV":"Kodeks dyplomatyczny Małopolski , t. IV (1386-1450), wyd. F. Piekosiński, Kraków 1905",
    "KDW":"Kodeks dyplomatyczny Wielkopolski , t. I-X, wyd. [I. Zakrzewski] (I-IV), F. Piekosiński (V), A. Gąsiorowski, T. Jasiński, H. Kowalewicz, R. Walczak (VI-X), Poznań 1877-1993",
    "KDWRacz.":"Kodeks dyplomatyczny Wielkiej Polski, wyd. E. Raczyński, Poznań 1840",
    "Kętrzyński":"W. Kętrzyński, Katalog rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich , t. I-III, Lwów 1881-1898",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "Kluczycki":"Pisma do wieku i spraw Jana Sobieskiego, t. I-II, wyd. F. Kluczycki, Kraków 1880-1881",
    "KmK":"Kodeks dyplomatyczny miasta Krakowa, cz. I-II, wyd. F. Piekosiński, Kraków 1879-1882",
    "KMazLub.":"Kodeks dyplomatyczny księstwa mazowieckiego, wyd. J. T. Lubomirski, Warszawa 1863",
    "Kolankowski, Dzieje":"L. Kolankowski, Dzieje Wielkiego Księstwa Litewskiego. Warszawa 1930",
    "Kolankowski, Roty":"L. Kolankowski, Roty koronne na Rusi i Podolu, 1491-1572 , Ziemia Czerwieńska, R. 1, 1935",
    "Konarski":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-genealogiczne , t. I-III, Warszawa 1859-1872",
    "Kriegseisen":"W. Kriegseisen, Samorząd szlachecki w Małopolsce 1669-1717, Warszawa 1989",
    "KRK":"Księgi Referendarii Koronnej z czasów saskich, t. I-II, oprać. M. Woźniakowa, Warszawa 1969-1970",
    "Kromer, Polonia":"Martini Cromeri, Polonia sive de situ, populis, moribus, magistratibus et Republica regni Polonici libri duo 1578, wyd. W. Czermak, Kraków 1901 (Biblioteka Pisarzów Polskich nr 40)",
    "KsLw.":"Księga przychodów i rozchodów miasta Lwowa , wyd. A. Czołowski, t. I-III, Lwów 1898 n.",
    "KwHist.":"Kwartalnik Historyczny",
    "Lewicki, Powstanie Świdrygiełly":"A. Lewicki, Powstanie Świdrygiełły, Kraków 1892",
    "Lrus. 1661":"Lustracja województwa ruskiego 1661-1665, wyd. K. Arłamowski, W. Kaput, E. Arłamowska, t. I-III, Wrocław 1970-1976",
    "Lubieniecki":"A. Lubieniecki, Poloneutychia, Warszawa 1982",
    "LVIA":"Lietuvos Mosklu Akademijos boblioteka w Wilnie",
    "ŁaszczHerb.":"O. Łaszczyńska, RódHerburtów w wiekach średnich, Poznań 1948",
    "MaleczTremb.":"K. Maleczyński. Urzędnicy grodzcy trembowelscy 1403-1783, Ziemia Czerwieńska 2. 1936. s. 302-317",
    "MalcczULw.":"K. Maleczyński, Urzędnicy grodzcy i ziemscy lwowscy u- latach 1352-1783, Lwów 1938",
    "Marczyński":"W. Marczyński. Statystsczne. topograficzne i hisro/yczne opisanie gubemii podolskiej, i. I-1V, Wilno 1820-1823",
    "MatHruś.":"Materiały do istorii suspilno-polityćinch i ekonomićnych vidnosyn zachidnoj Ukrainy, wyd. M. Hrusevskvj.Zapyskv NaukovohoTovarystvaim. Sevcenka 63-64, 1905 fdruk Lviv 1906)",
    "MatSambora":"Materiały do historii miasta Sambora 1390-1795. opr. A. Dórflerówna. Lwów 1936",
    "Matwijowski":"K. Matwijowski. Pierwsze sejmy z czasów Jana Sobieskiego. Wrocław 1976",
    "Michałowski":"J. Michałowski. Księga pamiętnicza.... w yd. A. Z. Helcel. Kraków 1864",
    "MiesHerald.":"Miesięcznik Heraldyczny",
    "MK":"Meiryka Koronna w AGAD",
    "ML":"Metryka Litewska (w Ruskom Gosudarsivennom archive drevnich aktov w Moskwie. Fond 389)",
    "MPH":"Monumenta Poloniae Historica, t. I-VI. Lwów -Kraków 1864-1893",
    "MrozNagr.":"P. Mrozowski, Polskie nagrobki gotyckie. Warszawa 1994",
    "MRPS":"Matricidarum regni Poloniae summaria. 1 . 1-1V, V/l. wyd. T. Wierzbowski. t. V/2 wyd. J. Płocha, A. Rybarski. I. Sulkowska-Kurasiowa. Warszawa 1905-1919. 1961",
    "Myszkowski":"Dziennik biskupa Piotra Myszkowskiego 1555-1568. wvd. Ł. Kurdybacha. KwHist. 47. 1933 s. 447-468",
    "NGAB":"Nacjanalnyj archiu Belarusi w Mińsku",
    "Nieś.":"K. Niesiecki. Herbarz polski, t. I-X. wyd. J. N. Bobrowicz. Lipsk 1839-1846",
    "Okolski":"S. Okolski. Orbis Polonis, t. I-III. Cracoviae 1641",
    "P.":"K. Przyboś. Urzędnicy województwa podolskiego XV-XVII wieku. Spisy. Kraków 1994",
    "Pamiatniki":"Pamiatniki diplomaticeskich snoŚenij moskorskavo gosudarstva s polsko-litovskim. T. 1(1488-1533), wwd. Karpov. Sbornikimperialnoj russkoj istorii, obść. t. XXXV, Petersburg 1882",
    "Pamiętniki o Koniecpolskich":"Pamiętniki o Koniecpolskich, wyd. S. Przylęcki. Lwów 1842",
    "Paprocki":"B. Paprocki. Herby lycerstwapolskiego, wyd. K. J. Turowski. Kraków 1858",
    "Pasek":"J. Ch. Pasek. Pamiętniki, wyd. W. Czapliński, Wrocław 1979",
    "Pasiecznik":"J. Pasiecznik OFN. Kościół i klasztor Franciszkanów-Reformatów w Bieczu. Kraków 1984",
    "PlewczŻołn.":"M. Plewczyński. Żołnierz jazdy obronx potocznej zci panowania Zygmunta Augusta. Studia nad zawodem wojskowym w XVI w.. Warszawa 1985",
    "Pohorecki":"Catalogus diplomatum Bibliothecae Instituti Ossoliniani nec non Bibliothecae Pavlikovianae inde ab anno 1227 usque ad annum 1505. opr. F. Pohorecki. Lwów 1932",
    "Prochaska. Mat.":"Materiały archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 r.. wyd. A. Prochaska. Lwów 1890",
    "Prochaska. Podole":"A. Prochaska, Podole lennem Korony , RAUhf 32. 1895",
    "Prochaska, Sejmik":"A. Prochaska. Sejmik podolski in hostico. Przewodnik Naukowy i Literacki. 48. 1920. s. 804-822",
    "Przyboś. Archiwum":"A. Przyboś. Inwentarz archiwum skazinieckiego... Markowskich. Rocznik Podolski, t. I, 1938",
    "PSB":"Polski słownik biograficzny",
    "PSRL":"Polnoje Sobranije Russkich Letopisej",
    "PułKron.":"K. Pułaski. Kronika polskich rodów szlacheckich Podola. Worinia i Ukrainy, t. I-II. Brody 1911. Warszawa 1991",
    "PułOpis":"Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, opr. F. Pułaski. Warszawa 1915",
    "PułOsady":"K. Pułaski. Stare osady w ziemi kamienieckiej i dziedziczące na nich rody podolskiej szlachy historycznej. Przewodnik Naukowy i Literacki 30. 1902",
    "PułSzkice":"K. Pułaski, Szkice i poszukiwania history czne, seria 1-IV. Kraków-Petersburg-Lwów 1887-1909 (zwłaszcza seria III. Kraków 1906)",
    "Radziwiłł":"A. S. Radziwiłł. Memoriale rerum gestarum in Polonia, t. I-IV. Wrocław 1968-1974",
    "RAUhf":"Rozprawy (Polskiej) Akademii Umiejętności. Wydział Historvczno-Fiiozoficzny",
    "Rembowski":"A. Rembowski, Konfederacja i rokosz , Warszawa 1S96",
    "RolleSylwetki":"J. A. Rolle. Sylwetki historyczne, seria I-IX. Kraków-Lwów 1875-1893",
    "RolleWybór":"J. A. Rolle, Wybór pism. t. II-III. Kraków 1966",
    "RolleZam.":"J. A. Rolle. Zameczki podolskie na kresach maltańskich, t. I-III. Kraków-Warszawa 1872-1881",
    "RolleZdrada":"J. A. Rolle. Zdrada kamieniecka, w: Opowiadania historyczne. ser. I. Lwów 1891",
    "Rozbiór":"Rozbiór krytyczny Annalium Poloniae Jana Długosza z lat 1385-1480. t. I-II. red. J. Dąbrowski. Wrocław 1961-1965",
    "Rozov":"Ukrain'ski i>rarnoti. . 1. wvd. V. Rozov. Kiev 1928",
    "RTH":"Rocznik (Polskiego) Towarzystwa Heraldycznego we Lwowie",
    "Rynduch":"Z. Rynduch. Andrzej Maksymilian Fredro. Gdańsk 1980",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego. Diariusze i relacje z lat 1691-1696. wyd. J. Woliński, Wrocław 1958",
    "SemkAwd.":"W. Semkowicz. Ród Awdańców w wiekach średnich , Poznań 1920",
    "SemkBojar.":"W. Semkowicz,, O litewskich rodach bojarskich zbratanych ze szlachtą polską w Horodle roku 1413 , Lithuano-Slavica Posnaniensia III, 1989, s. 7-139.",
    "SHGKr.":"Słownik historyczno-geograficzny województwa krakowskiego w średniowieczu, cz. I-III, Wroclaw-Kraków 1980-1994",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "SMHW":"Studia i Materiały do Historii Wojskowości",
    "Sobieski":"J. Sobieski, Listy do Marysieńki, wyd. L. Kukulski, t. I-II, Warszawa 1962",
    "Sozański":"A. Sozański, Imienne spisy osób, które w pierwszych ośmiu łatach panowania Stanisława Augusta w rządzie/.. / udział brały, Kraków 1866",
    "SpierOb.":"Z. Spieralski, Kampania obertyńska 1531 roku, Warszawa 1962",
    "SPPP":"Starodawne prawa polskiego pomniki, 1 .11. VIII, Kraków 1870-1884",
    "SRP":"Scriptores Rerum Polonicarum, t. I-XXII, Kraków 1872-1917",
    "SSNO":"Słownik staropolskich nazw osobowych",
    "StadRod.":"K. Stadnicki, Rodowody domu Stadnickich 1386-1861, Lwów 1857-1861",
    "StadWspomn.":"K. Stadnicki, Wspomnienie o Abdankach-Konopkach Buczackich i Jazłowieckich, Przewodnik Naukowy i Literacki 1, 1873, s. 145-159",
    "StadZLw.":"A. Stadnicki. Ziemia lwowska za rządów polskich w XIV i XV wieku we względzie społecznych stosunków rozpoznana. Biblioteka Naukowego Zakładu imienia Ossolińskich, t. III. 1863, s. 1-103",
    "Starowolski":"Simon Starovolscius, Monumenta Sarmatarum viam universae carnis ingressorum, Cracoviae 1655",
    "Stryjkowski":"M. Stryjkowski, O początkach, wywodach, dzielnościach, sprawach rycerskich i domowych sławnego narodu litewskiego..., oprać. J. Radziszewska, Warszawa 1978",
    "Swięcki":"T. Swięcki, Historyczne pamiątki znamienitych rodzin i osób dawnej Polski , wyd. J. Bartoszewicz, t. II. Warszawa 1859",
    "TB":"Terrestria Biecensia w APKr.",
    "TC":"Terrestria Cracoviensia w APKr.",
    "TCam.":"Terrestria Camenecensia w CDIAU w Kijowie",
    "Teki Nar.":"Teki Naruszewicza w BCzart.",
    "Teut.":"Teutonicalia. Akta Sądu Wyższego Prawa Magdeburskiego na zamku krakowskim w APKr.",
    "TGJP":"Teki Gabriela Junoszy Podoskiego, wyd. K. Jarochowski, t. I-V, Poznań 1854-1856",
    "TLeopol.":"Terrestria Leopoliensia w CPHA",
    "TPaw.":"Teki Adolfa Pawińskiego, t. I-VII, Warszawa 1897-1905",
    "TPilsn.":"Terrestria Pilsnensia w APKr.",
    "Trajdos, Kościół":"T. M. Trajdos, Kościół katolicki na ziemiach ruskich Korony i Litwy zapanowania Władysławall Jagiełły (1386-I434),t.l, Wrocław-Warszawa 1983",
    "U":"Urzędnicy dawnej Rzeczpospolitej XII-XVIII wieku. Spisy, red. A. Gąsiorowski, t. I-XI, Wrocław, Kórnik 1985-1994",
    "Uljanicki":"V. A. Uljanicki, Materiały dlja istorii vzaimnych otnośenij Rossii, Polśi, Moldavii, Valachii i Turcii v XIV-XVI st ., Moskva 1887",
    "Ur.":"S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XXI, Warszawa 1904-1938",
    "Vitoldiana":"Vitoldiana. Codex privilegiorum Vitoldi magni ducis Lithuaniae 1386-1430 , wyd. J. Ochmański, Warszawa-Poznań 1986",
    "VL":"Volumina legum, wyd. J. Ohryzko i Z. Kaczmarczyk, t. I-X, St. Petersburg 1859-Poznań 1952",
    "VUB":"Vilniaus universiteto moksline biblioteka",
    "WdowBog.":"Z. Wdowiszewski, Ród Bogoriów w wiekach średnich, RTH 9. 1928-1929 (druk 1930), s. 1-95",
    "Weise":"Die Staatsvertrdge des Deutschen Ordens in Preussen im 15. Jahrhundert, t. I-III. wyd. E. Weise, Kónigsberg 1939 - Marburg 1966",
    "Wielądko":"W. W. Wielądko, Heraldyka, czyli opisanie herbów w jakim który jest kształcie..., t. I-V, Warszawa 1792-1798",
    "WimmerMat.":"J. Wimmer, Materiał}' do zagadnienia liczebności armii koronnej w /. 1600-1667, SMHW t. VI, cz. 2",
    "Wittyg":"Nieznana szlachta polska i jej herby, opr. W. Wittyg, S. Dziadulewicz, Kraków 1908",
    "Witusik":"A. A. Witusik, Młodość Tomasza Zamoyskiego, Lublin 1977",
    "Wolff":"3. Wolff, Kniaziowie litewsko-ruscy od końca czternastego wieku, Warszawa 1895",
    "Z korespondencji Kościuszki":"Z korespondencji Kościuszki urzędowej i prywatnej 1790-1817, wyd. A. M. Skalkowski, Kórnik 1939",
    "Załuski":"A. Ch. Załuski, Epistolarum historico-familiarum, t. III, Brunsbergae 1711",
    "ZbPin.":"Zbiór Pinoccich w APKr.",
    "ZbRus.":"Zbiór Rusieckich w APKr.",
    "ZDK":"Zbiór dokumentów katedry i diecezji krakowskiej, t. I-II, wyd. S. Kuraś, Lublin 1965-1973",
    "ZDM":"Zbiór dokumentów małopolskich, t. I-VIII, wyd. I. Sułkowska-Kuraś, S. Kuraś, Kraków-Wrocław 1962-1975",
    "ŹDz.":"Źródła dziejowe, t. I-XIX, Warszawa 1876-1910",
    "Źrzódła":"Źrzódła do dziejów polskich, wyd. M. Grabowski, A. Przeździecki, t. I, Wilno 1843",
    "Źychliński":"T. Żychliński, Złota księga szlachty' polskiej, t. I-XXXI, Poznań 1879-1908"
}