""" słownik skrótów literatury """

literatura = {
    "Abiurata nowogr.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo nowogródzkie 1690 r., red. A. Rachuba, oprac. H. Lulewicz, A. Rachuba, Warszawa 2002",
    "Abiurata poł.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo połockie 1667 i 1690 r., red. A. Rachuba, oprac. H. Lulewicz, A. Rachuba, Warszawa 2018",
    "Abiurata żm.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Księstwo Żmudzkie 1690 r., oprac. G. Błaszczyk, Warszawa 2009",
    "Acta primae visitationis":"Acta primae visitationis dioecesis Vilnensis anno Domini 1522 peractae. Vilniaus Kapitulos Archyvo Liber IIb atkūrimas, sudarė S.C. Rowell, Vilnius 2015",
    "AD":"Awtografy Dubrowskiego (F. 971) w RNB",
    "ADSap.":"Archiwum Domu Sapiehów wydane staraniem rodziny, t. 1, Listy z lat 1575–1606, wyd. A. Prochaska, Lwów 1892",
    "ADSiedlce":"Archiwum Diecezjalne w Siedlcach",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "Akademijos laurai":"Akademijos laurai, wyd. M. Svirskas, I. Balčienė, Vilnius 1996",
    "AKP":"Archiwum Królestwa Polskiego w AGAD",
    "Akta SKow.":"Akta sejmiku kowieńskiego z lat 1733–1795, wyd. M. Jusupowić, Warszawa 2019",
    "Akta Unji":"Akta Unji Polski z Litwą 1385–1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "Akta zjazdów I":"Akta zjazdów stanów Wielkiego Księstwa Litewskiego, t. I: Okresy bezkrólewi (1572–1576, 1586–1587, 1632, 1648, 1696–1697, 1706–1709, 1733–1765, 1763–1764), oprac. H. Lulewicz, Warszawa 2006",
    "Akta zjazdów II":"Akta zjazdów stanów Wielkiego Księstwa Litewskiego, t. II: Okresy panowań królów elekcyjnych XVI–XVII wiek, oprac. H. Lulewicz, Warszawa 2009",
    "Akty LRG":"Акты Литовско-Русского государства, t. 1–2, wyd. М.В. Довнар-Запольский, Москва 1899–1900",
    "Akty ZR":"Акты, относящиеся к истории Западной России, собранные и изданные Археографическою комиссиею, t. I: 1340–1506, Санкт Петербург 1846; t. II: 1506–1544, 1848; t. III: 1544–1587, 1848; t. IV: 1588–1632, 1851; t. V: 1633–1699, 1853",
    "ALM":"Акты Литовкой Метрики собр. Ф.И. Леонтовичем, t. 1, cz. 1–2, Варшава 1896–1897",
    "Almanach błękitny":"J. Dunin-Borkowski, Almanach błękitny. Genealogia żyjących rodów polskich, Lwów [1908]",
    "AMCh":"Archiwum Młynowskie Chodkiewiczów w ANKr., Oddział na Wawelu",
    "ANKr.":"Archiwum Narodowe w Krakowie",
    "AP":"Archiwum Państwowe",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APR":"Archiwum Potockich z Radzynia w AGAD",
    "AR":"Archiwum Radziwiłłów w AGAD",
    "Archiw JZR":"Архив Юго-западной России, издаваемый Временною комиссиею для разбора древних актов высoчaйшe утвержденною при Киевском военном, Подольском и Волынском ген. Губернаторе, cz. VI, t. 1, Киев 1876",
    "ASang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. 1–7, Lwów 1887–1910",
    "ASD":"Археографический сборник документов, относящихся к истории Северо-Западной Руси, t. I–XIV, Вильна 1867–1904",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "Augustyniak":"U. Augustyniak, Testamenty ewangelików reformowanych w Wielkim Księstwie Litewskim w XVI–XVIII wieku, Warszawa 2014",
    "AWAK":"Акты, издаваемые Виленскою археографическою комиссиею, t. I–XXXIX, Вильна 1865–1915",
    "AZ":"Archiwum Zamoyskich w AGAD",
    "AZR":"Акты относящиеся къ истории Западной России, собранные и изданные Архeографическою комиссиею, t. I–V, C.-Петербург 1848–1863",
    "Bartoszewicz, Kropińscy":"J. Bartoszewicz, Kropińscy. Obrazki sejmikowego życia w czasach saskich, w: Dzieła Juljana Bartoszewicza, t. VII: Szkice z czasów saskich, Kraków 1880",
    "Bartoszewiczów":"Archiwum rodziny Bartoszewiczów w AP w Łodzi",
    "Barwinskij":"Б. Барвінський, Жигимонт Кейстутович, великий князь литовсько-руський (1432–1440), Жовква 1905",
    "Biełaruskaja Daunina":"Беларуская даўніна. Studia et fontes, t. 3, ред . Ю.М. Мікульскі, Мінск 2016",
    "Biełorussja w epochu fi eodalizma":"Белоруссия в эпоху феодализма. Сборник документов и материалов, t. II: С середины XVII до конца XVIII века, до воссоединения с Россией, Минск 1960",
    "Bienziaruk":"А. Бензярук, Касцюшкі-Сяхновіцкія. Гісторыя старадаўняга роду, Брэст 2006",
    "Biłka Szlachecka":"AGAD, Księgi metrykalne parafi i wyznania rzymskokatolickiego z archidiecezji lwowskiej, 1604–1945. Parafi a Biłka Szlachecka, dekanat Lwów; Księga metrykalna ślubów dla całej parafi i",
    "BN":"Biblioteka Narodowa w Warszawie",
    "BNANB":"Бибиотека Нацыянальная акадэмія навук Беларусі w Mińsku",
    "Bon.":"A. Boniecki, Herbarz polski, t. I–XVI, Warszawa 1899–1913",
    "BonPoczet":"A. Boniecki, Poczet rodów w Wielkim Księstwie Litewskim w XV i XVI wieku, Warszawa 1887",
    "BonU.":"A. Boniecki, Herbarz polski. Uzupełnienia i sprostowania do Części I, Warszawa 1901",
    "Borkowski":"J.S. Dunin-Borkowski, Genealogie żyjących utytułowanych rodów polskich, Lwów 1895",
    "Bosiacka":"A. Bosiacka, Leśniańska Księga Cudów 1683–1768, „Barok. Historia-Literatura-Sztuka”, XIII/1 (25), 2006, s. 207–236",
    "BOZ":"Biblioteka Ordynacji Zamojskiej w BN",
    "BPW":"Biblioteka Publiczna m.st. Warszawy, Biblioteka Główna Województwa Mazowieckiego",
    "BUW":"Biblioteka Uniwersytecka w Warszawie",
    "CDIAUK":"Центральний державний історичний архів України w Kijowie",
    "CDIAULw.":"Центральний державний історичний архів України we Lwowie",
    "Chrapowicki II":"J.A. Chrapowicki, Diariusz, cz. II, oprac. A. Rachuba, T. Wasilewski, Warszawa 1988",
    "Ciechanowicz":"J. Ciechanowicz, Rody rycerskie Wielkiego Księstwa Litewskiego, t. I–V, Rzeszów 2001",
    "Citou, Piaczatki":"A. Цітоў, Пячаткі старажытнай Беларусі. Нарысы сфрагістыкі, Мінск 1993",
    "Czamańska":"I. Czamańska, Wiśniowieccy. Monografi a rodu, Poznań 2007",
    "Czart.":"Biblioteka Książąt Czartoryskich w Krakowie",
    "Czołow.":"Zbiór Aleksandra Czołowskiego w AGAD",
    "Czwojdrak":"B. Czwojdrak, Rogowscy herbu Działosza podskarbiowie królewscy, Katowice 2002",
    "Daneykowicz":"Swada polska i łacińska albo Miscellanea Oratorskie, Seymowe, Weselne, Kancellaryjne, Listowne, Kaznodziejskie, Pogrzebowe, Statystyczne, Panegiryczne, Inskrypcyjne, y inne różne, w oboim języku Prozą y Wierszem…, t. 1, Lublin 1745",
    "Daniłowicz":"Skarbiec diplomatów papieskich, cesarskich, królewskich, zebr. I. Daniłowicz, t. I–II, Wilno 1860–1862",
    "Deputacja wołyńska":"Державний Архів Житомирської Області, F. 146 D. 430 (Postanowienie Zgromadzenia Szlacheckiego Wołyńskiej Deputacji Wywodowej z 16 XII 1825 r.)",
    "Diariusze sejmowe":"Diariusze sejmowe z wieku XVIII, t. III, wyd. W. Konopczyński, Warszawa 1937",
    "DKJKP":"Dziennik Konfederacyi Jeneralney Królestwa Polskiego",
    "Dla lepszoje twierdosti":"„Для лепшое твердості…”. Пергаментныя дакументы перыяду Вялікага Княства Літоўскага з фондаў Нацыяналнага гістарычнага архіва Беларусі (1391–1566 гг.), укл. Я.С. Глінскі, А.А. Жлутка. Д.В. Лісейчікаў, Мінск 2018",
    "Długosz, Annales":"Ioannis Dlugossii Annales seu Cronicae incliti Regni Poloniae. Liber 10, 1370–1405, Varsaviae 1985; Liber 11 et 12, 1431–1444, Varsavie 2001; Liber 12, 1445–1461, Varsaviae 2003",
    "Dok. pap.":"Dokumenty papierowe",
    "Dok. perg.":"Dokumenty pergaminowe",
    "Dubiński":"P. Dubiński, Zbiór praw i przywilejów miastu stołecznemu Wilnowi nadanych, Wilno 1788",
    "Dworzaczek":"W. Dworzaczek, Genealogia. Tablice, Warszawa 1959",
    "Elekt.":"J. Dunin-Borkowski, M. Dunin-Wąsowicz, Elektorowie królów Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, Lwów 1910; O. Pietruski, Elektorów poczet, którzy niegdyś głosowali na elektorów Jana Kazimierza roku 1648, Jana III roku 1674, Augusta II roku 1697 i Stanisława Augusta roku 1764, Lwów 1845",
    "Estr.":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografi a polska, stulecie XV–XVIII, t. I–XXXIX, Kraków 1870–1952",
    "Extranea":"Riksarkivet, Stockholm: Extranea 75. IX Polen, mikrofilmy w AGAD",
    "Faszczów":"Archiwum Faszczów w AGAD",
    "FHPL I":"Fontes Historiae Parlamentorum Lituanicorum, t. I, Lietuvos Didžiosios Kunigaikštystės seimelių instrukcijos 1788–1790, parengė R. Jurgaitis, A. Stankevič, A. Verbickienė, Vilnius 2015",
    "Filipczak":"W. Filipczak, Polityczna rola Elżbiety z Branickich Sapieżyny w latach 1783–1784, w: Wielkie rody dawnej Rzeczypospolitej XVI–XIX wieku, t. 1: Sapiehowie, red. T. Ciesielski, M. Sawicki, Opole 2018, s. 203–227",
    "Ganczarenka":"С.А. Ганчарэнка, „Апошні шлях” сенатара Вялікага Княства Літоў скага: да праблемы даты і месца смерці і пахавання кашталяна віленскага і вялікага канцлера Астафея Валовіча, „Архіварыус”, Вып. 14, Мінск 2016, s. 220–228",
    "Gawrysiakowa, Litak":"J. Gawrysiakowa, S. Litak, Spis ludności parafi i zabrzeskiej obrządku łacińskiego na Białorusi z 1768 roku, „Przegląd Demografi czny Polski. Materiały i Studia”, t. XXI, 2000, s. 87–134",
    "GazWarsz.":"„Gazeta Warszawska”",
    "GazWil.":"„Gazety Wileńskie”",
    "GBS":"Гербоўнік беларускай шляхты, t. I–V, Мінск 2002–2017",
    "GDGAM":"Гродзенскі дзяржаўны гісторыка-археалагічны музей",
    "Genealogia Imienia Pociejów":"Genealogia imienia Pociejów, „Przegląd Poznański”, t. XXX, 1860, s. 210–228",
    "Genealogia Ordów":"Genealogia Ordów herbu Orda, Materiały Romana Aftanazego, Oss., akc. 9/04/1",
    "GIBM":"Государственная публичная историческая библиотека России w Moskwie",
    "Gmiterek":"H. Gmiterek, Protokół komisji granicznej polsko-litewskiej z 1623 roku, „Res Historica”, t. 21, 2005, s. 115–133",
    "GNO":"„Gazeta Narodowa i Obca”",
    "Gordziejew":"J. Gordziejew, Komisje Porządkowe Cywilno-Wojskowe w Wielkim Księstwie Litewskim w okresie Sejmu Czteroletniego (1789–1792), Kraków 2010",
    "GP":"„Gazety Polskie”",
    "GStAPK":"Geheimes Staatsarchiv Preussischer Kulturbesitz w Berlinie",
    "Halecki":"O. Halecki, Ostatnie lata Świdrygiełły i sprawa wołyńska za Kazimierza Jagiellończyka, Kraków 1915",
    "Hedemann":"O. Hedemann, Dzieje puszczy białowieskiej w Polsce przedrozbiorowej (w okresie do 1798 roku), Warszawa 1939",
    "HHSAWien":"Haus-, Hof- und Staatsarchiv w Wiedniu",
    "Horoszkiewicz":"R. Horoszkiewicz, Spis rodów szlachty zaściankowej ziemi pińskiej, Warszawa 1937",
    "IGAW":"Indeks geografi czny Archiwum Wileńskiego w LVIA",
    "IJM":"Историко-юридическiе матерiалы, извлеченные изъ актовыхъ книг губернiи Витебской и Могилевской, t. I–XXXII, изд. A.M. Созонов, Н. Мещерски, М. Веровкин, Д.И. Довгялло, Витебск 1871–1906",
    "Imago Lithuaniae":"IMAGO LITHUANIAE. Lietuvos Didžiosios Kunigaikštystes žemelapiai ir dokumentai iš Tomaszo Niewodniczańskio rinkinių. IMAGO LITHUANIAE. Mapy i dokumenty Wielkiego Księstwa Litewskiego ze zbiorów Tomasza Niewodniczańskiego. IMAGO LITHUANIAE. Maps and documents of the Grand Duchy of Lithuania from the collections of Tomasz Niewodniczański, oprac. K. Kozica, J. Pezda, Vilnius 2003",
    "IRI RAN":"Научно-исторический архив Санкт-Петербургского института истории РАН, Русская секция архива",
    "Jabłonowski":"J.S. Jabłonowski, Dziennik, wyd. W. Chomętowski, Warszawa 1865",
    "Jag.":"Biblioteka Jagiellońska w Krakowie",
    "Jakowienko":"Н.М. Яковенко, Українська шляхта з кiнця XIV до середини XVII ст. (Волинь i Центральна Україна), Київ 1993 (wyd. 1), Київ 2008 (wyd. 2)",
    "Janczyński":"R. Janczyński, Erectia Planetow Tyszkiewiczowskich, albo krótkie kazanie na pogrzebie - miane roku 1631 die 4 Novembris, Lublin 1637",
    "Jasnowski":"J. Jasnowski, Mikołaj Czarny Radziwiłł (1515–1565). Kanclerz i marszałek ziemski Wielkiego Księstwa Litewskiego, Warszawa 1939, Rozprawy Historyczne Towarzystwa Naukowego Warszawskiego, t. 22 (reprint - Oświęcim 2014)",
    "Jaszczołt":"T. Jaszczołt, Materiały genealogiczne szlachty parafi i Huszlew z lat 1672–1797, w: Studia Genealogiczne. Poświęcone pamięci profesora Włodzimierza Dworzaczka, t. III, red. A. Sikorski, T. Sławiński, Warszawa 2019, s. 343–540",
    "Jewłaszewski":"„Гістарычныя запіскі” Ф. Еўлашоўскага, уклаў. У.М. Свяжынскі, Мінск 1990",
    "JfG":"„Jahrbuch für Genealogie, Heraldik und Sphragistik”, Jb. 1893–1914, Mitau 1894–1930",
    "Kal. Polit.":"Kalendarz (Kalendarzyk) Polityczny",
    "Kal. Poł.":"Kalendarz Połocki Societatis Jesu",
    "Kal. Wil.":"Kalendarz Wileński",
    "Kamer.":"Archiwum Kameralne w AGAD",
    "Kamieniecki":"W. Kamieniecki, Chorążowie w parlamentaryźmie litewskim przed unią lubelską, „Antemurale”, t. IX, Romae 1965, s. 165–203",
    "Kaniewska":"Listy króla Zygmunta Augusta do Radziwiłłów, oprac. I. Kaniewska, Kraków 1999",
    "Kapicjana":"Zbiór Ignacego Kapicy Milewskiego: Kapicjana, 1430–1804 w AGAD",
    "Katalog dok. perg. MNKr.":"Katalog dokumentów pergaminowych Muzeum Narodowego w Krakowie, oprac. J. Tomaszewicz, Kraków 1992",
    "Katalog dokumentów i listów":"Katalog dokumentów i listów królów polskich z Archiwum Państwowego w Gdańsku (do 1492 roku), oprac. M. Grulkowski, B. Możejko, S. Szybkowski, Gdańsk 2014",
    "KDKW":"Kodeks dyplomatyczny katedry i diecezji wileńskiej, t. I, wyd. J. Fijałek, W. Semkowicz, Kraków 1932–1948",
    "KDOss.":"Katalog dokumentów Biblioteki Zakładu Narodowego im. Ossolińskich, cz. I, Dokumenty z lat 1507–1700, oprac. A. Fastnacht, Wrocław 1953",
    "KDPCz. II":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, cz. II, Dokumenty z lat 1506–1828, oprac. J. Tomaszewicz, Kraków 1991.",
    "KL":"„Kuryer Litewski”",
    "Kodeks Małopolski":"Kodeks dyplomatyczny Małopolski, t. IV, 1383–1450, wyd. F. Piekosiński, Kraków 1905",
    "KojałComp.":"W. Wijuk Kojałowicz, Herbarz rycerstwa W.X.Litewskiego tak zwany Compendium, wyd. F. Piekosiński, Kraków 1897",
    "Kol. Warsz.":"Kolęda Warszawska (na kolejne lata)",
    "Komier.":"Archiwum Komierowskich w AGAD",
    "Konarski, Platerowie":"S. Konarski, Platerowie, „Materiały do Biografi i, Genealogii i Heraldyki Polskiej”, t. IV, 1967",
    "Konarski, Szlachta":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Konieczna":"D. Konieczna, Ustrój i funkcjonowanie sejmiku brzeskolitewskiego w latach 1565–1763, Warszawa 2013",
    "Korczak":"L. Korczak, Monarcha i poddani. System władzy w Wielkim Księstwie Litewskim w okresie wczesnojagiellońskim, Kraków 2008",
    "Korzon, Kościuszko":"T. Korzon, Kościuszko. Biografi a z dokumentów wysnuta przez K. poprzedzona rzutem oka na dzieje Muzeum Narodowego w Rapperswylu i Katalogiem zbiorów Kościuszkowskich, w temże Muzeum przechowywanych, Kraków–Muzeum Narodowe w Rapperswylu 1894",
    "Kossakowski":"S.K. Kossakowski, Monografi e historyczno-genealogiczne niektórych rodzin polskich, t. I–III, Warszawa 1859",
    "Kościałkowski, Tyzenhauz":"S. Kościałkowski, Antoni Tyzenhauz podskarbi nadworny litewski, t. I–II, Londyn 1970–1971",
    "Kórnik":"Biblioteka Kórnicka Polskiej Akademii Nauk w Kórniku",
    "KP":"„Kuryer Polski”",
    "Kronika Bychowca":"Хроника Быховца, издал H.H. Улащик, Москва 1966",
    "Krupowicz":"M. Krupowicz, Zbiór dyplomatów rządowych i aktów prywatnych posługujących do rozjaśniania dziejów Litwy i złączonych z nią krajów (od 1387 do 1710, Wilno 1858",
    "Krzyżanowski":"A. Krzyżanowski, Pogląd na powołanie, dzieje i sprawy Zakonu Trynitarzy w Polsce, „Pamiętnik Religijno-Moralny”, t. 20, 1851, s. 381–516",
    "Księga radziecka":"Księga radziecka miasta Starej Warszawy, t. I, 1447–1527, wyd. A. Wolﬀ , Wrocław–Warszawa–Kraków 1963",
    "Księgi ławnicze":"Księgi ławnicze Starej Warszawy z lat 1453–1535, red. A. Bartoszewicz, Warszawa 2020",
    "Księgi wójtowsko-ławnicze":"Księgi wójtowsko-ławnicze miasta Lublina z XV wieku, oprac. G. Jawor, M. Kołacz-Chmiel, A. Sochacka, Lublin 2012",
    "Lietuvos invent. XVII a.":"Lietuvos inventoriai XVII a. Dokumentų rinkinys, Sudarė K. Jablonskis ir M. Jučas, Vilnius 1962",
    "LM 1":"Lietuvos Metrika. Knyga nr 1 (1380–1584), Užrašymų knyga 1, par. A. Baliulis, R. Firkovičius, Vilnius 1998",
    "LM 3":"Lietuvos Metrika. Knyga nr 3 (1440–1498), Užrašymų knyga 3, par. L. Anužytė, A. Baliulis, Vilnius 1998",
    "LM 4":"Lietuvos Metrika. Knyga nr 4 (1479–1491), Užrašymų knyga 4, par. L. Anužytė, Vilnius 2004",
    "LM 5":"Lietuvos Metrika. Knyga nr 5 (1427–1506), par. A. Baliulis, A. Dubonis, D. Antanavičius, Vilnius 2012",
    "LM 6":"Lietuvos Metrika. Knyga nr 6 (1494–1506), Užrašymų knyga 6, par. A. Baliulis, Vilnius 2007",
    "LM 7":"Lietuvos Metrika. Knyga nr 7 (1506–1539), Užrašymų knyga 7, par. I. Ilarienė, L. Karalius, D. Antanavičius, Vilnius 2011",
    "LM 8":"Lietuvos Metrika. Knyga nr 8 (1499–1514), Užrašymų knyga 8, par. A. Baliulis, R. Firkovičius, D. Antanavičius, Vilnius 1995",
    "LM 9":"Lietuvos Metrika. Knyga nr 9 (1511–1518), Užrašymų knyga 9, par. K. Pietkiewicz, Vilnius 2003",
    "LM 10":"Lietuvos Metrika. Knyga nr 10 (1440–1523), Užrašymų knyga 10, par. E. Banionis, A. Baliulis, Vilnius 1997",
    "LM 11":"Lietuvos Metrika. Knyga nr 11 (1518–1523), Užrašymų knyga 11, par. A. Dubonis, Vilnius 1997",
    "LM 12":"Lietuvos Metrika, Knyga nr 12 (1522–1529), Užrašymų knyga 12, par. D. Antanavičius, A. Baliulis, Vilnius 2001",
    "LM 14":"Lietuvos Metrika. Knyga nr 14 (1524–1529), Užrašymų knyga 14, par. L. Karalius, D. Antanavičius, Vilnius 2008",
    "LM 15":"Lietuvos Metrika. Knyga nr 15 (1528–1538), Užrašymų knyga 15, par. A. Dubonis, Vilnius 2002",
    "LM 17":"Lietuvos Metrika, Knyga nr 17 (1530–1536), Užrašymų knyga 17, par. L. Karalius, D. Antanavičius, Vilnius 2015",
    "LM 20":"Lietuvos Metrika. Knyga nr 20 (1536–1539), Užrašymų knyga 20, par. R. Ragauskienė, D. Antanavičius, Vilnius 2009",
    "LM 21":"Lietuvos Metrika. Knyga nr 21 (1536–1537), Užrašymų knyga 21, par. A. Dubonis, Vilnius 2019",
    "LM 22":"Lietuvos Metrika. Knyga nr 22 (1547), Užrašymų knyga 22, par. A. Blanutsa, D. Vashchuk, D. Antanavičius, Vilnius 2010",
    "LM 27":"Lietuvos Metrika. Knyga nr 27 (1541–1542), Užrašymų knyga 27, par. I. Valikonytė, T. Čelkis, L. Steponavičiene, Vilnius 2016",
    "LM 29":"Lietuvos Metrika. Knyga nr 29 (1546–1547), Užrašymų knyga 29, par. I. Ilarienė, Vilnius 2016",
    "LM 37":"Lietuvos Metrika. Knyga nr 37 (1552–1561), Užrašymų knyga 37, par. D. Baronas, Vilnius 2011",
    "LM 47":"Lietuvos Metrika. Knyga nr 47 (1565–1567), Užrašymų knyga 47, par. E. Deveikytė, ir G. Lesmaitis, Vilnius 2018",
    "LM 49":"Lietuvos Metrika. Knyga nr 49 (1566–1572), Užrašymų knyga 49, par. E. Deveikytė, Vilnius 2014",
    "LM 51":"Lietuvos Metrika. Knyga nr 51 (1564–1574), Užrašymų knyga 51, par. A. Baliulis, R. Ragauskienė, A. Ragauskas, Vilnius 2000",
    "LM 224":"Lietuvos Metrika. Knyga nr 224 (1522–1530), 4-oji Teismų bylų knyga, par. S. Lazutka, I. Valikonyte, G. Kirkiene, E. Gudavičius, J. Karpovičiene, S. Viskantaitė, Vilnius 1997",
    "LM 225":"Lietuvos Metrika. Knyga nr 225 (1528–1547), 5-oji Teismų bylų knyga, par. S. Lazutka, I. Valikonyte, Vilnius 1995",
    "LM 227":"Lietuvos Metrika. Knyga nr 227 (1533–1535), 8-oji Teismų bylų knyga, par. S. Lazutka, I. Valikonyte, N. Šlimienė, Vilnius 1999",
    "LM 229":"Lietuvos Metrika. Knyga nr 229 (1540–1541), 10 -oji Teismų bylų knyga, par. S. Lazutka, I. Valikonyte, S. Viskantaitė-Saviščevienė, J. Karpavičienė, Vilnius 2003",
    "LM 231":"Lietuvos Metrika. Knyga nr 231 (1540–1543), 12 -oji Teismų bylų knyga, par. I. Valikonyte, N. Šlimienė, S. Viskantaitė-Saviščevienė, L. Steponavičienė, Vilnius 2007",
    "LM 248":"Lietuvos Metrika. Knyga nr 248 (1554–1556), 34-oji Teismų bylų knyga, par. N. Šlimienė, I. Valikonytė, Vilnius 2018",
    "LM 251":"Lietuvos Metrika. Knyga nr 251 (1555–1558), 37-oji Teismų bylų knyga, par. I. Valikonytė, L. Steponavičienė, Vilnius 2010",
    "LM 254":"Lietuvos Metrika. Knyga nr 254 (1559–1563), 40-oji Teismų bylų knyga, par. N. Šlimienė, I. Valikonytė, Vilnius 2015",
    "LM 261":"Lietuvos Metrika. Knyga nr 261 (1562–1566), 47-oji Teismų bylų knyga, par. I. Valikonytė, N. Šlimienė, Vilnius 2011",
    "LM 264":"Lietuvos Metrika. Knyga nr 264 (1565–1566), 50-oji Teismų bylų knyga, par. L. Steponavičienė, I. Valikonytė, Vilnius 2015",
    "LM 276":"Lietuvos Metrika. Knyga nr 276 (1584, 1586, 1597), 62-oji Teismų bylų knyga, par. D. Antanavičius, Vilnius 2015",
    "LM 532":"Lietuvos Metrika. Knyga nr 532 (1569–1571), Viešųjų reikalų knyga 10, par. L. Anužytė, A. Baliulis, Vilnius 2001",
    "LM 564":"Lietuvos Metrika. Knyga nr 564 (1558–1563), Viešųjų reikalų knyga 7, par. A. Baliulis, Vilnius 1996",
    "LMAVB":"Lietuvos mokslų akademijos Vrublevskių biblioteka w Wilnie",
    "LNBRyga":"Latvijas nacionālā bibliotēka w Rydze",
    "LNBW":"Lietuvos nacionaline Martyno Mažvydo biblioteka w Wilnie Lubawskij, Siejm - М.К. Любавский, Литовско-Русский сейм. Опыт по истории учреждения в связи с внутренним строем и внешней жизнью государства, Москвa 1900",
    "Lulewicz, Miszkowicze":"H. Lulewicz, Miszkowicze, Kalenikowicze, Tyszkowicze (Tyszkiewicze) - cztery pokolenia w dziejach rodu (XV wiek - pierwsza połowa XVI wieku), w: Władza i prestiż. Magnateria Rzeczypospolitej w XVI−XVIII wieku, red. J. Urwanowicz, współudział E. Dubas-Urwanowicz, P. Guzowski, Białystok 2003",
    "Lulewicz, Problem identyfikacji":"H. Lulewicz, Problem identyfi kacji postaci na Rusi litewskiej w drugiej połowie XV wieku, w: Świat pogranicza, red. M. Nagielski, A. Rachuba, S. Górzyński, Warszawa 2003",
    "Lulewicz, Rałowicz":"H. Lulewicz, Perypetie rodu marszałka Jakuba Rałowicza herbu Pobóg (XV–XVI wiek), w: Unia w Horodle na tle stosunków polsko-litewskich. Od Krewa do Zaręczenia wzajemnego Obojga Narodów, red. S. Górzyński, Warszawa 2015",
    "LVIA":"Lietuvos valstybės istorijos archyvas w Wilnie",
    "LVVA":"Latvijas Valsts vēstures arhīvs w Rydze",
    "LwNNB":"Львівська національна наукова бібліотека України імені В. Стефаника",
    "Łappo":"И.И. Лаппо, Великое княжество Литовское за время от заключения Люблинской унии до смерти Стефана (1569–1586). Опытъ изслѣдованія политическаго и общественнаго строя, t. I, С. Петербургъ 1901",
    "Łappo, L-R powiet":"И.И. Лаппо, Литовско-русский повет и его сеймик, Юрьев 1911",
    "Łappo, Pinskij siejmik":"И.И. Лаппо, Пинский сеймик после отречения Яна Казимира, „Журнал Министерства народного просвещения”, новая серия, t. 25 (1910, № 2), отд. 2",
    "Łappo, Podkomorskij sud":"И.И. Лаппо, Подкоморскій судъ въ Великомъ княжествѣ литовскомъ въ концѣ XVI и началѣ XVII вѣка, „Журнал Министерства Народного Просвещения”, 1899, часть 324",
    "Ławno":"Acta Stanów Wielkiego Xięstwa Litewskiego na pospolite ruszenie vigore laudum Wileńskiego 14 Augusti 1698 postanowionego między Ławnem a Puzewiczami - 1698 21 Decembris, Wilno 1699",
    "Łop.":"Biblioteka Publiczna im. Hieronima Łopacińskiego w Lublinie. Dział Rękopisów",
    "Łopaciński":"E. Łopaciński, Akcesy do konfederacji warszawskiej, „Ateneum Wileńskie”, XI, 1936",
    "Malinowskij, Sbornik":"Сборник материалов, относящихся к истории панов-рады Великого княжества Литовского, издал J. Малиновскiй, Томскъ 1901",
    "Materiały Historyczno-Genealogiczne":"M. Tyszkiewicz, Materiały Historyczno-Genealogiczne do monografi i domu Tyszkiewiczów, t. I, Wieki XV i XVI (1413–1599), Warszawa 1911",
    "Matuszewicz":"M. Matuszewicz, Diariusz życia mego, t. I–II, oprac. B. Królikowski, komentarz Z. Zielińska, Warszawa 1986",
    "Metryka obolecka":"Wypisy z ksiąg metrykalnych parafi i Obolce i notaty pamiętnikarskie Jana Antoniego Weyssenhoﬀ a (kserokopia w posiadaniu Tomasza Jaszczołta)",
    "MGNSz":"Малы гербоўнік Наваградзкай шляхты, склад. С.А. Рыбчонак, Мінск 1997",
    "Mienicki":"R. Mienicki, Stanisław Dowojno wojewoda połocki, „Ateneum Wileńskie”, R. XII, 1937, s. 404–481",
    "Mies.":"Месяцеслов с росписью чиновных особ в Государстве на лето от Рождества Христова … (od r. 1805: Месяцеслов с росписью чиновных особ или Общий штат Российской Империи на лето от Рождества Христова…)",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka Litewska w RGADA (F. 389, nr księgi)",
    "MLKS":"Metryka Litewska. Księga Sigillat 1709–1719, oprac. A. Rachuba, Warszawa 1987",
    "MLKW 131":"Metryka Litewska. Księga Wpisów nr 131, oprac. A. Rachuba, Warszawa 2001",
    "MNKr.":"Muzeum Narodowe w Krakowie, Depozyt w Czart. (MNK)",
    "MWKL 30":"Метрыка Вялікага Княства Літоўскага. Кніга 30 (1480–1546 гг.). Кніга запісаў № 30 (копія канца XVI ст.), падрыхт. В.С. Мянжынскі, Мінск 2008",
    "MWKL 35":"Метрыка Вялікага Княства Літоўскага. Кніга 35 (1551–1558 гг.). Кніга запісаў № 35 (копія канца XVI ст.), падрыхт. A.A. Мяцельскі, Мінск 2020",
    "MWKL 42":"Метрыка Вялікага Княства Літоўскага. Кніга 42 (1556–1562 гг.). Кніга запісаў № 42 (копія канца XVI ст.), падрыхт. В.С. Мянжынскі, Мінск 2015",
    "MWKL 44":"Метрыка Вялікага Княства Літоўскага. Кніга 44 (1559–1566 гг.). Кніга запісаў 44, падрыхт. А.І. Груша, Мінск 2001",
    "MWKL 46":"Метрыка Вялікага княства Літоўскага. Кніга 46 (1562–1565 гг.). Кніга запісаў 46 (копія канца XVI ст.), падрыхт. В.С. Мянжынскі, Мінск 2006",
    "Nagielski, Instrukcja":"M. Nagielski, Instrukcja na sejm ordynaryjny w Warszawie 9 XI 1666 roku szlachty pińskiej, w: Origines, fontes et narrationes - pośród kręgów poznania historycznego. Prace ofi arowane Profesorowi Marcelemu Antoniewiczowi w 65. rocznicę urodzin, red. M. Cetwiński, M. Janik, współudział M. Nita, Częstochowa 2018",
    "NBU-IR":"Національна бібліотека України імені В.І. Вернадського, Інститут рукопису w Kijowie",
    "NGABGr.":"Нацыянальны гістарычны архіў Беларусі w Grodnie",
    "NGABM":"Нацыянальны гістарычны архіў Беларусі w Mińsku",
    "Nies.":"K. Niesiecki, Herbarz polski, t. I–X, wyd. J.N. Bobrowicz, Lipsk 1839–1846",
    "Ochmann-Staniszewska, Staniszewski":"S. Ochmann-Staniszewska, Z. Staniszewski, Sejm Rzeczypospolitej za panowania Jana Kazimierza Wazy. Prawo - doktryna - praktyka, t. I, Wrocław 2000",
    "Oficerowie":"M. Machynia, V. Rakutis, C. Srzednicki, Oficerowie wojska Wielkiego Księstwa Litewskiego 1777–1794. Spisy, Kraków 1999",
    "Olkieniki":"Postanowienie Generalne Stanów WXLit. - na Zjeździe Walnym woiewództw y powiatów, pospolitym ruszeniem pod Olkienikami uchwalone, [24 XI] RP 1700, Wilno 1700",
    "Opis dok. WCA":"Опись документовъ Виленскаго Центральнаго Архива древнихъ актовыхъ книгъ. Выпуск 10: Акты Брестскаго гродскаго суда за 1575–1715 годы, Вильна 1913",
    "Opisanije ROWPB":"Описанiе рукописнаго отделения Виленской публичной бивлiотеки, t. I–V, Вильна 1893–1906",
    "Oss.":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "PAUKr.":"Biblioteka Naukowa Polskiej Akademii Umiejętności i Polskiej Akademii Nauk w Krakowie",
    "Pergamentų katalogas":"Pergamentų katalogas, sudarė R. Jasas, Vilnius 1980 Petrauskas, Lietuvos diduomene - R. Petrauskas, Lietuvos diduomenė XIV a. pabaigoje - XV a. Sudėtis - struktūra - valdžia, Vilnius 2003",
    "Piłsud.":"Archiwum Piłsudskich-Giniatowiczów w AGAD",
    "Pinskije akty":"dodatek źródłowy do: А.С. Грушевский, Пинское Полесье. Исторические очерки, cz. 2, Киев 1903",
    "Pinskoje Polesie":"А.С. Грушевский, Пинское Полесье. Исторические очерки, cz. 1, Киев 1901; cz. 2, Киев 1903",
    "Pisma do wieku i spraw":"Pisma do wieku i spraw Jana Sobieskiego, t. I, cz. 2, wyd. F. Kluczycki, Kraków 1881",
    "PIWJ VI":"Памятники истории Восточной Европы. Источники XV–XVII вв., t. 6, Радзивилловские акты из собрания Российской национальной библиотеки: Первая половина XVI в., cост. М.М. Кром, Москва–Варшава 2002",
    "Platerów":"Archiwum Platerów z Antuzowa w AGAD",
    "Pociecha":"W. Pociecha, Królowa Bona (1494–1557). Czasy i ludzie Odrodzenia, t. I–IV, Poznań 1949–1958",
    "Pogonowski":"J. Pogonowski, Nominacja Konstantego Jana Szuyskiego na podkomorzego brzeskiego, „Miesięcznik Heraldyczny”, R. IX, 1930, nr 8",
    "Polechow":"С. Полехов, Наследники Витовта. Династическая война в Великом княжестве Литовском в 30-е годы XV века, Москва 2015",
    "Polechow, Itinerarium":"S. Polechow, Itinerarium wielkiego księcia litewskiego Witolda, „Rocznik Lituanistyczny”, t. 5, 2019",
    "Polechow, Kilka uwag":"S. Polechow, Kilka uwag historyka Wielkiego Księstwa Litewskiego do itinerarium Kazimierza Jagiellończyka, „Średniowiecze polskie i powszechne”, t. 8 (12), 2016, s. 287–299",
    "Popielów":"Zbiór Popielów w AGAD",
    "Popisy wojskowe":"Popisy wojskowe pospolitego ruszenia Wielkiego Księstwa Litewskiego (1524–1566), oprac. G. Lesmaitis, Białystok 2016",
    "Prozorów":"Archiwum Prozorów i Jelskich w AGAD",
    "Przezdz.":"Archiwum Przezdzieckich w AGAD",
    "Przy boku króla Stanisława I":"Przy boku króla Stanisława Leszczyńskiego (1706–1709), t. I: Wyprawy do Saksonii i Litwy w latach 1706–1708. Listy królewskich sekretarzy Samuela Kazimierza Szwykowskiego i Jozafata Michała Karpia oraz fragmenty z gazet pisanych i diariuszy, wyd. J. Dygdała, Warszawa 2018",
    "PSB":"Polski słownik biografi czny, t. I–LIII, Kraków 1935–2019",
    "PSRL":"Полное собрание русских летописей, t. 35: Летописи Белорусско-Литовские, Москва 1980",
    "Ptaszycki, Sprostowania":"S.L. Ptaszycki, Dzieje rodów litewskich jako materyjał do archeologii historycznej, Warszawa 1888 (odbitka z „Ateneum”, 1888, t. III, z. 3)",
    "Pułaski":"F. Pułaski, Opis 815 rękopisów Biblioteki Ord. Krasińskich, Warszawa 1915",
    "Rachuba":"A. Rachuba, Uwagi do genealogii Maskiewiczów, w: Litw a i jej sąsiedzi od XII do XX wieku, red. G. Błaszczyk, A. Kijas, Poznań 1994",
    "Racz.":"Biblioteka Raczyńskich w Poznaniu",
    "Radaman 2002":"А. Радаман, Кіраванне соймікавамі пасяджэннямі ў Вялікім Княстве Літоўскім, Рускім і Жамойцкім у другой палове XVI - пачатку XVII ст., „Весці Беларускага дзяржаўнага педагагічнага ўніверсітэта імя Максіма Танка”, 2002, nr 2 (32), s. 120–131",
    "Radaman 2004":"А. Радаман, Элекцыйныя лісты як крыніца вывучэння дзейнасці соймікаў Вялікага Княства Літоўскага, Рускага і Жамойцкага другой паловы XVI - пачатку XVII ст. Актыкацыя ў берасцейскія гродскія кнігі элекцыйнага ліста шляхты Бе расцейскага павета да караля польскага і вялікага князя літоўскага, рускага і жа мойцкага Жыгімонта III Ваза, у якім паведамляецца аб выбранні на элекцыйным сойміку электаў (кандыдатаў) на пасаду земскага пісара, 3 лютага 1589 г., Берась це, „Архіварыус”, 2004, nr 2, s. 99–104",
    "Radaman 2005":"А. Радаман, Віленскі земскі прывілей 1565 г. вялікага князя літоўскага Жыгімонта Аўгуста, „Беларускі гістарычны агляд”, t. 12, z. 1–2 (22–23), Снежань 2005, s. 133–161",
    "Radaman 2007":"А. Радаман, Да праблемы вызначэння мяжы паміж Новагародскім і Пінс кім паветамі Вялікага Княства Літоўскага, Рускага і Жамойцкага ў другой палове XVI ст., w: Памяць стагоддзяў на карце Айчыны: зборнік навуковых прац у го нар 70-годдзя Міхаіла Фёдаравіча Спірыдонава, Нацыянальная акадэмія навук Беларусі, Інстытут гісторыі, укладальнік Р.А. Аляхновіч [i іншыя], Мінск 2007",
    "Radaman 2013":"А. Радаман, Іерархія ўраднікаў на сойміку Новагародскага павета Вялікага Княства Літоўскага, Рускага і Жамойцкага ў другой палове XVI - першай трэці XVII ст., w: Людзі і ўлада Навагрудчыны: гісторыя ўзаемадзеяння (да 500-годдзя надання Навагрудку прывілея на магдэбургскае права), укладальнікі: А.А. Скеп’ян, В.В. Даніловіч, А.Б. Доўнар, Мінск 2013, s. 162–177",
    "Radzimiński":"Z. Luba Radzimiński, Słowo o Namiestnikach rusko-litewskich i Marszałkach Wołyńskiej ziemi wywołane pracą p. Józefa Wolﬀ a „Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego”, poprzedzone i zakończone uwagami i uzupełnieniami do niej, „Przegląd Polski”, R. XX, kwartał 2 (Ogólnego zbioru t. 77), Kraków 1885",
    "Radziwiłł, Zebranie dni":"K.S. Radziwiłł, Zebranie dni z kalendarzów, AGAD, AR, dz. VI, nr II–79",
    "RadzMem.":"A.S. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I–IV, wyd. A. Przyboś, R. Żelewski, Wrocław 1968–1974",
    "Ramankiewicz":"А.Ф. Раманкевiч, Адзин са старажытнейшых рэестрау беларускiх архивау (Пiнскi гродскi суд 1522–1631 гг.), „Архiварыус” вып. 4, Мiнск 2006, s. 14–24",
    "Regestra thelonei":"Regestra thelonei aquatici Wladislaviensis saeculi XVI, wyd. S. Kutrzeba, F. Duda, Kraków 1915",
    "Relacja życia Dolskiego":"Relacja życia JW. JPana Jana Karola na Dolsku, Dąbrowicy i Komarnie Dolskiego, Marszałka Wil. [s] W.X.litt. [s], pińskiego, wiłkomirskiego [s] Starosty - Anno 1701, wyd. J.I. Kraszewski, „Atheneum”, Wilno 1843, z. IV",
    "Rewizija puszcz":"Ревизія пущъ и переходовъ звериныхъ въ бывшемъ Великомъ Княжестве Литовскомъ, съ присовокупленіемъ грамотъ и привилегій на входы въ пущи и на земли, составленная старостою мстибоговскимъ Григоріемъ Богдановичемъ Воловичемъ въ 1559 году съ прибавленіемъ другой актовой книги, содержащей въ себе привилегіи, данныя дворянямъ и священникамъ Пинскаго повета, составленной въ 1554 году, Вильна 1867",
    "RGADA":"Российский государственный архив древних актов w Moskwie",
    "RGBM":"Российская государственная библиотека w Moskwie",
    "RGIA":"Российский государственный исторический архив w Sankt Petersburgu",
    "RIB":"Русская Историческая Библиотека, t. XX: Литовская метрика, cz. 2, t. 1: Книги судных дел, С.-Петербург 1903; t. XXX: Литовская метрика, cz. 3, t. 1: Книги публичных дел, Юрьевъ 1914; t. XXXIII: Литовская метрика, cz. 3, t. 1: Книги публичных дел: Переписи войска литовского, изд. С. Пташицкий, Петроград 1915",
    "Rimša":"E. Rimša, Pieczęcie miast Wielkiego Księstwa Litewskiego, Warszawa 2007",
    "RKE":"Ревизія Кобринской экономіи, составленная въ 1563 году королевкимъ ревизоромъ Дмитріемъ Сапегою, съ присовокупленіемъ актовъ Браславскаго земскаго суда, Относящихся къ Кобринской Архимандріи, Вильна 1876",
    "RNB":"Российская национальная библиотека w Sankt Petersburgu",
    "Rod Iliniczau":"Р.А. Aляхновіч, С.А. Рыбчонак, А.І. Шаланда, Род Іллінічаў у Вялікім Княстве Літоўскім у ХV–ХVІ ст.: радавод, гербы, уладанні, Мір 2015",
    "Roskie":"AGAD, Archiwum Roskie",
    "Roskie, król.":"AGAD, Archiwum Roskie, Akta królewszczyzn",
    "Roskie, r-m.":"AGAD, Archiwum Roskie, Akta rodzinno-majątkowe",
    "Rutkowska":"G. Rutkowska, Itinerarium króla Kazimierza Jagiellończyka z lat 1440–1492, Warszawa 1914",
    "Ryżewski":"G. Ryżewski, Ród Chreptowiczów herbu Odrowąż. Dobra i kariery Chreptowiczów w Wielkim Księstwie Litewskim w XV–XVIII w., Kraków 2006",
    "S…cki":"S…cki [S. Ptaszycki], Dostojnicy litewscy. Rozbiór krytyczny i uzupełnienia dzieła J. Wolﬀ a, Senatorowie, „Ateneum”, t. I, 1886",
    "SA":"Senieji aktai (Akta dawne) w LVIA",
    "Sadkowska":"Cz. Sadkowska, Ludwik Konstanty Pociej hetman wielki Wielkiego Księstwa litewskiego i „regestr” jego archiwum z roku 1720, „Archeion”, t. 59, 1973, s. 67–85",
    "Sajkowski":"A. Sajkowski, Od Sierotki do Rybeńki. W kręgu radziwiłłowskiego mecenatu, Poznań 1965",
    "Sang.":"Archiwum Sanguszków w ANKr., Oddział na Wawelu Sapiehowie - Sapiehowie. Materjały historyczno-genealogiczne i majątkowe, t. I–III, Petersburg 1890–1894",
    "Sarnecki":"Pamiętniki z czasów Jana Sobieskiego, t. I, Diariusz (1691–1695), oprac. J. Woliński, Wrocław 2004",
    "Sbornik dok. Siew.-Zap. kraja":"Сборник документов, касающихся административного устройства Северо-Западного края при императрице Екатерине II (1792–1796), Вильна 1903",
    "Semkowicz":"W. Semkowicz, O litewskich rodach bojarskich zbratanych ze szlachtą polską w Horodle roku 1413, „Lithuano-Slavica Posnaniensia. Studia Historica”, t. III, 1989, s. 7–139",
    "Sig.":"Metryka Koronna, Sigillata w AGAD",
    "Silva rerum Szyrmów":"Biblioteka Naukowa im. Zielińskich Towarzystwa Naukowego Płockiego, rkps 113",
    "Skorobohaty, Diariusz":"A. Skorobohaty, Diariusz, oprac. T. Wasilewski, Warszawa 2002",
    "Sliż":"Н.У. Сліж, Гісторыя роду Валовічаў на Гарадзеншчыне ў XV– XVII стст., „Гарадзенскі палімпсест”, 2012: Людзі даўняй Гародні. XV–XX стст., рэд. А.Ф. Смаленчук, Н.У. Сліж, Гродна 2013, s. 133–186",
    "Sobczak":"J. Sobczak, Sejmik kobryński 14 II 1792 r., „Studia Podlaskie”, t. IV, 1993",
    "Sperka":"J. Sperka, Szafrańcowie herbu Starykoń, Katowice 2001",
    "Spiridonow":"М.Ф. Спиридонов, Источники о реформе административно-территориального деления Великого Княжества Литовского 1565 г. в зарубежных архивах, w: Замежная архіўная Беларусіка. Матэрыялы міжнароднай навуковай канферэнцыі 25–26 красавіка 1996 г., г. Мінск, укл. У.М. Міхнюк, М.Ф. Шумейка, Я.Я. Янушкевіч, Mińsk 1998",
    "Spirydonau":"М.Ф. Спірыдонаў, Завяршэнне фарміравання Пінскага павета ў 1566 г., „Весці Нацыянальнай Акадэміі Навук Беларусі. Серыя гуманітарных навук”, 1998, nr 4, s. 42–50",
    "Sprawa Szczepanowiczów":"Sprawa WW. JPanów Jana Pisarza Grodz: Powiatu Oszmiań: Franciszka Komornika Oszmiańskiego i Sylwestra Porucznika byłych Woysk Litewskich Braci Szczepanowiczów z WW. JPP. Dominikiem Głuchowskim Szambelanem woru Polskiego Aktorem, Stanisławem Laskow- skim Woysk: Kobryńskim, Janem Sieklu ckim Woysk: Lidzkim reskryptem Króla byłego Pol: naznaczonemi, a JWW. Adamem Wierzeyskim Marszałkiem Nowogr. Antonim Lachnickim chorążym Wileńskim Dekretem Sadu Głównego Litewskiego dodanemi Kuratorami, tudzież JWW. Xiędzem Adamem Bisku- pem Dyokleńskim Oﬃ cyałem Żmudzkim, Hiacyntem Chorążym Kobryńskim Kawalerem Orderu Świętego Stanisława Bracia Kościami, druk BN 3.7676",
    "Stawski":"A. Stawski [J.F. Sapieha], Monumenta albo zebranie starożytnych ozdób Przenayczystszey Bogarodzicy Panny Maryi w dawnym wielce obrazie Kodeńskim, cz. II, Varsaviae 1723",
    "Strenkouski":"С.П. Стрэнкоўскі, Гарадское самакіраванне на тэрыторыі Беларусі ў канцы XIV–XVIII ст., cz. 1–2, Мінск 2013",
    "Subotnik":"Subotnik ili Pominnik monasteru supraskiego, wyd. A. Mironowicz, Białystok 2015",
    "Sucha":"Zbiór Branickich z Suchej w AGAD",
    "Suﬀragia 1733":"Suﬀragia Woiewodztw y Ziem Koronnych y W. X. Litewskiego Zgodnie na Nayiaśnieyszego Stanisława Pierwszego, Obranego Krola Polskiego, Wielkiego Xiążęcia Litewskiego, Ruskiego, Pruskiego, Mazowieckiego, Żmudzkiego, Kijowskiego, Wołhyńskiego, Podolskiego, Podlaskiego, Smoleńskiego, Siewierskiego, Infl antskiego y Czerniechowskiego, dane między Warszawą a Wolą dnia 25 Sierpnia Roku Pańskiego 1733 [druk, b.m.d. - elekcja zakończyła się 12 IX 1733]",
    "Supruniuk, Mazowsze":"A. Supruniuk, Mazowsze Siemowitów (1341–1442). Dzieje polityczne i struktury władzy, Warszawa 2010",
    "Supruniuk, Otoczenie":"A. Supruniuk, Otoczenie księcia mazowieckiego Siemowita IV (1374–1426). Studium o elicie politycznej Mazowsza na przełomie XIV i XV w., Warszawa 1998",
    "Swodnaja galicko-rus. letopis":"Сводная галицко-русская летопись с 1600 по 1700 год, изд. A. Петрушевич, w: Литературный сборник Галицко- Русской матицы за 1873 г., Львовъ 1874",
    "Szalewicz":"A. Szalewicz, Rodopis Szalewiczów. Czy wszyscy pochodzimy od jednego przodka, Warszawa 2008",
    "Szałanda":"A. Шаланда, Радавод і герб зямян Гарадзенскага павету Пуціўлянінаў Свяцкіх у другой палове ХVІ–ХVІІІ ст., „Gerold Lither- land”, R. 1, 2001, nr 1",
    "Szczygielski":"W. Szczygielski, Referendum trzeciomajowe. Sejmiki lutowe 1792, Łódź 1994",
    "Szołkowicz":"Сборник статей, разъясняющих польское дело по отношению к Западной России, вып. 1–2, Сост. и изд. С. Шолкович, Вильна 1885–1887",
    "Szyndler":"B. Szyndler, Tadeusz Kościuszko 1746–1817, Warszawa 1991",
    "Święcki":"Tomasza Święckiego Historyczne pamiątki znamienitych rodzin i osób dawnej Polski, t. I, Warszawa 1859",
    "Tastamienty":"Тастаменты шляхты і мяшчан Беларусі другой паловы XVI ст. (з актавых кніг Нацыянальнага гістарычнага архіва Беларусі), склaд. А.Ф. Аляксандрава, В.У. Бабкова, I.M. Бобер, Мінск 2012",
    "Tęgowski":"J. Tęgowski, Rodowód kniaziów Świrskich do końca XVI w., Wrocław 2011",
    "TML":"Transkrypcje Metryki Litewskiej w AGAD",
    "Trojanowska":"Katalog dokumentów różnej proweniencji miast, wsi, cechów, parafi i, klasztorów i osób prywatnych 1397–1794, oprac. M. Trojanowska, Lublin 1998",
    "Trybunał II":"Deputaci Trybunału Głównego Wielkiego Księstwa Litewskiego 1697–1794. Spis, red. A. Rachuba, oprac. A. Rachuba, P.P. Romaniuk, współpraca A. Macuk, J. Aniszczenko, Warszawa 2004",
    "Typografia wileńska":"K. Čepienė, I. Petrauskienė, Vilniaus akademijos spaustuvės leidiniai 1576–1805. Bibliografi ją, Vilnius 1979",
    "Tyszkiewicz":"E. Tyszkiewicz, Groby rodziny Tyszkiewiczów, Warszawa 1873",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII–XVIII wieku. Spisy, red. A. Gąsiorowski, t. I n., Wrocław–Kórnik 1985 n.",
    "Uruski":"S. Uruski, A.A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I–XV, Uzupełnienia t. I–VI, Warszawa 1904–1938",
    "UWKL":"Urzędnicy Wielkiego Księstwa Litewskiego. Spisy:",
    "VC":"Volumina Constitutionum, t. I–IV, Warszawa 1996–2017",
    "Vilimas":"D. Vilimas, Lietuvos Didžiosios Kunigaikštystės žemės teismo sistemos formavimasis (1564–1588), Vilnius 2006",
    "Vitoldiana":"Vitoldiana. Codex privilegiorum Vitoldi magni ducis Lithuaniae 1386–1430, wyd. J. Ochmański, Warszawa–Poznań 1986",
    "VL":"Volumina legum, t. I–X, Petersburg 1859, Kraków 1889, Poznań 1952",
    "VUB":"Vilniaus universiteto bibliotekos rankraščių skyrius w Wilnie",
    "Wanat":"B.J. Wanat, Klasztor karmelitów bosych w Berdyczowie na Ukrainie. Studium monograficzne, Kraków 2007",
    "Wapowski":"Dzieje Korony Polskiej i Wielkiego Księstwa Litewskiego od roku 1380 do 1535 przez Bernarda z Rachtamowic Wapowskiego, t. II, wyd. M. Malinowski, Wilno 1847",
    "Wawrzyńczyk":"A. Wawrzyńczyk, Rozwój wielkiej własności na Podlasiu w XV i XVI wieku, Wrocław 1951",
    "Weyssenhoﬀ":"J. Weyssenhoﬀ , Kronika rodziny Weyssenhoﬀ ów, Wilno 1935",
    "WiadWarsz.":"„Wiadomości Warszawskie”",
    "Wielądko I":"W.W. Wielądko, Heraldyka czyli opisanie herbów […], t. I, cz. I, Warszawa 1792",
    "Wigand von Marburg":"Wigand von Marburg, Nowa kronika pruska, oprac. S. Zonenberg, K. Kwiatkowski, Toruń 2017",
    "Wilczyński":"J.K. Wilczyński, Herbarz starodawnej szlachty podług Heraldyków polskich z dopełnieniem do czasów obecnych, Paryż [1860?]",
    "Witkowski":"R. Witkowski, Saeculum Carthusiae Berezanae, „Lituano-Slavica Posnaniensia. Studia Historica”, VII, 1995, Poznań 1997, s. 173–244",
    "Wittyg":"W. Wittyg, Nieznana szlachta polska i jej herby, Kraków 1908",
    "Wolﬀ":"J. Wolﬀ , Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386–1795, Kraków 1885 (egzemplarz z BN z własnoręcznymi popraw- kami i uzupełnieniami autora)",
    "Wolﬀ , Pacowie":"J. Wolﬀ , Pacowie. Materyjały historyczno-genealogiczne, Petersburg 1885",
    "Wolﬀ Kn.":"J. Wolﬀ , Kniaziowie litewsko-ruscy od końca czternastego wieku, Warszawa 1895",
    "Wolﬀ , Żyd":"J. Wolﬀ , Żyd ministrem króla Zygmunta, Kraków 1885",
    "Wójciuk, Urzędnicy":"M. Wójciuk, Urzędnicy ziemscy województwa brzesko-litewskiego w czasach saskich, „Wschodni Rocznik Humanistyczny”, t. II, 2005",
    "Wysłouch, Rozwój":"S. Wysłouch, Rozwój granic i terytorium powiatu kobryń- skiego do połowy XVI wieku, „Ateneum Wileńskie”, t. 6, 1929, z. 1–2",
    "Wysłouch, Zenon Wysłouch":"I. Wysłouch, „Zenon Wysłouch podkomorzy brzeski (1727–1805)”, Warszawa 1928 (maszynopis)",
    "Zabiełłów":"Archiwum Zabiełłów w AGAD",
    "Załęski":"S. Załęski, Jezuici w Polsce, t. I–V, Lwów–Kraków 1900–1906",
    "Zapiski Litwina":"Zapiski Litwina, sługi i wychowawcy Zygmunta Augusta, „Biblioteka Ossolińskich”, Poczet nowy, nr XI, Lwó w 1868",
    "Zb. Anny z Potockich Branickiej":"Zbiór Anny z Potockich Ksawerowej Branickiej w AGAD",
    "Zb. Marczaka":"Zbiór Michała Marczaka w AGAD",
    "Zb. MN":"Zbiór Muzeum Narodowego w AGAD",
    "Zb. Rus.":"Zbiór Rusieckich w ANKr., Oddział na ul. Siennej",
    "Zbiór dawnych dyplomatów":"Zbiór dawnych dyplomatów i aktów miast Wilna, Kowna, Trok, prawosławnych monasterów, cerkwi i w różnych sprawach, cz. I–II, Wilno 1843",
    "Zdański":"K. Zdański, Przyczynki do dziejów powiatu brzesko-litewskiego i ziem nim objętych, Warszawa 1939",
    "ZMRP":"Zbiór materiałów różnej proweniencji w AGAD",
    "ZNB":"Zbiory Niewodniczańskiego w Bitburgu (obecnie depozyt wieczysty na Zamku Królewskim w Warszawie)",
    "ZZG":"Zbiór Zygmunta Glogera w ANKr., Oddział na Wawelu",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. I n., Poznań 1879 n."
}