""" słownik skrótów literatury """

literatura = {
    "Acta Tom.":"Acta Tomicianat. I-XVI, Poznań - Wrocław-Kraków 1852-1960",
    "AEp":"Acta episcopalia w Archiwum Archidiecezjalnym w Krakowie",
    "AG AD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tzw. bernardyńskiego we Lwowie..., t. I-XXI, Lwów 1868-1906",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności, t. III, Kraków 1885; t. VIII, Kraków 1898",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, wyd. S. Kutrzeba i W. Semkowicz, Kraków 1932",
    "AmL":"Akta miasta Lublina w APL",
    "AOfL":"Acta officialia Lublinensia w Archiwum Archidiecezjalnym w Krakowie",
    "APKr.":"Archiwum Państwowe w Krakowie",
    "APL":"Archiwum Państwowe w Lublinie",
    "ASejmKr.":"Akta sejmikowe województwa krakowskiego, t. IV, wyd. A. Przyboś, Wrocław 1963",
    "ASK":"Archiwum Skarbu Koronnego w AG AD",
    "AZP":"Akta ziemskie parczewskie w APL",
    "BANL Oss.":"Biblioteka Akademii Nauk we Lwowie, Zbiór Ossolińskich",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwom Czartoryskich",
    "BJ":"Biblioteka Jagiellońska w Krakowie",
    "Bon.":"A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "CC":"Castrensia Cracoviensia w APKr.",
    "CCR":"Castrensia Cracoviensia Relationes w APKr.",
    "CIP":"Corpus iuris Polonici, wyd. O. Balzer, t. III-IV, Kraków 1906-1910",
    "CL":"Castrensia Lublinensia w APL",
    "CLD":"Castrensia Lublinensia Decretorum w APL",
    "CLI":"Castrensia Lublinensia Inscriptiones w APL",
    "CL RMO":"Castrensia Lublinensia Relationes, Manifestationes, Oblatae w APL",
    "CS":"Castrensia Sandecensia w APKr.",
    "DworzGen.":"W. Dworzaczek, Genealogia, Warszawa 1959",
    "Estreicher":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografia polska, t. I-XXXIV, Kraków 1870-1952",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD",
    "Kaniewska":"I. Kaniewska, Małopolska reprezentacja sejmowa za czasów Zygmunta Augusta 1548-1572, Warszawa 1974",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "Konarski":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Kossakowski":"S. K. Kossakowski, Monografie historyczno-geticalogiczne, t. I-III, Warszawa 1859-1872",
    "KPL":"Księgi podkomorskie lubelskie w APL",
    "Kuraś":"Słownik historyczno-geograficzny województwa lubelskiego w średniowieczu, opr. S. Kuraś, Dzieje Lubelszczyzny, t. III, Warszawa 1983",
    "KZab.":"Katalog zabytków sztuki w Polsce, t. VIII, Warszawa 1960-1982",
    "LLub. 1661":"Lustracja województwa lubelskiego 1661, wyd. H. Oprawko i K. Schuster, Warszawa 1962",
    "Lop.":"Wojewódzka i Miejska Biblioteka Publiczna im. H. Lopacińskiego w Lublinie",
    "Michałowski":"Jakuba Michałowskiego, Księgapamiętnicza..., Kraków 1864",
    "MK":"Metryka Koronna w AGAD",
    "ML":"Metryka tzw. Litewska w AGAD",
    "MRPS":"Matricularum Regii Poloniae summaria, wyd. T. Wierzbowski i inni, t. I-V, Warszawa 1905-1961",
    "Nieś.":"K. Niesiecki, Herbarz polski, t. I-X, Lipsk 1839-1846",
    "Nowy Korbut":"Bibliogafia literatury polskiej Nowy Korbut, t. I-III, Warszawa 1963-1965",
    "Opis":"Opis 815 rękopisów Biblioteki Ord. Krasińskich, opr, F. Pułaski, Warszawa 1915",
    "Orzelski":"Świętosława Orzełskiego Bezkrólewia ksiąg ośmioro 1572-1576, wyd. E. Kuntze, Kraków 1917",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników ziemskich w Koronie do schyłku XVI wieku, Warszawa 1962",
    "PANKr.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, Kraków 1858",
    "PSB":"Polski słownik biograficzny, t. I-XXXII, Kraków 1935-1990",
    "Pszonka":"J. Pszonka. Pamiętnik, Lwów 1874",
    "Radziwiłł":"A. S. Radziwiłł, Pamiętnik o dziejach w Polsce, t. I-III, wyd. A. Przyboś, R. Żelewski, Warszawa 1980",
    "Reg. thel.":"Regestra thelonei aquatici Wladislaviensis saeculi XVI, wyd. S. Kutrzeba i F. Duda, Kraków 1915",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "Starowolski":"S. Starowolski, Monumenta Sarmatarum..., Cracoviae 1655",
    "TL":"Terrestria Lublinensia w APL",
    "TLD":"Terrestria Lublinensia Decretorum w APL",
    "TLI":"Terrestria Lublinensia Inscriptionum w APL",
    "TPaw.":"Teki A. Pawińskiego, t. I-II, Warszawa 1897",
    "TUI":"Terrestria Urzendoviensia Inscriptionum w APL",
    "U":"Urzędnicy dawnej RzeczypospolitejXII-XVIII wieku. Spisy, 1.1 n.",
    "Uruski":"S. Uruski, Rodzina, t. I-XV, Warszawa 1904-1931",
    "Uruszczak":"W. Uruszczak, Sejm walny koronny w latach 1506-1540, Warszawa 1980",
    "VL":"Volumina legum, wyd. J. Ohryzko, Z. Kaczmarczyk, t. I-X, Petersburg 1859 - Poznań 1952",
    "Wadowski":"J. A. Wadowski, Kościoły lubelskie, Kraków 1907",
    "Wielądko":"W. Wielądko, Heraldyka..., t. I-V, Warszawa 1792-1798",
    "ZbR":"Zbiór Rusieckich w APKr.",
    "ZDP":"Radom, Archiwum Państwowe, Zarząd Dóbr Państwowych",
    "Żychliński":"T. Żychliriski, Złota księga szlachty polskiej, t. I-XXX, Poznań 1879-1908"
}