""" słownik skrótów literatury """

literatura = {
    "ACap.":"Acta capitulonim nec non iudiciorum ecclesiasticorum selecta, t. I n., Kraków 1894 n.",
    "Acta Tom.":"Acta Tomiciana..., t. I-XTV, Poznań - Wrocław - Kraków 1852-1952",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie..., t. 1 n., Lwów 1868 n.",
    "AKH":"Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKPr.":"Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności, t. VIII, Kraków 1898",
    "Akta Aleksandra":"Akta Aleksandra króla polskiego, wielkiego księcia litewskiego itd. (1501-1506), Kraków 1927",
    "APKw":"Archiwum Państwowe w Krakowie",
    "APP":"Archiwum Państwowe w Poznaniu",
    "ArchSang.":"Archiwum książąt Lubartowiczów Sanguszków w S. tawucie, t. II n., Lwów 1888 n.",
    "Arch. Zamoyskiego":"Archiwum Jana Zamoyskiego kanclerza i hetmana wielkiego koronnego, t. I-IV, Warszawa - Kraków 1904-1948",
    "ASejmKr.":"Akta sejmikowe województwa krakowskiego, t. I, Kraków 1932",
    "ASK":"Archiwum Skarbu Koronnego w AGAD",
    "BCzart.":"Muzeum Narodowe w Krakowie, Biblioteka i Archiwum Czartoryskich",
    "BJ":"Biblioteka J. agiellońska w Krakowie",
    "BKórn.":"Biblioteka Kórnicka Polskiej Akademii Nauk w Kórniku",
    "Błesz.":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) XVIII wieku, [w:] S. K. Kossakowski, Monografie historyczno-genealogiczne niektórych rodzin polskich, t. TI, Warszawa 1872",
    "Bon.":"Ą. Boniecki, Herbarz polski, t. I-XV, Warszawa 1899-1912",
    "BOW":"Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BRacz.":"Biblioteka Publiczna im. Edwarda Raczyńskiego w Poznaniu",
    "BullPol.":"Bullarium Poloniae, t. Il n., Romae 1985 n.",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego",
    "CE":"Codex epistolaris saeculi decimi quinti, t. H-III, Kraków 1891, 1894",
    "Chłapowski":"K. Chłapowski, Starostowie w Małopolsce 1565-1668, w: Społeczeństwo staropolskie, IV, Warszawa 1986, s. 105 n.",
    "Chrapowicki":"J. A. Chrapowicki, Diariusz. Cz. I: Lata 1656-1664, Warszawa 1978; Cz. II: Lata 1665-1669, Warszawa 1988",
    "CInscrP":"Corpus inscriptionum Poloniae, t. I n.",
    "CPH":"Czasopismo Prawno-Historyczne",
    "Długosz":"Joannis Długossii Senioris canonici Cracoviensis opera omnia, t. 1, XII-XIV, Kraków 1863 n.",
    "Dobrowolska":"W. Dobrowolska, Młodość Jerzego i Krzysztofa Zbaraskich, Przemyśl 1926",
    "Dogiel":"Codex diplomaticus Regni Poloniae et Magni Ducatus Lithuaniae..., t. I, [wyd. M. Dogiel], Wilno 1758",
    "DSZK":"Dokurmenty sądu ziemskiego krakowskiego, Wrocław 1971",
    "DwGen.":"W. Dworzaczek, Genealogia, Warszawa 1959, tablice",
    "DwTarn. I-II":"W. Dworzaczek, [I:] Łełiwici Tarnowscy, Warszawa 1971; tenże [II:] Hetman Jan Tarnowski, Warszawa 1985",
    "Dziennik Myszkowskiego":"Dziennik biskupa Piotra Myszkowskiego 1555-1568, wyd. Ł. Kurdybacha, Kw. Hist. 47, 1933, s. 447-468",
    "Elementa":"Elementa ad fontium editiones, t. XXX n., Romae 1973 n.",
    "Estreicher":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografia polska, stulecie XV-XVIII, t. I-XXXIX, Kraków 1870-1952",
    "FastnachtKat.":"A. Fastnacht, Katalog dokumentów Biblioteki Zaktadu Narodowego im. Ossolińskich, cz. 1: dokumenty z lat 1507-1700, Wrocław 1953",
    "GazWarsz.":"Gazeta Warszawska, Warszawa 1774 n.",
    "Gąsltiner.":"A. Gąsiorowski, Itinerarium króla Władystawa Jagietty 1386-1434, Warszawa 1972",
    "GąsStar.":"A. Gąsiorowski, Starostowie wielkopolskich miast królewskich w dobie jagiellońskiej, Warszawa 1981",
    "Hozjusz":"Stanisłai Hosii...epistolae, t. I, Kraków 1879",
    "IA":"Index actorum saeculi XV ad res publicas Poloniae spectantium, Kraków 1888",
    "Jasas":"R. Jasas, Pergamentu katalogas, Vilnus 1980",
    "Kal.":"Kalendarzyk polityczny na rok przybyszowy 1794",
    "Kam.":"Księgi Kameralne Metryki Koronnej w AGAD",
    "Katalog perg.":"Katalog pergamentnich dokumentiv Centralnogo Derżavnogo Istoriczeskogo Archivu USSR u Lvovi 1233-1799, Kiiv 1972",
    "KDKK":"Kodeks dyplomatyczny katedry krakowskiej Ś. Wacława, cz. 1-Il, Kraków 1874-1883",
    "KDM":"Kodeks dyplomatyczny Matopolski, t. I-IV, Kraków 1876-1905, t. V - Materiały w Pracowni Słownika Historyczno-Geograficznego Ziem Polskich w Średniowieczu IH PAN w Krakowie",
    "KDW":"Kodeks dyplomatyczny Wielkopolski, t. 1I-1X, Poznań 1878-1990",
    "KerstenCzarn.":"A. Kersten, Stefan Czamiecki 1599-1665, Warszawa 1963",
    "KerstenRadz.":"A. Kersten, Hieronim Radziejowski, Warszawa 1988",
    "KętrzElem.":"S. Kętrzyński, O elementach chronologicznych dokumentów Kazimierza Wielkiego, w: Rozprawy Wydziału Historyczno-Filozoficznego Akademii Umiejętności, t. LVI, Kraków 1914, s. 77-178",
    "KK":"Księgi Kanclerskie Metryki Koronnej w AGAD",
    "KKrak.":"Kodeks dyplomatyczny miasta Krakowa 1257-1506, cz. I-IV, Kraków 1879-1882",
    "KLitwy":"Kodeks dyplomatyczny Litwy, Wrocław 1845",
    "Kłaczewski":"W. Kłaczewski, W przededniu wojny domowej w Polsce. Walka sejmowa w latach 1664-1665, Lublin 1984",
    "KMog.":"Diplommata monasterii Ciarae Tumbae prope Cracoviam, Kraków 1865",
    "Knigi":"Knigi polskoj koronnoj mietriki XV stoletija, t. l, Warszawa 1914",
    "Komoniecki":"Chronologia albo dziejopis żywiecki... „Andrzeja Komonieckiego, Żywiec 1987",
    "Kor. Kras.":"Korespondencja Ignacego Krasickiego, t. I-II, Wrocław 1958",
    "Kor. Nar.":"Korespondencja Adama Naruszewicza 1762-1796, Wrocław 1959",
    "KorPrał.":"J. Korytkowski, Prałaci i kanonicy katedry metropolitalnej gnieźnieńskiej od roku 1000 aż do dni naszych, t. I-IV, Gniezno 1883",
    "KPol.":"Kodeks dyplomatyczny Polski, t. I-IV, Warszawa 1847 n.",
    "KrzyżKanc. I-II":"J. Krzyżaniakowa, Kancelaria królewska Władysława Jagiełty. Studium z dziejów kultury politycznej Polski w XV wieku, cz. I-II, Poznań 1972, 1979",
    "KTyn.":"Kodeks dyplomatyczny klasztoru tynieckiego, cz. I, Lwów 1875",
    "Kutrzeba":"S. Kutrzeba, Urzędy koronne i nadwome w Polsce, ich początki i rozwój do roku 1504, Przewodnik Naukowy i Literacki, 31, 1903",
    "Lengnich":"G. Lengnich, Geschichte der Preussischen Landes Kóniglich Polnischen Antheil, Bd. VII-IX, Danzig 1734-1755",
    "Łętowski":"L. Łętowski, Katalog biskupów, pratatów i kanoników krakowskich, t. II-IV, Kraków 1852-1853",
    "Matwijowski":"K. Matwijowski, Pierwsze sejmy z czasów Jana Sobieskiego, Wrocław 1976",
    "Michałowski":"Jakuba Michałowskiego wojskiego lubelskiego a później kasztelana bieckiego księga pamiętnicza..., Kraków 1864",
    "MK":"Metryka Koronna w AGAD",
    "ML":"tzw. Metryka Litewska w AGAD",
    "Mosbach":"Wiadomości do dziejów polskich z Archiwum Prowincyi Szląskiej, wyd. A. Mosbach, Wrocław 1860",
    "MPH":"Monurmtenta Poloniae historica. Pomniki dziejowe Polski, t. II-V, Lwów - Kraków 1872-1888; nowa seria (s.n.), t. V, Warszawa 1978",
    "MRPS":"Matricularum Regni Poloniae sumumaria, cz. I-V, Warszawa 1905-1961",
    "MSambora":"Materiały do historii miasta Sambora 1390-1795, wyd. A. Dórfierówna, Lwów 1936",
    "Nies.":"K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-X, Lipsk 1839-1846",
    "Now. II":"J. Nowacki, Dzieje archidiecezji poznańskiej, t. 11, Poznań 1964",
    "Orzelski":"Świętosława Orzelskiego Bezkrólewia ksiąg ośmioro 1572-1576, w: SSRP, t. XXII, Kraków 1917",
    "PamkKon.":"Pamiętniki o Koniecpolskich. Przyczynek do dziejów polskich XVII wieku, Lwów 1842",
    "PamOss.":"Pamiętnik Zbigniewa Ossolińskiego, Warszawa 1983",
    "PANK.":"Biblioteka Polskiej Akademii Nauk w Krakowie",
    "Paprocki":"B. Paprocki, Herby rycerstwa polskiego, wyd. K. J. Turowski, Kraków 1858",
    "Pociecha":"W. Pociecha, Królowa Bona (1494-1557). Czasy i ludzie Odrodzenia, t. II, Poznań 1949",
    "PPK":"Prawa, przywileje i statuta miasta Krakowa (1507-1795), Kraków 1885-1905",
    "Prochaska":"A. Prochaska, Materiały archiwalne wyjęte głównie z Metryki Litewskiej od 1348 do 1607 roku, Lwów 1890",
    "Prz. Hist.":"Przegląd Historyczny",
    "PSB":"Polski słownik biograficzny, t. I n., Kraków 1935 n.",
    "Pszonka":"J. Pszonka, Pamiętnik, Lwów 1874",
    "Pułaski":"F. Pułaski, Opis 815 rękopisów Biblioteki Ordynacji hr. Krasińskich, [w:] Biblioteka Ordynacji Krasińskich i Muzeum Konstantego Świdzińskiego, t. XXIII-XXIX, Warszawa 1915",
    "RachK":"AGAD, ASK I, Rachunki królewskie",
    "RachKról.":"Rachunki królewskie z lat 1471-1472 i 1476-1478, Wrocław 1960",
    "Raczyński, Wlkp.":"Kodex dyplomatyczny Wielkiej Polski, wyd. E. Raczyński, Poznań 1840",
    "Radziwiłł":"A. S. Radziwiłł, Memoriale renum gestanum in Polonia, t. I-IV, Wrocław 1968—1974",
    "RJJ":"Rachunki dworu króla Władysława Jagiełty i królowej Jadwigi z lat 1388-1420, Kraków 1896",
    "Sarnecki":"K. Sarnecki, Pamiętniki z czasów Jana Sobieskiego. Diariusz relacje z łat 1691-1696, Wrocław 1958",
    "SBW":"Słownik biograficzny Warnii, Prus Książęcych i ziemi malborskiej, opr. T. Oracki, Olsztyn 1988",
    "Seredyka":"J. Seredyka, Rzeczpospolita w ostatnich latach panowania Zygrnunta III (1629-1632). Zarys wewnętrznych dziejów politycznych, Opole 1978",
    "SHGKTr.":"Słownik historyczno-geograficzny województwa krakowskiego w średniowieczu, cz. I-II, Wrocław 1980 n.",
    "SHGLub.":"Słownik historyczno-geograficzny województwa lubelskiego w średniowieczu, oprac. $. Kuraś, [w:] Dzieje Lubelszczyzny, t. III, Warszawa 1983",
    "Sig.":"Księgi Sigillat Metryki Koronnej w AGAD",
    "Sobieski, Listy":"J. Sobieski, Listy do żony Manii Kazimiery, Kraków 1860",
    "SPPP":"Starodawne prawa polskiego pomniki, t. I n., Kraków 1856 n.",
    "SSRP":"Scriptores rerum Polonicarum",
    "Stadtebuch":"Stidtebuch des Landes Posen, wyd. H. Wuttke, Leipzig 1864",
    "Starowolski":"S, Starowolski, Monumenta Sarmatarum, viam universae carnis ingressorum, Cracoviae 1655",
    "Steinwchr":"Zbiór rękopisów Stcinwehra w Bibliotece Uniwersytetu Wrocławskiego",
    "Straty":"Straty archiwów i bibliotek warszawskich w zakresie rękopiśmiennych Źródet historycznych, t. III, Warszawa 1955",
    "SułkDok.":"I. Sułkowska-Kurasiowa, Dokumenty królewskie i ich funkcja w państwie polskim za Andegawenów i pierwszych Jagiellonów 1370-1444, Warszawa 1977",
    "SułkKanc.":"I. Sułkowska-Kurasiowa, Polska kancelaria królewska w latach 1447-1506, Warszawa 1967",
    "Szostkiewicz":"Z. Szostkiewicz, Katalog biskupów obrządku łacińskiego przedrozbiorowej Polski, w: Sacrum Poloniae Millenium, I, Rzym 1954",
    "Tajna kor.":"Tajna korespondencja z Warszawy 1792-1794 do Ignacego Potockiego..., Warszawa 1961",
    "Temberski":"Stanisława Temberskiego roczniki 1647-1656, Kraków 1897",
    "Toeppen":"Acten der Stindetage Preussens unter der Herrschaft des Deutschen Ordens, wyd. M. Toeppen, Bd. IV, Leipzig 1884",
    "TPaw. I-II":"Teki A. Pawińskiego: [1:] Liber quitantiarum Alexandri regis ab a. 1501 ad 1506. (Księga skarbowa króla Aleksandra Jag.); [II:] Liber quitantiarum regis Casimiri ab a. 1484 ad a. 1488. (Księga skarbowa króla Kazimierza Jag.), Warszawa 1897",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII-XVIII wieku. Spisy, t. I n., Wrocław-Kórnik 1985 n.",
    "Uruski":"S. Uruski, A. A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. IV-X1X, Warszawa 1907-1935",
    "VL":"Volummina legum, t. I-VII, Petersburg 1859",
    "Wielewicki":"Ks. Jana Wielewickiego, Dziennik spraw domu zakonnego pp. jezuitów u Św. Barbary w Krakowie, [w:] SSRP, t. VII, X, XIV, Kraków 1881, 1886, 1889",
    "Wolff":"J. Wolff, Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "Wójcik":"Z. Wójcik, Jan Sobieski, Warszawa 1983",
    "WSB":"Wielkopolski słownik biograficzny, Warszawa 1981",
    "Załuski":"Z. Ch. Załuski, Epistolarum historico-familiarum..., t. I-III, Brunsbergae - Vratislaviae 1709-1711",
    "ZDKKr.":"Zbiór dokumentów katedry i diecezji krakowskiej, cz. 1, Lublin 1965",
    "ZDLmPŁ.":"Zbiór dokumentów i listów miasta Płocka, t. II, Warszawa 1987",
    "ZDM":"Zbiór dokumentów małopolskich, cz. I-VIII, Wrocław 1962-1975",
    "ŻD":"Źródła dziejowe",
    "Źródłopisma":"Źródłopisma do dziejów unii Kor. Polskiej i W. X. Litewskiego, cz. II, III, Poznań 1856",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. 1 n., Poznań 1879"
}