literatura = {
    "AcN": "Archivum conventus Novensis w TNT",
    "AcS" : "Archiwum conventus Svecensis w TNT",
    "AcZ" : "Archivum conventus Zamartensis w TNT" ,
    "ADCh" : "Archiwum Diecezji Chełmińskiej w Pelplinie" ,
    "ADW" : "Archiwum Diecezji Warmińskiej w Olsztynie",
    "AGAD" : "Archiwum Główne Akt Dawnych w Warszawie",
    "AKCh" : "Akta kapituły chełmińskiej w ADCh",
    "AKH" : "Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności",
    "AKrokow." : "Archiwum Krokowskich z Krokowej w APG" ,
    "Akta Kruszyńskich" : "Akta Kruszyńskich z Nawry, mikrofilm w posiadaniu TNT",
    "APB" : "Archiwum Państwowe w Bydgoszczy",
    "APG" : "Archiwum Państwowe w Gdańsku" ,
    "APP" : "Archiwum Państwowe w Poznaniu" ,
    "APT" : "Archiwum Państwowe w Toruniu" ,
    "ARadz." : "Archiwum Radziwiłłów w AGAD" ,
    "ARos." : "Archiwum Ordynacji Roskiej w AGAD" ,
    "ASczan." : "Archiwum Sczanieckich z Nawry w APT" ,
    "ASK" : "Archiwum Skarbu Koronnego w AGAD",
    "ASPK" : "Akta stanów Prus Królewskich, t. I-VII, wyd. K. Górski, M. Biskup, Fontes 41 n., Toruń 1955 n.",
    "ATom." : "Acta Tomiciana, t. I i n., Poznań 1852 n.",
    "AUstarb." : "Archiwum Ustarbowskich i Wejherów z Ustarbowa w APG",
    "Bär, Der Adel" : "M. Bär, Der Adel und der adlige Grundbesitz in Polnischen-Preussen zur Zeit der preussische Besitzergreifung, Leipzig 1911",
    "Bär, Westpreussen" : "M. Bär, Westpreussen unter Friedrich dem Grossen, Bd. II, Leipzig 1909",
    "BCzart." : "Muzeum Narodowe w Krakowie - Biblioteka Czartoryskich",
    "BG" : "Biblioteka Gdańska Polskiej Akademii Nauk",
    "Bon." : "A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899 n." ,
    "Bork" : "J. Bork, Echo sepulchralis . . . w ADCh",
    "Bornbach" : "S. Bornbach, Rezesse der Jahre 1501-1519 w BG" ,
    "Botsacus" : "J. Botsacus, Stella lucida . . ., Danzig 1666",
    "BOW" : "Biblioteka im. Ossolińskich we Wrocławiu",
    "BPelp." : "Biblioteka Wyższego Seminarium Duchownego w Pelplinie",
    "Breza" : "E. Breza, Pochodzenie przydomków szlachty pomorskiej, Gdańsk 1986",
    "BrodM" : "Akta miasta Brodnicy w APT",
    "BrzG Rel. Dec." : "Akta grodzkie brzeskie-kujawskie, seria Relationes, Decretorum w AGAD",
    "BTor." : "Akta benedyktynek toruńskich w ADCh",
    "BuKDWestpr." : "J. Heise, Die Bau- und Kunstdenkmäler der Prowinz Westpreussen, Bd. I-II, Danzig 1884-1885",
    "Bysławek" : "Akta majątku Bysławek w APG",
    "BZał." : "Biblioteka Załuskich w AGAD" ,
    "ChełM" : "Akta miasta Chełmży w APT" ,
    "ChojM" : "Akta miasta Chojnic w APB",
    "CIP" : "Corpus iuris Polonici, wyd. O. Balzer, t. III, Kraków 1906",
    "Culm." : "Dział Culmensia w ADCh",
    "Czaplewski" : "P. Czaplewski, Senatorowie świeccy, podskarbiowie i starostowie Prus Królewskich w latach 1454-1772, „Roczniki TNT”, R. 26-28, Toruń 1919-1921",
    "Dachnowski, Herbarz" : "J. K. Dachnowski, Sumariusz herbarza szlachty prusko-polskiej w APT",
    "Dachnowski, Żałobny rytm" : "J. K. Dachnowski, Żałobny rytm . . ., starodruk w posiadaniu KMTor.",
    "Deresiewicz" : "J. Deresiewicz, Z przeszłości Prus Królewskich, Poznań 1947",
    "Diecezja chełmińska" : "Diecezja chełmińska. Zarys historyczno -statystyczny, Pelplin 1928",
    "Długosz" : "Joannis Długossii seu Longini cananici Cracoviensis Historiae Polonioae libri XII, [w:] tegoż, Oyera omnia, t. XII-XIV, Kraków 1876-1878",
    "DTor." : "Akta klasztoru dominikanów z Torunia w APT Dworzaczkowa - J. [Dworzaczkowa] Essmanowska, Ruch szlachecki w Prusach Królewskich w pierwszej połowie XVI w., Poznań 1951 (maszynopis)",
    "Dygdała" : "J. Dygdała - informacje z kartoteki dotyczącej szlachty Prus Królewskich w XVIII w.",
    "Dygdała, Życie" : "J. Dygdała, Życie polityczne Prus Królewskich u schyłku ich związku z Rzecząpospolitą w XVIII w., „Roczniki TNT”, R. 81, Toruń 1984, z. 3",
    "DzierzG" : "Sąd grodzki w Dzierzgoniu w APG",
    "EaFE" : "„Elementa ad fontium editiones”" ,
    "ElbM" : "Akta miasta Elbląga w APG",
    "Elekt." : "J. Dunin-Borkowski, M. Dunin-Wąsowicz, Elektorowie królów Wladysława IV, Michala Korybuta, Stanisława Leszczyńslciego i spis stronników Augusta III, „Roczniki Tow. Heraldycznego we Lwowie”, t. I: 1908-1909",
    "Estreicher" : "K. Estreicher, Bibliografia polska, t. XII n., Warszawa 1891 n.",
    "Fankidejski" : "ks. Fankidejski, Klasztory żeńskie w dyecezyi chełmińskiej, Pelplin 1887",
    "Fontes" : "Fontes TNT",
    "Frydrychowicz" : "R. Frydrychowicz, Geschichte der Cistercienserabtei Pelplin und Ihre Bau- und Kunstdenkmäler, Düsseldorf 1905",
    "Gallandi" : "J. Gallandi, Altpreussisches Adelslexicon, cz. 1: Prussia, H. 26: 1926; cz. 2; ib., H. 27: 1927; cz. 3, ib., H. 28: 1928; cz. 4, ib., H. 31: 1935",
    "Gause" : "F. Gause, Geschichte der Landgerichte des Ordenslanden Preussen, „Altpreussische Forschungen”, 3, Königsberg 1926",
    "GdM" : "Akta miasta Gdańska w APG",
    "Ged." : "Dział Gedanensia w ADCh",
    "Glemma" : "T. Glemma, Piotr Kostka - Lata młodzieńcze i działalność polityczna, „Roczniki TNT”, R. 61, Toruń 1959, z. 2",
    "Gumowski" : "M. Gumowski, Herbarz patrycjatu toruńskiego, „Roczniki TNT”, R. 74, Toruń 1970, z. 3",
    "Hozjusz" : "Stanislai Hosii...epistolae, t. I-II, Kraków 1879 n., t. III n.: Stanislai Hosii Cardinalis et Episcopi Varmiensis Epistolaria, wyd. A. Szorc, H. Wojtyska, „Studia Warmińskie”, t. XIII n., Olsztyn 1976 n.",
    "InowG" : "Księgi grodzkie inowrocławskie w APP",
    "ISO" : "Imienne spisy osób, które w pierwszych ośmiu latach panowania króla Stanisława Paniatowskiego w rządzie lub przy administracji Rzeczypospolitej udzial brały . . ., cz. I: Tablice i rejestry, wyd. A. Sozański, Kraków 1866",
    "JTor." : "Akta ojców jezuitów z Torunia w APT",
    "Kam.III/324" : "Sigillata w Archiwum Kameralnym w AGAD Kartuzy - Akta klasztoru kartuzów z Kartuz w ADCh",
    "Kat. zab." : "Katalog zabytków sztuki w Polsce, t. XI: Województwo bydgoskie, red. T. Chrzanowski, M. Kornecki, Warszawa 1969-1982, z. 1-21",
    "KBG" : "Kronika benedyktynów grudziądzkich, wyd. M. Szołdrski, Pelplin 1935",
    "KBT" : "Kronika bernardynów toruńskich w TNT",
    "Kętrzyński" : "W. Kętrzyński, O ludności polskiej w Prusach niegdyś krzyżackich, Lwów 1882",
    "KMCh" : "Kronika xx. misjonarzy w Chełmnie, wyd. W. Szołdrski, Pelplin 1936",
    "KMTor." : "Książnica Miejska w Toruniu",
    "Kossakowski" : "S. Kossakowski, Monografie historyczno-genealogiczne niektórych rodzin polskich, t. I-III, Warszawa 1872",
    "Kościński" : "K. Kościński, Kościoły i kaplice w Nowem w pow. świeckim [w:] Prusach Zachodnich, Gdańsk 1896",
    "KośM" : "Akta miejskie Kościerzyny w APG",
    "KowM" : "Akta miasta Kowalewa w APT",
    "Kujot" : "S. Kujot, Opactwo pelplińskie, Pelplin 1875",
    "Lau" : "P. Lau, Chronik der Evangelischen Kirche zu Rheinfeld, Rheinfeld 1932",
    "Lengnich" : "G. Lengnich, Geschichte der Preussischen Landes Königlich Polnischen Antheil, Bd. I-IX, Danzig 1722-1755",
    "Leźno" : "Akta majątku Leźno w APG",
    "LM" : "Liber mortuorum",
    "Lustracja 1565" : "Lustracja województwa pomorskiego 1565, wyd. S.Hoszowski, Gdańsk 1961",
    "Lustracja 1624" : "Lustracja województw Prus Królewskich 1624, wyd. S. Hoszowski, Gdańsk 1967",
    "Maercker, Schwetz" : "H. Maercker, Eine polnische Starostei und ein preussischer Landrathskreis. Geschichte des Schwetzer Kreis 1466-1873, ZWG, XVII-XIX: 1896",
    "Maercker, Thorn" : "H. Maercker, Geschichte der ländlichen Ortschaften und der drei kleineren Stadte des Kreises Thorn, Bd. I-II, Danzig 1899-1900",
    "Maliszewski" : "K. Maliszewski, Jakub Kazimierz Rubinkowski, szlachcic, mieszczanin toruński, erudyta barokowy, „Roczniki TNT”, R. 81, Toruń 1982, z. 1",
    "MalM" : "Akta miasta Malborka w APG",
    "Maroński" : "Maroński, Wyciągi z akt Kancelarii Biskupiej w Pelplinie w TNT",
    "Matwijowski" : "K. Matwijowski, Pierwsze sejmy z czasów Jana Sobieskiego, Wrocław 1976",
    "Mączyński" : "T. Mączyński, Kazimierz Rogala-Zawadzki. Jego życie i dzieła, „Roczniki TNT”, R. 35, Toruń 1928",
    "MCV" : "„Mitteilungen des Coppernicus-Vereins für Wissenschaft und Kunst zu Thorn”",
    "MK" : "Metryka Koronna w AGAD",
    "MPH" : "Monumenta Poloniae historica, t. I-VI, Lwów 1864-1893",
    "MRPS" : "Matricularum Regni Poloniae summaria, t. I-V, Warszawa 1905-1961",
    "NakłoG" : "Księgi grodzkie nakielskie w APP",
    "Nies." : "K. Niesiecki, Herbarz polski, wyd. J. N. Bobrowicz, t. I-IX, Lipsk 1839-1845",
    "NoweM" : "Akta miasta Nowego w APB",
    "Nowy Korbut" : "Bibliografia literatury polskiej. Nowy Korbut, t. I-III, Warszawa 1963-1965",
    "Pelplin" : "Akta klasztoru cystersów z Pelplina w ADCh" ,
    "Perlbach, Zuckau" : "Das Totenbuch des Prämonstrantenserinnen-Kloster Zuckau bei Danzig, hrsg. v. M. Perlbach, „Quellen und Darstellungen zur Geschichte Westpreussen”, t. V, Danzig 1906",
    "Plehn" : "H. Plehn, Ortsgeschichte des Kreises Strasburg in Westpreussen, Leipzig 1900",
    "Portret" : "J. Kruszelnicka, Portret na ziemi chelmińskiej, Toruń 1982-1983",
    "Praetorius" : "C. G. Praetorius, Thorner Ehrentempel oder Verzeichniss der Bürgermeister und Rathmanner der Stadt Thorn, Berlin 1832",
    "PSB" : "Polski słownik biograficzny, t. I n., Kraków 1935 n." ,
    "PuckM" : "Akta miasta Pucka w APG",
    "RachKról." : "Rachunki królewskie z lat 1471-1472 i 1476-1478, opr. S. Gawęda, Z. Perzanowski i A. Strzelecka, Wrocław 1960",
    "Radziwiłl" : "A. S. Radziwiłł, Memoriale rerum gestarum in Polonia, 1632-1656, opr. A. Przyboś, R. Żelewski, t. I-V, Wrocław 1968-1975",
    "Rocz.Gd." : "Rocznik Gdański",
    "Roczniki TNT" : "„Roczniki Towarzystwa Naukowego w Toruniu”",
    "Rocz. Tow. Herald." : "„Rocznik Towarzystwa Heraldycznego we Lwowie”",
    "Rozdrażewski" : "Korespondencja Hieronima Rozdrażewskiego, wyd. P. Czaplewski, t. I-II, Toruń 1937-1939, Fontes 30-31",
    "Schultz" : "F. Schultz, Geschichte der Kreise Neustadt und Putzig, Danzig 1907",
    "Schultz, Krockow" : "F. Schultz, Geschichte der Gräflich Krockowschen Familie, b. m. wyd. 1911",
    "Sig." : "Księgi sigillat w AGAD",
    "SkarM" : "Akta miasta Skarszew w APG",
    "Smogulec" : "Akta majątku Smogulec w APP",
    "SRP" : "Scriptores rerum Prussicarum, ed. T. Hirsch, M. Toeppen, E. Strehlke, t. I-V, Leipzig 1861-1874",
    "Sulmin" : "Akta majątków Sulmin i Niestępowo w APG",
    "SztM" : "Akta miasta Sztumu w APG",
    "SztZ" : "Sąd ziemski w Sztumie w APG",
    "Ślaski" : "B. Śląski, Materiały i przyczynki do dziejów nadmorskiego miasta Pucka oraz dawnej ziemi puckiej, Warszawa 1916",
    "ŚwM" : "Akta miasta Świecia w ADCh",
    "Thunert" : "Acten der Ständetage Preussens Königliche Anteils, ed. F. Thunert, Bd. I (1466-1479), Danzig 1869",
    "TNT" : "Towarzystwo Naukowe w Toruniu",
    "Toeppen" : "Acten der Ständetage Preussens unter der Herrschaft des Deutschen Ordens, ed. M. Toeppen, Bd. I-V, Leipzig 1878-1886",
    "TorM" : "Akta miasta Torunia w APT",
    "TPaw." : "Teki Pawińskiego",
    "TWNA" : "„Thornische Wöchentliche Nachrichten und Anzeigen”, Bd. I-XII: 1760-1771",
    "Ur." : "S. Uruski, A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XXI, Warszawa 1904-1938",
    "Varia" : "Dział Varia w ADCh",
    "VL" : "Volumina legum, t. I-X, Warszawa 1732 n.",
    "Voigt" : "J. Voigt, Geschichte Preussens von den ältesten Zeiten bis zum Untergange der Herrschaft des Deutschen Ordens, t. I-I X, Königsberg 1827-1839",
    "Waschinsky" : "E. Waschinsky, Geschichte der Johanniterkomturei und Stadt Schöneck Wstpr., Danzig 1904",
    "Wielądko" : "Heraldyka, czyli apisanie herbów, w jakim który jest ksztalcie oraz familie rodowitej szlachty polskiej i W. Ks. Litewskiego z ich herbami przez Wojciecha Wincentego na Wielądkach Wielądka, t. I, Warszawa 1792",
    "Woelky" : "Urkundenbuch des Bistums Culm, ed. C. P. Woelky, t. I-II, Danzig 1885-1887",
    "Wolff" : "J. Wolff, Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "Zap. Hist." : "„Zapiski Historyczne” (do t. XX, 1954: „Zapiski Towarzystwa Naukowego w Toruniu”)",
    "Zdrójkowski" : "Z. Zdrójkowski, Zarys dziejów prawa chełmińskiego 1233-1862, Toruń 1983",
    "Zebrzydowski" : "Andrzeja Zebrzydowskiego biskupa włocławskiego i krakowskiego korespondencja z lat 1546-1553, wyd. W. Wisłocki, Kraków 1878",
    "Zernecke" : "J. H. Zernecke, Thornische Chronica, Berlin 1727",
    "ZHMar." : "„Zeitschrift des historischen Vereins fi.ir den Regirungs-Bezirk Marienwerder”",
    "ZWG" : "„Zeitschrift des westpreussisches Geschichtsvereins”",
    "Źr. dziej." : "Źródła dziejowe, t. XXIII: Polska XVI w. pod względem geograficzno-statystycznym, t. XII: Prusy Królewskie, wyd. J. T. Baranowski, Warszawa 1911",
    "Żarnowiec" : "Akta klasztoru cysterek, później benedyktynek w Żarnowcu w APG",
    "Żernicki-Szeliga" : "E. Żernicki-Szeliga, Geschichte des polnischen Adels in Westpreussen, Hamburg 1905",
    "Żukowo" : "Akta klasztoru w Żukowie w ADCh",
    "Żychliński" : "Złota księga szlachty polskiej, t. I-XXXI, Poznań 1879-1908"
}