literatura = {
    "AB" : "Archiwum Bernardynów w Krakowie",
    "Aftanazy" : "R. Aftanazy, Dzieje rezydencji na dawnych kresach Rzeczypospolitej, t. 5, Wrocław 1994",
    "AGAD" : "Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ" : "Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z Archiwum tzw. Bernardyńskiego we Lwowie, t. I-XXV, Lwów 1868-1935",
    "AJZR" : "Archiv jugo-zapadnoj Rossii, cz. I-VIII, Kiev 1858-1911",
    "AKP" : "Archiwum Krzeszowickie Potockich w APKr.",
    "AL" : "Archiwum Leszczyńskich w APL",
    "AMCh" : "Archiwum Młynowskie Chodkiewiczów w APKr.",
    "AMLw." : "Archiwum Metropolii Lwowskiej w Krakowie",
    "AMP" : "Archiwum Metropolii w Przemyślu",
    "AOU" : "Archiwum Ostrowskich z Ujazdu w AGAD",
    "APKr." : "Archiwum Państwowe w Krakowie",
    "APL" : "Archiwum Państwowe w Lublinie",
    "APP" : "Archiwum Publiczne Potockich w AGAD",
    "APR" : "Archiwum Potockich z Radzynia w AGAD",
    "AR" : "Archiwum Radziwiłłów w AGAD",
    "AS" : "Archiwum Sanguszków w APKr.",
    "ASK" : "Archiwum Skarbu Koronnego w AGAD",
    "AVAK" : "Akty izdavaemye Vilenskoju Kommissieju dlja razbora drevnich aktov, 1.1 n., Vilna 1865 n.",
    "AW" : "Archiwum Woronieckich w APL",
    "AZ" : "Archiwum Zamoyskich w AGAD",
    "Baw." : "Zbiór Baworowskich w LBN",
    "BCzart." : "Biblioteka XX. Czartoryskich w Krakowie",
    "Belaruski archiu" : "Belaruski archiu, t. I-III, Minsk 1927-1931",
    "Birżu dvaro" : "Birżu dvaro teismo knygos 1620-1745, wyd. V. Raudeliunas i R. Firkovicius, Vilnius 1982",
    "BJ" : "Biblioteka Jagiellońska w Krakowie",
    "BKórn." : "Biblioteka PAN w Kórniku",
    "BN" : "Biblioteka Narodowa w Warszawie",
    "Bon." : "A. Boniecki, Herbarz polski, t. I-XVI, Warszawa 1899-1913, t.",
    "BOW" : "Biblioteka Zakładu Narodowego im. Ossolińskich we Wrocławiu",
    "BOZ" : "Biblioteka Ordynacji Zamojskiej w BN",
    "BPAN i PAUKr." : "Biblioteka Polskiej Akademii Nauk i Polskiej Akademii Umie­jętności w Krakowie",
    "BRacz." : "Biblioteka Publiczna im. Edwarda Raczyńskiego w Poznaniu",
    "BULw." : "Biblioteka Uniwersytetu Lwowskiego we Lwowie",
    "CBel." : "Castrensia Belsensia w CDIAULw.",
    "CBiec." : "Castrensia Biecensia w APKr.",
    "CBus." : "Castrensia Buscensia w CDIAULw.",
    "CChelm." : "Castrensia Chelmensia w APL",
    "CCR" : "Castrensia Cracoviensia Relationes w APKr.",
    "CCrasn." : "Castrensia Crasnostaviensia w APL",
    "CDIAU" : "Centralnyj Derzavnyj Istoryćnyj Archiv Ukrainy w' Kijowhe",
    "CDIAULw." : "Centralnyj Derzavnyj Istoryćnyj Archiv Ukrainy we Lwowie",
    "CGrabov." : "Castrensia Graboviecensia w APL",
    "CHal." : "Castrensia Halicensia w CDIAULw.",
    "Chłapowski" : "K. Chłapowski, Starostowie w Malopolsce 1565-1668, w: Społe­czeństwo staropolskie. Studia i szkice, t. IV, Warszawa 1986",
    "Chrapowicki" : "J. A. Chrapowicki, Diariusz, cz. I-II, oprać. A. Rachuba i T. Wa­silewski, Warszawa 1978-1988",
    "CKij." : "Castrensia Kijoviensia w CDIAU",
    "CLeop." : "Castrensia Leopoliensia w CDIAULw.",
    "CLub." : "Castrensia Lublinensia w APL",
    "CLub. Ins." : "Castrensia Lublinensia Inscriptiones w APL",
    "CLub. Plenip." : "Castrensia Lublinensia Plenipotentiae w APL",
    "CLuc." : "Castrensia Luceoriensia w CDIAU",
    "COwr." : "Castrensia Ovrucensia w CDIAU",
    "CPilz." : "Castrensia Pilznensia w APKr.",
    "CSanoc." : "Castrensia Sanocensia w CDIAULw.",
    "CTremb." : "Castrensia Trembovlensia w CDIAULw.",
    "CWlod." : "Castrensia Wlodimiriensia w CDIAU",
    "Czeppe" : "M. Czeppe, Kamaiyla Pana z Dukli. Kształtowanie się obozu politycznego Jerzego Augusta Mniszcha 1750-1763, Warszawa 1998",
    "CZyt." : "Castrensia Zytomierensia w CDIAU",
    "Drohojowscy" : "J. Drohojowski, Kronika Drohojowskich, cz. I-II, Kraków 1904",
    "Dwa pamiętniki" : "Dwa pamiętniki z XVII wieku Jana Cedrowskiego i Jana Floriana Drobysza Tuszyńskiego, oprać. A. Przyboś, Wrocław-Kraków 1954",
    "El." : "Elektorowie Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, wyd. J. Dunin-Wąsowicz i M. Dunin-Wąsowicz, RTH, 1.1, 1910",
    "Górski" : "K. Górski, Historia piechoty polskiej, Kraków 1893",
    "IJM" : "Istoriko-juridiceskije materiały izvleeonnyje iz aktoxych knig gubernij Vitebskoj i Mogilevskoj, wyd. A. Sazonov, t. I-XXXII, Vitebsk 1871-1906",
    "IRBOW" : "Inwentarz rękopisów Biblioteki Zakładu Narodowego im. Ossolińskich we Wrocławiu, pod red. J. Turskiej, t. I-XII, Wrocław 1969 n.",
    "IRBOZ" : "Inwentarz rękopisów Biblioteki Ordynacji Zamojskiej, oprać. B. Kocówna i K. Muszyńska, Warszawa 1967",
    "Jakowenko" : "N. M. Jakowenko, Ukraińska śljachta z kińca XIV do serediri XVII st., Kiiv 1993",
    "Kalendarz" : "Kalendarz polityczny 1762, Lublin 1762",
    "Kalendarzyk poi." : "Kalendarzyk polityczny na 1779-1794. Warszawa 1779-1794",
    "Kam." : "Księgi Kameralne Metryki Koronnej wr AGAD",
    "Kersten" : "A. Kersten, Stefan Czarniecki 1599-1665, Warszawka 1963",
    "KGBOW" : "A. Bułówna, Katalog gazet pisanych z XVIII wieku w zbiorach Biblioteki Zakładu Narodowego im. Ossolińskich, Wrocław 1969",
    "KK" : "Księgi Kanclerskie Metryki Koronnej w AGAD",
    "KKAK" : "Katalog kolekcii dokumentiv Kyivskoi Archeografićnoi Komissii 1369 1899, Kiiv 1971",
    "Klepackij" : "R G. Klepackij, Oczerki istorii Kijevskoj zemli, t. 1, Odessa 1912",
    "Kom." : "Zbiór Komierowskich w AGAD",
    "Kossakowski" : "S. A. Kossakowski, Monografie histoiyczno-genealogiczne, 1.1-III, Warszawa 1859-1872",
    "Knegseisen" : "W. Kriegseisen, Samorząd szlachecki w Małopolsce w latach 1669-1717, Warszawa 1989",
    "Kulecki" : "M. Kulecki, Wygnańcy ze Wschodu. Egzulanci w Rzeczypospolitej w ostatnich latach panowania Jana Kazimierza i za panowania Michała Korybuta Wiśniowieckiego, Warszawa 1997",
    "Kułakowśkyj" : "R Kułakowśkyj, Urzędnicy ziemscy Czernihowszczyzny i Siewierszczyzny (do 1648 r), „Studia Źródłoznawcze”, t. 38, 2000",
    "KZS" : "Kremienieckij ziemskij sud. Opisi aktovich knig, Wipusk I-III, Kiev 1959-1965",
    "LBN" : "Lvivska Naukova Bibliteka im. W. Stefanyka Akademii Nauk Ukrainy",
    "Lietuvos inventoriai" : "Lietuvos inventoriai XVII a, wyd. K. Jablonskis, M. Jucas, Vilnius 1962",
    "Litwin" : "H. Litwin. Naplvw szlacht polskiej na Ukrainę 1569-1648, Warszawa 2000",
    "LMAB" : "Lietuvos Mosklu Akademijos Biblioteka w Wilnie",
    "LVIA" : "Lietuvos valstybinis istorijos archyvas w Wilnie",
    "LWA" : "Latvijas valsts vestures arhivs w Rydze",
    "Matuszewicz" : "M. Matuszewicz, Diariusz życia mego, t. 1-2, oprac. B. Królikowski i Z. Zielińska, Warszawa 1986",
    "MK" : "Metryka Koronna w AGAD",
    "ML" : "Lietuvos Metrika, t. I-XXV, Vilnius 1993-1998",
    "MLit." : "Metryka Litewska w Rossijskom Gosudarstvennom archive drevnich aktov w Moskwie, Fond 389",
    "MLRPWB" : "Metryka Litewska. Rejestr podymnego województwa brzeskiego, wyd. A. Rachuba, Warszawa 2000",
    "MNK" : "Muzeum Narodowe w Krakowie",
    "MR" : "Ruska (Volinska) metrika. Kniga za 1652-1673 gg., oprać. P. Kułakowśskyj, Pamiatniki istorii vostocznoj Jevropy, t. V, Ostrog-Warszawa-Moskwa 1999",
    "MW" : "Metryka Wołyńska, księgi przygotowane do wydania w CDIAU w Kijowie",
    "MŹdDK" : "Materiały źródłowe do dziejów kultury i sztuki XVI-XVIIL oprać. M. Gębarowicz, Wrocław 1973",
    "NBU" : "Nacyjanalna Bibliteka Ukrainy im. Wemadskogo Akademii Nauk Ukrainy w Kijowie",
    "NGABM" : "Nacyjanalny Gistaryćny Archiu Belarusi w Mińsku",
    "Nies." : "K. Niesiecki, Herbarz polski, t. I-X, wyd. J. N. Bobrowicz, Lipsk 1839-1846",
    "Niesiołowski" : "A. Niesiołowski, Otia publica vix domestica, Pińsk 1743",
    "Ochocki" : "J. D. Ochocki, Pamiętniki, t. 1-4. wyd. J. I. Kraszewski, Wilno 1857",
    "Opis" : "Opisi aktovych knig Kijevskogo Centralnogo Archiva, wyd. E. P. Djakowskij, nr 1-38, Kiev 1869-1909",
    "Pamiątki" : "Pamiątki polskie z różnych czasów, t. I-II. wyd. E. Iwanowski, Kraków 1882",
    "Podoski" : "Teki Gabriela Junoszy Podoskiego, t. I-V, wyd. K. Jarochowski, Poznań 1854-1856",
    "PSB" : "Polski słownik biograficzny, t. 1 n., Kraków 1935 n., t.",
    "Pul." : "K. Pułaski, Kronika polskich rodów szlacheckich Podola, Wołynia i Ukrainy, t. I-II, Brody 1911, Warszawa 1991",
    "PułOpis" : "Opis 815 rękopisów Biblioteki Ordynacji Krasińskich, opr. F. Pułaski. Warszawa 1915",
    "Radziwiłł" : "A. S. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I-IV, Wrocław 1968-1974",
    "Relacje wojenne" : "Relacje wojenne zpienvszych lat walk polsko-kozackich powstania Bohdana Chmielnickiego okresu Ogniem i Mieczem ”, oprać. M. Nagielski, Warszawa 1999",
    "RGADA" : "Rossijskij Gosudarstvennyj Archiv Drevnich Aktov w Moskwie",
    "RGBSPet." : "Rossyjska Gosudarstvennaja Biblioteka w Sankt Peterburgu",
    "Roskie, m-p" : "Archiwum Roskie, dział majątkowo-prawny w AGAD",
    "RTH" : "Rocznik (Polskiego) Towarzystwa Heraldycznego we Lwowie",
    "Russ." : "Zbiór Russieckich w APKr.",
    "SA" : "Senieji aktai w LV1A",
    "Sig." : "Księgi Sigillat Metryki Koronnej w AGAD",
    "Stryjkowski" : "M. Stryjkowski, O początkach, wywodach, dzielnościach, sprawach rycerskich i domowych sławnego narodu litewskiego..., oprać. J. Ra­dziszewska, Warszawa 1978",
    "Svodnaja" : "Svodnaja galicko-russkaja ljetopis s 1600 po 1700 god, w: Literaturnyj sbomik izdavaemy Galicko-russkoju Matiejeju. Lvov 1874",
    "SumMK" : "Sumariusz Metryki Koronnej. Seria nowa. t. I-II, wyd. W. Krawczuk i in., Kraków 1999, 2001",
    "Tyz." : "Archiwum Tyzenhauzów w AGAD",
    "Ur." : "S. Uruski, A. A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I-XXI, Warszawa 1904-1938, t.",
    "U " : "Urzędnicy dawnej Rzeczypospolitej XII-XTII1 wieku. Spisy. t. I n., Wroclaw-Kórnik 1985 n., t.",
    "VL" : "Volumina legum, t. I-X, wyd. J. Ohryzko. Z. Kaczmarczyk. St. Petersburg 1859-Poznań 1952",
    "VUB" : "Vilniaus universiteto mokslines bibliotekos rankrasciu skyrius",
    "Wolff" : "J. Wolff, Senatorow ie i dygnitarze Wielkiego Księstwa Litewskiego 1386-1795, Kraków 1885",
    "WolffKn." : "J.Wolff, Kniaziowie litewsko-ntscy od końca czternastego wieku, Warszawa 1985",
    "ZZG" : "Zbiór Zygmunta Glogera w APKr.",
    "ŹDz." : "Źródła dziejowe, t. I-XXI, Warszawa 1876-1910",
    "Zrzódła" : "Żrzódła do dziejów polskich, wyd. M. Malinowski i A. Przeździecki, t. 2, Wilno 1944",
    "Żychl." : "T. Żychliński, Złota księga szlochy polskiej, 1.1 n., Poznań 1879 n."
}