""" słownik skrótów literatury """

literatura = {
    "AAP":"Archiwum Archidiecezji Poznańskiej w Poznaniu",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z archiwum tak zwanego bernardyńskiego we Lwowie, t. I n., Lwów 1868 n.",
    "AKH":"'Archiwum Komisji Historycznej (Polskiej) Akademii Umiejętności'",
    "AKPr.":"'Archiwum Komisji Prawniczej (Polskiej) Akademii Umiejętności'",
    "Akta unii":"Akta unii Polski z Litwą 1385-1791, wyd. S. Kutrzeba, W. Semkowicz, Kraków 1932",
    "APP":"Archiwum Państwowe w Poznaniu",
    "ASejm:":"Akta sejmikowe województw poznańskiego i kaliskiego, wyd. W. Dworzaczek, t. I (1572-1632), cz. 1 (1572-1616), Poznań 1957, cz. 2 (1616-1632), Poznań 1962",
    "BCzart.":"Muzeum Narodowe w Krakowie - Biblioteka Czartoryskich",
    "BKórn.":"Biblioteka Kórnicka Polskiej Akademii Nauk w Kórniku",
    "Błeszczyński":"J. Błeszczyński, Spis senatorów i dygnitarzy koronnych (świeckich) z XVIII wieku. Wedlug źródel autentycznych (Metryki Koronnej, Sigillat Kanclers. Voluminów legum i i.), Warszawa 1862",
    "BOW":"Biblioteka im. Ossolińskich we Wrocławiu",
    "BRacz.":"Biblioteka Publiczna im. Edwarda Raczyńskiego w Poznaniu",
    "BUW":"Biblioteka Uniwersytetu Warszawskiego w Warszawie",
    "BydgG":"Księgi grodzkie bydgoskie w APP",
    "BydgZ":"Księgi ziemskie bydgoskie w APP",
    "Chodyński, Kościół":"A. Chodyński, Kościół i klasztor O. O. Reformatów w Kaliszu, Warszawa 1874",
    "CIP":"Corpus iuris Polonici, wyd. O. Balzer, t. III, Kraków 1906 ",
    "Diariusz 1565":"Dyaryusz sejmu piotrkowskiego R.P. 1565. Poprzedzony kroniką 1559-1562, objaśnił W. Chomętowski, wyd. W. Krasiński, Warszawa 1868",
    "Diariusz 1566":"J. Kaniewska, Diariusz sejmu lubelskiego 1566 r., Wrocław 1980",
    "Diariusz 1780":"Diariusz sejmu walnego ordynaryjnego warszawskiego sześcioniedzielnego MDCCLXXX, Warszawa 1780 ",
    "Diariusz 1784":"Dyaryusz seymu wolnego ordynaryinego grodzieńskiego sześcioniedzielnego roku pańskiego 1784; Warszawa 1785",
    "Diariusz 1790/91":"Diariusz sejmu 1790/1 r. przez Antoniego Siarczyńskiego, Warszawa 1791",
    "Dzienniki sejmów":"Dzienniki sejmów walnych koronnych za panowania Zygmunta Augusta króla polskiego, W X Litewskiego 1555 i 1558 w Piotrkowie złożonych. Wydanie braci Lubomirskich, Kraków 1869",
    "Dziubkowa":"J. Dziubkowa, Portrety trumienne i tablice inskrypcyjne i herbowe, Poznań 1981",
    "Elektorowie":"Elektorowie Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta 1I, wyd. J. Dunin-Borkowski i M. Dunin-Wąsowicz, “Rocznik Towarzystwa Heraldycznego”, t. I, Lwów 1910",
    "GnG":"Księgi grodzkie gnieźnieńskie w APP ",
    "GnZ":"Księgi ziemskie gnieźnieńskie w APP ",
    "GnWc":"Księgi wieców gnieźnieńskich w APP ",
    "InowG":"Księgi grodzkie inowrocławskie w APP ",
    "InowZ":"Księgi ziemskie inowrocławskie w APP ",
    "KalG":"Księgi grodzkie kaliskie w APP",
    "KalP":"Księgi podkomorskie województwa kaliskiego w APP ",
    "KalZ":"Księgi ziemskie kaliskie w APP",
    "KalWc":"Księgi wieców kaliskich w APP",
    "Kam. III/324":"Sigillata w Archiwum Kameralnym w AGAD ",
    "Kat. zab.":"Katalog zabytków sztukż w Polsce, t. V, woj. poznańskie, pod red. T. Ruszczyńskiej i A. Sławskiej",
    "KcG":"Księgi grodzkie kcyńskie w APP ",
    "KcZ":"Księgi ziemskie kcyńskie w APP ",
    "KK":"Księgi kanclerskie w AGAD",
    "Kohte":"J. Kohte, Verzeichnis der Kunstdenkmäler der Provinz Posen, t. I-IV, Berlin 1896",
    "KonG":"Księgi grodzkie konińskie w APP ",
    "KonZ":"Księgi ziemskie konińskie w APP",
    "Konfederacja 1792.":"L. Wegner, Konfederacja województw wielkopolskich: poznańskiego, kaliskiego, gnieźnieńskiego i ziemi wschowskiej dnia 20 sierpnia 1792 r. w mieście Środzie zawiązana, Poznań 1863",
    "Konstytucje publiczne":"Konstytucje publiczne seymu extra-ordynaryinego warszawskiego pod węzłem generalnyj konfederacyi oboyga narodów trwajacego roku 1773, dnia l9 IV zaczętego, t. I, Warszawa 1775",
    "Kopia pobożnej":"Kopia pobożnej pamięci imci Pani Elżbiety Orzelskiej, Poznań 1866",
    "Koresp. H. Rozrażewskiego":"Korespondencja Hieronima Rozrażewskiego, wyd. P. Czaplewski, t. I (1567-2 VII 1582), Toruń 1937, Fontes 30, t. II (2 VII 1582-1600), Toruń 1939, Fontes 31",
    "KoścG":"Księgi grodzkie kościańskie w APP ",
    "KoścZ":"Księgi ziemskie kościańskie w APP",
    "KPol..":"Kodeks dyplomatyczny Polski, wyd. L. Rzyszczewski i A. Muczkowski, t. I, Warszawa 1847",
    "LM":"Księgi zgonów parafii katolickich w AAP (według wypisów W. Dworzaczka)",
    "LMMC":"Liber mortuorum monasterii Coronoviensis ordinis Cisterciensis, wyd. A. Mańkowski, Toruń 1931, Fontes 25 ",
    "LMML":"Liber mortuorum monasterii Landensis, MPH, t. V ",
    "LMMS":"Liber mortuorum monasterii Strelnensis, MPH, t. V ",
    "ŁKO":"J. Łukaszewicz, Krótki opis historyczny kościołów parochialnych, kościołów, kaplic, klasztorów, szkółek parochialnych, szpitali i innych zakładów dobroczynnych w dawnej diecezji poznańskiej, t. I-II, Poznań 1858-1859",
    "MK":"Metryka Koronna w AGAD",
    "MRPS":"Matricularum Regni Poloniae summaria, t. I-V, Warszawa 1905-1961",
    "Mon. Sarm.":"Starovolscius Simon, Monumenta Sarmatorum viam universae carnis ingressorum, Cracoviae 1635",
    "NakG":"Księgi grodzkie nakielskie w APP ",
    "NakZ":"Księgi ziemskie nakielskie w APP",
    "Nies.":"K. Niesiecki, Herbarz polski powiększony dodatkami z późniejszych autorów, rękopismów, dowodów urzędowych i wydany przez Jana Nep. Bobrowicza, t. I-X, Lipsk 1839-­1845",
    "Orzelski":"Świętosława Orzelskiego bezkrólewia ksiąg ośmioro 1572-1576, wyd. E. Kuntze, Scriptores rerum Polonicarum, t. XXII, Kraków 1917",
    "Pałucki":"W. Pałucki, Studia nad uposażeniem urzędników w Koronie 0XVI wieku, Warszawa 1962",
    "PozG":"Księgi grodzkie poznańskie w APP",
    "PozP":"Księgi podkomorskie województwa poznańskiego w APP ",
    "PozZ":"Księgi ziemskie poznańskie w APP",
    "PozWc":"Księgi wieców poznańskich w APP",
    "Przywileje":"Przywileje królewskiego miasta stołecznego Starej Warszawy, 1376-1772, wyd. T: Wierzbowski, Warszawa 1913 ",
    "PSB":"Polski słownik biograficzny, t. I i n., Kraków 1935 i n. ",
    "PyzG":"Księgi grodzkie pyzdrskie w APP",
    "PyzZ":"Księgi ziemskie pyzdrskie w APP",
    "Radziwiłł, Memoriale":"A. S. Radziwiłł, Memoriale rerum gestarum in Polonia 1632-1656, opr. A. Przyboś i R. Żelewski, t. I-IV, Warszawa 1968-1974",
    "Rocznik Leszcz.":"I. Kubistalowa, Portret trumienny w południowo-zachodniej Wielkopolsce, “Rocznik Leszczyński”, t. VI, Poznań 1982",
    "Sig.":"Księgi sigillat w AGAD",
    "SPPP":"Starodawne prawa polskiego pomniki, t. VII, Kraków 1882",
    "Straty":"Straty archiwów i bibliotek warszawskich w zakresie rękopiśmiennych źródeł historycznych, t. I-III, Warszawa 1957, 1956, 1955",
    "Teka Podoskiego":"Teka Gabriela Junoszy Podoskiego arcybiskupa gnieźnieńskiego, wyd. K. Jarochowski, t. I, Poznań 1854",
    "Tom.":"Acta Tomiciana, t. I i n., Poznań 1852 i n.",
    "VL":"Volumina legum, t. I-X, Warszawa 1732 i n. ",
    "WałG":"Księgi grodzkie wałeckie w APP",
    "Warschauer, Die Chronik":"A. Warschauer, Die Chronik der Stadtschreiber von Posen, “Zeitschrift der Historischen Gesellschaft fur die Provinz Posen”, t. II-III, 1888",
    "Wielądko":"Heraldyka, czyli opisanie herbów, w jakim który jest kształcie oraz familie rodowitej szlachty polskiej i W Ks. Litewskiego z ich herbami przez Wojciecha Wincentego na Wielądkach Wielądka, t. I, Warszawa 1792",
    "WschG":"Księgi grodzkie wschowskie w APP ",
    "WschZ":"Księgi ziemskie wschowskie w APP",
    "Źr.dz.":"Źródła dziejowe, t. I: K. Grzymułtowski, Listy i mowy, Warszawa 1876",
    "Źródłopisma":"Źródłopisma do dziejów unii Korony Polskiej i W. Ks. Litewskiego, wyd. T. Działyński, cz. II, Poznań 1856 ",
    "Żych.":"T. Żychliński, Złota księga szlachty polskiej, t. I-XXXI, Poznań 1879-1908"
}