""" słownik skrótów literatury """

literatura = {
    "AAW":"Archiwum Archidiecezjalne Warszawskie",
    "ABWil.":"Archiwum Benedyktynek Wileńskich w Opactwie Benedyktynek w Żarnowcu",
    "Acta Stanów":"Acta Stanow Wielkiego Xięstwa Littewskiego na pospolite ruszenie vigore laudum Wileńskiego 14. Augusti 1698 Postanowionego między Ławnem a Puzewiczami, Wilno 1699",
    "ADL":"Archiwum Druckich Lubeckich w Czart.",
    "AGAD":"Archiwum Główne Akt Dawnych w Warszawie",
    "AGZ":"Akta grodzkie i ziemskie z czasów Rzeczypospolitej Polskiej z Archiwum tak zwanego bernardyńskiego we Lwowie, t. X, Lwów 1884; t. XXV, Lwów 1935",
    "akc.":"akcesja",
    "Akta zjazdów II":"Akta zjazdów stanów Wielkiego Księstwa Litewskiego, t. II: Okresy panowań królów elekcyjnych XVI–XVII wiek, oprac. H. Lulewicz, Warszawa 2009",
    "Akty JZR":"Акты, относящиеся к истории Юужной и Западной России, собранные и изданные Археографическою комиссиею, t. I–XV, Санкт Петербург 1863–1892",
    "Akty ZR":"Акты, относящиеся к истории Западной России, собранные и изданные Археографическою комиссиею, t. I: 1340–1506, Санкт Петербург 1846; t. II: 1506–1544, 1848; t. III: 1544–1587, 1848; t. IV: 1588–1632, 1851; t. V: 1633–1699, 1853",
    "AMCh":"Archiwum Młynowskie Chodkiewiczów w ANKr., Oddział na Wawelu",
    "ANKr.":"Archiwum Narodowe w Krakowie",
    "AP":"Archiwum Państwowe",
    "APP":"Archiwum Publiczne Potockich w AGAD",
    "APR":"Archiwum Potockich z Radzynia w AGAD",
    "AR":"Archiwum Warszawskie Radziwiłłów w AGAD",
    "Arch.":"Archiwum",
    "Arch. Bartoszewiczów":"Archiwum Bartoszewiczów w AP w Łodzi",
    "Archiw JZR":"Архив Юго-западной России, издаваемый Временною комиссиею для разбора древних актов высoчaйшe утвержденною при Киевском военном, Подольском и Волынском ген. Губернаторе, cz. I–VIII, Киев 1859–1914",
    "ASang.":"Archiwum książąt Lubartowiczów Sanguszków w Sławucie, t. 6, Lwów 1910",
    "ASC":"Archiwum Sejmu Czteroletniego w AGAD",
    "ASD":"Археографический сборник документов, относящихся к истории Северо-Западной Руси, t. I–XIV, Вильна 1867–1904",
    "Augusiewicz":"S. Augusiewicz, Rodowód Woyniłlowiczów na Sawiczach. Próba rekonstrukcji genealogii rodu w XVI–XX wieku, „Przegląd Wschodni”, t. X, Warszawa 2005/06, z. 1 (37)",
    "AWAK":"Акты, издаваемые Виленскою археографическою комиссiею, t. I–XXXIX, Вильна 1865–1915",
    "AZR":"Акты относящиеся къ истории Западной России, собранные и изданные Архeографическою комиссиею, t. I–V, C.-Петербург 1848–1863",
    "Biržų dvaro":"Biržų dvaro teismo knygos 1620–1745, par. V. Raudeliūnas ir R. Firkovičius, Vilnius 1982",
    "BN":"Biblioteka Narodowa w Warszawie",
    "BNANB":"Бибиотека Нацыянальная акадэмія навук Беларусі w Mińsku",
    "Bon.":"A. Boniecki, Herbarz polski, t. I–XVI, Warszawa 1899–1913",
    "BonPoczet":"A. Boniecki, Poczet rodów w Wielkim Księstwie Litewskim w XV i XVI wieku, Warszawa 1887",
    "BonU.":"A. Boniecki, Herbarz polski. Uzupełnienia i sprostowania do Części I, Warszawa 1901",
    "Borkowska":"M. Borkowska, Dekret w niebieskim ferowany parlamencie. Wybór testamentów z XVII–XVIII wieku, Warszawa 1984",
    "BOZ":"Biblioteka Ordynacji Zamojskiej w Bibliotece Narodowej",
    "BPrzedz.":"Rękopisy z Biblioteki Przezdzieckich w AGAD",
    "BPW":"Biblioteka Publiczna m.st. Warszawy",
    "Bułatow":"Матерiалы для генеалогiи и исторiи дворянскихъ родовъ Ростовскаго уѣзда Ярославской губернiи 1783–1887 гг., t. 1, cост. Д.А. Булатовъ, Ростовъ 1887",
    "BUW":"Biblioteka Uniwersytecka w Warszawie",
    "CDIAU":"Центральний державний історичний архів України, Kijów",
    "Cedrowski":"Pamiętniki historyczne do wyjaśnienia spraw publicznych w Polsce XVII wieku posługujące, w dziennikach domowych Obuchowiczów i Cedrowskiego pozostałe, wyd. M. Baliński, Wilno 1859",
    "Chrapowicki":"J.A. Chrapowicki, Diariusz, cz. I, oprac. T. Wasilewski, Warszawa 1978; cz. II, oprac. A. Rachuba i T. Wasilewski, Warszawa 1988; [cz. III] Dyaryusz wojewody witepskiego Jana Antoniego dwóch imion Chrapowickiego, wyd. J. Rusiecki, Warszawa 1845",
    "Cichocki":"Od Augusta Mocnego do Augusta III. Doniesienia z Warszawy Andrzeja Cichockiego z lat 1732–1734, oprac. J. Dygdała, Warszawa 2016",
    "Ciechanowicz":"J. Ciechanowicz, Rody rycerskie Wielkiego Księstwa Litewskiego, t. I–V, Rzeszów 2001",
    "Czarniauski":"Ф.В. Чарняўскi, Ураднiкi Менскага ваяводства XVI–XVIII стст. Бiяграфiчны даведнiк, выпуск I–IV, Мiнск 2007–2015",
    "Czart.":"Biblioteka Książąt Czartoryskich w Krakowie",
    "Czaykowski":"Regestr diecezjów Franciszka Czaykowskiego czyli Właściciele ziemscy w Koronie 1783–1784, oprac. K. Chłapowski, S. Górzyński, Warszawa 2006",
    "Cztienija":"Чтенiя въ Историческомъ Обществе Нестора летописца, книга 12, Кiев 1898",
    "Dok. perg.":"Dokumenty pergaminowe",
    "Dzieje Ciechanowieckich":"H. Lulewicz, A. Rachuba, J. Sikorska-Kulesza, S. Dumin, A. Haratym, A. Macuk, A. Pospiszil, Dzieje rodziny Ciechanowieckich herbu Dąbrowa (XIV–XXI wiek), pod red. A. Rachuby, Warszawa 2013",
    "Elekt.":"J. Dunin-Borkowski, M. Dunin-Wąsowicz, Elektowowie królów Władysława IV, Michała Korybuta, Stanisława Leszczyńskiego i spis stronników Augusta III, Lwów 1910; O. Pietruski, Elektorów poczet, którzy niegdyś głosowali na elektorów Jana Kazimierza roku 1648, Jana III roku 1674, Augusta II roku 1697 i Stanisława Augusta roku 1764, Lwów 1845",
    "EncOrg.":"Encyklopedyja Powszechna S. Orgelbranda, t. I–XXVIII, Warszawa 1859–1868",
    "Estr.":"K. Estreicher, S. Estreicher, K. Estreicher, Bibliografi a polska, stulecie XV–XVIII, t. I–XXXIX, Kraków 1870–1952",
    "Faszczów":"Archiwum Faszczów w AGAD",
    "FHPL":"Fontes Historiae Parlamentorum Lituanicorum, t. I: Lietuvos Didžiosios Kunigaikštystis seimelių instrukcijos 1788–1790, parengė R. Jurgaitis, A. Stankevič, A. Verbickienė, Vilnius 2015",
    "Francuzowa":"Е.Б. Французова, Из истории русско-польскихъ отношений в последней трети XVII в. (по материалам межевых комиссий), „Исторические записки”, nr 105, Москва 1980",
    "FRC":"Zbiory Fundacji Rodziny Ciechanowieckich, Zamek Królewski w Warszawie",
    "Gawron":"P. Gawron, Postawa Jakuba Karola Madaleńskiego wobec litewskich magnatów. Kilka uwag na temat relacji patron - klient w Wielkim Księstwie Litewskim w I połowie XVII wieku, w: Магнацкі двор і сацыяльнае ўзаемадзеянне (XV–XVIII стст.), редак. А. Янушкевіч, Мір 2014",
    "GazWarsz.":"„Gazeta Warszawska”",
    "GazWil.":"„Gazety Wileńskie”",
    "GBS":"Гербоўнік беларускай шляхты, t. I–V, Мінск 2002–2017",
    "GIBM":"Государственная публичная историческая библиотека России, Moskwa",
    "Godziszewski":"W. Godziszewski, Granica polsko-moskiewska wedle pokoju polanowskiego (wytyczona w latach 1634–1648), „Prace Komisji Atlasu Historycznego Polski”, t. III, Kraków 1935",
    "GP":"„Gazety Polskie”",
    "HKP":"Heroldia Królestwa Polskiego w AGAD",
    "IGAW":"Indeks geografi czny Archiwum Wileńskiego w LVIA",
    "IJM":"Историко-юридическiе матерiалы, извлеченные изъ актовыхъ книг губернiи Витебской и Могилевской, изд. A.M. Созонов, Н. Мещерски, М. Веровкин, Д.И. Довгялло, t. I–XXXII, Витебск 1871–1906",
    "inw.":"inwentarz",
    "Inwentari-Timkowiczi":"Инвентари магнатских владений Белоруссии XVII–XVIII вв., Владение Тимковичи, сост. П.Г. Козловский, Е.П. Шлоссберг, Е.Л. Бравер, Минск 1982",
    "Jag.":"Biblioteka Jagiellońska w Krakowie",
    "Jankowski":"Cz. Jankowski, Powiat oszmiański. Materjały do dziejów ziemi i ludzi, cz. 1–4, Petersburg 1896–1900",
    "JfG":"„Jahrbuch für Genealogie, Heraldik und Sphragistik”, Jb. 1893–1914, Mitau 1894–1930",
    "Jusupović":"M. Jusupović, Prowincjonalna elita litewska w XVIII wieku. Działalność polityczna rodziny Zabiełłów w latach 1733–1795, Warszawa 2014",
    "Kal. Grodz.":"Kalendarz Grodzieński",
    "Kal. Polit.":"Kalendarz (Kalendarzyk) Polityczny",
    "Kal. Poł.":"Kalendarz Połocki",
    "Kal. Wil.":"Kalendarz Wileński",
    "Kamer.":"Archiwum Kameralne w AGAD",
    "Katalog Czart.":"Katalog dokumentów pergaminowych Biblioteki Czartoryskich w Krakowie, cz. 2: Dokumenty z lat 1506–1828, oprac. W. Szelińska, J. Tomaszewicz, Kraków 1991",
    "Kempa":"T. Kempa, Kariery przedstawicieli prawosławnych rodów Ogińskich i Stetkiewiczów w XVII wieku - podobieństwa i różnice awansu społecznego, ekonomicznego i politycznego, w: Władza i prestiż. Magnateria Rzeczypospolitej w XVI−XVIII wieku, red. J. Urwanowicz, przy współudziale E. Dubas-Urwanowicz i P. Guzowskiego, Białystok 2003",
    "Kirkor":"S. Kirkor, Kirkorowie litewscy, Londyn 1968",
    "KMMP 1727":"Кніга магістрата места Полацка 1727 года, падр. А.М. Латушкін, М.Д. Макараў, Вільня-Беласток 2012 ",
    "Kol. Warsz.":"Kolęda Warszawska (na kolejne lata)",
    "Konarski, Szlachta":"S. Konarski, Szlachta kalwińska w Polsce, Warszawa 1936",
    "Konarski, Kanoniczki":"S. Konarski, Kanoniczki warszawskie: 24 IV 1744 - 13 VIII 1944, Paryż 1952",
    "Konarski, Tomaszewscy":"S. Konarski, „Tomaszewscy h. Bończa”, maszynopis w Gabinecie Genealogiczno-Heraldycznym Zamku Królewskiego w Warszawie",
    "Konopczyński":"W. Konopczyński, Konfederacja barska, t. 1–2, Warszawa 1991",
    "Korczak":"L. Korczak, Monarcha i poddani. System władzy w Wielkim Księstwie Litewskim w okresie wczesnojagiellońskim, Kraków 2008",
    "KorKras.":"Korespondencja Ignacego Krasickiego, red. T. Mikulski, t. I–II, Wrocław 1968",
    "KorKZ":"„Korrespondent Kraiowy y Zagraniczny”",
    "Korona Polska":"Korona polska przy złotej wolności starożytnymi wszystkich katedr, prowincji i rycerstwa klejnotami… ozdobiona, potomnym zaś wiekom na zaszczyt i nieśmiertelną sławę pamiętnych w tej ojczyźnie synów podana… roku wolności ludzkiej przez wcielonego Boga windykowanej 1728, oprac. K. Niesiecki, t. I–IV, Lwów 1728–1743",
    "Kossakowski":"S.K. Kossakowski, Monografi e historyczno-genealogiczne niektórych rodzin polskich, t. 1–3, Warszawa 1859",
    "Kórnik":"Biblioteka PAN w Kórniku",
    "KP":"„Kuryer Polski”",
    "Krasnołuckij":"А. Краснолуцкий, Злая судьба рода Голынскихъ?, Санкт Петербург 2009",
    "Krupska":"A. Krupska, Udzielne księstwo mścisławskie pod rządami Litwy, w: Prace Naukowe Uniwersytetu Śląskiego. Prace Historyczne, t. 2, Katowice 1971",
    "KSA":"Korespondencja Stanisława Augusta w AGAD",
    "Kuczyński":"S.M. Kuczyński, Ziemie czernihowsko-siewierskie pod rządami Litwy, Warszawa 1936",
    "Kurland Genealogie":"K. Lackschewitz, A. Prus-Niewiadomski, T. Lenczewski, W. Buchholtz, Genealogien kurländisch-ritterschaftlicher Geschlechter die bisher weder im Genealogischen Handbuch der baltischen Ritterschaften, Teil Kurland, noch im Genealogischen Handbuch des Adels erschienen sind, Sonderausgabe 2004",
    "Laszuk":"A. Laszuk, Zaścianki i królewszczyzny. Struktura własności ziemskiej w województwie podlaskim w drugiej połowie XVII wieku, Warszawa 1998",
    "LM 1":"Lietuvos Metrika. Knyga nr 1 (1380–1584), Užrašymų knyga 1, par. A. Baliulis, R. Firkovičius, Vilnius 1998",
    "LM 3":"Lietuvos Metrika. Knyga nr 3 (1440–1498), Užrašymų knyga 3, par. L. Anužytė, A. Baliulis, Vilnius 1998",
    "LM 5":"Lietuvos Metrika. Knyga nr 5 (1427–1506), par. A. Baliulis, A. Dubonis, D. Antanavičius, Vilnius 2012",
    "LM 6":"Lietuvos Metrika. Knyga nr 6 (1494–1506), Užrašymų knyga 6, par. A. Baliulis, Vilnius 2007",
    "LM 7":"Lietuvos Metrika. Knyga nr7 (1506–1539), Užrašymų knyga 7, par. I. Ilarienė, L. Karalius, D. Antanavičius, Vilnius 2011",
    "LM 8":"Lietuvos Metrika. Knyga nr 8 (1499–1514), Užrašymų knyga 8, par. A. Baliulis, R. Firkovičius, D. Antanavičius, Vilnius 1995",
    "LM 9":"Lietuvos Metrika. Knyga nr 9 (1511–1518), Užrašymų knyga 9, par. K. Pietkiewicz, Vilnius 2003",
    "LM 10":"Lietuvos Metrika. Knyga nr 10 (1440–1523), Užrašymų knyga 10, par. E. Banionis, A. Baliulis, Vilnius 1997",
    "LM 11":"Lietuvos Metrika. Knyga nr 11 (1518–1523), Užrašymų knyga 11, par. A. Dubonis, Vilnius 1997",
    "LM 12":"Lietuvos Metrika, Knyga nr 12 (1522–1529), Užrašymų knyga 12, par. D. Antanavičius, A. Baliulis, Vilnius 2001",
    "LM 14":"Lietuvos Metrika. Knyga nr 14 (1524–1529), Užrašymų knyga 14, par. L. Karalius, D. Antanavičius, Vilnius 2008",
    "LM 17":"Lietuvos Metrika, Knyga nr 17 (1530–1536), Užrašymų knyga 17, par. L. Karalius, D. Antanavičius, Vilnius 2015",
    "LM 19":"Lietuvos Metrika. Knyga nr 19 (1535–1537), Užrašymų knyga 19, par. D. Vilimas, Vilnius 2009",
    "LM 20":"Lietuvos Metrika. Knyga nr 20 (1536–1539), Užrašymų knyga 20, par. R. Ragauskienė, D. Antanavičius, Vilnius 2009",
    "LM 21":"Lietuvos Metrika. Knyga nr 21 (1536–1537), Užrašymų knyga 21, par. A. Dubonis, Vilnius 2019",
    "LM 28":"Метрыка Вялікага княства Літоўскага. Кніга 28 (1522–1552). Кніга запісаў 28, падр. В.С. Мянжынскі, У.М. Свяжынскі, Менск 2000",
    "LM 37":"Lietuvos Metrika. Knyga nr 37 (1552–1561), Užrašymų knyga 37, par. D. Baronas, Vilnius 2011",
    "LM 49":"Lietuvos Metrika. Knyga nr 49 (1566–1572), Užrašymų knyga 49, par. E. Deveikytė, Vilnius 2014",
    "LM 224":"Lietuvos Metrika, Knyga nr 224 (1522–1530), 4-oji Teismų bylų knyga, par. S. Lazutka, I. Valikonyte, G. Kirkiene, E. Gudavičius, J. Karpovičiene, S. Viskantaitė, Vilnius 1997",
    "LM 226":"Lietuvos Metrika, Knyga nr 226 (1532–1534), 7-oji Teismų bylų knyga, par. L. Karalius, Vilnius 2019",
    "LM 234":"Lietuvos Metrika, Knyga nr 234 (1546–1548), 19-oji Teismų bylų knyga, par. I. Valikonytė, S. Viskantaitė-Saviščevienė, L. Steponavičiene, Vilnius 2009",
    "LM 248":"Lietuvos Metrika, Knyga nr 248 (1554–1556), 34-oji Teismų bylų knyga, par. N. Šlimienė, I. Valikonytė, Vilnius 2018",
    "LM 249":"Lietuvos Metrika, Knyga nr 249 (1554–1568), 35-oji Teismų bylų knyga, par. S. Viskantaitė-Saviščevienė, I. Valikonytė, Vilnius 2018",
    "LM 264":"Lietuvos Metrika, Knyga nr 264 (1565–1566), 50-oji Teismų bylų knyga, par. L. Steponavičiene, I. Valikonytė, Vilnius 2015",
    "LM 523":"Lietuvos Metrika, Knyga nr 523 (1528 m.), Viešųjų reikalų knyga 1, par. A. Baliulis, A. Dubonis, Vilnius 2006",
    "LM 531":"Lietuvos Metrika, Knyga nr 531 (1567–1569), Viešųjų reikalų knyga 9, par. L. Anužytė, A. Baliulis, Vilnius 2001",
    "LMAB":"Lietuvos mokslų akademijos Vrublevskių biblioteka w Wilnie",
    "LNBW":"Lietuvos nacionaline Martyno Mažvydo biblioteka w Wilnie",
    "Lubawskij, Obłastnoje dielenie":"М.К. Любавский, Областное деление и местное самоуправление Литовско-Русского государства ко времени издания первого Литовского статута. Исторические очерки, Мocквa 1892",
    "Lubawskij, Siejm":"М.К. Любавский, Литовско-Русский сейм. Опыт по истории учреждения в связи с внутренним строем и внешней жизнью государства, Москвa 1900",
    "LVIA":"Lietuvos valstybės istorijos archyvas w Wilnie",
    "LVVA":"Latvijas valsts vēstures arhīvs w Rydze",
    "LwNB":"Львівська національна наукова бібліотека України імені В. Стефаника",
    "Łappo, Lit.-rus. powiet":"И.И. Лаппо, Литовско-русский повет и его сеймик, Юрьев 1911",
    "Łappo. Podkomorskij sud":"И.И. Лаппо, Подкоморский суд в Великом княжестве Литовском в конце XVI и начале XVII в., „Журнал Министерства Народного Просвещения”, 1899, nr 8",
    "Łopaciński":"Dyariusz życia Ignacego Łopacińskiego, „Biblioteka Warszawska”, 1855, t. III",
    "Macuk":"A. Мацук, Канкурэнцыя шляхты за мсціслаўскае гродскае стараства ў 1735–1763 гг., w: Мсціслаў і Мсціслаўскі край. Зборнік навуковых артыкулаў, Мінск 2019",
    "Mag.mag.":"Беларусь у актавых кнігах XVI–XVIII стст, t. 1: Магілёўскі - магістрат 1580–1581, 1588, cклад. З.Л. Яцкевіч, А.А. Лашкевіч, Мінск 1999",
    "Maksimiejko, Siejmy, Priłożenija":"Н.А. Максимейко, Сеймы Литов- ско-Русского государства до Люблинской унии 1569. Приложения, Харьков 1902",
    "Malinowskij, Sbornik":"Сборник материалов, относящихся к истории панов-рады Великого княжества Литовского, издал J. Малиновскiй, Томскъ 1901",
    "Metryka obolecka":"Wypisy z ksiąg metrykalnych parafi i Obolce i notaty pamiętnikarskie Jana Antoniego Weyssenhoﬀ a (kserokopia w posiadaniu Tomasza Jaszczołta)",
    "Miacielski":"А. Мяцельскі, Мсціслаўскае княства і ваяводства ў XII–XVIII ст., Мінск 2010",
    "Mies.":"Месяцеслов с росписью чиновных особ в Государстве на лето от Рождества Христова … (od r. 1805: Месяцеслов с росписью чиновных особ или Общий штат Российской Империи на лето от Рождества Христова…)",
    "Miller":"A. Miller, Pierwsza porozbiorowa konspiracja litewska. Spisek ks. Ciecierskiego przeora Dominikanów wileńskich (1796–1797). Studjum historyczne, Kraków 1936",
    "ML":"Metryka Litewska (RGADA, F. 389, nr ksiegi)",
    "MLKS":"Metryka Litewska. Księga Sigillat 1709–1719, oprac. A. Rachuba, Warszawa 1987",
    "MLKW 131":"Metryka Litewska. Księga Wpisów nr 131, oprac. A. Rachuba, Warszawa 2001",
    "MNKr.":"Muzeum Narodowe w Krakowie, Depozyt w Czart.",
    "Nabytki":"Nabytki Oddziału III w AGAD",
    "NBU-IR":"Національна бібліотека України імені В. І. Вернадського, Інститут рукопису",
    "NGABGr.":"Нацыянальны гістарычны архіў Беларусі w Grodnie",
    "NGABM":"Нацыянальны гістарычны архіў Беларусі w Mińsku",
    "Nies.":"K. Niesiecki, Herbarz polski, t. I–X, wyd. J.N. Bobrowicz, Lipsk 1839–1846",
    "Niesiołowski":"K.I. Niesiołowski, Otia Publica Vix Domestica, b.m. 1743",
    "Okuliczowie":"W. Okulicz-Kozaryn, Z historii rodu Okulicz-Kozarynów, Kozarynów, Okuliczów i Kozaryn-Okuliczów, Warszawa 2003",
    "Olkieniki":"Postanowienie Generalne Stanów WXLit. – na Zjeździe Walnym woiewództw y powiatów, pospolitym ruszeniem pod Olkienikami uchwalone, Wilno 1700",
    "Opis dokum. VCA":"Опись документов Виленского Центрального Архива древних актовых книг, t. 10: Акты Брестского градского суда за 1575–1715 годы, Вильна 1910",
    "Opisanije ROVPB":"Описанiе рукописнаго отделения Виленской публичной бивлiотеки, t. I–V, Вильна 1893–1906",
    "Oss.":"Biblioteka Ossolińskich we Wrocławiu",
    "Oświęcim":"S. Oświęcim, Dyaryusz 1643–1651, wyd. W. Czermak, Kraków 1907",
    "PANKr.":"Biblioteka Naukowa Polskiej Akademii Umiejętności i Polskiej Akademii Nauk w Krakowie",
    "PDS":"Памятники дипломатических сношений древней России с державами иностранными, t. XXXV, S.-Петербург 1882",
    "Podymne mścis.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo mścisławskie 1667 r., oprac. A. Rachuba, Warszawa 2008 ",
    "Podymne smol.":"Metryka Litewska. Rejestry podymnego Wielkiego Księstwa Litewskiego. Województwo smoleńskie 1650 r., red. A. Rachuba, oprac. S. Dumin, A. Rachuba, Warszawa 2009",
    "Polechow":"С. Полехов, Наследники Витовта. Династическая война в Великом княжестве Литовском в 30-е годы XV века, Москва 2015",
    "Popow":"A. Попов, Русское посольство въ Польше въ 1673–1677 годахъ. Несколько летъ изъ исторiиотношенiи древней Россiи къ европейскимъ державамъ, Санктпетербургъ 1854",
    "Poselstwo":"Poselstwo Aleksandra Piaseczyńskiego i Kazimierza Leona Sapiehy do Moskwy w 1635 roku, oprac. A. Filipczak-Kocur, Opole 2017",
    "Prozorów":"Archiwum Prozorów i Jelskich w AGAD",
    "Przyb.":"Przybytki",
    "PSB":"Polski słownik biograficzny",
    "PSRL":"Полное cобрание русских летописей",
    "Ptaszycki, Sprostowania":"S. Ptaszycki, Dzieje rodów litewskich jako materyjał do archeologii historycznej, Warszawa 1888 (odbitka z „Ateneum”, t. III, 1888, z. 3)",
    "Ptaszycki, Z dziejów":"S. Ptaszycki, Z dziejów starego rodu, „Charitas” − księga zbiorowa, Petersburg 1894",
    "Pułaski":"Pułaski F., Opis 815 rękopisów Biblioteki Ord. Krasińskich, Warszawa 1915",
    "Racz.":"Miejska Biblioteka Publiczna im. E. Raczyńskiego w Poznaniu",
    "Radaman":"А. Радаман, Кіраванне соймікавамі пасяджэннямі ў Вялікім Княстве Літоўскім, Рускім і Жамойцкім у другой палове XVI - пачатку XVII ст., „Весці Беларускага дзяржаўнага педагагічнага універсітэта імя Максіма Танка”, 2002, nr 2 (32)",
    "Radzimiński":"Z. Luba Radzimiński, Sprawa odrębnego pochodzenia Chodkiewiczów litewskich i białoruskich, „Rocznik Polskiego Towarzystwa Heraldycznego”, t. VIII, 1926–1927",
    "RadzMem.":"A.S. Radziwiłł, Memoriale rerum gestarum in Polonia, t. I–IV, wyd. A. Przyboś, R. Żelewski, Wrocław 1968–1974",
    "RBS I":"Русско-белорусские связи: сборник документов (1570–1667 гг.), редак. Л.С. Абецедарский, Минск 1963",
    "RGADA":"Российский государственный архив древних актов w Moskwie",
    "RGBM":"Российская государственная библиотека w Moskwie",
    "RGIA":"Российский государственный исторический архив w Sankt Petersburgu",
    "RIB":"Русская Историческая Библиотека, t. XX (Литовская метрика, часть 2, т. 1: Книги судных дел, С.-Петербург 1903); t. XXX (Литовская метрика, часть 3, т. 1: Книги публичных дел, Юрьевъ 1914",
    "RNBSPet.":"Российская национальная библиотека w Sankt Petersburgu",
    "Rod Iliniczau":"Р. Аляхновіч, С. Рыбчонак, А. Шаланда, Род Іллінічаў у Вялікім Княстве Літоўскім у ХV–ХVІ ст.: радавод, гербы, уладанні, Мір 2015",
    "Roskie, r.-m.":"AGAD, Archiwum Roskie, Akta rodzinno-majątkowe",
    "Rybczonak":"C. Рыбчонак, Радавод Вайніловічаў гербу „Сыракомля” змененая, „Герольд Litherland”, nr 18, Горадня–Менск 2011",
    "S…cki":"S…cki [K. Stadnicki], Dostojnicy litewscy. Rozbiór krytyczny i uzupełnienia dzieła J. Wolﬀ a, Senatorowie, „Ateneum”, t. I, 1886",
    "SA":"Senieji aktai (Akta dawne) w LVIA",
    "Sang.":"Archiwum Sanguszków w ANKr., Oddział na Wawelu",
    "Sapiehowie":"Sapiehowie. Materjały historyczno-genealogiczne i majątkowe, t. I–III, Petersburg 1890–1894",
    "Sbornik dok. Siew.-Zap. kraja":"Сборник документов, касающихся административного устройства Северо-Западного края при императрице Екатерине II (1792–1796), Вильна 1903",
    "Sęczys":"E. Sęczys, Szlachta wylegitymowana w Królestwie Polskim w latach 1835–1861, Warszawa 2000",
    "SGKP":"Słownik geografi czny Królestwa Polskiego i innych krajów słowiańskich, t. I–XV, Warszawa 1880–1900",
    "Smoleński":"W. Smoleński, Konfederacya targowicka, Kraków 1903",
    "Sozański":"A. Sozański, Imienne spisy osób duchownych, świeckich i wojskowych, które w pierwszych ośmiu latach panowania króla Stanisława Poniatowskiego od 1764–1772 r. w rządzie lub przy administracyi Rzeczypospolitej udział brały…, cz. I: Tablice i rejestr, Kraków 1866",
    "Syta":"K. Syta, Testament Marcjana Antoniego Ogińskiego, kasztelana mścisławskiego. Przyczynek do dziejów rodziny z zasobu archiwum Ogińskich w Litewskim Historycznym Archiwum Państwowym w Wilnie, „Archiwa. Kancelarie. Zbiory”, t. 2, 2008"
    "Szalewicz - A. Szalewicz, Rodopis Szalewiczów. Czy wszyscy pochodzimy od jednego przodka?, Warszawa 2008",
    "Szałanda":"А. Шаланда, Дакументальныя матэрыялы ХVII–ХVIII ст. у фондах Слонімскага краязнаўчага музея імя І.І. Стаброўскага, „Gerold Litherland”, 2002, nr 3–4 (7–8)",
    "Szpilenko":"Смотровой список шляхты Смоленского воеводства 1648 г., публ. Д.П. Шпиленко, w: Российская генеалогия. Научный альманах, t. 2. Москва 2017",
    "Szymielewicz":"M. Szymielewicz, Szkice do monografi i Żołudka, „Ziemia Lidzka”, R. II, 1937, nr 11",
    "Szymukienus":"М.У. Шымукенус, Iван Галынскi i яго нашчадкi, „Архiварыус”, t. VI, Мiнск 2008",
    "Tęgowski":"J. Tęgowski, Pierwsze pokolenia Giedyminowiczów, Poznań–Wrocław 1999",
    "TML":"Transkrypcje Metryki Litewskiej w AGAD",
    "Trybunał I":"Deputaci Trybunału Głównego Wielkiego Księstwa Litewskiego 1582–1696. Spis, red. A. Rachuba, oprac. H. Lulewicz, A. Rachuba, Warszawa 2007",
    "Trybunał II":"Deputaci Trybunału Głównego Wielkiego Księstwa Litewskiego, 1697–1794. Spis, red. A. Rachuba, oprac. A. Rachuba, P.P. Romaniuk przy współpracy A. Macuka i J. Aniszczenki, Warszawa 2004",
    "Tyz.":"Archiwum Tyzenhauzów w AGAD",
    "Tzw. ML":"Tak zwana Metryka Litewska w AGAD",
    "U":"Urzędnicy dawnej Rzeczypospolitej XII–XVIII wieku. Spisy, red. A. Gąsiorowski, t. I n., Wrocław–Kórnik 1985 n.",
    "Unus":"Unus pro omnibus. Валовічы ў гісторыі Вялікага княства Літоўскага XV–XVIII стст., pэд. А.І. Шаланда, Мінск 2014",
    "Uruski":"S. Uruski, A.A. Kosiński, A. Włodarski, Rodzina. Herbarz szlachty polskiej, t. I–XV, Uzupełnienia t. I–VI, Warszawa 1904–1938",
    "UWKL":"Urzędnicy Wielkiego Księstwa Litewskiego. Spisy",
    "Vilimas":"D. Vilimas, Lietuvos Didžiosios Kunigaikštystės žemės teismo sistemos formavimasis (1564–1588), Vilnius 2006",
    "VL":"Volumina legum, t. I–X, Petersburg 1859, Kraków 1889, Poznań 1952",
    "VUB":"Vilniaus universiteto bibliotekos rankraščių skyrius",
    "Wałowiczy":"Валовiчы герба „Багорыя”, рэд. А.I. Шаланда, Мiнск 2019",
    "Waronin":"В.А. Варонін, Князь Юрай Лынгвеневіч Мсціслаўскі. Гістарычны партрэт, Мінск 2010",
    "Wiaraukin":"Ў. Вяроўкін-Шэлюта, Дашкевічы гэрбу „Ляліва”, „Годнасць”, Мiнск 1994, nr 1(2)",
    "Wielądko":"W.W. Wielądko, Heraldyka Czyli Opisanie Herbów […] Oraz Familie Rodowitey Szlachty Polskiey i W.X. Litewskiego z ich herbami […], t. 1, cz. 1–2, Warszawa 1792",
    "Wiśniowiecki":"J.A. Wiśniowiecki, Ilias polski (1700–1710), wyd. P.P. Romaniuk, J. Burdowicz-Nowicki, Warszawa 2018",
    "Wittyg":"W. Wittyg, Nieznana szlachta polska i jej herby, Kraków 1908",
    "Wojna Polski i Litwy":"S. Jóźwiak, K. Kwiatkowski, A. Szweda, S. Szybkowski, Wojna Polski i Litwy z zakonem krzyżackim w latach 1409–1411, Malbork 2010",
    "Wolﬀ":"J. Wolﬀ , Senatorowie i dygnitarze Wielkiego Księstwa Litewskiego 1386–1795, Kraków 1885 (egzemplarz z BN z własnoręcznymi poprawkami i uzupełnieniami autora)",
    "Wolﬀ Kn.":"J. Wolﬀ , Kniaziowie litewsko-ruscy od końca czternastego wieku, Warszawa 1895",
    "Wolﬀ , Pacowie":"J. Wolﬀ , Pacowie. Materyjały historyczno-genealogiczne, Petersburg 1885",
    "Wóycicki":"W. Wóycicki, Cmentarz Powązkowski pod Warszawą, t. III, Warszawa 1858",
    "Zabiełłów":"Archiwum Zabiełłów w AGAD",
    "Zaliwaka":"А. Залiвака, Фасцыкул I–V, Мiнск 2011–2015",
    "Załęski IV":"S. Załęski, Jezuici w Polsce, t. I–V, Lwów–Kraków 1900-1906",
    "Zawisza":"K. Zawisza, Pamiętniki… wojewody mińskiego, wyd. J. Bartoszewicz, Warszawa 1862",
    "Zb. Bran.":"Zbiór Adama i Beaty Branickich w AGAD",
    "Zb. Czoł.":"Zbiór Czołowskiego w AGAD",
    "Zb. Rus.":"Zbiór Rusieckich w ANKr., Oddział na ul. Siennej",
    "ZMRP":"Zbiór materiałów różnej proweniencji w AGAD",
    "ZNB":"Zbiory Niewodniczańskiego w Bittburgu",
    "ZZG":"Zbiór Zygmunta Glogera w ANKr., Oddział na Wawelu",
    "Żychl.":"T. Żychliński, Złota księga szlachty polskiej, t. I n., Poznań 1879 n.",
    "Żytkowicz":"L. Żytkowicz, Rządy Repnina na Litwie w l. 1794–7, Wilno 1937"
}